[id='custom-tasks-creating-custom-tasks-in-vscode']
= Creating custom tasks in VS code BPMN extension
For creating a custom task in VS code editor you must use the project created in business-central UI and clone this project into VS code filesystem.

.Procedure
. Log in into {central} and create a project.

. Go to Project settings tab and copy the project Git url.

. Clone the project into your local filesystem or VS Code using the following command:
+

[source,xml]
----
git clone ssh://$UserName@localhost:8001/MySpace/TestProject
----

. Work Item Definitions can be provided as `.wid` files or through `@wid` annotations. The `.wid` files can be placed in:
+
* The top-level `global/` directory, or
* The `src/main/resources/` directory, optionally within a Java package structure (For example, `src/main/resources/com/ibm/`)
+
For more information about `.wid` files, see xref:{jbpm-dir}/BPMN2/custom-tasks-work-item-definitions-vscode.adoc[Work item definitions]
+
[NOTE]
====
Icons for custom tasks can be placed in the same directory as the `.wid` file. 
====
+
. You can now access the custom task from the process pallet in the VS Code.

+
[NOTE]
====
In some cases, VS Code may not immediately recognize the `.wid` file, causing the custom Work Item to be unavailable in the designer palette. To resolve this, run git and `customtask.wid` to ensure the file is tracked. If the issue persists, try opening the BAMOE project in a new VS Code workspace.
====
