[id='custom-tasks-creating-work-item-handler-projects']
= Creating work item handler projects

Create the software project to contain all configurations, mappings, and executable code for the custom task.

You can create a work item handler from scratch or use a Maven archetype to create an example project. BAMOE provides the `jbpm-workitems-archetype` from the Maven repository for this purpose.

. Open the command line and create a directory where you will build your work item handler such as workitem-home:
+

[source,xml]
----
mkdir workitem-home
----

. Check the Maven `settings.xml` file and ensure that the Red Hat Maven repository is included in the repository list.
For example, to add the online Red Hat Maven repository to your Maven `settings.xml` file see the subsequent command:
+

[source,xml]
----
<settings>

  <profiles>

    <profile>

      <id>my-profile</id>

      <activation>

        <activeByDefault>true</activeByDefault>

      </activation>

      <repositories>

        <repository>

          <id>redhat-ga</id>

          <url>http://maven.repository.redhat.com/ga/</url>

          <snapshots>

            <enabled>false</enabled>

          </snapshots>

          <releases>

            <enabled>true</enabled>

          </releases>

        </repository>

        ...

      </repositories>

    </profile>

  </profiles>

  ...

</settings>
----

. In the workitem-home directory, execute the following command:
+

[source,xml]
----
$ mvn archetype:generate \
-DarchetypeGroupId=org.jbpm \
-DarchetypeArtifactId=jbpm-workitems-archetype \
-DarchetypeVersion=7.67.2.Final-redhat-00034 \
-Dversion=1.0.0-SNAPSHOT \
-DgroupId=com.ibm \
-DartifactId=myworkitem \
-DclassPrefix=MyWorkItem
----
+

.parameter descriptions
[cols="30%,70%a", frame="all", options="header"]
|===
|Parameter
|Description
|`-DarchetypeGroupId`
|Specific to the archetype and must remain unchanged.
|`-DarchetypeArtifactId`
|Specific to the archetype and must remain unchanged.
|`-DarchetypeVersion`
|Red Hat library version that is searched for when Maven attempts to download the jbpm-workitems-archetype artifact.
|`-Dversion`
|Version of your specific project. For example, 1.0.0-SNAPSHOT.
|`-DgroupId`
|Maven group of your specific project. For example, com.redhat.
|`-DartifactId`
|Maven ID of your specific project. For example, myworkitem.
|`-DclassPrefix`
|String added to the beginning of Java classes when Maven generates the classes for easier identification. For example, MyWorkItem.
|===
+
After executing the command a `myworkitem` folder is created in the workitem-home directory. For example:
+
[source,xml]
----
assembly/
  assembly.xml
src/
  main/
    java/
      com/
        ibm/
          MyWorkItemWorkItemHandler.java
    repository/
    resources/
  test/
    java/
      com/
        ibm/
          MyWorkItemWorkItemHandlerTest.java
          MyWorkItemWorkItemIntegrationTest.java
    resources/
      com/
        ibm/
pom.xml
----

. Add any Maven dependencies required by the work item handler class to the `pom.xml` file.

. To create a deployable JAR for this project, in the parent project folder where the `pom.xml` file is located, execute the following command:
+

[source,xml]
----
$ mvn clean package
----

As a result, several files are created in the target directory which include the following two main files:

* `myworkitems-<version>.jar`: Used for direct deployment to Red Hat Process Automation Manager.

* `myworkitems-<version>.zip`: Used for deployment using a service repository.