[id='managing-events-using-correlation-feature-{context}']
= Managing events using the Correlation feature

The Correlation feature in BAMOE 8.x enables users to define a correlation key for managing events in their workflow. This feature is based on the 'EventTypeFilter' and adds a new level of filtering based on the content of the message.

== Prerequisites

* You must configure their KIE Server to send and receive Kafka messages from the process. This can be done by following the steps outlined in the *document*. 
* You must use VS Code IDE with the BPMN plugin, as correlation properties are not available in the {central} web designer.

== Using Static Correlation in Message StartEvent

To use static correlation in Message StartEvent:
. Define the Kafka channel name under Implementation/Execution -> Message property.
. Define a correlation for the process from Process properties->Collaboration->Correlations.
. Create a process with MessageStartEvent and define the following correlation fields:

* Property: Select the correlation created in the earlier step.
* Message Expression: Define the variable name that will be available in the generated event.
* Message Expression Type: Select the appropriate expression type (for example, String, Long, Object).
* Data Expression: Define the expected values to trigger the process from the generated event.
* Data Expression Type: Select the appropriate expression type (for example, String, Long, Object).


== Using Dynamic Correlation in Message Intermediate Catch Event, Message Boundary Event

To use dynamic correlation in Message Intermediate Catch Event, Message Boundary Event:

. Create a BPMN process with IntermediateCatchEvent or BoundaryEvent and create a process variable (e.g., ProcessVarOrderId of type String) that can be used to trigger these nodes.
. Define the Kafka channel name under Implementation/Execution -> Message property for IntermediateCatchEvent or BoundaryEvent.
. Define a correlation for the process from Process properties->Collaboration->Correlations.
. In the BPMN process, define the correlation fields that use the process variable defined in the earlier step.

The jbpm engine will put the correlation subscription based on the dynamic expression based on process variables.

