[id='process-instance-admin-con']
= Process instance operations
Process instance administration API exposes the following operations for the {PROCESS_ENGINE} and the individual process instance.

* *get process nodes - by process instance id*: Returns all nodes, including all embedded sub-processes that exist in the process instance. You must retrieve the nodes from the specified process instance to ensure that the node exists and includes a valid ID so that it can be used by other administration operations.
* *cancel node instance - by process instance id and node instance id*: Cancels a node instance within a process instance using the process and node instance IDs.
* *retrigger node instance - by process instance id and node instance id*: Re-triggers a node instance by canceling the active node instance and creates a new node instance of the same type using the process and node instance IDs.
* *update timer - by process instance id and timer id*: Updates the timer expiration of an active timer based on the time elapsed since the timer was scheduled. For example, if a timer was initially created with delay of one hour and after thirty minutes you set it to update in two hours, it expires in one and a half hours from the time it was updated.
** *delay*: The duration after the timer expires.
** *period*: The interval between the timer expiration for cycle timers.
** *repeat limit*: Limits the expiration for a specified number for cycle timers.
* *update timer relative to current time - by process instance id and timer id*: Updates the timer expiration of an active timer based on the current time. For example, if a timer was initially created with delay of one hour and after thirty minutes you set it to update in two hours, it expires in two hours from the time it was updated.
* *list timer instances - by process instance id*: Returns all active timers for a specified process instance.
* *trigger node - by process instance id and node id*: Triggers any node in a process instance at any time.

[NOTE]
====
Do not use trigger operation for failed asynchronous task. Instead, you must first fix the issue that blocks the task execution and then requeue the failing Job at *Business Central: select Menu* -> *Jobs* -> *[Filter by Status=Error and Process Instance ID=pid]* -> *Actions* -> *Requeue* -> *Requeue Job*. 
The requeue option is also available as REST Endpoint. Use the following command:
[source]
----
curl -X PUT "http://localhost:8080/kie-server/services/rest/server/jobs/JOB_ID" -H "accept: application/json"
----
====