= Migrating to the latest version of DRL
include::../partials/attributes.adoc[]

When migrating to {PRODUCT_LONG} v {PRODUCT_VERSION} you may be faced with the task of migrating your technical rules, which are currently represented by **Drools Rule Language** (DRL) files.

== Overview

This section describes how to migrate your technical rules to make use of the new features of Drools Rule Language (DRL) Version 8.0.
Note that while {PRODUCT_SHORT} v {PRODUCT_VERSION} is partly based on Drools Rule Language version 8.0, it still supports the previous version's language APIs and syntax. 
Hence, it might not be necessary to migrate your rules, except in the case of a new language feature that you want to use.

== Prerequisites

The following tools are required to migrate to {PRODUCT_SHORT} v {VERSION}:

include::../partials/prerequisites.adoc[]

== Maven dependencies

Drools Version 6 or early Drools Version 7 projects have `pom.xml` dependencies like the following:

[source,xml]
----
<dependencies>
    <dependency>
        <groupId>org.drools</groupId>
        <artifactId>drools-core</artifactId>
        <version>${version.org.drools}</version>
    </dependency>

    <dependency>
        <groupId>org.drools</groupId>
        <artifactId>drools-compiler</artifactId>
        <version>${version.org.drools}</version>
    </dependency>
</dependencies>
----

Drools Version 7.45.0 introduced `drools-engine` and `drools-engine-classic` as aggregator dependencies.
As of Drools Version 8.0, the dependencies `drools-engine-classic` and `drools-mvel` are **deprecated**. Hence, use `drools-engine` as in the following example:

[source,xml]
----
</dependencies>
    <dependency>
        <groupId>org.drools</groupId>
        <artifactId>drools-engine</artifactId>
        <version>${version.org.drools}</version>
    </dependency>
  </dependencies>
----

Drools Version 8.0 includes module refactoring and hence it might be difficult to collect the dependencies.
The aggregator dependency definitely helps.

== Rule Units

As introduced earlier, using `Rule Units` are _**a recommended style**_ for implementing rules in Drools Version 8.0.
It requires modifications to your codebase.
If you are developing cloud-native applications, Rule Units are _**recommended**_, as they are supported by Kogito.
Rule units represent a declarative approach to partitioning a rules set into smaller units by binding different data sources to those units and orchestrating the execution of an individual unit. 
A rule unit is an aggregate of data sources, global variables, and rules.

To utilize Rule Units, add the following dependency, which is required for using Rule Unit APIs:

[source,xml]
----
</dependencies>
    <dependency>
        <groupId>org.drools</groupId>
        <artifactId>drools-ruleunits-engine</artifactId>
        <version>${version.org.drools}</version>
    </dependency>
  </dependencies>
----

For the related Java API usage in Drools Version 7, you can create a `KieSession` from rule assets, and insert facts and fire rules as in the following example:

// TODO replace by link to new adoc?
.Traditional DRL API
[source,java]
----
KieServices ks = KieServices.Factory.get();
KieContainer kcontainer = ks.getKieClasspathContainer();
KieBase kbase = kcontainer.getKieBase();
KieSession ksession = kbase.newKieSession();
try {
    ksession.insert(new Measurement("color", "red"));
    ksession.insert(new Measurement("color", "green"));
    ksession.fireAllRules();
} finally {
    ksession.dispose();
}
----

However, by using the Rule Unit APIs, the resulting Java snippet is displayed as follows:

.Rule Unit API
[source,java]
----
MeasurementUnit measurementUnit = new MeasurementUnit();
RuleUnitInstance<MeasurementUnit> instance = RuleUnitProvider.get().createRuleUnitInstance(measurementUnit);

try {
    measurementUnit.getMeasurements().add(new Measurement("color", "red"));
    measurementUnit.getMeasurements().add(new Measurement("color", "green"));
    instance.fire();
} finally {
    instance.dispose();
}
----

In Rule Unit, instantiate `RuleUnitInstance` instead of `KieSession`. Add facts to `DataSource` property instead of `insert`. Generic KIE API calls (for example, KieServices, KieContainer, KieBase …​ ) are not required anymore. 
Define one more class Unit instead.

.Rule Unit Java Class
[source,java]
----
public class MeasurementUnit implements RuleUnitData {

    private final DataStore<Measurement> measurements;
    private final Set<String> controlSet = new HashSet<>();

    public MeasurementUnit() {
        this(DataSource.createStore());
    }

    public MeasurementUnit(DataStore<Measurement> measurements) {
        this.measurements = measurements;
    }

    public DataStore<Measurement> getMeasurements() {
        return measurements;
    }

    public Set<String> getControlSet() {
        return controlSet;
    }
}
----

This Rule Unit class, associates rules (DRL) and inserted facts (DataSource) to help you manage the relationship.
In addition to the API, the DRL syntax style also changes from traditional DRL, as displayed in the following example:

.Traditional DRL
[source,drl]
----
global java.util.Set controlSet;

rule "will execute per each Measurement having ID color"
when
	Measurement( id == "color", $colorVal : val )
then
	controlSet.add($colorVal);
end
----

.Rule Unit DRL
[source,drl]
----
unit MeasurementUnit;

rule "will execute per each Measurement having ID color"
when
	/measurements[ id == "color", $colorVal : val ]
then
	controlSet.add($colorVal);
end
----

Initially, declare a `unit` and do not set it as `global` because `controlSet` is a field of `MeasurementUnit`.
Traditional global usage becomes the Unit's field.
In addition, the main difference is that the `OOPath notation` is in the left hand side (LHS) of the rule.
It is described in detail at Rule conditions in DRL.
You must change from the class name (Measurement) to the DataSource property name in the Unit class (measurements).

In addition, you need to take care of the insert in the right hand side (RHS) of the rule.
The `insert` method inserts a fact into a DEFAULT entry-point, but in Rule Unit use cases, you must specify a DataSource where you want to insert the fact.
Hence, you must call `DataStore.add` or `DataStream.append` instead of insert.

.Traditional DRL
[source,drl]
----
rule "Insert another Measurement"
when
	Measurement( id == "color", $colorVal : val )
then
	insert(new Measurement("monochrome", "false"));
end
----

.Rule Unit DRL
[source,drl]
----
unit MeasurementUnit;

rule "Insert another Measurement"
when
	/measurements[ id == "color", $colorVal : val ]
then
	measurements.add(new Measurement("monochrome", "false"));
end
----

[NOTE]
====
You need not rewrite, update, modify and delete because they work for a fact in its DataSource as expected.
These changes are not negligible, but not difficult to implement either.
====

== Migration from non-executable model to executable model

The `drools-engine-classic` and `drools-mvel` dependencies execute rules with **non executable model**, and `drools-engine` with **executable model**.  
You can use the executable model to pre-compile so that at runtime, the sessions are easier to create, basically by speeding up the entire rule execution process.
In general, from an external perspective, rule evaluation and rule consequence execution results are expected to be the same by using either the non-executable model or the executable model.
You may however encounter a few edge cases during compile time or runtime.
If you find any issues, report them.

=== Invalid Cast

When you specify dialect `mvel` in a rule, the non-executable model is tolerant of invalid type cast, because of type coercion behavior in MVEL.
For example:

[source,drl]
----
global MyUtils myUtils;

rule Rule1
dialect "mvel"
when
  $p : Person()
then
  myUtils.doWork((String) $p.age )));
end
----

This rule can be built with the non-executable model even if `$p.age` is an int which is not acceptable in Java syntax.

With the executable model, the rule fails with a build error, `Cannot cast from int to String`. 
You can fix the rule by using valid Java syntax.
For example:

[source,drl]
----
...
then
  myUtils.doWork(java.util.Objects.toString( $p.age ));
end
----

=== Generics Support
The non-executable model is tolerant of generics type.
For example:

[source,drl]
----
rule Rule1
  no-loop true
  when
    $fact : Fact( str == "ADD", $val : "100" )
  then
    modify($fact) {
      bdList.add($val);
    }
end
----

By using the non-executable model you can add a String object to `bdList` even if `Fact.bdList` is `List<BigDecimal>` which is not acceptable in Java syntax.
With the executable model, the rule fails with a build error, `The method add(BigDecimal) in the type List<BigDecimal> is not applicable for the arguments (String)`.
You can fix the rule by using valid Java syntax.
For example:

[source,drl]
----
...
then
  modify($fact) {
    bdList.add(new BigDecimal($val));
  }
end
----

=== Invalid Coercion

For example, Java allows coercion from int to long.
However, Java does not allow coercion from int to Long.
This is the rule to call the setWrapperLong method which accepts Long:

[source,drl]
----
rule Rule1
dialect "mvel"
when
  $f : Fact()
then
  $f.setWrapperLong(10);
end
----

The non-executable model coerces 10 to Long, and hence it does not throw an Exception.
However, the executable model throws a build error, `The method setWrapperLong(Long) in the type Fact is not applicable for the arguments (int)`. 
You can fix the rule by using valid Java syntax. For example:

[source.java]
----
...
then
  $f.setWrapperLong(10L);
end
----

Generics return type resolution, assuming you have classes below:

.Parent Class
[source.java]
----
public abstract class Vehicle<TEngine extends Engine> {
    // ...

	public abstract TEngine getEngine();

	public TEngine getMotor() {
		return getEngine();
	}
----

.Sub Class
[source,java]
----
public class DieselCar extends Vehicle<DieselEngine> {
	private final DieselEngine engine;

	public DieselCar(String maker, String model, int kw, boolean adBlueRequired) {
		super(maker, model);
		this.engine = new DieselEngine(kw, adBlueRequired);
	}

	@Override
	public DieselEngine getEngine() {
		return engine;
	}
}
----

.Java Class
[source,java]
----
public class DieselEngine extends Engine {

	private final boolean adBlueRequired;
----

.Rule
[source,drl]
----
rule Rule1
	when
		$v : DieselCar(motor.adBlueRequired == true)
	then
		// do something
end
----

The non-executable model can dynamically resolve that motor is `DieselEngine` and hence the rule works.
However, the executable model resolves motor to TEngine, so a build error is thrown as, `Unknown field adBlueRequired on TEngine`.
You can fix the rule by specifying the subtype with the # operator.
For example:

[source,drl]
----
...
when
	$v : DieselCar(motor#DieselEngine.adBlueRequired == true)
----
