= Migration guide 
include::../partials/attributes.adoc[]

{PRODUCT_LONG}, also known as {PRODUCT}, is a cloud-native business automation technology for building cloud-ready business applications.
{PRODUCT} is optimized for a hybrid cloud environment and adapts to your domain and tooling needs.

{PRODUCT_LONG} v{PRODUCT_VERSION} is based soley on the upstream community project known as https://kie.org/about/[Apache KIE], which stands for `Knowledge Is Everything`.
The Apache KIE Community is a home for leading Open Source projects that play a role in delivering solutions around Business Automation and Artificial Intelligence in the cloud.

The https://kogito.kie.org/[Apache KIE Kogito] initiative is the next generation of business automation platforms focused on cloud-native development, deployment, and execution.
Kogito comprises the battle-tested modules of the Apache KIE group: `Apache KIE Drools` and `Apache KIE jBPM`.

The core objective of {PRODUCT}'s implementation of Kogito-based microservices is to help you mold a set of decisions into your own domain-specific cloud-native set of services.
As a developer of business automation applications, you can use {PRODUCT} Version {VERSION} to build cloud-native applications that adapt to your business domain and tooling.

== Overview

This section describes how to migrate your existing business automation applications and platforms to the most recent version of {PRODUCT_LONG}.
The supported upgrade process is from the previous version to the current version.
If you are migrating from an older version, you must follow the migration steps to upgrade to each intermediate version, as documented.
Depending on the complexity of your installation, you might want IBM(R) Services to participate in your project.
If so, contact your IBM service representative.

The following topics are covered in this chapter:

* xref:{RH_BPMS_MIGRATION_DOC_LINK}[Red Hat v6 to v7] for migration from {RH_BPMS} to v7 of the former Red Hat offerings of {RH_PAM} and/or {RH_DM}.
* xref:redhat-to-ibm.html[Red Hat v7 to {PRODUCT} v{VERSION_80}] for migration from the former Red Hat offerings _({RH_PAM} and/or {RH_DM})_ to IBM's various enterprise releases of {PRODUCT_DM} ({PRODUCT_DM_SHORT}) and/or {PRODUCT_PAM} ({PRODUCT_PAM_SHORT}).
* xref:now-to-next.html[{PRODUCT} v{VERSION_80} {PRODUCT} v{VERSION_90X}] for migration from {PRODUCT_LONG} Version {VERSION_80} to {PRODUCT_LONG} Version {VERSION_90X}.
* xref:90x-to-91x.html[{PRODUCT} v{VERSION_90X} {PRODUCT} v{VERSION_91X}] for migration from {PRODUCT_LONG} Version {VERSION_90X} to {PRODUCT_LONG} Version {VERSION_91X}.
* xref:business-central.html[Business Central] for migration from Business Central to IBM {DEV_TOOLS}.
//* xref:drl.html[Drools Rule Language] for migration to the latest version of Drools Rule Language (DRL).

== Prerequisites

include::../partials/prerequisites.adoc[]
