= Migration Guide 
include::../partials/attributes.adoc[]

{PRODUCT_LONG}, also known as {PRODUCT}, is a cloud-native business automation technology for building cloud-ready business applications.
{PRODUCT} is optimized for a hybrid cloud environment and adapts to your domain and tooling needs.

{PRODUCT_LONG} v{PRODUCT_VERSION} is based on the upstream community project known as https://kie.org/about/[Apache KIE], which stands for `Knowledge Is Everything`.  The Apache KIE Community is a home for leading Open Source projects that play a role in delivering solutions around Business Automation and Artificial Intelligence in the cloud.

The https://kogito.kie.org/[Apache KIE Kogito] initiative is the next generation of business automation platforms focused on cloud-native development, deployment, and execution. Kogito is composed of the battle-tested modules of the Apache KIE group: `Apache KIE Drools` and `Apache KIE jBPM`.

The core objective of {PRODUCT}'s implementation of Kogito-based microservices is to help you mold a set of decisions into your own domain-specific cloud-native set of services.
As a developer of business automation applications, you can use {PRODUCT} Version {VERSION} to build cloud-native applications that adapt your business domain and tooling.

== Overview

This chapter describes how to migrate your existing business automation applications and platforms to {PRODUCT_LONG}.
The following topics are covered in this chapter:

- xref:{RH_BPMS_MIGRATION_DOC_LINK}[Red Hat v6 to v7] for migration from {RH_BPMS} to v7 of the former Red Hat offerings of {RH_PAM} and/or {RH_DM}.
- xref:redhat-to-ibm.html[Red Hat v7 to {PRODUCT} v{VERSION_OLD}] for migration from the former Red Hat offerings _({RH_PAM} and/or {RH_DM})_ to IBM's various enterprise releases of {PRODUCT_DM} ({PRODUCT_DM_SHORT}) and/or {PRODUCT_PAM} ({PRODUCT_PAM_SHORT}).
- xref:now-to-next.html[{PRODUCT} v{VERSION_OLD} {PRODUCT} v{VERSION}] for migration from {PRODUCT_LONG} Version {VERSION_OLD} to {PRODUCT_LONG} Version {VERSION}.
- xref:business-central.html[Business Central] for migration from Business Central to IBM {DEV_TOOLS}.
//- xref:drl.html[Drools Rule Language] for migration to the latest version of Drools Rule Language (DRL).

[NOTE]
====
{PRODUCT_LONG} v{PRODUCT_VERSION} based soley on the Apache KIE module known as  https://kogito.kie.org/[the Kogito Initiative], and currently limited to decision management features such as Decision Model and Notation (DMN), Drools Rule Language (DRL), and Predictive Model Markup Language (PMML). 

This support will be improved and extended to Business Process Modeling Notation (BPMN) in a future release.
====

== Prerequisites

include::../partials/prerequisites.adoc[]
