= Support
include::../partials/attributes.adoc[]

== Support lifecycle policy

Business Automation Manager uses a continuous delivery support model to provide new functions and enhancements more frequently, along with security updates and defect fixes. For more information, see https://www.ibm.com/support/pages/node/7007883[{PRODUCT_LONG} 9.x Product Support Lifecycle].


== Troubleshooting

To enable the {PRODUCT_LONG} Support team (Support) to assist with your problem, you must collect documentation so that the Support team can diagnose your problem. 
Gathering the required documentation before you contact Support expedites the troubleshooting process and saves you time. Otherwise, you might be directed to collect this data after the case is opened to allow us to proceed with our investigation.

For more information on collecting troubleshooting data for {PRODUCT_LONG}, see https://www.ibm.com/support/pages/collect-troubleshooting-data-ibm-business-automation-manager-open-editions-v9-release
