= Using Events in Workflows
include::../partials/attributes.adoc[]
include::../styles/images.adoc[]

The combination of events and business processes is a way to unlock powerful capabilities in automation solutions developed in {PRODUCT_SHORT}. 

== Combining events and Workflows
Here are some examples of the use cases:

* Process monitoring: by emitting events at various stages of a process it is possible to monitor process execution and create real-time dashboards.
* Auditability: use detailed event logs to record significant process changes and provide a complete audit trail for compliance.
* Event-based integration: enable loosely coupled, scalable microservices through actions triggered by events. 
* Optimize processes: use events to enable external consumption of process changes and identify bottlenecks. 

Messaging and event-driven capabilities are provided through a modular and flexible approach using add-ons to enable these capabilities in your Quarkus or Spring Boot based projects. Events are published in the CloudEvents format, making them easily consumable by external systems.

Events are categorized as follows:

Messaging Events:: are related to BPMN message elements enabling a process to register an event listener.

Process/Runtime Events:: are related to process instances, tasks, and variables

== Messaging add-on

The Messaging add-on enables integration between BPMN message elements and external event sources or listeners, depending on the message type:

* Start message node
* Intermediate Message 
* Throw/Catch nodes
* End message node

The following table shows more detail on message events and the corresponding Kafka topics used as channels to publish message events. 

[cols="1,1,1"]
|===
|*Event Type* |*Published when* |*Kafka Topics* 

|Start Message Event
|When message is received on incoming channel to start Process Instance
|Channel name configured in `mp.messaging.incoming.<channel-name>` (e.g., travelers)

|Intermediate Message Throw Event
|During process execution when the throw event node is reached
|Channel name configured in `mp.messaging.outgoing.<channel-name>` (e.g., correlation)

|Intermediate Message Catch Event
|Process waits at this node until message is received on incoming channel
|Channel name configured in `mp.messaging.incoming.<channel-name>` (e.g., customers)

|End Message Event
|When process instance completes and sends final message
|Channel name configured in `mp.messaging.outgoing.<channel-name>` (e.g., processedtravelers)

|Boundary Message Event
|When message is received while attached task is active
|Channel name configured in `mp.messaging.incoming.<channel-name>`

|===

// Correlation feature (although this is advanced and could also be linking to the process-event-driven example itself)

To configure messaging capabilities for your _Business Services_ in Quarkus add the following dependency: 


[source,xml]
----
<dependency>
  <groupId>org.kie</groupId>
  <artifactId>kie-addons-quarkus-messaging</artifactId>
</dependency>
----

As the Quarkus add-on is vendor independent you will need to add the following dependency to be able to use Kafka as the message broker:

[source,xml]
----
<dependency>
  <groupId>io.quarkus</groupId>
  <artifactId>quarkus-messaging-kafka</artifactId>
</dependency>
----

You can see an example application of an event driven process (`process-event-driven`) developed with Quarkus in the {PRODUCT_SHORT} samples, see xref:../getting-started/examples.adoc[Example _Business Service_ projects].

The Spring Boot add-on is Kafka-specific therefore you will only need to add the following dependency to enable messaging:

[source,xml]
----
<dependency>
  <groupId>org.kie</groupId>
  <artifactId>kie-addons-springboot-messaging</artifactId>
</dependency>
----

== Process event add-on

{PRODUCT_SHORT} provides the Process event add-on, used to send processes, tasks, and variable events to an external event listener when execution of an operation modifies the state of a process. These events are known as runtime events, and can include any of the following:

* Any change in the state of a process instance, including execution and violation of SLA
* Any change of state of a task or its metadata, including violation of an SLA 
* any change in existing process definitions at application start including updates to metadata or structure. Used to capture and track the definition and version of processes. 

The Process event add-on can also be used to build a historical representation of all process instance executions. If you use this add-on with the Process REST API you can also build a custom graphical user interface to handle the user tasks.

Each modifying operation is executed within an abstraction called a unit of work. A runtime event is published when a unit of work is completed. Events are published in the CloudEvents format to one of three Kafka Topics. See table below for more details on the publication of the three supported event types. 

[cols="1,1,1"]
|===
|*Event Type* |*Published when* |*Kafka Topics* 

|`ProcessInstanceEvent` 
a| * the process instance changes state (started, ended - completed/aborted, migrated to a different version, updated - when a change in the internal state happens e.g., retriggering the SLA)
* there is an error in the process execution
* each time a node is executed
* there is a change in variables
* an SLA is violated
|`kogito-processinstances-events`


|`UserTaskInstanceEvent` 
a|* the task state changes (transitions between states)
* the task assignments change (the owner or actor of the task)
* the task deadlines aren't met
* there are variable changes (inputs or outputs)
* there are changes in the task attachments (added, modified, deleted)
* there are changes in the task comments (added, modified, deleted)
|`kogito-usertaskinstances-events`

|`ProcessDefinitionEvent` 
a|* when process definitions change (metadata and node structures). 

|`kogito-processdefinitions-events`

|===

In Quarkus, you configure process event capabilities for your _Business Services_ by adding the process event add-on using the following dependency:

[source,xml,subs="+attributes"]
----
<dependency>
  <groupId>org.kie</groupId>
  <artifactId>kie-addons-quarkus-events-process</artifactId>
</dependency>
----

In Spring Boot, you configure process event capabilities for your _Business Services_ by adding the following dependency:

[source,xml,subs="+attributes"]
----
<dependency>
  	<groupId>org.kie</groupId>
  	<artifactId>kie-addons-springboot-events-process-kafka</artifactId>
</dependency>
----

The Process event add-on for Spring Boot is specific to Kafka. Therefore, you do not need to add additional dependencies to use an event broker.

For Quarkus, the {PRODUCT_SHORT} process event add-on implementation is based on Smallrye Messaging library, which provides a set of connectors for event brokers, such as JMS, AMQP, and Kafka. The Smallrye connector dependency is part of the `quarkus-messaging-kafka` dependencey.

Smallrye defines an abstraction named channel to enable multi-broker support. For every channel that you define in your _Business service_ application, you can specify the connector to use for that channel using the following form:

[source,console,subs="+attributes"]
----
mp.messaging.[incoming|outgoing].<channel name>.connector = <connector name>
----

Optionally, for Kafka connector, you can define the Kafka topic to be used for that channel using the following form:

[source,console,subs="+attributes"]
----
mp.messaging.[incoming|outgoing].<channel name>.topic = <topic name>
----

You can also set up a channel property using the following form:

[source,console,subs="+attributes"]
----
mp.messaging.[incoming|outgoing].<channel name>.<property name>= <property value>
----

If the defined property is not found, then the topic name is considered to be the same as Kafka name.

The process event add-on defines a channel for each event type (`kogito-processinstances-events`, `kogito-usertaskinstances-events`, `kogito-variables-events`, `kogito-processdefinitions-events`). Therefore, when the process event add-on is enabled, you must add the event types to your `application.properties` file using the following properties:

[source,properties,subs="+attributes"]
----
# Kafka broker URL
kafka.bootstrap.servers=localhost:9092

# Process instance events
mp.messaging.outgoing.kogito-processinstances-events.connector=smallrye-kafka
mp.messaging.outgoing.kogito-processinstances-events.topic=kogito-processinstances-events
mp.messaging.outgoing.kogito-processinstances-events.value.serializer=org.apache.kafka.common.serialization.StringSerializer

# User task events
mp.messaging.outgoing.kogito-usertaskinstances-events.connector=smallrye-kafka
mp.messaging.outgoing.kogito-usertaskinstances-events.topic=kogito-usertaskinstances-events
mp.messaging.outgoing.kogito-usertaskinstances-events.value.serializer=org.apache.kafka.common.serialization.StringSerializer

# Variable events
mp.messaging.outgoing.kogito-variables-events.connector=smallrye-kafka
mp.messaging.outgoing.kogito-variables-events.topic=kogito-variables-events
mp.messaging.outgoing.kogito-variables-events.value.serializer=org.apache.kafka.common.serialization.StringSerializer

# Process definition events
mp.messaging.outgoing.kogito-processdefinitions-events.connector=smallrye-kafka
mp.messaging.outgoing.kogito-processdefinitions-events.topic=kogito-processdefinitions-events
mp.messaging.outgoing.kogito-processdefinitions-events.value.serializer=org.apache.kafka.common.serialization.StringSerializer
----

Additionally, you can disable the publishing on any channel by setting the related property to false as shown in the following example:

[source,props,subs="+attributes"]
----
kogito.events.usertasks.enabled=false
kogito.events.variables.enabled=false
----

== Managing Event Data

When designing _Business Services_ with event-driven capabilities it is important to evaluate and define how event data is handled:

Security and privacy:: If your events and messages transmit sensitive data review recommended methods to secure data and integration with your events platform.

High volume of events:: Be prepared to manage high volumes of events in particular for frequently executed processes. to do this you will need to put in place scaling and event buffering mechanisms in the Kafka environment. 

Event retention policy:: Storing events for long periods of time requires more storage resources which directly impacts the final cost of your system. You can mitigate this by adjusting event retention policies. 