= Getting started with process automation
include::../partials/attributes.adoc[]

This section provides information on how to access the technology preview and describes how to create a stateful hiring process through an example: xref:../getting-started/examples.html[jbpm-compact-architecture-example]. This example drives a candidate through different interviews to the successful hiring decision. The example includes the use of DMN decisions to generate the candidate offer and timers to skip user tasks. 

== Accessing the technology preview

Question - is there anything to specifically install for the technology preview?

// TODO: Add any installation information to enable developers to access the stateful workflow functionality

== Creating a stateful Hiring process 

In this section we will focus on how to build and configure the Hiring process in Canvas. The example README provides more information on how to configure the recommended architecture for stateful processes in the {PRODUCT_SHORT} environment: Compact Architecture because it enables the simplification of communication between services, removing the need for events (Kafka/HTTP). 

The source for this sample can be found in your installation in the bamoe-9.1.0-examples.zip

// TODO: add procedural descriptions to enable users to understand how to create a stateful workflow application

Link to current sample readme: https://github.com/apache/incubator-kie-tools/tree/main/examples/jbpm-compact-architecture-example#readme

Related PR: https://github.com/apache/incubator-kie-kogito-examples/pull/1833

