= Getting started with process automation
include::../partials/attributes.adoc[]

This section provides information on how to access the technology preview and describes how to create a stateful hiring process through an example: xref:../getting-started/examples.html[jbpm-compact-architecture-example]. This example drives a candidate through different interviews to the successful hiring decision. The example includes the use of DMN decisions to generate the candidate offer and timers to skip user tasks. 

== Accessing the technology preview

The features from the technology preview can be accessed by importing the technology preview bill of materials (BOM). A bill of materials (BOM) can be added to an existing POM file by adding it to the **_dependencyManagement_** section as a dependency with a pom type:

include::../partials/maven-bom-techpreview.adoc[]

After the technology preview bill of materials is added, individual features from it can be enabled by adding relevant dependencies declared in the technology preview bill of materials to the **_dependencies_** section of an existing POM file.

== Creating a stateful Hiring process 

In this section we will focus on how to build and configure the Hiring process in Canvas. The example README provides more information on how to configure the recommended architecture for stateful processes in the {PRODUCT_SHORT} environment: Compact Architecture because it enables the simplification of communication between services, removing the need for events (Kafka/HTTP). 

The source for this sample can be found in your installation in the bamoe-9.1.0-examples.zip

// TODO: add procedural descriptions to enable users to understand how to create a stateful workflow application

Link to current sample readme: https://github.com/apache/incubator-kie-tools/tree/main/examples/jbpm-compact-architecture-example#readme

Related PR: https://github.com/apache/incubator-kie-kogito-examples/pull/1833

