= Getting started with stateful processes
include::../partials/attributes.adoc[]

This section walks you through the installation of the technology preview and a stateful hiring process example that drives a candidate through different interviews to the successful hiring decision. The example includes the use of DMN decisions to generate the candidate offer and timers to skip user tasks. 

== Installing the technology preview

Question - is there anything to specifically install for the technology preview?

// TODO: Add any installation information to enable developers to access the stateful workflow functionality

== Creating a stateful Hiring process 

This example demonstrates how to configure the recommended architecture for stateful processes in the BAMOE environment. This is referred to as the Compact Architecture because it enables the simplification of communication between services, removing the need for events (Kafka/HTTP). This can be achieved using the following Quarkus addons:

kogito-addons-quarkus-data-index-persistence-postgresql:: enables the Kogito Runtime to persist directly into the Data-Index database

kogito-addons-quarkus-jobs:: enables the collocation of the Jobs Service inside the Kogito RuntimeThis example shows how to include user tasks and timers in your workflow. It also explains how persistance is configured. 

The source for this sample can be found in your installation in the bamoe-9.1.0-examples.zip

// TODO: add procedural descriptions to enable users to understand how to create a stateful workflow application

Link to current sample readme: https://github.com/apache/incubator-kie-tools/tree/main/examples/jbpm-compact-architecture-example#readme

Related PR: https://github.com/apache/incubator-kie-kogito-examples/pull/1833

