= Overview stateful process technology preview

include::../partials/attributes.adoc[]

Stateful business process services are introduced as a technology preview in this {PRODUCT} {PRODUCT_VERSION}. A technology preview is not fully supported by IBM and therefore the functionality provided should not be deployed in a production system. IBM will be collecting your feedback on the using the technical preview through xxxx. 

As a developer of business processes, you can use BAMOE to develop process services using Business Process Model and Notation (BPMN) 2.0 models. BPMN process models are graphical representations of the steps required to achieve a business goal. You can design your BPMN processes with Canvas or the Kogito BPMN modeler in VSCode. Alternatively you can import existing BPMN processes into your BAMOE projects for deployment and execution.

For more information about BPMN, see the Object Management Group (OMG) Business Process Model and Notation 2.0 specification https://www.omg.org/spec/BPMN/2.0/About-BPMN 

This section also describes the components and architecture of stateful workflow service which will be referred to as the Compact Architecture. This is a new way to setup the BAMOE environment using a new set of Addons to colocate certain services directly in the Runtime. This architecture simplifies the application configuration and minimizes the communication between components which ensures that Kogito applications are stable and robust in a Business Process environment. 

// TODO: Complete overview content including diagrams





