= WorkItemHandler Library
include::../partials/attributes.adoc[]
include::../styles/images.adoc[]

The BAMOE WorkItemHandlers Library is a framework providing a centralized collection of BAMOE-supported Work Item Handlers (WIHs). This library is designed to be a logical grouping of handlers, and it includes independent dependencies for each handler.

This section provides information about the elements of the BAMOE WorkItemHandlers Library that help you design, develop, deploy, and manage _Business Services_ effectively.

- xref:../workflow/WIH-BAMOE-REST.adoc[REST Service Call Task WorkItemHandler]
- xref:../workflow/WIH-gen-ai-task.adoc[GenAI Task WorkItemHandler]
- xref:../workflow/WIH-ai-agent-task.adoc[AI Agent Task WorkItemHandler]
- xref:../workflow/WIH-use-cases-errors.adoc[WorkItemHandler use cases and error handling]

You can also create a custom WorkItemHandler. For more information, see the xref:./extending-workflow-engine.adoc#custom-wih[Creating a custom WorkItemHandler] section.

If you do not have an existing project, to get started with the BAMOE WorkItemHandlers Library, do the following steps:

. Create a new project using BAMOE Accelerator.
. Open a workflow in the BPMN Editor.
. Add a REST Service Call Task.
. Configure it through the properties panel.
. Deploy and run.

If you already have a project, with BAMOE WorkItemHandlers Library you can access new authentication and configuration options with comprehensive guidance for REST integration patterns. You can adopt the library in your existing projects without breaking changes, since existing REST WorkItemHandlers are still supported. You can leverage new validation rules for better development-time feedback and update workflows to use new REST Service Call Task for enhanced visual configuration.