= Technology preview: Stateful workflow

include::../partials/attributes.adoc[]

Stateful business process services are introduced as a technology preview in this {PRODUCT} {PRODUCT_VERSION}. The functionality available in a technology preview is not supported in a production system and should only be used to discover and test in a development environment. If you encounter problems with the functionality you can contact IBM support in the usual way. You can also consult the forum to see feedback from other users. 

This section includes all the information you need to get started with the technology preview.

* xref:overview.html[Overview] - provides you with the information you need to understand the components and architecture of stateful workflow service.

* xref:gs-stateful-processes.html[Getting started] - explains how to install and access the technology preview, walking you through an example of a stateful hiring process.

* xref:workflow-with-bpmn.html[Workflow with BPMN] - documents the new BPMN support provided in BAMOE to support stateful workflows.

* xref:deploying-process-services.html[Deploying a stateful process service] - explains how to deploy a stateful process service and how that differs from a straight through workflow.