= Designing Architecture
:DM:
:PAM:
:imagesdir: _images
include::_artifacts/document-attributes.adoc[]

//@comment: As we add other related content about architecture (such as process management architecture), we can expand this title, add a parent title with intro, and context, and broaden the master-docinfo file, like we have with the other multi-assembly titles. See others for an example to follow when the time comes. (Stetson, 10 Aug 2020)

As a business analyst, system administrator, or business rules developer, the types of {PRODUCT} business assets that you create and the way in which you develop, store, execute, and deploy those assets varies based on the needs of your business automation environment. You can design a decision management architecture that uses {CENTRAL} or an external integrated development environment (IDE) for asset development, a built-in or external Git repository for storage and version control, a {KIE_SERVER} or embedded application for deployment, or other implementation combinations. You can also deploy {PRODUCT} into a {OPENSHIFT} environment for an enhanced containerized implementation.

This document describes basic concepts and options for an {PRODUCT} implementation to consider when designing your decision management architecture. To verify the most suitable implementation for your environment, contact your Red Hat Technical Account Manager or Solutions Architect.

// Assembly includes


// Versioning info
//include::_artifacts/versioning-information.adoc[]

// Contact information
//include::_artifacts/author-group.adoc[]

