= IBM Business Automation Manager Open Editions :: Documentation

Documentation for the IBM Business Automation Manager Open Editions product lives here.
It is a combination of Asciidoc files and possibly links to other repositories within the Apache KIE community.

== Installing asciidoctor

Please consult the https://asciidoctor.org/#installation[asciidoctor installation instructions].

== Building

Using either the native asciidoctor, asciidoctor.js, or asciidoctor in Docker, execute the following command to build the documentation from the cloned repository:

[source,shell]
----
rm -rf output && mkdir output && cp -r images output/images && asciidoctor -vw -R . -D output **/*.adoc
----

This will build all the files as HTML, show you any warnings, and output into the `output` directory, which is ignored by git.

== Authoring

We recommend using the https://github.com/asciidoctor/asciidoctor-vscode[VS Code extension] for authoring and previewing.

== Writing Conventions

* One sentence per line.
* Tables one column per line, rows seperated by an empty line.
* TBD

== Repository Layout

The root of the repository contains a `nav.adoc` file, which closely resembles an https://antora.org[Antora] navigation file.
This is used in building the Table of Contents (TOC) for the documentation.

Each main section in the navigation file corresponds to a directory.
Each secondary section of the navigation has its own file.

Images are kept at the root level.

All attributes are in the `partials/attributes.adoc` file and included at the top of every file.

== Adding shadow to screenshots

Regular screenshots don't have any dropshadow, which makes them too flat on the asciidoc theme that these docs are rendered to. In order to fix this we can add some css. Make sure to include the `styles/images.adoc` in the top of your file:

[source,asciidoc]
----
\include::../styles/images.adoc[]
----

