= Support
:DM:
:PAM:
:imagesdir: _images
include::_artifacts/document-attributes.adoc[]


== Support lifecycle policy
Business Automation Manager uses a continuous delivery support model to provide new functions and enhancements more frequently, along with security updates and defect fixes. For more information, see https://www.ibm.com/support/pages/node/6603031(IBM Business Automation Manager Open Editions Software Support Lifecycle Addendum).

== Troubleshooting
When opening a case with JBoss Middleware Support, it is not known what information the support engineers need to diagnose the issue. As a result, the first response from JBoss Support is often a request for additional information. This results in an initial delay in resolving the issue. To open an issue for IBM Business Automation manager, see https://access.redhat.com/articles/17131#rhpam(What information do I supply when opening a Middleware support case?).

//include::_artifacts/snip-conscious-language.adoc[]

// Assembly includes


// Contact information
//include::_artifacts/author-group.adoc[]

