= Support
:DM:
:PAM:
:imagesdir: _images
include::_artifacts/document-attributes.adoc[]


== Support lifecycle policy
Business Automation Manager uses a continuous delivery support model to provide new functions and enhancements more frequently, along with security updates and defect fixes. For more information, see https://www.ibm.com/support/pages/node/6603031[IBM Business Automation Manager Open Editions Software Support Lifecycle Addendum].

== Troubleshooting
To enable the IBM Business Automation Manager Open Editions Support team (Support) to assist with your problem, you must collect documentation so that the Support team can diagnose your problem. Gathering the required documentation before you contact Support expedites the troubleshooting process and save you time. Otherwise, you might be directed to collect this data after the case is opened to allow us to proceed with our investigation.
For more information on collecting troubleshooting data for IBM Business Automation Manager Open Editions, see https://www.ibm.com/support/pages/collect-troubleshooting-data-ibm-business-automation-manager-open-editions-v8-release[Collect troubleshooting data for IBM Business Automation Manager Open Editions for V8 Release].
 
//include::_artifacts/snip-conscious-language.adoc[]

// Assembly includes


// Contact information
//include::_artifacts/author-group.adoc[]

