= Upgrading to BAMOE 8.0.x
:DM:
:PAM:
:imagesdir: _images
include::_artifacts/document-attributes.adoc[]

The offerings formally known as {RH_PAM}/{RH_DM} were transitioned to IBM in 2022, where the product was re-branded as {PRODUCT_LONG}.

{PRODUCT_LONG} version {VERSION_80} provides upgrade path for customers and workloads formally leveraging the Red Hat offerings.
BAMOE is a functionally equivalent product to the Red Hat offering, customers can easily upgrade from the former Red Hat offering once they have purchased an IBM subscription for {PRODUCT}.

For information about upgrading from version 6 to version 7, see https://docs.redhat.com/en/documentation/red_hat_process_automation_manager/7.0/html/migrating_from_red_hat_jboss_bpm_suite_6.4_to_red_hat_process_automation_manager_7.0/migration-overview-con.html[Upgrading].


[NOTE]
====
If you are using Red Hat Process Automation Manager 7.10 and you want to upgrade to {PRODUCT} {PRODUCT_VERSION}, see https://access.redhat.com/documentation/en-us/red_hat_process_automation_manager/7.10/html-single/installing_and_configuring_red_hat_process_automation_manager/index#assembly-patching-and-upgrading[_Patching and upgrading Red Hat Process Automation Manager 7.10_].

If you are using Red Hat Process Automation Manager 7.11 or higher, follow the instructions in https://www.ibm.com/support/pages/node/6830111[_Migrating from Red Hat Process Automation Manager and Decision Manager 7.x to IBM Business Automation Manager Open Editions 8.0_].
====
