= Upgrading to BAMOE 8.0.x
:DM:
:PAM:
:imagesdir: _images
include::_artifacts/document-attributes.adoc[]

The offerings formally known as {RH_PAM}/{RH_DM} were transitioned to IBM in 2022, where the product was re-branded as {PRODUCT_LONG}.

{PRODUCT_LONG} version {VERSION_80} provides upgrade path for customers and workloads formally leveraging the Red Hat offerings.
BAMOE is a functionally equivalent product to the Red Hat offering, customers can easily upgrade from the former Red Hat offering once they have purchased an IBM subscription for {PRODUCT}.

For information about upgrading from version 6 to version 7, see https://docs.redhat.com/en/documentation/red_hat_process_automation_manager/7.0/html/migrating_from_red_hat_jboss_bpm_suite_6.4_to_red_hat_process_automation_manager_7.0/migration-overview-con.html[Red Hat Process Automation Manager Migration overview].


[NOTE]
====
If you are using Red Hat Process Automation Manager 7.10 and you want to upgrade to {PRODUCT} {PRODUCT_VERSION}, see https://access.redhat.com/documentation/en-us/red_hat_process_automation_manager/7.10/html-single/installing_and_configuring_red_hat_process_automation_manager/index#assembly-patching-and-upgrading[_Patching and upgrading Red Hat Process Automation Manager 7.10_].

If you are using Red Hat Process Automation Manager 7.11 or higher, follow the instructions in https://www.ibm.com/support/pages/node/6830111[_Migrating from Red Hat Process Automation Manager and Decision Manager 7.x to IBM Business Automation Manager Open Editions 8.0_].
====


== {PRODUCT} versioning

{PRODUCT} versions are designated with a numerical `Major.Minor.Patch` format, such as {ENTERPRISE_VERSION_LONG}. In this example, the major release is `8.x.x`, the minor release is `8.0.x`, and the patch release is {ENTERPRISE_VERSION_LONG}. Major releases often require data upgrade, while minor release upgrades and patch updates are typically managed with update tools provided with the {PRODUCT} release artifacts.

The following are the general types of releases for {PRODUCT}:

Major release Upgrades::

Major releases of {PRODUCT} include substantial enhancements, security updates, bug fixes, and possibly redesigned features and functions. Data upgrade is typically required when an application is moved from one major release to another major release, such as from {PRODUCT_OLD} 6.4.x to Red Hat Process Automation Manager 7.0. Automated upgrade tools are often provided with new major versions of {PRODUCT} to facilitate upgrade, but some manual effort is likely required for certain data and configurations. The supported upgrade paths are specified in product announcements and documentation.
+
For upgrade instructions example, see link:https://access.redhat.com/documentation/en-us/red_hat_process_automation_manager/7.0/html/migrating_from_red_hat_jboss_bpm_suite_6.4_to_red_hat_process_automation_manager_7.0/[_Migrating from {PRODUCT_OLD} 6.4 to Red Hat Process Automation Manager 7.0_].



=== Minor release upgrades::

Minor releases of {PRODUCT} include enhancements, security updates, and bug fixes. Data upgrade may be required when an application is moved from one minor release to another minor release. Automated update tools are often provided with both patch updates and new minor versions of {PRODUCT} to facilitate updating certain components of {PRODUCT}, such as {CENTRAL}, {KIE_SERVER}, and the {HEADLESS_CONTROLLER}. Other {PRODUCT} artifacts, such as the {DECISION_ENGINE} and standalone {CENTRAL}, are released as new artifacts with each minor release and you must reinstall them to apply the update.
+
Before you upgrade to a new minor release, apply the latest patch update to your current version of {PRODUCT} to ensure that the minor release upgrade is successful.

=== Patch updates::

Patch updates of {PRODUCT} include the latest security updates and bug fixes. Scheduled patch updates contain all previously released patch updates for that minor version of the product, so you do not need to apply each patch update incrementally in order to apply the latest update. However, for optimal {PRODUCT} performance, apply product updates as they become available. Occasionally, IBM might release unscheduled patch updates outside the normal update cycle of the existing product.
//These may include security or other updates provided by Red Hat Global Support Services (GSS) to fix specific issues, and may not be cumulative updates.
+
Automated update tools are often provided with both patch updates and new minor versions of {PRODUCT} to facilitate updating certain components of {PRODUCT}, such as {CENTRAL}, {KIE_SERVER}, and the {HEADLESS_CONTROLLER}. Other {PRODUCT} artifacts, such as the {DECISION_ENGINE} and standalone {CENTRAL}, are released as new artifacts with each minor release and you must reinstall them to apply the update.

To ensure optimal transition between releases and to keep your {PRODUCT} distribution current with the latest enhancements and fixes, apply new product releases and updates to {PRODUCT} as they become available on the IBM Support page.
