include::../../partials/attributes.adoc[]

= Known limitations

Before you use {PRODUCT_LONG}, make sure that you are aware of the known limitations.

For the most up-to-date information, see the support page which is regularly updated.

The following sections provide the known limitations by BAMOE capability.

This webpage is for known limitations in {PRODUCT_LONG} {VERSION} and its fix releases. When possible, workarounds will be included with the limitations.
Currently, this webpage is empty. However, the latest issues identified in the {PRODUCT_SHORT} will be reported in this document.

* Apache Drools
* Apache Kogito
* KIE Tools
* Technology preview stateful process

Table 1. Apache Drools
[%header,cols=2]
[%autowidth]
|===

|Limitation | Description, workaround
|TBD | TBD
|TBD | TBD

|===


Table 2. Apache Kogito
[%header,cols=2]
[%autowidth]
|===

|Limitation | Description
|TBD | TBD
|TBD | TBD

|===

Table 3. KIE Tools
[%header,cols=2]
[%autowidth]
|===

|Limitation | Description
|TBD | TBD
|TBD | TBD

|===


Table 4. Technology preview stateful process
[%header,cols=2]
[%autowidth]
|===

|Limitation | Description
|TBD | The management console does not support authentification for basic task inbox management capabilities when it is used with the technology preview for stateful processes.
|TBD | TBD

|===