= Licensing Guide
include::../../partials/attributes.adoc[]

[NOTE]
====
This License Guide is intended to provide only supplementary information to assist you in deploying the Program(s) you have licensed from IBM within your purchased entitlement. Your license agreement (such as the _IBM International Program License Agreement_ (IPLA) or equivalent and its transaction documents, including the License Information for {PRODUCT_LONG}, is the sole and complete agreement between you and IBM regarding use of the {PRODUCT_LONG}.
====

If you are not familiar with the concepts of how licensing works for IBM software, see the https://www.ibm.com/about/software-licensing/us-en/licensing/basics[Licensing Basics], https://www.ibm.com/about/software-licensing/us-en/licensing/essentials[Essential Elements], and https://www.ibm.com/about/software-licensing/us-en[Licensing & Compliance] pages.

The licensing information for {PRODUCT_LONG} is divided into the following sections.

* Licensing Overview
** Licensing for Disaster Recovery or Backup
** Supporting Program: IBM Robotic Process Automation
* License Metrics
* License Reporting
* Accessing the software

== Licensing Overview

{PRODUCT_LONG} is available to clients who have entitlement by purchasing part numbers from IBM directly, or through IBM business partners.

IBM offers {PRODUCT_LONG} license subscriptionsfootnote:[For additional information on what is the IBM's Software Subscription and Support License refer to the https://www.ibm.com/software/passportadvantage/licensing.html[Passport Advantage Licensing Overview]].

Different part numbers are available for purchase depending on the chosen usage pattern and on the desired capabilities of {PRODUCT_LONG}.

Clients can choose entitlements for the following components available in the {PRODUCT_LONG} offering:

- https://www.ibm.com/products/business-automation-manager-open-editions/decision-manager[{PRODUCT_DM}]
- https://www.ibm.com/products/business-automation-manager-open-editions/process-automation-manager[{PRODUCT_PAM}]

Details about the capabilities components of {PRODUCT_LONG} can be found in the https://www.ibm.com/docs/en/ibamoe/9.1.x?topic=overview-key-components[documentation].

[NOTE]
====
Evaluation of the product's components, for non-productive usage, in single-user workstations, is available through the https://ibm.biz/bamoe-developer-program[IBM Developer Program for Open Editions].

As the software usage expands, the proper entitlements are required according to license terms.
====

For both components, {PRODUCT_DM} and {PRODUCT_PAM}, clients can expect the following:

- The different parts reflect different levels of entitlement for product capabilities.
- Subscription includes entitlements to running the purchased components in containers or virtual machines.
- This solution is currently not available as a Software as a Service (SaaS) offering.
- While active, the subscription entitles clients to use and receive support for the commercially available releases.
- While maintaining at least one active subscription, each and every active instance or installation of the software requires active subscriptions.

=== Licensing for Disaster Recovery or Backup

When considering backup installations, active licenses are required for backup copies that are running simultaneously with the primary installation. Inactive or idling backup copies typically don't need extra licenses. In-depth information can be found in the https://www.ibm.com/about/software-licensing/assets/guides_pdf/Backup.pdf[Backup and Disaster Recovery Licensing Guide].


You can find the latest LI information for the available components, parts, and software versions in the https://www.ibm.com/about/software-licensing/us-en/product_search?search=5900-AR4&type=pid&platform=[License Information (LI) for {PRODUCT_LONG}].

=== Supporting Program: IBM Robotic Process Automation

Subscriptions for Open Editions include access to https://www.ibm.com/br-pt/products/robotic-process-automation[IBM Robotic Process Automation] as a Supporting program.

In such scenario, IBM grants limited access to the supporting program (IBM Robotic Process Automation) at no additional charge on the condition that these programs are used only in conjunction with (and  only to the extent necessary to support) the components of {PRODUCT_LONG}.

==== Included components
The following components are included in the supporting program:

- Unattended Bot Agent
- IBM Robotic Process Automation Environment
- IBM Robotic Process Automation Studio

==== Limitations

Regardless of the number of entitlements obtained to {PRODUCT_LONG}, the entitlement to IBM Robotic Process Automation components is limited to:

- *IBM Robotic Process Automation Environment*: 1 Virtual Server
- *IBM Robotic Process Automation Unattended Bot Agent*: 1 Concurrent Connection

Usage of IBM Robotic Process Automation is allowed in traditional installations only; container-based installations are not included.

Any additional use of IBM Robotic Process Automation will require separate entitlement to IBM Robotic Process Automation.

== License Metrics

{PRODUCT_LONG} offerings are licensed on a capacity basis. Clients purchase entitlements for the number of Virtual Processor Cores (VPCs) that will be used by the software ({PRODUCT_DM} and/or {PRODUCT_PAM}).

Virtual processor core (VPC) is a unit of measurement that is used to determine the licensing cost of IBM products. When you license a virtual machine (VM), VPC is based on the number of virtual cores that are assigned to the VM. One VPC license is required for every core that is available to the IBM program.

In short, {PRODUCT_LONG} deployments are licensed by *Virtual Processor Core (VPC)*, where generally, 1 VPC = 1 physical core or 1 virtual core.

Regarding the usage of the product in association with the entitled number of VPCs:

** Active subscriptions allow product deployments into as many environments as clients choose, as long as they don’t exceed the total number of VPCs they have purchased.
** The number of entitlements must cover the highest expected usage of VPCs during peak periods.
** Clients are responsible for ensuring they don’t exceed their deployment entitlement.

Additional information, can be found at https://www.ibm.com/software/passportadvantage/about_software_licensing.html[IBM Licensing Metrics].

== License Reporting

The IBM License Metric Tool (ILMT) tracks which software programs are installed on particular physical hardware. ILMT provides reports that can be presented to IBM when compliance around entitlement capacity is requested. The tool can also be used to track installations in VMs entitled under VPCs.

When installing {PRODUCT_LONG} in *containers*:

* The container size specifies the CPU-limit of the container. This is reported as the deployment size of the container instance for {PRODUCT_LONG}. If no CPU-limit is set for the container, then the reported size of the container is set to be the size of the worker node where the container instance is deployed.
* Container deployments of the product components must use IBM License Service to report on their deployment for licensing usage.The IBM License Service needs to be deployed on Kubernetes.
* Learn the details about set up of the License Service with {PRODUCT_LONG} in the documentation section https://www.ibm.com/docs/en/ibamoe/9.1.x?topic=installing-license-metric-tool-ilmt[IBM License Metric Tool (ILMT)].

When installing {PRODUCT_LONG} in *Virtual Machines (VMs)*:

* the size of the Virtual Machine will determine the size that needs to be entitled. Licensing is unaffected if multiple other products are deployed in the same Virtual Machine.
* Deployments in Virtual Machines need to use IBM License Management Tool (ILMT) or other approved tools for tracking deployments in sub-capacity environments.
* For additional information on how ILMT tracks deployments of VPC metrics in Virtual Machines, refer to the https://www.ibm.com/docs/en/license-metric-tool?topic=metrics-virtual-processor-core-vpc[Documentation for License Metric Tool - Virtual processor core (VPC)].


IBM clients are responsible for:

* Deploying and configuring {PRODUCT_LONG} in line with their license entitlement.
* Ensuring container deployments are reporting correctly to IBM License Service.
* Ensuring that if installing into virtual machines, that ILMT or other tools are correctly configured to track installations.

== Accessing the software

There are no activation keys for using {PRODUCT_LONG}.

To access the product purchased, clients should log in to IBM Passport Advantage and download the product install images they want to use.

{PRODUCT_LONG} offers downloadable resources for installing on-premise and certified container images for deployment into supported Kubernetes environments.

Available supporting programs are also available for download from Passport Advantage.


