include::../../partials/attributes.adoc[]

= {PRODUCT_LONG} {VERSION_901} release notes

The release notes contain information to ensure the successful installation and operation of {PRODUCT_LONG} Version {VERSION_901} fix release. Last updated 16th November 2023.

== Contents

* <<Description>>
* <<New in this release>>
* <<System requirements>>
* <<Fix lists>>
* <<Known limitations>>
* <<Download documents>>
* <<Upgrade {PRODUCT_SHORT} from Version 9.0.0 to Version 9.0.1>>

== Description

{PRODUCT_LONG}, {VERSION_901}  fix release provides important bug fixes requested by customers and the security fixes to CVEs.

== New in this release
    
* Documented the ILMT compliance and reporting of customer usage for {PRODUCT_SHORT} Version {VERSION_901}
* Documented instructions for patch update from {VERSION_900} to {VERSION_901}
* Delivered Migration guide for Version 9.0
* Delivered Security bulletin for {CANVAS} and runtime libraries
* Support for Quarkus Version 2.16.12

== System requirements

This section highlights the supported version updates in Version {VERSION_901} fix release. 
You can access the detailed system requirements from the IBM Support site link for {PRODUCT} {VERSION_901} fix release.
See https://www.ibm.com/software/reports/compatibility/clarity-reports/report/html/softwareReqsForProduct?deliverableId=839878FFE5974B07B85E83D0B1D368B0[Detailed system requirements].

== Fix lists
The summary list of fixes that are included in Version {VERSION_901} fix release.

* git-cors-proxy-image and kie-sandbox-image do not work on macOS ARM processors  
* MvelCompiler is not coercing type double apache or incubator-kie-issues
* Usage of appropriate BigDecimal method to convert to primitive type apache or incubator-kie-issues
* {CANVAS} image uses the root filesystem on the container to store its assets and configuration files
* {PRODUCT_SHORT} {VERSION} runtime image fails to run on Kubernetes with readOnlyRootFilesystem: true due to swidtag creation
* ILMT Libraries does not work on native builds

== Known limitations
Stateful processes are not supported in this release. For more information, see <<Unsupported capabilities on 9.0>>

To review the most current known limitations in detail, see Known limitations in {PRODUCT_LONG} {VERSION_901} fix releases. 
The issues that arise will be reported through this source.


== Download documents

The document contains information for obtaining {PRODUCT_LONG} ({PRODUCT_SHORT}) {VERSION_90X}, earlier release and its fix releases, currently Version {VERSION_901}. 
{PRODUCT_SHORT} versions are designated with a numerical Major.Minor.Patch following Open Source community Semantic Versioning principle. 
Fixes for on-premise installs are available through IBM Fix Central, and {CANVAS} container images are available through Quay Container Registry.
For more information, see https://www.ibm.com/support/pages/node/7001673[BAMOE 9.0 Download Document].

== Upgrade {PRODUCT_SHORT} from Version 9.0.0 to Version 9.0.1

To upgrade {PRODUCT_SHORT} from Version 9.0.0 to Version 9.0.1, follow these steps:

* Update QUARKUS Version to {QUARKUS_VERSION_SHORT_12_FINAL}
* Update pom file from their projects with Version 9.0.1 {PRODUCT_SHORT} BOM
* For direct library components, use Version 8.40.1 for drools or Version 1.40.2 for kogito libraries.
* Rebuild projects and re-deploy as regular software rollout.

For {CANVAS}:

The new containers are the drop-in replacements for the existing. 
You can use https://docs.openshift.com/container-platform/4.14/applications/deployments/route-based-deployment-strategies.html#deployments-blue-green_route-based-deployment-strategies[blue/green deployment strategies]

== Unsupported capabilities on 9.0
* Stateful Processes: 

Note that only decisions are supported in BAMOE version 9.0. Stateful process use cases are not yet supported although BPMN files can be used for straight through processing focused on orchestrating rules. This means that stateful processes may not function as expected in your current 9.0 environment if you have implementations based on the open source community versions.