include::../../partials/attributes.adoc[]

= {PRODUCT_LONG}, {VERSION_910}, release notes

The release notes contain information to ensure the successful installation and operation of {PRODUCT_LONG}, Version {VERSION_91x} fix release. Last updated 16th November 2023.

== Contents

* <<Description>>
* <<New in this release>>
* <<System requirements>>
* <<Fix lists>>
* <<Known limitations>>
* <<Download documents>>

== Description

{PRODUCT_LONG}, {VERSION_910}  fix release, provides important bug fixes requested by customers and the security fixes to CVEs.

== New in this release
    
* Helm Chart
* Stateful process services
* TBD
* TBD
* TBD

== System requirements

This section highlights the supported version updates in Version {VERSION_91x} fix release. 
You can access the detailed system requirements from the IBM Support site link for {PRODUCT} {VERSION_91x} fix release.
See https://www.ibm.com/software/reports/compatibility/clarity-reports/report/html/softwareReqsForProduct?deliverableId=839878FFE5974B07B85E83D0B1D368B0[Detailed system requirements].

== Fix lists
The summary list of fixes that are included in Version {VERSION_901} fix release.

* git-cors-proxy-image and kie-sandbox-image do not work on macOS ARM processors  
* MvelCompiler is not coercing type double apache or incubator-kie-issues
* Usage of appropriate BigDecimal method to convert to primitive type apache or incubator-kie-issues
* {CANVAS} image uses the root filesystem on the container to store its assets and configuration files
* {PRODUCT_SHORT} {VERSION} runtime image fails to run on Kubernetes with readOnlyRootFilesystem: true due to swidtag creation
* ILMT Libraries does not work on native builds

== Known limitations

To review the most current known limitations in detail, see Known limitations in {PRODUCT_LONG} {VERSION_901} fix releases. 
The issues that arise will be reported through this source.

== Download documents

The document contains information for obtaining {PRODUCT_LONG} ({PRODUCT_SHORT}) {VERSION}, earlier release and its fix releases, currently Version {VERSION_901}. 
{PRODUCT_SHORT} versions are designated with a numerical Major.Minor.Patch following Open Source community Semantic Versioning principle. 
Fixes for on-premise installs are available through IBM Fix Central, and {CANVAS} container images are available through Quay Container Registry.
For more inforamation, see https://www.ibm.com/support/pages/node/7001673


