include::../../partials/attributes.adoc[]

= {PRODUCT_LONG}, {VERSION_910}, release notes

The release notes contain information to ensure the successful installation and operation of {PRODUCT_LONG}, Version {VERSION_910} release. Last updated 3rd May 2024.

== Contents

* <<Description>>
* <<New in this release>>
* <<System requirements>>
* <<Fix lists>>
* <<Known limitations>>
* <<Download documents>>

== Description

{PRODUCT_LONG}, {VERSION_910}  release, provides important bug fixes requested by customers and the security fixes to CVEs.

== New in this release
    
* Helm Chart - A new Helm Chart is available and can be used to deploy {CANVAS} image on a Kubernetes cluster using the Helm package manager. This Helm chart, facilitates the management (define, install, and upgrade) of complex Kubernetes applications.
[Learn more...]

* Technology preview stateful process services - You can use BAMOE to develop process services using Business Process Model and Notation (BPMN) models. You can design your BPMN processes with Canvas or the Kogito BPMN modeler in VSCode. The technology preview relies on a new compact architecture of stateful workflow services, which minimizes the communication between components and ensures that [PRODUCT_SHORT] applications are stable and robust in a Stateful Business Process environment. xref:workflow-techpreview.html[Learn more...]

* New DMN Editor - how does it compare to classic DMN editor? xref:decisions-with-dmn.html[Learn more...]

* New DMN 1.5 support - what does the new support bring in terms of supported constructs? xref:dmn.adoc.html[Learn more...]

* Security fixes - TBD


== System requirements

You can access the detailed system requirements from the IBM Support site link for {PRODUCT} {VERSION_910} release.
See https://www.ibm.com/software/reports/compatibility/clarity-reports/report/html/softwareReqsForProduct?deliverableId=839878FFE5974B07B85E83D0B1D368B0[Detailed system requirements].

An additional section is available inside the documentation that summarizes the tested and supported configurations for {PRODUCT_SHORT} {VERSION_910}. See xref:supported-environments.html[Supported Environments]

== Fix lists
The summary list of fixes that are included in Version {VERSION_910} release.

* git-cors-proxy-image and kie-sandbox-image do not work on macOS ARM processors  
* MvelCompiler is not coercing type double apache or incubator-kie-issues
* Usage of appropriate BigDecimal method to convert to primitive type apache or incubator-kie-issues
* {CANVAS} image uses the root filesystem on the container to store its assets and configuration files
* {PRODUCT_SHORT} {VERSION} runtime image fails to run on Kubernetes with readOnlyRootFilesystem: true due to swidtag creation
* ILMT Libraries does not work on native builds

== Known limitations

To review the most current known limitations in detail, see Known limitations in {PRODUCT_LONG} {VERSION_910} release. 
The issues that arise will be reported through this source.

== Download documents

The document contains information for obtaining {PRODUCT_LONG} ({PRODUCT_SHORT}) {VERSION}, earlier release and its fix releases, currently Version {VERSION_910}. 
{PRODUCT_SHORT} versions are designated with a numerical Major.Minor.Patch following Open Source community Semantic Versioning principle. 
Fixes for on-premise installs are available through IBM Fix Central, and {CANVAS} container images are available through Quay Container Registry.
For more information, see https://www.ibm.com/support/pages/node/7001673


