= BAMOE Version 9.1.0 Supported Configurations

include::../../partials/attributes.adoc[]

This section summarizes the tested and supported configurations available for {PRODUCT_SHORT} {VERSION_910}. Support is available for any issues you identify while using the functionality provided in the product in production or development, physical or virtual environments, and depending on your subscription agreement. For any supplementary details, in particular for patch releases, you can see the https://www.ibm.com/software/reports/compatibility/clarity-reports/report/html/softwareReqsForProduct?deliverableId=7EB91B9BC18A437FB13944FFEA2DC2FF#[IBM Support site link]. 

A supported configuration includes the application containers, the JVM version families and their corresponding Operating Systems.

This section covers GA functionality available with full support. For more information on supported configurations for the technology preview, see xref:../../workflow/overview.adoc[Overview Stateful Process]

[%header,cols=2]
[%autowidth]
|===
|JAVA Virtual Machine | Version
|OPENJDK | 17
|Adoptium Open JDKT | 17
|IBM Semeru Runtime Open Edition |17.0.10.0
//check referece to red hat article

|===

//check if BAMOE works on any application containers OR if this table has to be removed.

== {PRODUCT_SHORT} {VERSION_910} Tested Configurations

A full range of platform tests have been performed on the following configurations:

[%header,cols=3]
[%autowidth]
|===
|Operating System/Chip | Container architecture | JAVA Virtual Machines
|Red Hat Enterprise Linux 8 (RHEL) / x86_64

Red Hat Enterprise Linux 9 (RHEL) / x86_64 | OpenShift Container Platform 4.14 

Kubernetes 1.29 | OpenJDK 17

Adoptium OpenJDK 17

Quarkus 3.8.4
|Microsoft Windows Server 2019 / x86_64

Microsoft Windows Server 2022 / x86_64 | OpenShift Container Platform 4.14

Kubernetes 1.29 | OpenJDK 17

Adoptium OpenJDK 17

Quarkus 3.8.4

|===


== {PRODUCT_SHORT} {VERSION_910} Tested Integrations

[%header,cols=2]
[%autowidth]
|===
|Product| Version
|Visual Studio Code | Latest 
|Apache Kafka | 3.6


|===

The following web browsers were tested as part of the BAMOE 9.1 release process:

[%header,cols=2]
[%autowidth]
|===

|Web Browser | Version
|Google Chrome | Latest release, tested with 125.0.6422.76


|===

== {PRODUCT_SHORT} {VERSION_910} Decision Services Support

Decision services are supported as long as they run in production on an OpenShift Container Platform version in Full or Maintenance support in the Stable and EUS channels of OpenShift.

Any fixes, patches, and CVEs in BAMOE are provided only until the next BAMOE release.

=== Supported runtimes:

[%header,cols=3]
[%autowidth]
|===
|Runtime | Version | JDK
|Quarkus | 3.8.4 | OpenJDK 17
|SpringBoot | 3.2.4 | OpenJDK 17

|===

=== Model level support:
[%header,cols=3]
[%autowidth]
|===
|Language | Version | Quarkus Extension

|DMN (Design) | 1.5 down | Kogito - Decisions (DMN)
|DMN (Runtime) | 1.5 down | Kogito - Decisions (DMN)
|BPMN (Design & Runtime) | 2.0 (TBC) | ? |

|===

== {PRODUCT_SHORT} {VERSION_910} Components:

IBM BAMOE 9.1.0 components correspond to Apache KIE 10.0.0 community components. 

// There was add-ons in the previous versions. Do we need to include it here?