= BAMOE version 9.1.0 supported configurations

include::../../partials/attributes.adoc[]

This section summarizes the tested and supported configurations available for {PRODUCT_SHORT} {VERSION_910}. Support is available for any issues you identify while using the functionality provided in the product in production or development, physical or virtual environments, and depending on your subscription agreement. For any supplementary details, in particular for patch releases, you can see the https://www.ibm.com/software/reports/compatibility/clarity-reports/report/html/softwareReqsForProduct?deliverableId=1EA3BE2E21944FDABF4A432FD818E438[IBM Support site link].

A supported configuration includes the application containers, the JVM version families and their corresponding Operating Systems.

[%header,cols=2]
[%autowidth]
|===
|JAVA Virtual Machine | Version
|OPENJDK | 17
|Adoptium Open JDK | 17
|IBM Semeru Runtime Open Edition |17.0.10.0
|GraalVM Community Edition for JDK | 17 
|Quarkus | 3.8.4
//check referece to red hat article

|===

//check if BAMOE works on any application containers OR if this table has to be removed.

== {PRODUCT_SHORT} {VERSION_910} tested configurations

A full range of platform tests have been performed on the following configurations:

[%header,cols=3]
[%autowidth]
|===
|Operating System/Chip | Container architecture | JAVA Virtual Machines

|Red Hat Enterprise Linux 9 (RHEL) / x86_64 | OpenShift Container Platform 4.14 

Kubernetes 1.29 | OpenJDK 17

Adoptium OpenJDK 17

Quarkus 3.8.4

GraalVM Community Edition for JDK 17

|Microsoft Windows Server 2022 / x86_64 | OpenShift Container Platform 4.14

Kubernetes 1.29 | OpenJDK 17

Adoptium OpenJDK 17

Quarkus 3.8.4

GraalVM Community Edition for JDK 17
|===

For more information on support statements for various Kubernetes platforms, see https://www.ibm.com/support/pages/node/7037216[BAMOE support statements]

== {PRODUCT_SHORT} {VERSION_910} tested integrations

[%header,cols=2]
[%autowidth]
|===
|Product| Version
|Visual Studio Code | Latest 
|Apache Kafka | 3.6


|===

The following web browsers were tested as part of the BAMOE 9.1 release process:

[%header,cols=2]
[%autowidth]
|===

|Web Browser | Version
|Google Chrome | Latest release, tested with 125.0.6422.76


|===

The following database was tested as part of the BAMOE 9.1 release process:

[%header,cols=2]
[%autowidth]
|===

|Database | Version
|Postgres| 16.1

|===

== {PRODUCT_SHORT} {VERSION_910} decision services support

Decision services are supported as long as they run in production on an OpenShift Container Platform version in Full or Maintenance support in the Stable and EUS channels of OpenShift.

Any fixes, patches, and CVEs in BAMOE are provided only until the next BAMOE release.

=== Supported runtimes:

[%header,cols=3]
[%autowidth]
|===

|Runtime | Version | JDK
|Quarkus | 3.8.4 | OpenJDK 17

|===

=== Model level support:

[%header,cols=2]
[%autowidth]
|===

|Language | Version 
|DMN | 1.5
|BPMN | 2.0

|===
