= What's new in version 9.1.1
include::../../partials/attributes.adoc[]

{PRODUCT_LONG}, version {VERSION_911} introduces significant enhancements and capabilities as well as providing critical security and known issue fixes.


=== Standalone editors released in version {VERSION_911}

Standalone BPMN and DMN Editors can be embedded in your application from version {VERSION_911} . The same editors used in both BAMOE Canvas and BAMOE Developer Tools for VS Code are available as standalone Javascript libraries that can be imported into any frontend web application. They are available in two separate libraries that can be installed from https://www.npmjs.com/org/ibm[npm] or downloaded from Passport advantage, see https://www.ibm.com/support/pages/node/7151078[BAMOE 9.1 Download Document]:

* @ibm/bamoe-standalone-bpmn-and-dmn-editors-classic : The classic DMN and BPMN Editors
* @ibm/bamoe-standalone-dmn-editor : The new DMN Editor

For more information on using the editors, see xref:../../tools/editors-libraries.adoc[DMN and BPMN Editors JavaScript Libraries]


=== Modernized Technology Stack

{PRODUCT_SHORT} version {VERSION_911} supports the following new versions for the technology stack:

* IBM Semeru Runtime Open Edition - 17.0.11.0
* Quarkus - 3.8.6
* Red Hat Enterprise Linux (RHEL) - 9.4  
* OpenShift Container Platform - 4.15
* Kubernetes - 1.30 
* Google Chrome - Latest release
* Postgres - 16.4

For more information, see xref:supported-environments.adoc[Supported Environments]

 
== System requirements

A detailed system requirements that can be accessed using the IBM Support site link for {PRODUCT} {VERSION_911} release.
See https://www.ibm.com/software/reports/compatibility/clarity-reports/report/html/softwareReqsForProduct?deliverableId=839878FFE5974B07B85E83D0B1D368B0[Detailed system requirements].

An additional section is available inside the documentation that summarizes the tested and supported configurations for {PRODUCT_SHORT} {VERSION}. See xref:supported-environments.html[Supported Environments]

== Download documents 

A download document that contains the information for obtaining {PRODUCT_LONG} ({PRODUCT_SHORT}) {VERSION}, earlier release and its fix releases, currently Version {VERSION_910}. 
{PRODUCT_SHORT} versions are designated with a numerical Major.Minor.Patch following Open Source community Semantic Versioning principle. 
Fixes for on-premise installs are available through IBM Fix Central, and {CANVAS} container images are available through Quay Container Registry.
For more information, see https://www.ibm.com/support/pages/node/7151078[BAMOE 9.1 Download Document].