= What's new in 9.1.0

include::../../partials/attributes.adoc[]

{PRODUCT_LONG}, version {VERSION_910}, although a minor release, introduces significant enhancements and capabilities as well as providing critical security and known issue fixes.

=== Transition to downstream build

* Independent build - With the version {VERSION_910} release, BAMOE employs a complete downstream build by eliminating dependency on open-source binaries.

* Maven Repository Distribution - The downstream libraries are no longer available on Maven Central. Instead, they are provided in a zip file for integration into corporate Maven Repository Managers such as Nexus or Artifactory. {PRODUCT_SHORT} includes a production-ready Maven repository as a container for customers without a corporate Maven Repository Manager. You can configure the details for local Maven settings using the information in the document. xref:../../installation/configure-maven.adoc[Learn more...]

=== Modernized Technology Stack

* Java upgrade - Version {VERSION_910} incorporates an upgraded technology stack featuring Java 17 and Jakarta EE 10.

* Quarkus LTS upgrade - {PRODUCT_SHORT} version 9.1.0 now supports the latest Long-Term Support (LTS) version of Quarkus 3.8.4, enhancing performance and reliability. 

For more information, see xref:supported-environments.html[Supported Environments]

//Not sure if we give the link to supported environments page like this/ is it required?. 
 
=== Helm Chart
    
A new Helm Chart is available and can be used to deploy {CANVAS} image on a Kubernetes or OpenShift cluster using the Helm package manager. This Helm chart, facilitates the management (define, install, and upgrade) of complex Kubernetes applications. xref:../../installation/kie-helm-charts.adoc[Learn more...]

=== Technology preview: Stateful process services 

Stateful process services are available in this release as a technology preview. This functionality is supported by a new compact architecture which minimizes the inter-component communication and ensures stability and the robustness of your applications. While BPMN models were supported in previous versions, additional BPMN functionality is available to support stateful processes. You can design your BPMN processes with Canvas or the BPMN modeler in VSCode. xref:../../workflow/workflow-techpreview.adoc[Learn more...]

=== New DMN Editor

A New DMN editor in this release provides runtime and design support for DMN 1.5 models at conformance level 3. You can design your DMN models with BAMOE Canvas or import existing DMN models into your {PRODUCT_SHORT} projects for deployment and execution. The 9.0.x DMN editor, referred as the Classic DMN editor, is still available. By default, the New DMN Editor will be opened when you open it. To switch to the Classic DMN Editor, click the "New DMN Editor" dropdown and select "Switch back to the Classic DMN Editor". 

Existing DMN files can be opened directly in the new DMN Editor; however, if they are edited and saved, they will no longer be compatible with the classic DMN editor. xref:../../editing/authoring-decisions.adoc[Learn more...]

=== Samples package

A sample package that includes 19 additional examples, 16 of which focus on workflow use cases, bringing the total to 36 example use cases. The examples section features this comprehensive sample package and accompanying documentation. 
 xref:../../getting-started/examples.adoc[Learn more...]
 
== System requirements

A detailed system requirements that can be accessed using the IBM Support site link for {PRODUCT} {VERSION_910} release.
See https://www.ibm.com/software/reports/compatibility/clarity-reports/report/html/softwareReqsForProduct?deliverableId=839878FFE5974B07B85E83D0B1D368B0[Detailed system requirements].

An additional section is available inside the documentation that summarizes the tested and supported configurations for {PRODUCT_SHORT} {VERSION_910}. See xref:supported-environments.html[Supported Environments]

== Download documents

A download document that contains the information for obtaining {PRODUCT_LONG} ({PRODUCT_SHORT}) {VERSION}, earlier release and its fix releases, currently Version {VERSION_910}. 
{PRODUCT_SHORT} versions are designated with a numerical Major.Minor.Patch following Open Source community Semantic Versioning principle. 
Fixes for on-premise installs are available through IBM Fix Central, and {CANVAS} container images are available through Quay Container Registry.
For more information, see https://supportcontent.ibm.com/support/pages/node/7151078[BAMOE 9.1.0 Download Document].