= What's new in 9.1.0

include::../../partials/attributes.adoc[]

{PRODUCT_LONG}, version {VERSION_910}, a minor  release, introduces substantial enhancements and updates that significantly evolving the product's capabilities while providing important bug fixes and critical security fixes for CVEs.

=== Transition to downstream build

* Independent build - With the version {VERSION_910} release, BAMOE employs a complete downstream build by eliminating dependency on open-source binaries.

* Maven Repository Distribution - The downstream libraries are no longer available on Maven Central. Instead, they are provided in a zip file for integration into corporate Maven Repository Managers such as Nexus or Artifactory. {PRODUCT_SHORT} includes a production-ready Maven repository as a container for customers without a corporate Maven Repository Manager. For configuration details for local Maven settings, see ....

//Seems not the right link but to write a section for it - Checked with Alex

=== Modernized Technology Stack

* Java upgrade - Version {VERSION_910} incorporates an upgraded technology stack featuring Java 17 and Jakarta EE 10.

* Quarkus LTS upgrade - {PRODUCT_SHORT} version 9.1.0 now supports the latest Long-Term Support (LTS) version of Quarkus 3.8.4, enhancing performance and reliability.
 
=== Helm Chart
    
A new Helm Chart is available and can be used to deploy {CANVAS} image on a Kubernetes or OpenShift cluster using the Helm package manager. This Helm chart, facilitates the management (define, install, and upgrade) of complex Kubernetes applications. xref:../../installation/kie-helm-charts.adoc[Learn more...]

=== Technology preview stateful process services 

The latest BAMOE release introduces a technology preview of stateful workflow services supported by the new compact architecture. This architecture minimizes the inter-component communication and ensures stability and robustness of BAMOE applications in a Stateful Business Process environment. While BPMN models were supported in previous versions, you can now develop process services using Business Process Model and Notation (BPMN) models in a stateful mode. You can design your BPMN processes with Canvas or the Kogito BPMN modeler in VSCode. xref:../../workflow/workflow-techpreview.adoc[Learn more...]

=== New DMN Editor

{PRODUCT_LONG} provides runtime and design support for DMN 1.5 models at conformance level 3. You can design your DMN models with BAMOE Canvas or import existing DMN models into your {PRODUCT_SHORT} projects for deployment and execution. Any DMN models that you import and open in the DMN editor are converted to DMN 1.2 or 1.5 models. xref:../../reference-guide/dmn.adoc[Learn more...]

You can now access a new DMN Editor that is compatible with DMN 1.5. The 9.0.x DMN Editor, referred as the Classic DMN Editor, is still available and will be referenced throughout the user documentation. By default, the New DMN Editor will be opened when you click it. To switch to the Classic DMN Editor, click the "New DMN Editor" dropdown and select "Switch back to the Classic DMN Editor". The existing DMN files can be opened directly in the new DMN Editor; however, once edited and saved in the new editor, they are no longer compatible with the Classic DMN Editor. 
xref:../../runtime-services-modeling/services-execution.adoc[Learn more...] 

=== Samples package

The new version includes 19 additional examples, 16 of which focus on workflow use cases, bringing the total to 36 example use cases. The examples section features this comprehensive sample package and accompanying documentation. 
 xref:../../getting-started/examples.adoc[Learn more...]
 
== System requirements

You can access the detailed system requirements from the IBM Support site link for {PRODUCT} {VERSION_910} release.
See https://www.ibm.com/software/reports/compatibility/clarity-reports/report/html/softwareReqsForProduct?deliverableId=839878FFE5974B07B85E83D0B1D368B0[Detailed system requirements].

An additional section is available inside the documentation that summarizes the tested and supported configurations for {PRODUCT_SHORT} {VERSION_910}. See xref:supported-environments.html[Supported Environments]

== Download documents

The document contains information for obtaining {PRODUCT_LONG} ({PRODUCT_SHORT}) {VERSION}, earlier release and its fix releases, currently Version {VERSION_910}. 
{PRODUCT_SHORT} versions are designated with a numerical Major.Minor.Patch following Open Source community Semantic Versioning principle. 
Fixes for on-premise installs are available through IBM Fix Central, and {CANVAS} container images are available through Quay Container Registry.
For more information, see https://supportcontent.ibm.com/support/pages/node/7151078[BAMOE 9.1.0 Download Document].