= What's new in version 9.1.1
include::../../partials/attributes.adoc[]

{PRODUCT_LONG}, version {VERSION_911} introduces significant enhancements and capabilities as well as providing critical security and known issue fixes.


=== Standalone editors released in version {VERSION_911}

Standalone BPMN and DMN Editors can be embedded in your application from version {VERSION_911} . The same editors used in both BAMOE Canvas and BAMOE Developer Tools for VS Code are available as standalone Javascript libraries that can be imported into any frontend web application. They are available in two separate libraries that can be installed from https://www.npmjs.com/org/ibm[npm] or downloaded from Passport advantage, see https://www.ibm.com/support/pages/node/7151078[BAMOE 9.1 Download Document]:

* @ibm/bamoe-standalone-bpmn-and-dmn-editors-classic : The classic DMN and BPMN Editors
* @ibm/bamoe-standalone-dmn-editor : The new DMN Editor

For more information on using the editors, see xref:../../tools/editors-libraries.adoc[DMN and BPMN Editors JavaScript Libraries]


=== Modernized Technology Stack

{PRODUCT_SHORT} version {VERSION_911} supports the following new versions for the technology stack:

* IBM Semeru Runtime Open Edition - 17.0.11.0
* Quarkus - 3.8.6
* Red Hat Enterprise Linux (RHEL) - 9.4  
* OpenShift Container Platform - 4.15
* Kubernetes - 1.30 
* Google Chrome - Latest release
* Postgres - 16.4

For more information, see xref:supported-environments.adoc[Supported Environments]

 
== System requirements

This section covers the supported configurations for versions {PRODUCT} {VERSION_911} and {VERSION_910}. For more information, see xref:supported-environments.html[Supported Environments]

== Download documents 

For more information on {PRODUCT_LONG} version {VERSION} download document, see https://www.ibm.com/support/pages/node/7151078[BAMOE 9.1 Download Document].