= What's new in 9.1.0

include::../../partials/attributes.adoc[]

The release notes contain information to ensure the successful installation and operation of {PRODUCT_LONG}, Version {VERSION_910} release. Last updated 3rd May 2024.

== Contents

* <<Description>>
* <<New in this release>>
* <<System requirements>>
* <<Download documents>>

== Description

{PRODUCT_LONG}, {VERSION_910}  release, provides important bug fixes requested by customers and the security fixes to CVEs.

== New in this release
    
* Helm Chart - A new Helm Chart is available and can be used to deploy {CANVAS} image on a Kubernetes cluster using the Helm package manager. This Helm chart, facilitates the management (define, install, and upgrade) of complex Kubernetes applications. xref:../../installation/kie-helm-charts.adoc[Learn more...]

* Technology preview stateful process services - You can use BAMOE to develop process services using Business Process Model and Notation (BPMN) models. You can design your BPMN processes with Canvas or the Kogito BPMN modeler in VSCode. The technology preview relies on a new compact architecture of stateful workflow services, which minimizes the communication between components and ensures that {PRODUCT_SHORT} applications are stable and robust in a Stateful Business Process environment.  xref:../../workflow/workflow-techpreview.adoc[Learn more...]

* New DMN Editor - You can access a new DMN Editor that is compatible with DMN 1.5. The 9.0.x DMN Editor can still be used and will be referred to throughout the user doc as the Legacy DMN Editor. By default, the New DMN Editor will be opened when you click on, and the user can choose to switch to the Legacy DMN Editor by clicking into the "New DMN Editor" dropdown and selecting "Switch back to the legacy DMN Editor". Your existing DMN files can be opened directly in the new editor, however once you edit and save them in the new DMN Editor, they are no longer compatible with the Legacy DMN Editor. 
// what is the benefit of using the new editor, apart from getting DMN 1.5 support

To reduce ambiguity in this documentation, we will address the new editor as the New DMN Editor, and the older editor as the Legacy DMN Editor ?


xref:../../runtime-services-modeling/decisions-with-dmn.adoc[Learn more...]

* New DMN 1.5 support - what does the new support bring in terms of supported constructs? xref:../../reference-guide/dmn.adoc[Learn more...]

* Security fixes - TBD


== System requirements

You can access the detailed system requirements from the IBM Support site link for {PRODUCT} {VERSION_910} release.
See https://www.ibm.com/software/reports/compatibility/clarity-reports/report/html/softwareReqsForProduct?deliverableId=839878FFE5974B07B85E83D0B1D368B0[Detailed system requirements].

An additional section is available inside the documentation that summarizes the tested and supported configurations for {PRODUCT_SHORT} {VERSION_910}. See xref:supported-environments.html[Supported Environments]

== Download documents

The document contains information for obtaining {PRODUCT_LONG} ({PRODUCT_SHORT}) {VERSION}, earlier release and its fix releases, currently Version {VERSION_910}. 
{PRODUCT_SHORT} versions are designated with a numerical Major.Minor.Patch following Open Source community Semantic Versioning principle. 
Fixes for on-premise installs are available through IBM Fix Central, and {CANVAS} container images are available through Quay Container Registry.
For more information, see https://www.ibm.com/support/pages/node/7001673[BAMOE 9.1.0 Download Document].