= What's new in 9.1.0

include::../../partials/attributes.adoc[]

The release notes contain information to ensure the successful installation and operation of {PRODUCT_LONG}, Version {VERSION_910} release. Last updated 7th June 2024.

== Contents

* <<Description>>
* <<New in this release>>
* <<System requirements>>
* <<Download documents>>

== Description

{PRODUCT_LONG}, version {VERSION_910}, a minor  release introduces not only substantial enhancements and updates, significantly evolving the product's capabilities but also provides important bug fixes and critical security fixes for CVEs.

== Transition to downstream build

* Independent build - With the version {VERSION_910} release, BAMOE employs a complete downstream build by eliminating dependency on open-source binaries.

* Maven Repository Distribution - The downstream libraries are no longer available on Maven Central. Instead, they are provided in a zip file for integration into corporate Maven Repository Managers such as Nexus or Artifactory. {PRODUCT_SHORT} includes a production-ready Maven repository as a container for customers without a corporate Maven Repository Manager. For configuration details for local Maven settings, see ....

//Seems not the right link but to write a section for it - Checked with Alex

== Modernized Technology Stack

* Java 17 and Jakarta EE 10 - version {VERSION_910} incorporates an upgraded technology stack featuring Java 17 and Jakarta EE 10.

* Quarkus LTS 3.8.x - {PRODUCT_SHORT} version 9.1.0 now supports the latest Long-Term Support (LTS) version of Quarkus, 3.8.x, enhancing performance and reliability.
 

== New and enhanced features
    
* Helm Chart - A new Helm Chart is available and can be used to deploy {CANVAS} image on a Kubernetes cluster using the Helm package manager. This Helm chart, facilitates the management (define, install, and upgrade) of complex Kubernetes applications. xref:../../installation/kie-helm-charts.adoc[Learn more...]

* Technology preview stateful process services - You can use BAMOE to develop process services using Business Process Model and Notation (BPMN) models. You can design your BPMN processes with Canvas or the Kogito BPMN modeler in VSCode. The technology preview relies on a new compact architecture of stateful workflow services, which minimizes the communication between components and ensures that {PRODUCT_SHORT} applications are stable and robust in a Stateful Business Process environment.  xref:../../workflow/workflow-techpreview.adoc[Learn more...]

* New DMN Editor - You can access a new DMN Editor that is compatible with DMN 1.5. The 9.0.x DMN Editor can still be used and will be referred throughout the user doc as the Classic DMN Editor. By default, the New DMN Editor will be opened when you click it, and the user can choose to switch to the Classic DMN Editor by clicking into the "New DMN Editor" dropdown and selecting "Switch back to the Classic DMN Editor". Your existing DMN files can be opened directly in the new editor, however once you edit and save them in the new DMN Editor, they are no longer compatible with the Classic DMN Editor. xref:../../runtime-services-modeling/services-execution.adoc[Learn more...]
// what is the benefit of using the new editor, apart from getting DMN 1.5 support

* New DMN 1.5 support - 
//what does the new support bring in terms of supported constructs? xref:../../reference-guide/dmn.adoc[Learn more...]

* Samples package - A new samples package  that includes all the samples reference by the product and documentation is contained in the examples section. xref:../../getting-started/examples.adoc[Learn more...]
 


== System requirements

You can access the detailed system requirements from the IBM Support site link for {PRODUCT} {VERSION_910} release.
See https://www.ibm.com/software/reports/compatibility/clarity-reports/report/html/softwareReqsForProduct?deliverableId=839878FFE5974B07B85E83D0B1D368B0[Detailed system requirements].

An additional section is available inside the documentation that summarizes the tested and supported configurations for {PRODUCT_SHORT} {VERSION_910}. See xref:supported-environments.html[Supported Environments]

== Download documents

The document contains information for obtaining {PRODUCT_LONG} ({PRODUCT_SHORT}) {VERSION}, earlier release and its fix releases, currently Version {VERSION_910}. 
{PRODUCT_SHORT} versions are designated with a numerical Major.Minor.Patch following Open Source community Semantic Versioning principle. 
Fixes for on-premise installs are available through IBM Fix Central, and {CANVAS} container images are available through Quay Container Registry.
For more information, see https://supportcontent.ibm.com/support/pages/node/7151078[BAMOE 9.1.0 Download Document].