= {PRODUCT_LONG}, {VERSION}, release notes

The release notes contain information to ensure the successful installation and operation of IBM Business Automation Manager Open Editions, Version 9.0.1. Last updated 31st October 2023.

== Contents

<<Description>>
<<New in this release>>
<<Deprecated features and services>>
<<System requirements>>
<<Fix lists>>
<<Installing version 9.0.1>>
<<Known problems>>
<<Download documents>>


== Description[[Description]]

IBM Business Automation Manager Open Editions, Version 9.0.1, enables you to .........

== New in this release[[New in this release]]
    Sample content below
- Seamless git integration ......
- Supports custom registry and specific images
- Enables output error logs of eager i
- Runtime support for DMN 1.4


== Deprecated features and services
    Sample content below
- Red Hat Business Automation VSCode Bundle

== System requirements
The Version 9.0.1 installation program runs a system requirements check and provides a report on the status of your computer.
See pass:[<u>Detailed system requirements</u>], then choose your operating system.
https://www.ibm.com/software/reports//compatibility/clarity-reports/re[…]14%7CC013&mandatoryCapIds=25&optionalCapIds=71%7C26%7C1


== Fix lists
For a summary list of fixes that are included in Version 9.0.1, see the pass:[<u>fix list document</u>].

== Installing version 9.0.1 
Version 9.0.1 is available for installation. Download instructions are available at the following link: https://www.ibm.com/support/pages/node/6322671


== Known problems

To review the most current known problems in detail, see Known problems and limitations in IBM Business Automation Management Open Editions 9.0.1. As problems are discovered and resolved, the IBM Support team updates the knowledge base. By searching the knowledge base, you can quickly find workarounds or solutions to problems.

To view additional known problems in the Support knowledge base, see View APARs for all supported versions of IBM Business Automation Management Open Editions.

== Download document

The document contains information for obtaining IBM Business Automation Manager Open Editions (BAMOE) 9.0.1 and its fix releases. BAMOE versions are designated with a numerical Major.Minor.Patch following Open Source community Semantic Versioning principle. Fixes for on-premises releases are available through IBM Fix Central, and Docker images are available through Red Hat Ecosystem Catalog.
For more inforamation, see https://www.ibm.com/support/pages/node/7001673