include::../partials/attributes.adoc[]
= Using AI Agent Tasks in Workflows

include::../styles/images.adoc[]

The AI Agent task allows you to integrate AI agents into your BPMN workflows, making them smarter and more efficient. This feature is powered by Langflow, an open-source tool that simplifies building AI applications through a visual interface. By using AI Agent tasks, you can automate processes, create intelligent flows, and connect with leading AI models. The AI agent processes the input and returns the result to the next node. 
For more details on Langflow and its capabilities, see https://www.langflow.org.

== Configuring AI provider

To use an AI Agent task, you must configure an AI provider with {CANVAS} or {DEV_TOOLS} extension. Langflow is the only supported provider. You can set up Langflow through {CANVAS} or {DEV_TOOLS} extension as follows:

.Configuring Langflow through {CANVAS}:
. Click the profile icon in the top-right corner.
. Select *Connected accounts* from the menu.
. Choose Langflow from the list of AI providers.
. Enter a display name, Service URL and API Key for your Langflow account.
. Click *Connect* to establish the connection.

.Configure Langflow Through {DEV_TOOLS} Extension:
. Click the profile menu in the bottom-left corner.
. From the available options, select Langflow as your preferred AI provider.
. Enter the Service URL and API Key to establish the connection.

After connecting your Langflow account, from the the property panel you can select the Langflow account which you want to use for the task.

== Integrating AI Agents in development environment
To Integrate AI Agents into your BPMN workflow:

. Drag and drop the AI Agent node to the {CANVAS} or {DEV_TOOLS} extension.
. Select Langflow as the AI provider and choose an Agent from your instance.
+
You can either pick an Agent from the dropdown list linked to your Langflow account or enter the Agent ID directly in the input field. Once selected, the property panel displays basic details about the Agent, including its ID, description, MCP status, and the tag category.
+

. Provide input to the node either from the previous node or as custom input.
+
You can use the `aiAgentInput` variable to provide input to the AI agent. This variable is attached to the input by default and allows the agent to receive data from previously connected nodes, making the input dynamic. You can customize the input text and include process variables using the `{{<variable-name>}}` format.
The input field also includes an Advanced Mode, accessible by clicking the expand icon next to it. This opens an advanced editor with syntax highlighting for `{{<variable-name>}}` and offers autosuggest for process variables.
To use autosuggest, type inside double curly braces and press Ctrl + Space (or Cmd + Space on Mac). A dropdown list of data input mapping variables is displayed, showing the variables defined under Data Mapping Properties. Once you update these variables, the suggestion list automatically refreshes to include new ones.
+
. Add additional variables as needed to customize the mapping according to your specific requirements using Data mapping.
+
Input and output data mapping works the same way as other task types. By default, `aiAgentInput` and `aiAgentOutput` represent the agent’s input and output data. You can add additional variables as needed to customize the mapping and meet your specific requirements.
+

. Test data process variables used in the input by providing temporary values in the Preview table.
+
The Preview Table lets you test process variables used in the input by assigning temporary values. These values replace the variables during testing, allowing you to verify the formate and the agent will receive the expected data when executed.
+
. Test the agent in the property panel to view the results.
+
Use the Test Agent feature to verify the agent’s functionality. This feature executes the agent and displays its real-time response, allowing you to adjust input parameters based on the output until you achieve the desired result.

== Integrating AI Agents in runtime environment
To Integrate AI Agents into your BPMN workflow:

. Add the appropriate Work Item Handler (WIH) dependency to your project for Quarkus or Spring Boot:
+
* `bamoe-ai-agent-task-work-item-handler-spring-boot`
* `bamoe-ai-agent-task-work-item-handler-quarkus`
+
. Configure the `application.properties` file and update the following properties with your actual Langflow details.

[source, properties]
----
bamoe.workflow.ai-agent-task.provider.langflow.base-url=<your-langflow-host>
bamoe.workflow.ai-agent-task.provider.langflow.api-key=<api-key>
----