= Integrating a custom generative AI task in BPMN 
include::../partials/attributes.adoc[]
include::../styles/images.adoc[]

{PRODUCT_SHORT} enables you to create Business Services that contain Workflows able to send prompts that can query LLMs for generated textual-content as part of the business process. The workflow engine is extended via Work Item Handlers to enable this functionality. 

You will need to connect and authenticate to one of the AI providers available in this integration: watsonx, Ollama or Open AI. This authentication applies to your work in {CANVAS} and {DEV_TOOLS}. This is done using the 

Authenticating to AI Providers will work differently between the frontend (BAMOE Canvas and BPMN Editor VSCode extension) and backend (Business Service). In BAMOE Canvas we can leverage our implementations of AuthProviders/[AuthSessions|https://github.ibm.com/dba/bamoe/blob/main/packages-bamoe/canvas/src/authSessions/AuthSessionApi.ts], while in the BPMN Editor VSCode Extension we can leverage the VSCode’s APIs to securily store tokens and API keys. In the Business Service we will rely on evironment variables that can be defined in the application.properties, which in turn can be set during runtime.

To access 

