= Deploying a BAMOE application to OpenShift using Quarkus
include::../partials/attributes.adoc[]

This guide provides instructions for deploying a business application to OpenShift using three different methods. Ensure that the following prerequisites are in place before proceeding.

== Prerequisites

* https://docs.openshift.com/container-platform/4.16/cli_reference/openshift_cli/getting-started-cli.html#installing-openshift-cli[OpenShift CLI (`oc`)]
* https://docs.docker.com/manuals/[Docker]

== Deployment Options

=== 1. Build and Deploy on OpenShift

Use this method to build and deploy the application directly on OpenShift.

[.steps]

. **Log in to OpenShift CLI:**
+
[source,shell]
----
oc login
----

. **Add the OpenShift extension to the Quarkus project:**
+
[source,shell]
----
mvn quarkus:add-extension -Dextensions='quarkus-openshift'
----

. **Update the `src/main/resources/application.properties` file to enable the creation of an OpenShift Route:**
+
[source,properties]
----
# OpenShift
quarkus.openshift.route.expose=true
## Route TLS configuration:
quarkus.openshift.route.tls.termination=edge
quarkus.openshift.route.tls.insecure-edge-termination-policy=None
----

. **Build and deploy the application:**
+
[source,shell]
----
mvn install -Dquarkus.openshift.deploy=true
----

=== 2. Build Locally with Docker and Automatically Deploy on OpenShift

This method involves building the container image for the application locally using Docker, pushing the image to registry, followed by an automatic deployment to OpenShift.

[.steps]

. **Log in to OpenShift CLI:**
+
[source,shell]
----
oc login
----

. **Add the OpenShift extension to the Quarkus project:**
+
[source,shell]
----
mvn quarkus:add-extension -Dextensions='quarkus-openshift'
----

. **Update the `src/main/resources/application.properties` file with the following properties to configure the image and enable the creation of an OpenShift Route:**
+
[source,properties]
----
# Container Image Builder
quarkus.container-image.builder=docker
quarkus.container-image.registry=<image_registry>
quarkus.container-image.group=<registry_group_or_user>
quarkus.container-image.name=<image_name>
quarkus.container-image.tag=<image_tag>
quarkus.docker.buildx.platform=linux/amd64
# OpenShift
quarkus.openshift.route.expose=true
## Route TLS configuration:
quarkus.openshift.route.tls.termination=edge
quarkus.openshift.route.tls.insecure-edge-termination-policy=None
----

[NOTE]
====
**Replaceable Tokens**

In this method, several tokens in the `application.properties` file need to be replaced with actual values:

* `<image_registry>`: The URL of the container image registry where the Docker image will be stored. Example: `docker.io`.
* `<registry_group_or_user>`: The group or user in the container image registry. Example: `myuser`.
* `<image_name>`: The name of the Docker image to be built. Example: `myapp`.
* `<image_tag>`: The tag of the Docker image. Example: `v1.0.0`.

Replace these tokens with appropriate values based on the environment setup.
====

. **Add the `Dockerfile.jvm` file to `src/main/docker`:**
+
[source,Dockerfile]
----
FROM icr.io/appcafe/ibm-semeru-runtimes:open-17-jre-ubi-minimal

USER 0

COPY target /app/

# Support Arbitrary User IDs
# https://docs.openshift.com/container-platform/3.11/creating_images/guidelines.html#openshift-specific-guidelines
RUN chgrp -R 0 /app && \
  chmod -R g+rwX /app

USER 1001

WORKDIR /app

EXPOSE 8080

CMD ["java", "-jar", "quarkus-app/quarkus-run.jar"]
----

. **Build and deploy the application:**
+
[source,shell]
----
mvn install -Dquarkus.openshift.deploy=true
----

=== 3. Build Locally with Docker and Create Manual Deployment on OpenShift

This option provides a way to build the the container image for the application locally using Docker, push the image to a registry, and manually deploy it on OpenShift.

[.steps]

. **Log in to OpenShift CLI:**
+
[source,shell]
----
oc login
----

. **Add the Docker extension to the Quarkus project:**
+
[source,shell]
----
mvn quarkus:add-extension -Dextensions='quarkus-container-image-docker'
----

. **Update the `src/main/resources/application.properties` file with the following properties to configure the image:**
+
[source,properties]
----
# Container Image Builder
quarkus.container-image.builder=docker
quarkus.container-image.registry=<image_registry>
quarkus.container-image.group=<registry_group_or_user>
quarkus.container-image.name=<image_name>
quarkus.container-image.tag=<image_tag>
quarkus.docker.buildx.platform=linux/amd64
----

[NOTE]
====
**Replaceable Tokens**

In this method, several tokens in the `application.properties` file need to be replaced with actual values:

* `<image_registry>`: The URL of the container image registry where the Docker image will be stored. Example: `docker.io`.
* `<registry_group_or_user>`: The group or user in the container image registry. Example: `myuser`.
* `<image_name>`: The name of the Docker image to be built. Example: `myapp`.
* `<image_tag>`: The tag of the Docker image. Example: `v1.0.0`.

Replace these tokens with appropriate values based on the environment setup.
====

. **Add the `Dockerfile.jvm` file to `src/main/docker`:**
+
[source,Dockerfile]
----
FROM icr.io/appcafe/ibm-semeru-runtimes:open-17-jre-ubi-minimal

USER 0

COPY target /app/

# Support Arbitrary User IDs
# https://docs.openshift.com/container-platform/3.11/creating_images/guidelines.html#openshift-specific-guidelines
RUN chgrp -R 0 /app && \
  chmod -R g+rwX /app

USER 1001

WORKDIR /app

EXPOSE 8080

CMD ["java", "-jar", "quarkus-app/quarkus-run.jar"]
----

. **Build and push the Docker image:**
+
[source,shell]
----
mvn install -Dquarkus.container-image.build=true -Dquarkus.container-image.push=true
----

. **Manually create a deployment and expose it on OpenShift:**
+
[source,shell]
----
oc new-app --name=<deployment_name> <image_registry>/<registry_group_or_user>/<image_name>:<image_tag>
oc create route edge --service=<deployment_name>
----

== Conclusion

Choose the appropriate deployment method based on the development workflow and environment requirements. For further customization or troubleshooting, refer to the official Quarkus guides.

- https://quarkus.io/guides/container-image
- https://quarkus.io/guides/deploying-to-openshift

___

[NOTE]
====
The first option will use an UBI OpenJDK base image from RedHat (usually `registry.access.redhat.com/ubi9/openjdk-17`) while the second and third options are based on the IBM Semeru image (`icr.io/appcafe/ibm-semeru-runtimes:open-17-jre-ubi-minimal`), which can be customized by editing the created Dockerfile in `src/main/docker`.
====