= Initial _Business Service_ project setup
include::../partials/attributes.adoc[]
include::../styles/images.adoc[]

_Business Services_ are microservice Java applications built on top of Quarkus or Spring Boot, containing {PRODUCT_SHORT} runtime libraries and Business Automation assets such as Workflows (BPMN), Decisions (DMN), Rules (DRL), and spreadsheet Decision Tables (XLS or XLSX), following https://maven.apache.org/guides/introduction/introduction-to-the-standard-directory-layout.html[Maven's standard  directory layout].

Even though you can manually create everything from scratch, {PRODUCT_SHORT} provides an easier way to get started with pre-configured _Business Sevice_ project Accelerators.

There are four Accelerators that correspond to the two cloud development frameworks supported by {PRODUCT_SHORT} - Quarkus and Spring Boot:

- **`Quarkus (DMN)`** - For _Business Services_ that contain Decisions, Rules, or spreadsheet Decision Tables.
- **`Quarkus (Full)`** - For _Business Services_ that contain stateful Workflows in addition to Decisions, Rules, or spreadsheet Decision Tables.
- **`Spring Boot (DMN)`** - For _Business Services_ that contain Decisions, Rules, or spreadsheet Decision Tables.
- **`Spring Boot (Full)`** - For _Business Services_ that contain stateful Workflows in addition to Decisions, Rules, or spreadsheet Decision Tables.

There are three options to use Accelerators to set up your project:

* a. Create new Decisions and/or Workflows on {CANVAS} then apply an Accelerator.
* b. Open a new or existing folder in VS Code with {DEV_TOOLS} installed, and apply an Accelerator.
* c. (Advanced) Create a Java project manually, adding dependencies to the _Business Service_ project configuration file, using Accelerators as reference.

[NOTE]
====
It is possible to configure {CANVAS} and {DEV_TOOLS} with your custom Accelerators. It is a recommended practice to ensure that newly created _Business Services_ in your organization follow the standards and best practices defined for your usecases. Discover more on how to configure custom Accelerators on {CANVAS} and {DEV_TOOLS} at xref:../installation/canvas.adoc[Installing → {CANVAS}] and xref:../installation/developer-tools-for-vscode.adoc[Installing → {DEV_TOOLS}]
====

== a. Starting on {CANVAS}

Ensure you have have a {CANVAS} installation, provided by your organization or installed locally xref:../installation/canvas.adoc[Installing → {CANVAS}]

To create a new _Business Service_ project on {CANVAS}, see xref:../tools/applying-accelerators.adoc[{CANVAS} → Using Accelerators].

If you want to continue developing on {DEV_TOOLS} after starting on {CANVAS}, you can create a new Git repository in your Git provider of choice directly in {CANVAS} then clone it locally. Alternatively you can download your newly created _Business Sevice_ project from {CANVAS} as a .zip file and unpack it in your computer.

== b. Starting on {DEV_TOOLS}

Installing {DEV_TOOLS} is straightforward, an can be done directly in VS Code, simply follow xref:../installation/developer-tools-for-vscode.adoc[Installing → {DEV_TOOLS}].

{DEV_TOOLS} provides commands to rapidly create a new _Business Service_ project using Accelerators. The following steps will get you started:

- Open a new or existing folder on VS Code.
- _(optional)_ Create Business Automation assets, such as BPMN or DMN models.
- Run the `BAMOE Developer Tools: Apply Accelerator` command.
- Select the Accelerator you want to apply (DMN or Full, Quarkus or Spring Boot).

Your _Business Service_ project on {PRODUCT_SHORT}, based on your chosen Accelerator will be ready for you in the currently open folder and a new Git repository will be initiated for you if the currently open folder is not a Git repository. Existing Business Automation assets will be moved to the correct locations, and existing modifications in your staging area will be kept, so you remain in control of your development flow.

== c. (Advanced) Manually creating a Java project

If you are an experienced Java developer, you might have your own preferences when creating new projects and wish to manually create your Java project, deciding which {PRODUCT_SHORT} dependencies you need based on xref:../reference-guide/maven-repository-libraries.adoc[Reference → {MVN_REPO} libraries].

If you are planning on running Decisions, Rules, and/or spreadsheet Decision Tables on embedded Java mode using programmatic {PRODUCT_SHORT} Java API, see xref:../editing/dmn-decisions-embedded-java-mode.adoc[Executing Decisions in embedded Java mode] or xref:../editing/drl-rules-embedded-java-mode.adoc[Executing Rules in embedded Java mode].

== Next steps

Now that you have a fully functional _Busines Service_ project on {PRODUCT_SHORT}, there are several things you might want to do:

- Update the README.md file with the name and description of your _Business Service_ project.
- Check your {MVN_REPO} installation to be able to build your _Business Service_ project locally (xref:../installation/configure-maven.adoc[Installing → {MVN_REPO}]).

then

- xref:../getting-started/decision-microservice.html[Decision service in 15 minutes]
- xref:../getting-started/business-rule-microservice.html[Rule service in 15 minutes]
- xref:../getting-started/orchestrating.html[Orchestrating Decisions and Rules with Workflows in 15 minutes]
- xref:../getting-started/deploying-to-openshift.html[Deploying your first Business Service to OpenShift using Quarkus]

or

- xref:../editing/authoring-decisions.html[Authoring Decisions with DMN]
- xref:../editing/authoring-rules.html[Authoring Rules with DRL and spreadsheet Decision Tables]
- xref:../editing/authoring-scesim.html[Authoring unit tests with Test Scenarios]
- xref:../workflow/authoring-workflows.html[Authoring Workflows with BPMN]
- xref:../runtime-services-modeling/services-build.html[Building Business Services executables]
- xref:../runtime-services-modeling/services-deployment.html[Deploying Business Services]
