= _Business Service_ project setup
include::../partials/attributes.adoc[]
include::../styles/images.adoc[]

_Business Services_ are microservice Java applications built on top of Quarkus or Spring Boot, containing {PRODUCT_SHORT} runtime libraries and Business Automation assets such as Workflows (BPMN), Decisions (DMN), Rules (DRL), and spreadsheet Decision Tables (XLS or XLSX), following https://maven.apache.org/guides/introduction/introduction-to-the-standard-directory-layout.html[Maven's standard directory layout]. If you are using Gradle, follow https://docs.gradle.org/9.2.1/userguide/organizing_gradle_projects.html[Gradle's standard directory layout]. 

[#gs-accelerators]
== Introducing Accelerators
You can manually create everything from scratch, or use {PRODUCT_SHORT} to get started with pre-configured _Business Services_ project Accelerators.

In {PRODUCT_SHORT} you can use four Accelerators that correspond to the following cloud development frameworks supported by {PRODUCT_SHORT}: Quarkus and Spring Boot, each supported by Maven or Gradle.

You can use the following accelerators for _Business Services_ that contain stateful Workflows in addition to Decisions, Rules, or spreadsheet Decision Tables. The following accelerators are available for Quarkus and Spring Boot with Maven or Gradle.

* **`Workflows (Quarkus + Maven)`**
* **`Workflows (Spring Boot + Maven)`**
* **`Workflows (Quarkus + Gradle)`**
* **`Workflows (Spring Boot + Gradle)`**

You can use the following accelerators for _Business Services_ that contain Decisions, Rules, or spreadsheet Decision Tables. The following accelerators are available for Quarkus and Spring Boot with Maven or Gradle.

* **`Decisions (Quarkus + Maven)`**
* **`Decisions (Spring Boot + Maven)`**
* **`Decisions (Quarkus + Gradle)`**
* **`Decisions (Spring Boot + Gradle)`**

You can use Accelerators to set up your project in one of the following ways:

* Create new Decisions and/or Workflows on {CANVAS} then apply an Accelerator.
* Open a new or existing folder in VS Code with {DEV_TOOLS} installed, and apply an Accelerator.
* (Advanced) Create a Java project manually, adding dependencies to the _Business Service_ project configuration file, using Accelerators as reference.

[NOTE]
====
To ensure that newly created _Business Services_ in your organization follow the standards and best practices defined for your use cases, you can configure {CANVAS} and {DEV_TOOLS} with your custom Accelerators. For more information on configuring custom Accelerators on {CANVAS} and {DEV_TOOLS}, see xref:../installation/development-environment.adoc[Installing → Development Environment] and xref:../installation/developer-tools-for-vscode.adoc[Installing → {DEV_TOOLS}].
====

== Starting on {CANVAS}

Before you create a new _Business Service_ project on {CANVAS}, make sure you have installed {CANVAS} on your device. 

To install {CANVAS}, follow instructions provided by your organization or install {CANVAS} locally. For more information on local installation, see xref:../installation/development-environment.adoc[Installing → Development Environment].

To create a new _Business Service_ project on {CANVAS}, see xref:../tools/applying-accelerators.adoc[{CANVAS} → Using Accelerators].

=== Using {DEV_TOOLS} after starting on {CANVAS}

If you want to continue developing on {DEV_TOOLS} after starting on {CANVAS}, you can do one of the following:

* Create a new Git repository in your Git provider of choice directly in {CANVAS}, then clone it locally.
* Download your newly created _Business Services_ project from {CANVAS} as a .zip file and unpack it on your device.

[#starting-project-vscode]
== Starting on {DEV_TOOLS}

{DEV_TOOLS} provide commands to create a new _Business Service_ project using Accelerators.

To install {DEV_TOOLS} in the VS Code, see xref:../installation/development-environment.adoc#dev-tools-install[Installing {DEV_TOOLS}].

To use {DEV_TOOLS}, follow these steps:

. Open a new or existing folder in VS Code.
. _(optional)_ Create Business Automation assets, such as BPMN or DMN models.
. Run the `{DEV_TOOLS}: Apply Accelerator` command.
. Select the Accelerator you want to apply.

After completing the steps, your _Business Service_ project on {PRODUCT_SHORT} is ready in the currently open folder. Additionally, a new Git repository is initialized if the currently open folder is not already a Git repository.

If you have any existing Business Automation assets or modifications, your assets are moved to the corresponding locations, and modifications in your staging environment are kept, so you remain in control of your development flow.

== (Advanced) Manually creating a Java project

If you have your own preferences when creating new projects, create your Java project manually. You can decide which {PRODUCT_SHORT} dependencies you need based on xref:../reference-guide/maven-repository-libraries.adoc[Reference → {MVN_REPO} libraries].

If you are planning on running Decisions, Rules, and/or spreadsheet Decision Tables on embedded Java mode using programmatic {PRODUCT_SHORT} Java API, see xref:../editing/embedded-dmn-drl.adoc[Decisions and Rules _Business Services_ in embedded Java mode].

== Next steps

After you have created a _Business Service_ project on {PRODUCT_SHORT}, you can do the following actions:

. Update the README.md file with the name and description of your _Business Service_ project.
. Check your {MVN_REPO} installation to be able to build your _Business Service_ project locally. For more information, see xref:../installation/development-environment.adoc[Installing → Development Environment].

For more information on quick project set up, see:

- xref:../getting-started/decision-microservice.html[Decision service in 15 minutes]
- xref:../getting-started/business-rule-microservice.html[Rule service in 15 minutes]
- xref:../getting-started/orchestrating.html[Orchestrating Decisions and Rules with Workflows in 15 minutes]
- xref:../getting-started/deploying-to-openshift.html[Deploying your first Business Service to OpenShift using Quarkus]

For more information on authoring business logic, see:

- xref:../editing/authoring-decisions.html[Authoring Decisions with DMN]
- xref:../editing/authoring-rules.html[Authoring Rules with DRL and spreadsheet Decision Tables]
- xref:../editing/authoring-scesim.html[Authoring unit tests with Test Scenarios]
- xref:../workflow/authoring-workflows.html[Authoring Workflows with BPMN]

For more information on building and deploying, see:

- xref:../building-deploying/services-build.html[Building Business Services executables]
- xref:../building-deploying/services-deployment.html[Deploying Business Services]
