= Upgrading from 9.0.x

include::../partials/attributes.adoc[]


You can upgrade your existing business automation applications and platforms to the most recent version of {PRODUCT_LONG}. If you are upgrading from an older version, you must follow the steps to upgrade to each intermediate version, as documented. Depending on the complexity of your installation, you might want IBM(R) Services to participate in your project. If so, contact your IBM service representative.

If you want to know more on how to upgrade from version {VERSION_80} to version {VERSION_90X}, see https://www.ibm.com/docs/en/ibamoe/9.0.x?topic=guide-bamoe-v8-bamoe-v9[Migrating to IBM Business Automation Manager Open Editions v9.0.1]


This section will walk you through upgrading your:

* {PRODUCT_SHORT} development environment installation with {MVN_REPO}, {CANVAS}, {DEV_TOOLS}, and {FORM_GENERATION_TOOL}.

* _Business Service(s)_ project(s)

* {PRODUCT_SHORT} production environment installation with Management and Task console, and upgraded versions of your _Business Services_.

== Step 1: Download product archives

Start by downloading the product archives from either https://www.ibm.com/support/fixcentral[IBM Fix Central] which requires an active support subscription to {PRODUCT}, {PRODUCT_PASSPORT_ADVANTAGE_LINK}[IBM Passport Advantage], or via the {DEV_PROGRAM_PAGE_LINK}[IBM Business Automation Manager Open Editions Developer Program]. For more information, see https://www.ibm.com/support/pages/node/7151078[BAMOE 9.1 Download Document].

== Step 2: Upgrade your {PRODUCT_SHORT} development environment installation

When you upgrade your {PRODUCT_SHORT} development environment, you must upgrade {MVN_REPO}, {CANVAS}, {DEV_TOOLS} and {FORM_GENERATION_TOOL}. 

=== Upgrade {MVN_REPO}

On the {PRODUCT} version {VERSION_90x} the dependencies were hosted on the https://central.sonatype.com/search?q=bamoe[Maven Central].
Now the dependencies are distributed with a container image or a zip file.
For more information, see {PRODUCT_SHORT} version {VERSION} xref:../installation/configure-maven.adoc[Maven configuration].

It is recommended using the https://docs.openshift.com/container-platform/4.16/applications/deployments/route-based-deployment-strategies.html#deployments-blue-green_route-based-deployment-strategies[blue-green deployment strategy] for Maven artifacts to be available for both your current version and {PRODUCT_SHORT} version {VERSION_91X}.

If you are using the {MVN_REPO} `.zip` instead of {MVN_REPO} container images, simply extract the contents of {MVN_REPO} `.zip` version {VERSION_91X} to your local Maven repository.

=== Upgrade {CANVAS}

The {VERSION_91X} version of {CANVAS} is a drop in replacement for the {VERSION_90X} version (see xref:../installation/installation.adoc[Installing → {CANVAS}]). The projects you saved to your browser before the upgrade can simply be opened after installing the new version. 

If you prefer to install a parallel version using https://docs.openshift.com/container-platform/4.16/applications/deployments/route-based-deployment-strategies.html#deployments-blue-green_route-based-deployment-strategies[blue-green deployment strategies] you can import projects into the newly installed version (see xref:../tools/importing-existing-projects.adoc[Importing existing projects]) as long as the DNS domains between installations are different. If the DNS domains between installations are the same, your imported projects automatically show up in the new installation when you open it in your browser.

[NOTE]
====
If you have customized your previous {CANVAS} installation, remember to apply the same Environment Variables to the new installation. The same applies for customized container images for {CANVAS} Dev Deployments.
====

=== Upgrade {DEV_TOOLS}

{DEV_TOOLS} versions are managed by the Extension update mechanism in VS Code. You can set automatic update or manage it manually when notified. Because of version differences in the models supported by the BPMN, DMN, and Test Scenario editors it is recommended to choose when you upgrade to avoid issues when running models in services that have not been upgraded when the tools are upgraded.

See xref:../tools/developer-tools-for-vscode.adoc[{DEV_TOOLS}].

[NOTE]
====
After upgrading, the New DMN Editor will be opened automatically when you first access it in Canvas or Developer tools for VS Code.
Existing DMN files (any version) can be opened directly in the editor. For more information, see xref:../editing/authoring-decisions.adoc[Authoring decisions].
====

=== Upgrade {FORM_GENERATION_TOOL}

This tool is required for workflow execution. If the {FORM_GENERATION_TOOL} is already present, uninstall and re-install using steps available in xref:../tools/form-generation-tool.adoc[Form generation tool].

== Step 3: Upgrade your _Business Service(s)_ project(s)

_Business Service(s)_ project(s) can be upgraded in two ways, by:

* Updating an existing _Business Service_ project with its artifacts by changing the Maven dependencies. 

* Creating a _Business Service_ project from scratch and moving your existing assets to it.

The following tools are required to upgrade your _Business Service_ projects to version {VERSION_91X}:

- https://openjdk.org[JDK 17] is installed.
- https://maven.apache.org[Apache Maven 3.9.6] or later is installed.
- https://code.visualstudio.com/download[Visual Studio Code IDE] latest version installed.
- https://marketplace.visualstudio.com/items?itemName=IBM.bamoe-developer-tools[IBM {DEV_TOOLS}] latest version of VS Code IDE extensions
- Upgraded {PRODUCT_SHORT} development environment installation with {MVN_REPO} @ {IMAGE_VERSION_911}.
- Quarkus version {QUARKUS_VERSION} or later is installed.

== Step 3a: Upgrade _Business Service(s)_ project(s) on version {VERSION_90X}

Once your development environment installation is upgraded, it is straightforward to upgrade your _Business Service(s)_ project(s) on {PRODUCT_SHORT} {VERSION_90x} to {PRODUCT_SHORT} version {VERSION_91x}.

The project structure is not changed, updates only need to be made to the dependencies versions, some dependency names, and files.

[WARNING]
====
If you come across some difficulties when trying to upgrade your existing _Business Service(s)_ project(s), you are recommended to create a new project following xref:#step-3b[Step 3b: Upgrade Business Service projects on versions {VERSION_90X}].
====

[start=1]
. Upgrade the Quarkus version in the project POM file to the currently supported version `3.8.6`.
To make this upgrade, open the POM file and do the changes.

+
[source,xml]
----
 ---   <quarkus-plugin.version>2.16.10.Final</quarkus-plugin.version>
 +++   <quarkus-plugin.version>3.8.6</quarkus-plugin.version>
       <quarkus.platform.artifact-id>quarkus-bom</quarkus.platform.artifact-id>
       <quarkus.platform.group-id>io.quarkus</quarkus.platform.group-id>
 ---   <quarkus.platform.version>2.16.12.Final</quarkus.platform.version>
 +++   <quarkus.platform.version>3.8.6</quarkus.platform.version>
----

[start=2]
. Upgrade the BOM and Kogito versions in your POM xml.

+
Previously, the {PRODUCT_SHORT} version {VERSION_90x} used the BOM version {BOM_VERSION_901} and Kogito version {KOGITO_VERSION_901}.
Now, both versions are {BOM_VERSION_911}.
Update the following lines in your `pom.xml`:
+
[source,xml,subs="attributes+"]
----
       <kogito.bom.artifact-id>bamoe-bom</kogito.bom.artifact-id>
 ---   <kogito.bom.version>{BOM_VERSION_901}</kogito.bom.version>
 ---   <version.org.kie.kogito>{KOGITO_VERSION_901}</version.org.kie.kogito>
 +++   <kogito.bom.version>{BOM_VERSION_911}</kogito.bom.version>
 +++   <version.org.kie.kogito>{KOGITO_VERSION_911}</version.org.kie.kogito>
----

[start=3]
. Update the Maven GAV dependencies.
+
With the transition of the KIE projets to the Apache Software Foundation (ASF), it has become necessary to rename a number of Maven modules.  The following table(s) describe the changes to the Maven GAV (GroupID/ArtifactID/Version):

* xref:../upgrading/gav-mapping-rules.adoc[Drools Maven mappings] for anything related to rules or decisions.
* xref:../upgrading/gav-mapping-process.adoc[jBPM Maven mappings] for anything related to BPMN-based stateless/stateful processes.
* xref:../upgrading/gav-mapping-kogito.adoc[Kogito Maven mappings] for anything related to infrastructure or extended services.
* xref:../upgrading/gav-mapping-kie.adoc[KIE Maven mappings] for anything else that does not fall into the above categories.

Depending on your project setup you may also need to make changes to a parent POM xml if it exists.

[start=4]
. Update the `application.properties` file.
+
{PRODUCT_SHORT} version {VERSION_91x} does not fully support the Quarkus Dev Services and hence it is required to disable this feature by adding the following line to the `src/main/resources/application.properties` file:

+
[source,diff]
----
 +++ quarkus.devservices.enabled=false
----

[start=5]
. Upgrading the code to Quarkus 3.
+
A major Quarkus 3 change, is the usage of Jakarta EE 10, meaning that package imports also need to update from `javax` to `jakarta`.
+
This is simply achieved by replacing any `javax` instance over `jarkarta`, like the following:
+
[source]
----
 --- import javax.inject.Named;
 +++ import jakarta.inject.Named;
----
+
[NOTE]
====
Refer https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.0[Quarkus v3 migration guide] for any other change that is related to Quarkus.
====

[start=6]
. Build the project in the root folder:
+
[source,console]
----
mvn clean package
----
+
You might get Maven streaming text once again, and at the end you will see:
+
[source,console]
----
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  8.023 s
[INFO] Finished at: 2024-06-11T17:09:00-03:00
[INFO] ------------------------------------------------------------------------
----
+

Now, you can start using your {PRODUCT_SHORT} version {VERSION_91X} project.


== Step 3b: Creating a _Business Service_ project on version {VERSION_91x} from scratch

If you have experienced some difficulties when trying to upgrade your project you can create a new _Business Service_ project from scratch and import your existing business automation assets (Workflows, Decisions, Rules, and Decision Tables) to the new project.

For more information, see xref:../getting-started/project-setup.adoc[Getting started → Initial Business Service project setup and walkthrough] to create a new _Business Service_ project on {PRODUCT_SHORT} version {VERSION_91x}.

The most significant folder is `src/main/resources`, which is where new or upgraded business automation asset files must be stored.

Examples of supported business automation assets are:

- Decision Model & Notation (DMN) decisions (`.dmn`)
- Drools Rule Language (DRL) rules (`.drl`)
- Business Process Modeling & Notation (BPMN) workflows (`.bpmn`)
- Spreadsheet Decision Table files (`.xls` or `.xlsx`)
- Standard Properties files (`.properties`)
- Test Scenario Files (.scesim)

Copy all your assets from your _Business Service_ project to the respective folders on the new project on {PRODUCT_SHORT} version {VERSION_91x}. If you have custom Java code or any other type of file in your _Business Service_ project, move them to the same location as you had before, following https://maven.apache.org/guides/introduction/introduction-to-the-standard-directory-layout.html[Maven's standard  directory layout].

[NOTE]
====
The proper folder for Test Scenario files is `src/test/resources`.
====

== Step 4: Verify the upgrade of your _Business Service(s)_ project(s)
. To verify that your upgrade is successful, build the project one more time using Maven's standard command or any other customized build command you might have in your project.
+
[source,console]
----
mvn clean package
----
+
You might get Maven streaming text once again, and at the end of it you must have:
+
[source,console]
----
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  8.023 s
[INFO] Finished at: 2024-06-11T17:09:00-03:00
[INFO] ------------------------------------------------------------------------
----
+
Now you can start using your _Business Service_ project on {PRODUCT_SHORT} version {VERSION_91X}.

== Step 5: Upgrade your {PRODUCT_SHORT} production environment installation

After upgrading your _Business Services_ source code (Steps 3a or 3b), you need to upgrade Management and Task console before deploying a new version of the upgraded _Business Services_.

It is recommended that you use the https://docs.openshift.com/container-platform/4.16/applications/deployments/route-based-deployment-strategies.html#deployments-blue-green_route-based-deployment-strategies[blue-green deployment strategy] for upgrading Management and Task console so that you still have a reliable way of managing live _Business Services_ that might not have been upgraded to {PRODUCT_SHORT} version {VERSION_91X} yet. Once all your _Business Services_ are running, you can safely remove your previous Management and Task console installation.

If you are getting started with stateful Workflows, follow instructions in xref:../installation/installation.adoc[Installing] for information on initial project setup and walkthrough.

Once you have a new installation, you can follow the standard guidance on how to deploy a new version of your _Business Services_ (see xref:../runtime-services-modeling/building-decision-services.adoc[Building decision services]).

