= Upgrading

include::../partials/attributes.adoc[]


You can upgrade your existing business automation applications and platforms to the most recent version of {PRODUCT_LONG}. The supported upgrade process is from the previous version to the current version. If you are upgrading from an older version, you must follow the steps to upgrade to each intermediate version, as documented. Depending on the complexity of your installation, you might want IBM(R) Services to participate in your project. If so, contact your IBM service representative.
To know about upgrading to version {VERSION_80}, see [Link to 80 upgrading topic]

== Overview

This section describes migration of existing applications to version {VERSION_901} of {PRODUCT_LONG}. In {PRODUCT_SHORT} v{VERSION_90X}, the approach to deployment and runtime works in a very different way compared to {PRODUCT_SHORT} v{VERSION_80}. It uses a cloud native, serverless, micro-service architecture to deploy business automation projects that include a runtime via Maven plug-ins, directly to your cloud platform. Whereas in version {VERSION_80}, you packaged your BAMOE projects as KJars to be deployed on Kie Server. Hence, tools like Smart router which was designed to aggregate multiple independent KIE Server instances as though they were a single server are no longer necessary in the {PRODUCT_SHORT} v{VERSION_90X} architecture.

== Prerequisites

The following tools are required to migrate to {PRODUCT_SHORT} version {VERSION_901}:

include::../partials/prerequisites.adoc[]

== Procedure

