= How to Navigate This Document
include::../partials/attributes.adoc[]
include::../styles/images.adoc[]

This guide is designed to support teams upgrading from *BAMOE v8* to *BAMOE v9*, whether you're a architect, developer or business analyst. It is structured to reflect the typical upgrade journey, from understanding key differences to transforming projects and assets.

== Recommended Reading Flow

To get the most out of this guide, we suggest the following order:

. *Start with the xref:01-introduction.adoc[Introduction] and xref:02-key-differences.adoc[Key Differences]*
+
Understand the architectural and conceptual shifts between v8 and v9. This will help you frame the rest of the upgrade process.

. *Review the xref:04-development-environment-comparison.adoc[Development Environment] and uprade your project using xref:05-00-upgrading-projects.adoc[Project Upgrade Strategies]*
+
Whether you're upgrading client-server or standalone projects, these sections provide step-by-step guidance and configuration examples going through project structure differences and how to upgrade your assets.

. *Dive into xref:06-production-environment-comparison.adoc[Production Environment] Comparisons*
+
This section provides side-by-side insights into how the production environment has evolved in BAMOE v9.

. *Understand xref:07-migrating-live-data.adoc[Live Data migration], xref:08-operation-considerations.adoc[Operational] and xref:09-performance-considerations.adoc[Performance] Considerations*
+
These sections help you plan for scaling, persistence, monitoring, and long-running processes.

. *Check the xref:10-known-limitations.adoc[Known Limitations] and xref:11-not-supported.adoc[Not supported] features*
+
Be aware of unsupported features and practical tips that don't fit into other categories.

== Document Structure

Each section includes:

* *Comparative insights* between v8 and v9
* *Step-by-step instructions* for common upgrade tasks
* *Code snippets and configuration examples*
* *References to official documentation and community resources*

== Disclaimers

* Terminology may differ slightly between v8 and v9. Where possible, we clarify these differences.
* Some features in v9 are still evolving. Always refer to the https://www.ibm.com/docs/en/bamoe[official BAMOE documentation] for the latest updates.

== Providing Feedback

We welcome your feedback to improve this guide. If you find any inaccuracies, missing topics, or have suggestions, please use the Feedback button located at the top right corner of any upgrade guide page.

=== Need Help?

If you need further assistance:

* https://www.ibm.com/support/pages/node/7007883[IBM Business Automation Manager Open Editions 9.x Product Support Lifecycle]
* https://www.ibm.com/br-pt/products/expertlabs[IBM Expert Labs]
* Refer to the https://www.ibm.com/docs/en/bamoe[BAMOE documentation].
