= Upgrading event streaming
include::../partials/attributes.adoc[]
include::../styles/images.adoc[]

IBM Business Automation Manager Open Editions (BAMOE) has evolved its event streaming capabilities between versions 8 and 9.

BAMOE v8 allows users to configure the KIE Server to emit Kafka messages about every event when a process, case, or task is completed.

BAMOE v9 introduces a more modular and flexible approach using add-ons to enable messaging and event-driven capabilities in Quarkus or Spring Boot projects. Events are published in the CloudEvents format, making them easily consumable by external systems.

Events are categorized into:

* Messaging Events: Related to BPMN message elements.
* Process/Runtime Events: Related to process instances, tasks, and variables

== Messaging event add-on

This add-on enables integration between BPMN message elements and external event sources or listeners, depending on the message type.

=== Quarkus

To enable messaging in Quarkus, include the following dependency in your pom.xml:

[,xml]
----
<dependency>
  <groupId>org.kie</groupId>
  <artifactId>kie-addons-quarkus-messaging</artifactId>
</dependency>
----

To use Kafka as the message broker, add:

[,xml]
----
<dependency>
  <groupId>io.quarkus</groupId>
  <artifactId>quarkus-messaging-kafka</artifactId>
</dependency>
----

For more information, go through the example application process-event-driven that is shipped with IBM BAMOE in bamoe-9.x.x-examples.zip file. See https://www.ibm.com/docs/en/ibamoe/9.2.x?topic=started-example-business-service-projects[Example Business Service projects].

=== Spring Boot

Unlike the Quarkus add-on, which is vendor-independent, the Spring Boot add-on is Kafka-specific. To enable messaging, add the following dependency:

[,xml]
----
<dependency>
  <groupId>org.kie</groupId>
  <artifactId>kie-addons-springboot-messaging</artifactId>
</dependency>
----

== Process event add-on

This add-on emits events when operations alter the state of a process. Such operations include the creation of a process instance, task transitions, and variable modifications. Events are published in the CloudEvents format, with the data field containing a JSON representation of one of the following types:

* `ProcessInstanceEvent`, triggered when a process instance is created, modified, or completed.
* `UserTaskInstanceEvent`, triggered by changes to human tasks.
* `VariableInstanceEvent`, triggered when a variable is created, modified, or removed.
* These events are published to three Kafka topics: `kogito-processinstances-events`, `kogito-usertaskinstances-events`, and `kogito-variables-events`.

To disable publishing on any of these channels, set the corresponding property to false:

[,properties]
----
kogito.events.processinstances.enabled=false
kogito.events.usertasks.enabled=false
kogito.events.variables.enabled=false
----

=== Quarkus

To enable process events in Quarkus, include the following dependency:

[,xml]
----
<dependency>
  <groupId>org.kie</groupId>
  <artifactId>kie-addons-quarkus-events-process</artifactId>
</dependency>
----

To use Kafka, also include:

[,xml]
----
<dependency>
  <groupId>io.quarkus</groupId>
  <artifactId>quarkus-messaging-kafka</artifactId>
</dependency>
----



