= Upgrading standalone projects

include::../partials/attributes.adoc[]
include::../styles/images.adoc[]
include::../styles/tabs.adoc[]

Standalone mode allows you to run {PRODUCT_SHORT} projects as self-contained Java applications without requiring a full server environment.
BAMOE v9 provides two templates that include the minimal setup required to run a Business Service project in a functionality equivalent Embedded mode for more information see xref:../editing/embedded-dmn-drl.adoc[Decisions and Rules Services in Embedded Java mode].
Both templates include a `pom.xml` file with the minimal set of dependencies needed to run the project independently.

== Decisions template

Is available https://github.com/IBM/bamoe-docs/tree/9.3.x/_code/docs/decisions-embedded-mode-example[decisions-embedded-mode-example GitHub repository].
It contains executable java class https://github.com/IBM/bamoe-docs/blob/9.3.x/_code/docs/decisions-embedded-mode-example/src/main/java/com/ibm/bamoe/decisions/embedded/DecisionsEmbeddedModeExample.java[*DecisionsEmbeddedModeExample.java*].
You will need to update *DecisionsEmbeddedModeExample.java* code accordingly:

* *namespace*: change "https://kie.org/dmn/_C83DFD16-A42A-46BE-A843-370444580E0F" to your model namespace value
* *modelName*: change "loan-application-age-limit" to your model name value
* *dmnContext*: change to *dmnContext.set(key, value)* according to your model Input Data nodes

After applying the updates, run one of the following commands depending on the desired outcome:

* To run a full build lifecycle, including tests, and install the generated artifacts into the user's local repository, use the following command:

++++
<div class="tabs-container">
  <input type="radio" id="maven-tab1" name="group1-tabs" checked>
  <input type="radio" id="gradle-tab1" name="group1-tabs">
  <div class="tabs-header">
    <label for="maven-tab1">Maven</label>
    <label for="gradle-tab1">Gradle</label>
  </div>
  <div class="tabs-content">
    <div class="tab-panel">
++++
[source,bash]
----
mvn clean install
----
++++
    </div>
    <div class="tab-panel">
++++
[source,bash]
----
./gradlew clean build publishToMavenLocal
----
++++
    </div>
  </div>
</div>
++++

* To build the project and run tests, but not install the generated artifacts into the local repository, use the following command:

++++
<div class="tabs-container">
  <input type="radio" id="maven-tab2" name="group2-tabs" checked>
  <input type="radio" id="gradle-tab2" name="group2-tabs">
  <div class="tabs-header">
    <label for="maven-tab2">Maven</label>
    <label for="gradle-tab2">Gradle</label>
  </div>
  <div class="tabs-content">
    <div class="tab-panel">
++++
[source,bash]
----
mvn clean verify
----
++++
    </div>
    <div class="tab-panel">
++++
[source,bash]
----
./gradlew clean check
----
++++
    </div>
  </div>
</div>
++++

* To build the project without running tests or installing artifacts into the local repository, use the following command:

++++
<div class="tabs-container">
  <input type="radio" id="maven-tab3" name="group3-tabs" checked>
  <input type="radio" id="gradle-tab3" name="group3-tabs">
  <div class="tabs-header">
    <label for="maven-tab3">Maven</label>
    <label for="gradle-tab3">Gradle</label>
  </div>
  <div class="tabs-content">
    <div class="tab-panel">
++++
[source,bash]
----
mvn clean package
----
++++
    </div>
    <div class="tab-panel">
++++
[source,bash]
----
gradle clean build
----
++++
    </div>
  </div>
</div>
++++

NOTE: Maven places all build artifacts in the `/target` directory, while Gradle places them in the `build/` directory.

== Rules template

Is available https://github.com/IBM/bamoe-docs/tree/9.3.x/_code/docs/rules-embedded-mode-example[here].
It contains executable java class https://github.com/IBM/bamoe-docs/blob/9.3.x/_code/docs/rules-embedded-mode-example/src/main/java/com/ibm/bamoe/rules/embedded/RulesEmbeddedModeExample.java[*RulesEmbeddedModeExample.java*].
You will need to update *RulesEmbeddedModeExample.java* code accordingly:

* *CommandFactory.newInsert(new Applicant("#0001", 20), "applicant")*: replace *Applicant* according to your domain data objects

After applying the updates, run one of the following commands depending on the desired outcome:

* To run a full build lifecycle, including tests, and install the generated artifacts into the user's local repository, use the following command:

++++
<div class="tabs-container">
  <input type="radio" id="maven-tab4" name="group4-tabs" checked>
  <input type="radio" id="gradle-tab4" name="group4-tabs">
  <div class="tabs-header">
    <label for="maven-tab4">Maven</label>
    <label for="gradle-tab4">Gradle</label>
  </div>
  <div class="tabs-content">
    <div class="tab-panel">
++++
[source,bash]
----
mvn clean install
----
++++
    </div>
    <div class="tab-panel">
++++
[source,bash]
----
./gradlew clean build publishToMavenLocal
----
++++
    </div>
  </div>
</div>
++++


* To build the project and run tests, but not install the generated artifacts into the local repository, use the following command:

++++
<div class="tabs-container">
  <input type="radio" id="maven-tab5" name="group5-tabs" checked>
  <input type="radio" id="gradle-tab5" name="group5-tabs">
  <div class="tabs-header">
    <label for="maven-tab5">Maven</label>
    <label for="gradle-tab5">Gradle</label>
  </div>
  <div class="tabs-content">
    <div class="tab-panel">
++++
[source,bash]
----
mvn clean verify
----
++++
    </div>
    <div class="tab-panel">
++++
[source,bash]
----
./gradlew clean check
----
++++
    </div>
  </div>
</div>
++++

* To build the project without running tests or installing artifacts into the local repository, use the following command:

++++
<div class="tabs-container">
  <input type="radio" id="maven-tab6" name="group6-tabs" checked>
  <input type="radio" id="gradle-tab6" name="group6-tabs">
  <div class="tabs-header">
    <label for="maven-tab6">Maven</label>
    <label for="gradle-tab6">Gradle</label>
  </div>
  <div class="tabs-content">
    <div class="tab-panel">
++++
[source,bash]
----
mvn clean package
----
++++
    </div>
    <div class="tab-panel">
++++
[source,bash]
----
gradle clean build
----
++++
    </div>
  </div>
</div>
++++

NOTE: Maven places all build artifacts in the `/target` directory, while Gradle places them in the `build/` directory.

== Other assets

Your project may contain multiple types of assets. Each asset type may require a different migration approach. For more information, see xref:05-04-upgrading-individual-assets.adoc[Upgrading Individual Assets] topic.