= Upgrading custom WorkItemHandlers

include::../partials/attributes.adoc[]
include::../styles/images.adoc[]

This guide explains how to migrate custom WorkItemHandlers from {PRODUCT_SHORT} v8 to BAMOE v9. It outlines the key differences in APIs, registration mechanisms, and execution models. For more information on creating a custom work item handler in {PRODUCT_SHORT} {VERSION_RM} see xref:../workflow/authoring-workflows.adoc#custom-wih[Developing stateful Workflows → Authoring Workflows with BPMN].

== What is a custom Work Item in {PRODUCT_SHORT}?

In {PRODUCT_SHORT}, a Work Item represents a task or activity in a process that typically involves external operations, such as calling REST APIs, performing database operations, or consuming SOAP web services. A Custom Work Item Handler (WIH) is a user-defined Java class that implements the logic for executing such tasks. It extends the capabilities of standard BPMN tasks (like Service Tasks) by allowing developers to plug in custom code to meet specific business requirements not covered by built-in functionality.

Custom Tasks can also define visual and runtime properties for the node on the process model, enhancing both modeling and execution flexibility.

== Differences between BAMOE 8 and 9

=== API and lifecycle changes

In BAMOE v8, custom WorkItemHandlers implemented the interface `org.kie.api.runtime.process.WorkItemHandler` and used the methods `+executeWorkItem(...)+` and `+abortWorkItem(...)+`.

In BAMOE v9, these methods are no longer supported. Instead, handlers must extend `org.kie.kogito.process.workitems.impl.DefaultKogitoWorkItemHandler` and override the `+activateWorkItemHandler(...)+` and `+abortWorkItemHandler(...)+` lifecycle methods to define the behavior of your Custom Task.:

The new model is based on phases and transitions, which provide more flexibility and better integration with the Kogito runtime.

For more information about `KogitoWorkItemHandler`, see xref:{BAMOE_DOCS_TUTORIALS_DOCS_LINK}/tutorial-12-database-integration/README.md[Tutorial 12: Database Integration — BAMOE v8 to v9 Migration].

=== Registration changes

In v8, handlers were registered using `kie-deployment-descriptor.xml` or `kmodule.xml`.

In v9, handlers must be registered programmatically by extending `org.kie.kogito.process.impl.DefaultWorkItemHandlerConfig`.

Example:

[,Java]
----
@ApplicationScoped
public class CustomWorkItemHandlerConfig extends DefaultWorkItemHandlerConfig {
    {
        register("MyConcatDefinitions", new MyConcatWorkItemHandler());
    }
}
----

=== Annotation support

The `@Wid` annotation used in BAMOE v8 is no longer supported in BAMOE v9. Instead, Work Item Definitions must be provided as `.wid` files and placed in the root directory of your project or in the same folder as your BPMN file, see xref:../workflow/authoring-workflows.adoc#custom-wih[Authoring Workflows with BPMN → Creating a custom Work Item Handler]

=== Retry mechanisms
BAMOE 8.x there were two different mechanisms for handling retry logic in Custom WorkItemHandlers:

. Asynchronous WorkItemHandlers implementing Command, which contain their own configuration for retry attempts and retry delay inside the Command implementation.

. WorkItemHandlers extending DefaultWorkItemHandler, which rely on the engine’s Executor for retry configuration (attempts, delay, and error handling).

We need to understand what the equivalent mechanisms are in BAMOE 9.3, and how retry attempts and retry delays should be configured for Custom WorkItemHandlers in this new architecture.

Specifically, we want to clarify:
	•	Where retry attempts and retry delays are configured in BAMOE 9.3 when an error occurs during a WorkItem execution.
	•	Whether BAMOE 9.3 provides an equivalent retry Executor or configurable mechanism similar to the one in 8.x.
	•	How to throttle or space out external calls (e.g., HTTP integrations, service calls) either from WorkItemHandlers or ScriptTasks in case of intermittent failures.
	•	If there is any recommended pattern or configuration for handling automatic retries in the new compact runtime.

Our goal is to understand the official retry strategy in BAMOE 9.3 so we can migrate our existing WorkItemHandlers and ensure equivalent behavior.

In {PRODUCT_SHORT} {VERSION_RM} retries could be happening for both synchronous and asynchronous invocations. You can configure these with the following settings can be used:

In Quarkus

Synchrous via https://quarkus.io/guides/smallrye-fault-tolerance[Smallrye Fault Tolerance]:

* kogito.faultToleranceEnabled - enable fault tolerance and retries

* more fine grained config options as per the doc above, eg: quarkus.fault-tolerance."global".retry.max-retries=3

Async via the embedded jobs service:
kogito.jobs-service.maxNumberOfRetries: numbers of retry of a failred job. After this number is reached the job will be set to failure. (default is 3 times)
kogito.jobs-service.retryMillis: interval used to retry the new job (default 60 seconds)