= Upgrading event streaming
include::../partials/attributes.adoc[]
include::../styles/images.adoc[]

IBM Business Automation Manager Open Editions (BAMOE) has evolved its event streaming capabilities between versions 8 and 9.

BAMOE v8 allows users to configure the KIE Server to emit Kafka messages about every event when a process, case, or task is completed.

BAMOE v9 introduces a more modular and flexible approach using add-ons to enable messaging and event-driven capabilities in Quarkus or Spring Boot projects. Events are published in the CloudEvents format, making them easily consumable by external systems.

Events are categorized into:

* Messaging Events: Related to BPMN message elements.
* Process/Runtime Events: Related to process instances, tasks, and variables

== Messaging event add-on

This add-on enables integration between BPMN message elements and external event sources or listeners, depending on the message type.

For more information see xref:../workflow/event-driven-workflow.adoc[Using Events in Workflows]

== Process event add-on

This add-on emits events when operations alter the state of a process. Such operations include the creation of a process instance, task transitions, and variable modifications. Events are published in the CloudEvents format, with the data field containing a JSON representation of one of the following types


For more information see xref:../workflow/event-driven-workflow.adoc[Using Events in Workflows]