= Upgrading custom WorkItemHandlers

include::../partials/attributes.adoc[]
include::../styles/images.adoc[]

This guide explains how to migrate custom WorkItemHandlers from {PRODUCT_SHORT} v8 to BAMOE v9. It outlines the key differences in APIs, registration mechanisms, and execution models. For more information on creating a custom work item handler in {PRODUCT_SHORT} {VERSION_RM} see xref:../workflow/authoring-workflows.adoc#custom-wih[Developing stateful Workflows → Authoring Workflows with BPMN].

== What is a custom Work Item in {PRODUCT_SHORT}?

In {PRODUCT_SHORT}, a Work Item represents a task or activity in a process that typically involves external operations, such as calling REST APIs, performing database operations, or consuming SOAP web services. A Custom Work Item Handler (WIH) is a user-defined Java class that implements the logic for executing such tasks. It extends the capabilities of standard BPMN tasks (like Service Tasks) by allowing developers to plug in custom code to meet specific business requirements not covered by built-in functionality.

Custom Tasks can also define visual and runtime properties for the node on the process model, enhancing both modeling and execution flexibility.

== Differences between BAMOE 8 and 9

=== API and lifecycle changes

In BAMOE v8, custom WorkItemHandlers implemented the interface `org.kie.api.runtime.process.WorkItemHandler` and used the methods `+executeWorkItem(...)+` and `+abortWorkItem(...)+`.

In BAMOE v9, these methods are no longer supported. Instead, handlers must extend `org.kie.kogito.process.workitems.impl.DefaultKogitoWorkItemHandler` and override the `+activateWorkItemHandler(...)+` and `+abortWorkItemHandler(...)+` lifecycle methods to define the behavior of your Custom Task.:

The new model is based on phases and transitions, which provide more flexibility and better integration with the Kogito runtime.

For more information about `KogitoWorkItemHandler`, see xref:{BAMOE_DOCS_TUTORIALS_DOCS_LINK}/tutorial-12-database-integration/README.md[Tutorial 12: Database Integration — BAMOE v8 to v9 Migration].

=== Registration changes

In v8, handlers were registered using `kie-deployment-descriptor.xml` or `kmodule.xml`.

In v9, handlers must be registered programmatically by extending `org.kie.kogito.process.impl.DefaultWorkItemHandlerConfig`.

Example:

[,Java]
----
@ApplicationScoped
public class CustomWorkItemHandlerConfig extends DefaultWorkItemHandlerConfig {
    {
        register("MyConcatDefinitions", new MyConcatWorkItemHandler());
    }
}
----

=== Annotation support

The `@Wid` annotation used in BAMOE v8 is no longer supported in BAMOE v9. Instead, Work Item Definitions must be provided as `.wid` files and placed in the root directory of your project or in the same folder as your BPMN file, see xref:../workflow/authoring-workflows.adoc#custom-wih[Authoring Workflows with BPMN → Creating a custom Work Item Handler]

=== Retry mechanisms
In {PRODUCT_SHORT} {VERSION_80X} there were two different mechanisms for handling retry logic in Custom WorkItemHandlers:

. WorkItemHandlers extending `DefaultWorkItemHandler`, which rely on the engine’s Executor for retry configuration (attempts, delay, and error handling).

. Asynchronous WorkItemHandlers implementing `Command`, which contain their own configuration for retry attempts and retry delay inside the `Command` implementation.

In {PRODUCT_SHORT} {VERSION_RM} retries could be happening for both synchronous and asynchronous invocations and are managed, along with timers, via the Embedded Jobs Service. Retries may occur at different points in your Process Instance for example:

* when invoking a process execution through a REST endpoint and no nodes in the Process Definition are marked as asynchronous. Before the Process Instance reaches a safepoint, the execution fails with an exception. 
** In this case, the retries are controlled by the `kogito.faultToleranceEnabled` property and then handled by the platform specific implementations.

* when a Process Instance execution is triggered by a timer expiration, and this execution fails. 
** In this case, the Jobs Service specific configuration properties affect the retry logic.

Both these scenarios can be considered synchronous process execution because there is no node marked as `async`.

You can configure the retry logic with the following settings for both Quarkus or Spring Boot:

* `kogito.faultToleranceEnabled` - to enable fault tolerance and retries.

For more fine grained configuration options for synchronous retry logic, see:

* The https://quarkus.io/guides/smallrye-fault-tolerance[Smallrye Fault Tolerance] mechanism for Quarkus, e.g.,`quarkus.fault-tolerance."global".retry.max-retries=3`

* The https://resilience4j.readme.io/docs/retry[resilience4j Retry] mechanism for Spring Boot, e.g, `resilience4j.retry.configs.default.maxAttempts=3`, see https://github.com/resilience4j/resilience4j-spring-boot3-demo/blob/master/src/main/resources/application.yml#L64-L68[application.yml].

Setting any node in your Process Definition with the `async` flag will result in "asynchronous" process execution. When an `async` node is entered, the workflow engine terminates/commits the ongoing transaction, and subsequent execution happens in a separate thread. This has the additional benefit of introducing an artificial safe-point in the process. Although the concept exists in both v8 and v9, the implementation is different.

Asynchronous retry logic for Quarkus and Spring Boot is defined using the Embedded Jobs Service:

* `kogito.jobs-service.maxNumberOfRetries`- the number of retries of a failed job. After this number is reached the job will be set to failure. The default is 3 times. 

* `kogito.jobs-service.retryMillis`- the interval used to retry the new job. The default is 60 seconds. This is a global configuration. There is currently no option to configure different or increasing delays per retry attempt.