= Known limitations
include::../partials/attributes.adoc[]
include::../styles/images.adoc[]

This section covers known limitations in BAMOE v9. Some of those features can be implemented in upcoming BAMOE releases.

* Project and asset management: BAMOE v9 does not include features to manage projects like in BAMOE v8's Business Central. Users must rely on external tools such as Git providers and IDEs.
* Monitoring and reporting: BAMOE v9 does not include built-in monitoring or reporting tools. Instead, it relies on integration with Prometheus and Grafana.
* UI-based testing: The UI-based testing available in Business Central has been replaced by Maven-based unit and integration testing.
* Leader election conflict: When multiple business services connect to a shared database, a leader election conflict may occur. The first instance becomes the leader, but subsequent instances may fail to start due to repeated leadership attempts.
* Case Management: Full case management capabilities are not available in BAMOE v9. However, Adhoc (Flexible) Processes are still supported.

For additional details, refer to the https://www.ibm.com/docs/en/ibamoe/9.2.x?topic=notes-known-limitations[Known limitations of BAMOE v9].

