= Not supported in 9.3.1
include::../partials/attributes.adoc[]
include::../styles/images.adoc[]

This section lists the features that are not supported in {PRODUCT_SHORT} v9, showing their replacement.

* Business Central: Not available in {PRODUCT_SHORT} v9. Replaced by {CANVAS}, {DEV_TOOLS} and {MAVEN_REPO}.
* KIE Server: Replaced by Quarkus/Spring Boot runtimes.
* SmartRouter: Not available in {PRODUCT_SHORT} v9. Service discovery and orchestration are now handled through Kubernetes-native solutions.
* Asset Authoring: {CANVAS} supports editing BPMN and DMN files. {DEV_TOOLS} also supports those files, along with Test Scenarios. Other asset types are currently not supported for authoring.
* Legacy Form Modeler: The form modeler and its associated files from {PRODUCT_SHORT} v8 are not supported. Forms must be generated using xref:../tools/form-generation.adoc[Form code generation for User Tasks].
* Custom Dashboards and Reports: {PRODUCT_SHORT} v9 does not include built-in monitoring or reporting tools. Instead, it relies on integration with Prometheus and Grafana.
* Database Support: {PRODUCT_SHORT} v9 supports Microsoft SQL Server, PostgreSQL and Oracle. Other databases such as Sybase, and EDB are currently not supported. See xref:../release-notes/supported-environments.adoc[supported environments].
* Case Management: Full Case Management capabilities are not available in {PRODUCT_SHORT} v9. Adhoc (Flexible) Processes are supported as a replacement. 
* Build from UI: The capability to build projects from the UI in {PRODUCT_SHORT} v8 Business Central is not available in {CANVAS}. Projects are now built using Maven.
* Predefined WorkItemHandlers: Connectors such as CamelCXFConnector, CamelFTPConnector, KafkaPublishMessages, and WebServiceTask are not available out of the box.
* DRL-based Test Scenarios: Editing DRL-based Test Scenarios is currently not supported.
* PMML: Is currently not available in {PRODUCT_SHORT} v9.
* Pluggable variable persistence: Is currently not supported.
* Using JavaScript as a scripting language is not supported in V9.



