= Not Supported in BAMOE 9.2
include::../partials/attributes.adoc[]
include::../styles/images.adoc[]

This section covers not supported features on BAMOE v9. Some of those features can be implemented in upcoming BAMOE releases.

* Business Central: Not available in BAMOE v9. Replaced by BAMOE Canvas, BAMOE Developer Tools for VS Code and BAMOE Maven Repository.
* KIE Server: Replaced by Quarkus/Spring Boot runtimes.
* Asset Authoring: BAMOE Canvas supports editing BPMN and DMN files. BAMOE Developer Tools for VS Code also supports those files, along with Test Scenarios. Other asset types are not supported for authoring.
* Legacy Form Modeler: The form modeler and its associated files from BAMOE v8 are not supported. Forms must be generated using the BAMOE v9 form generation tool.
* Custom Dashboards and Reports: Removed with the deprecation of Business Central.
* Database Support: BAMOE v9 supports Microsoft SQL Server and PostgreSQL. Other databases such as Oracle, Sybase, and EDB are not supported. See the https://www.ibm.com/docs/en/ibamoe/9.2.x?topic=notes-supported-environments[supported environments].
* Build from UI: The capability to build projects from the UI in BAMOE v8 Business Central is not available in BAMOE Canvas. Projects must be built manually using Maven.
* @Wid Annotation: Not supported. This annotation was used in BAMOE v8 to define custom work item metadata.
* Custom Task Administration UI: BAMOE v9 does not provide an interface for managing custom work item handlers.
* Predefined WorkItemHandlers: Connectors such as CamelCXFConnector, CamelFTPConnector, KafkaPublishMessages, and WebServiceTask are not available out of the box.
* DRL-based Test Scenarios: Editing DRL-based test scenarios is not supported.
