= Upgrading from 9.3.x
include::../partials/attributes.adoc[]
include::../styles/images.adoc[]

This section describes the steps you must take to upgrade your {PRODUCT_SHORT} installation and _Business Services_ projects developed in version {VERSION_93X}. 

// See the following docs if you are upgrading from a version prior to this:

* xref:upgrade-overview.adoc[Upgrading from a previous version of {PRODUCT_SHORT}]

This guide will walk you through upgrading your:

* {PRODUCT_SHORT} development environment with {MVN_REPO}, {CANVAS}, and {DEV_TOOLS}

* _Business Service(s)_ project(s)

* {PRODUCT_SHORT} Runtime environment with {MANAGEMENT_CONSOLE}, {MCP_SERVER} and upgraded versions of your _Business Services_

== Step 1: Download product archives

Start by downloading the product archives from {PRODUCT_PASSPORT_ADVANTAGE_LINK}[IBM Passport Advantage], or via the {DEV_PROGRAM_PAGE_LINK}[IBM Business Automation Manager Open Editions Developer Program]. 

== Step 2: Upgrade your {PRODUCT_SHORT} development environment

When you upgrade your {PRODUCT_SHORT} development environment in {VERSION}, the individual component deliverables have been replaced by two new Helm charts to facilitate the installation and license tracking of {PRODUCT_SHORT} components in your selected offering, DMOE or PMOE. They include the product specific licensing annotations, removing the need for manual intervention:

The Dev helm charts include the following component Containers:

* {CANVAS}
* {EXT_SERVICES}
* {CORS_PROXY}
* {MVN_REPO}

=== Upgrade {CANVAS} and {MVN_REPO}
It is recommended that you use the https://docs.openshift.com/container-platform/4.19/applications/deployments/route-based-deployment-strategies.html#deployments-blue-green_route-based-deployment-strategies[blue-green deployment strategy] for Maven artifacts to be available for both your current version and {PRODUCT_SHORT} version {VERSION_93X}.

Follow the steps in xref:../installation/development-environment.adoc[Installing → Dev Environment Helm chart] to install the new {MVN_REPO} and{CANVAS} version.

If you decide to uninstall the previous individual containers and replace with the Dev environment Helm chart, the {VERSION} version of {CANVAS} is a drop in replacement for the {VERSION_93X} version. The projects you saved to your browser before the upgrade can simply be opened after installing the new version. 

You can import projects into the newly installed version (see xref:../tools/importing-existing-projects.adoc[Importing existing projects]) as long as the DNS domains between installations are different. If the DNS domains between installations are the same, your imported projects automatically show up in the new installation when you open it in your browser.

[NOTE]
====
If you have customized your previous {CANVAS} installation, remember to apply the same Environment Variables to the new installation. The same applies for customized container images for {CANVAS} Dev Deployments.
====

=== Upgrade {DEV_TOOLS}
{DEV_TOOLS} versions are managed by the Extension update mechanism in VS Code. You can set automatic update or manage it manually when notified. Because of version differences in the models supported by the BPMN, DMN, and Test Scenario editors it is recommended to choose when you upgrade to avoid issues when running models in services that have not been upgraded when the tools are upgraded. See xref:../tools/developer-tools-for-vscode.adoc[{DEV_TOOLS}].

== Step 3: Upgrade your _Business Service(s)_ project(s)

_Business Service(s)_ project(s) can be upgraded by changing their Maven dependencies and configuration files.  

The following tools are required to upgrade your _Business Service_ projects to {PRODUCT_SHORT} version {VERSION_931}:

- https://openjdk.org[JDK 21] is installed.
- https://maven.apache.org[Apache Maven 3.9.6] is installed.
- https://code.visualstudio.com/download[Visual Studio Code IDE] latest version installed.
- Upgraded {PRODUCT_SHORT} development environment with {MVN_REPO} @ {IMAGE_VERSION}

Once your {PRODUCT_SHORT} development environment is upgraded, it is straightforward to upgrade your _Business Service(s)_ project(s) on {PRODUCT_SHORT} {VERSION_930} to {PRODUCT_SHORT} version {VERSION_931}.

The project structure is not changed, updates only need to be made to the dependencies versions, some dependency names, and files.

[start=2]
. Upgrade the BAMOE BOM in the project POM file to {BOM_VERSION}:
+
[source,xml,subs="+attributes"]
----
<dependency>
  <groupId>com.ibm.bamoe</groupId>
  <artifactId>bamoe-bom</artifactId>
  <version>{BOM_VERSION}</version>
  <type>pom</type>
  <scope>import</scope>
</dependency>
----

[NOTE]
====
Refer to https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.20[Quarkus 3.20 LTS migration guide] for any other change related to Quarkus.
====

== Step 4: Verify the upgrade of your _Business Service(s)_ project(s)
. To verify that your upgrade is successful, build the project one more time using Maven's standard command or any other customized build command you might have in your project.
+
[source,console]
----
mvn clean package
----
+
You might get Maven streaming text once again, and at the end of it you must have:
+
[source,console]
----
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  8.023 s
[INFO] Finished at: 2025-09-30T17:09:00-03:00
[INFO] ------------------------------------------------------------------------
----
+
Now you can start using your _Business Service_ project on {PRODUCT_SHORT} version {VERSION}.

== Step 5: Upgrade your {PRODUCT_SHORT} Runtime environment

After upgrading your _Business Services_ source code (Step 3), you need to upgrade the Components in your Runtime environment and your stateful Workflows database before deploying a new version of the upgraded _Business Services_. The individual component deliverables have been replaced by two new Helm charts to facilitate the installation and license tracking of {PRODUCT_SHORT} components in your selected offering, DMOE or PMOE. They include the product specific licensing annotations, removing the need for manual intervention:

The Runtime helm charts for include the following Component Containers:

* {MANAGEMENT_CONSOLE}
* {MCP_SERVER}

It is recommended that you use the https://docs.openshift.com/container-platform/4.19/applications/deployments/route-based-deployment-strategies.html#deployments-blue-green_route-based-deployment-strategies[blue-green deployment strategy] for upgrading {MANAGEMENT_CONSOLE} so that you still have a reliable way of managing live _Business Services_ that might not have been upgraded to {PRODUCT_SHORT} version {VERSION_93X} yet. 

Follow the steps in xref:../installation/runtime-environment.adoc[Installing → Runtime Environment Helm chart] to install the new {MANAGEMENT_CONSOLE} version {MCP_SERVER}.

{MANAGEMENT_CONSOLE} {VERSION} is a drop-in replacement for the {VERSION_930} version, see xref:../installation/management-console.adoc[Installing → The Runtime environment Helm chart] for information on installing {MANAGEMENT_CONSOLE} and {MCP_SERVER}.

Once you have a new installation for {MANAGEMENT_CONSOLE} version {VERSION_930}, you can follow the standard guidance on how to deploy a new version of your _Business Services_ (see xref:../building-deploying/services-build.adoc[Building Business Services executables] and xref:../building-deploying/services-deployment.adoc[Deploying Business Services]).

[#migrate-stateful-workflow-db]
=== Upgrading your stateful Workflow database(s)

You can upgrade your database(s) used by _Business Services_ that run stateful workflows in {PRODUCT_SHORT} to {VERSION}. Perform the upgrade using the database migration scripts included in the `bamoe-{VERSION}-db-utils.zip` archive.

NOTE: This step is necessary to be able to use the new {PIM_ADDON} see xref:../managing-monitoring/migration-with-pim.adoc[Migrating your in-flight Process Instances using PIM]

The archive provides scripts named `from--$PREVIOUS_RELEASE--to--$CURRENT_RELEASE.sql` for each subsystem in a _Business Service_ that uses the Compact Architecture. These subsystems are Data-Index, Data-Audit, Jobs Service, User Tasks, and Runtime Persistence.

Before you begin, make sure you upgrade your _Business Services_ and your database(s) together. 

To upgrade safely:

* Back up your database

* Test the migration in a staging environment

* Apply the scripts sequentially for each subsystem 

* Schedule downtime for production

* Verify that all services function correctly after the upgrade

Avoid using KIE Flyway for automatic database schema migration in production environments. Instead, apply the scripts manually to maintain control and reduce the risk of issues.

For more information, see xref:../building-deploying/services-deployment.adoc#production-database-creation[Creating your database schema for stateful Workflows based on BAMOE Installation DDL scripts] and xref:../workflow/overview.html[Overview of stateful Workflows with Compact Architecture].