= Patching your 9.4 version
include::../partials/attributes.adoc[]
include::../styles/images.adoc[]

This section describes the steps you must take to apply a patch to your {PRODUCT_SHORT} installation and _Business Services_ projects developed in version {VERSION_X}. 

See the following docs if you are upgrading from a version prior to this:

* xref:upgrade-overview.adoc[Upgrading from a previous version of {PRODUCT_SHORT}]

{PRODUCT_SHORT} provides automated update tools to apply patch updates to the components in your Dev and Runtime environments. It is important to maintain your patch updates in order to benefit from the security fixes and bug corrections. 

This guide will walk you through patching your:

* {PRODUCT_SHORT} Dev environment with {MVN_REPO}, {CANVAS}, and {DEV_TOOLS}

* _Business Service(s)_ project(s)

* {PRODUCT_SHORT} Runtime environment with {MANAGEMENT_CONSOLE}, {MCP_SERVER} and upgraded versions of your _Business Services_

== Step 1: Download product archives

Download the new versions of your currently installed components from  {PRODUCT_PASSPORT_ADVANTAGE_LINK}[IBM Passport Advantage], or via the {DEV_PROGRAM_PAGE_LINK}[IBM Business Automation Manager Open Editions Developer Program]. 

// is there an upgrade tool or does the helm chart have an automatic upgrade mechanism?

== Step 2: Patch your Dev environment

Follow the steps in xref:../installation/development-environment.adoc[Installing → Dev Environment Helm chart] to install the new versions of {MVN_REPO}, {CANVAS} and {MCP_SERVER}.

The {VERSION} version of {CANVAS} is a drop in replacement for the {VERSION_940} version. The projects you saved to your browser before the upgrade can simply be opened after installing the new version. 

[NOTE]
====
If you have customized your previous {CANVAS} installation, remember to apply the same environment variables to the new installation. The same applies for customized container images for {CANVAS} Dev Deployments.
====

=== Upgrade {DEV_TOOLS}
{DEV_TOOLS} versions are managed by the Extension update mechanism in VS Code. You can set automatic update or manage it manually when notified. Because of version differences in the models supported by the BPMN, DMN, and Test Scenario editors it is recommended to choose when you upgrade to avoid issues when running models in services that have not been upgraded when the tools are upgraded. See xref:../tools/developer-tools-for-vscode.adoc[{DEV_TOOLS}].

== Step 3: Upgrade your _Business Service(s)_ project(s)

_Business Service(s)_ project(s) can be upgraded by changing their Maven dependencies and configuration files.  

The project structure is not changed, updates only need to be made to the versions, names of some dependencies and files.

[start=1]
. Upgrade the {PRODUCT_SHORT} BOM in the project POM file to {BOM_VERSION}:
+
[source,xml,subs="+attributes"]
----
<dependency>
  <groupId>com.ibm.bamoe</groupId>
  <artifactId>bamoe-bom</artifactId>
  <version>{BOM_VERSION}</version>
  <type>pom</type>
  <scope>import</scope>
</dependency>
----

== Step 4: Verify the upgrade of your _Business Service(s)_ project(s)
To verify that your upgrade is successful, rebuild the project using Maven's standard command or any other customized build command you might have in your project.

[source,console]
----
mvn clean package
----

You will get Maven streaming text with the message `Build Success` at the end if your upgrade was successful. 

You can now continue developing your _Business Service_ project on {PRODUCT_SHORT} version {VERSION}.

== Step 5: Upgrade your {PRODUCT_SHORT} Runtime environment

After upgrading your _Business Services_ source code (Step 3), you need to upgrade the components in your Runtime environment 

Install new versions of {MANAGEMENT_CONSOLE} and {MCP_SERVER}, by following the steps in xref:../installation/runtime-environment.adoc[Installing → Runtime Environment Helm chart].


Install new versions of {MANAGEMENT_CONSOLE} and {MCP_SERVER}, by following the steps in xref:../installation/runtime-environment.adoc[Installing → Runtime Environment Helm chart].

If you have stateful workflows in your _Business Services_ you will need to complete step 6 to update your database. If you only have DMN and DRL in your _Business Services_ you can now deploy your upgraded _Business Services_.


[#migrate-stateful-workflow-db]
== Step 6: Upgrade your stateful Workflow database(s)

If you have _Business Services_ that run stateful workflows in your system you can upgrade your runtime database using the database migration scripts included in the `bamoe-{VERSION}-db-utils.zip` archive.

The archive provides scripts named `from--$PREVIOUS_RELEASE--to--$CURRENT_RELEASE.sql` for each subsystem in a _Business Service_ that uses the Compact Architecture (Data-Index, Data-Audit, Embedded Jobs Service, User Tasks, and Runtime Persistence).

You must upgrade your _Business Services_ and your database(s) together. 

To upgrade safely:

. Back up your database

. Test the migration in a staging environment

. Schedule downtime if you are updating a production database

. Apply the scripts sequentially for each subsystem 

. Verify that all services function correctly after the upgrade

Avoid using KIE Flyway for automatic database schema migration in production environments. Instead, apply the scripts manually to maintain control and reduce the risk of issues.

For more information, see xref:../building-deploying/services-deployment.adoc#production-database-creation[Creating your database schema for stateful Workflows using {DDLS}]. 

Once you have installed your Runtime environment and updated the database for any stateful workflows in your system, you can follow the standard guidance on how to deploy upgraded versions of your _Business Services_ (see xref:../building-deploying/services-build.adoc[Building Business Services executables] and xref:../building-deploying/services-deployment.adoc[Deploying Business Services]).
