= Developing stateful business process services with BPMN 
include::../partials/attributes.adoc[]

Stateful business process services are introduced as a technology preview in this {PRODUCT} {PRODUCT_VERSION}. As a technology preview is not fully supported by IBM you should not use the technology for in production systems. IBM will be collecting your feedback on the functionality available in this technology preview through xxxx. 


== Overview and architecture
Describes the components and architecture of stateful workflow service. 

== Installation
Describes installation of a development environment (production environment will be described later)

== Getting started
This sample will be packaged for delivery https://github.com/apache/incubator-kie-kogito-examples/tree/main/kogito-quarkus-examples/process-usertasks-timer-data-index-persistence-addon-quarkus

Description of various important aspects of the sample

== BPMN editing in Canvas and VS Code
This section lists the supported BPMN elements in the tech preview showing how to use them in the two possible BPMN editors: process variables, events, service tasks a.k.a work item handlers, script and decision tasks, timers, Human-tasks 

For more information on BPMN see the Object Management Group (OMG ) Business Process Model and Notation 2.0 specification[xxxxx].

== Developing a business process service
More information about the historical/auditing query capabilities - https://github.com/kiegroup/kogito-apps/blob/main/data-audit/README.md and setting the right dependencies for your service.

== Deploying a business process service
To be defined
