include::../partials/attributes.adoc[]
= {MVN_REPO} libraries reference

include::../styles/images.adoc[]

Listed below you can find all consumable dependencies included in {MVN_REPO}. 

Dependencies not listed here are considered internal and should not be used directly.

Internal dependencies are subject to https://maven.apache.org/repositories/artifacts.html[GAV] and internal contents changing without notice.

== BAMOE BOMs (Bill of Materials)

To facilitate upgrading your _Business Services_ projects to newer versions of BAMOE and simplify version management, BAMOE provides BOMs, adhering to Maven's best pratices.

More on Maven's https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#Bill_of_Materials_.28BOM.29_POMs[Bill 
of Materials (BOM) POMs guide].

---

----
<dependency>
  <groupId>com.ibm.bamoe</groupId>
  <artifactId>bamoe-bom</artifactId>
</dependency>
----

Gives your _Business Service_ project access to fully supported libraries.

---

----
<dependency>
  <groupId>com.ibm.bamoe</groupId>
  <artifactId>bamoe-techpreview-bom</artifactId>
</dependency>
----

Gives your _Business Service_ project access to libraries in technology preview state.

== Decisions, Rules, and Decision Tables (Quarkus)
Mandatory dependencies for enabling Decisions and Rules in your _Business Services_ with Quarkus.

More at xref:../editing/quarkus-dmn-drl.adoc[Decisions and Rules services wih Quarkus].

----
<dependency>
  <groupId>org.drools</groupId>
  <artifactId>drools-quarkus-decisions</artifactId>
</dependency>
----
----
<dependency>
  <groupId>org.drools</groupId>
  <artifactId>drools-quarkus-rules</artifactId>
</dependency>
----

== Decisions, Rules, and Decision Tables (Spring Boot)
Mandatory dependencies for enabling Decisions and Rules in your _Business Services_ with Spring Boot.

More at xref:../editing/springboot-dmn-drl.adoc[Decisions and Rules services wih Spring Boot].

----
<dependency>
  <groupId>org.drools</groupId>
  <artifactId>drools-decisions-spring-boot-starter</artifactId>
</dependency>
----
----
<dependency>
  <groupId>org.drools</groupId>
  <artifactId>drools-rules-spring-boot-starter</artifactId>
</dependency>
----
----
<plugin>
  <groupId>org.kie.kogito</groupId>
  <artifactId>kogito-maven-plugin</artifactId>
</plugin>
----

== Decisions, Rules, and Decision Tables (Dev + testing)

More at xref:../editing/authoring-scesim.adoc[Authoring unit tests with Test Scenarios].

----
<dependency>
  <groupId>org.kie.kogito</groupId>
  <artifactId>kogito-scenario-simulation</artifactId>
</dependency>
----

== Decisions, Rules, and Decision Tables (Add-ons)

----
<dependency>
  <groupId>org.kie</groupId>
  <artifactId>kie-addons-quarkus-events-decisions</artifactId>
</dependency>
----
----
<dependency>
  <groupId>org.drools</groupId>
  <artifactId>drools-addons-quarkus-events-rules</artifactId>
</dependency>
----

----
<dependency>
  <groupId>org.kie</groupId>
  <artifactId>kie-addons-springboot-events-decisions</artifactId>
</dependency>
----
----
<dependency>
  <groupId>org.drools</groupId>
  <artifactId>drools-addons-springboot-events-rules</artifactId>
</dependency>
----

== Workflows (Quarkus)
Mandatory dependencies for enabling Workflows in your _Business Services_ with Quarkus.

More at xref:../workflow/workflows-with-quarkus.adoc[Workflows services with Quarkus].

----
<dependency>
  <groupId>org.jbpm</groupId>
  <artifactId>jbpm-quarkus</artifactId>
</dependency>
----
----
<dependency>
  <groupId>org.jbpm</groupId>
  <artifactId>jbpm-with-drools-quarkus</artifactId>
</dependency>
----

== Workflows (Spring Boot)

_Business Services_ containing Workflows can't be built with Spring Boot at the present moment.

== Workflows (Add-ons and extra features)
----
<dependency>
  <groupId>org.kie</groupId>
  <artifactId>kie-addons-quarkus-process-management</artifactId>
</dependency>
----
----
<dependency>
  <groupId>org.kie</groupId>
  <artifactId>kie-addons-quarkus-events-process</artifactId>
</dependency>
----
----
<dependency>
  <groupId>org.kie</groupId>
  <artifactId>kie-addons-quarkus-knative-eventing</artifactId>
</dependency>
----
----
<dependency>
  <groupId>org.kie</groupId>
  <artifactId>kie-addons-quarkus-messaging</artifactId>
</dependency>
----
----
<dependency>
  <groupId>org.jbpm</groupId>
  <artifactId>jbpm-addons-quarkus-mail</artifactId>
</dependency>
----
----
<dependency>
  <groupId>org.kie.kogito</groupId>
  <artifactId>kogito-rest-workitem</artifactId>
</dependency>
----

== Workflows (Dev + testing)
More at xref:../workflow/workflows-with-quarkus.adoc[Workflows services with Quarkus].
----
<dependency>
  <groupId>org.jbpm</groupId>
  <artifactId>jbpm-quarkus-devui</artifactId>
</dependency>
----
----
<dependency>
  <groupId>org.kie</groupId>
  <artifactId>kie-addons-quarkus-process-svg</artifactId>
</dependency>
----
----
<dependency>
  <groupId>org.kie</groupId>
  <artifactId>kie-addons-quarkus-source-files</artifactId>
</dependency>
----

== Workflows (Stateful) persistence

More at xref:../workflow/configuring-persistence-for-stateful-workflows.adoc[Configuring persistence for stateful Workflows].

----
<dependency>
  <groupId>org.kie</groupId>
  <artifactId>kie-addons-quarkus-persistence-jdbc</artifactId>
</dependency>
----

----
<dependency>
  <groupId>com.ibm.bamoe</groupId>
  <artifactId>bamoe-mssql-mappings</artifactId>
</dependency>
----

== Workflows (Stateful) subsystem :: Data-Index

More at xref:../workflow/overview.adoc#data-index[The Data-Index subsystem].

----
<dependency>
  <groupId>org.kie</groupId>
  <artifactId>kogito-addons-quarkus-data-index-jpa</artifactId>
</dependency>
----

== Workflows (Stateful) subsystem :: Data-Audit

More at xref:../workflow/overview.adoc#data-audit[The Data-Audit subsystem].

----
<dependency>
  <groupId>org.kie</groupId>
  <artifactId>kogito-addons-quarkus-data-audit</artifactId>
</dependency>
----
----
<dependency>
  <groupId>org.kie</groupId>
  <artifactId>kogito-addons-quarkus-data-audit-jpa</artifactId>
</dependency>
----

== Workflows (Stateful) subsystem :: Jobs Service

More at xref:../workflow/overview.adoc#jobs-service[The Jobs Service subsystem].

----
<dependency>
  <groupId>org.kie</groupId>
  <artifactId>kogito-addons-quarkus-jobs</artifactId>
</dependency>
----
----
<dependency>
  <groupId>org.kie</groupId>
  <artifactId>kogito-addons-quarkus-jobs-management</artifactId>
</dependency>
----
----
<dependency>
  <groupId>org.kie.kogito</groupId>
  <artifactId>jobs-service-storage-jpa</artifactId>
</dependency>
----

== Workflows (Stateful) subsystem :: User Tasks

More at xref:../workflow/overview.adoc#user-tasks[The User Tasks subsystem].

----
<dependency>
  <groupId>org.jbpm</groupId>
  <artifactId>jbpm-addons-quarkus-usertask-storage-jpa</artifactId>
</dependency>
----

== Monitoring

More at xref:../runtime-services-modeling/monitoring-services.adoc[Monitoring Business Services].

----
<dependency>
  <groupId>org.kie</groupId>
  <artifactId>kie-addons-quarkus-monitoring-prometheus</artifactId>
</dependency>
----
----
<dependency>
  <groupId>org.kie</groupId>
  <artifactId>kie-addons-springboot-monitoring-prometheus</artifactId>
</dependency>
----

== Decisions, Rules, and Decision Tables (Embedded Java mode)
More at xref:../editing/dmn-decisions-embedded-java-mode.adoc[Executing Decisions in embedded Java mode] and More at xref:../editing/drl-rules-embedded-java-mode.adoc[Executing Rules in embedded Java mode].
----
<dependency>
  <groupId>org.drools</groupId>
  <artifactId>drools-core</artifactId>
</dependency>
----
----
<dependency>
  <groupId>org.drools</groupId>
  <artifactId>drools-compiler</artifactId>
</dependency>
----
----
<dependency>
  <groupId>org.drools</groupId>
  <artifactId>drools-model-compiler</artifactId>
</dependency>
----
----
<dependency>
  <groupId>org.drools</groupId>
  <artifactId>drools-mvel</artifactId>
</dependency>
----
----
<dependency>
  <groupId>org.drools</groupId>
  <artifactId>drools-decisiontables</artifactId>
</dependency>
----
----
<dependency>
  <groupId>org.drools</groupId>
  <artifactId>drools-xml-support</artifactId>
</dependency>
----
----
<dependency>
  <groupId>org.kie</groupId>
  <artifactId>kie-dmn-core</artifactId>
</dependency>
----
----
<plugin>
  <groupId>org.kie</groupId>
  <artifactId>kie-maven-plugin</artifactId>
</plugin>
----

== BAMOE ILMT Compliance libraries

More at xref:../installation/ilmt-overview.adoc[Installing → Licenses and tracking usage]

----
<dependency>
  <groupId>com.ibm.bamoe</groupId>
  <artifactId>bamoe-ilmt-compliance-quarkus-dmoe</artifactId>
</dependency>
----
----
<dependency>
  <groupId>com.ibm.bamoe</groupId>
  <artifactId>bamoe-ilmt-compliance-spring-boot-dmoe</artifactId>
</dependency>
----
----
<dependency>
  <groupId>com.ibm.bamoe</groupId>
  <artifactId>bamoe-ilmt-compliance-quarkus-pamoe</artifactId>
</dependency>
----
----
<dependency>
  <groupId>com.ibm.bamoe</groupId>
  <artifactId>bamoe-ilmt-compliance-spring-boot-pamoe</artifactId>
</dependency>
----
