include::../partials/attributes.adoc[]
= {MVN_REPO} libraries reference

include::../styles/images.adoc[]

Listed below you can find all libraries included in {MVN_REPO}.

Format:
----
groupId ::: artifactId
----

== BAMOE BOMs (Bill of Materials)
----
com.ibm.bamoe ::: bamoe-bom
----
----
com.ibm.bamoe ::: bamoe-techpreview-bom
----

== BAMOE ILMT Compliance libraries
----
com.ibm.bamoe ::: bamoe-ilmt-compliance-quarkus-dmoe
----
----
com.ibm.bamoe ::: bamoe-ilmt-compliance-quarkus-pamoe
----
----
com.ibm.bamoe ::: bamoe-ilmt-compliance-spring-boot-dmoe
----
----
com.ibm.bamoe ::: bamoe-ilmt-compliance-spring-boot-pamoe
----

== Libraries

=== Decisions, Rules, and Decision Tables (Quarkus)
----
org.drools ::: drools-quarkus-decisions
----
----
org.drools ::: drools-quarkus-rules
----

=== Decisions, Rules, and Decision Tables (Spring Boot)
----
org.drools ::: drools-decisions-spring-boot-starter
----
----
org.drools ::: drools-rules-spring-boot-starter
----

=== Decisions, Rules, and Decision Tables (Dev + testing)
----
org.kie.kogito ::: kogito-scenario-simulation
----

=== Workflows (Quarkus)
----
org.jbpm ::: jbpm-quarkus
----
----
org.jbpm ::: jbpm-with-drools-quarkus
----

=== Workflows (Add-ons and extra features)
----
org.kie ::: kie-addons-quarkus-process-management
----
----
org.kie ::: kie-addons-quarkus-events-decisions
----
----
org.kie ::: kie-addons-springboot-events-decisions
----
----
org.drools ::: drools-addons-quarkus-events-rules
----
----
org.drools ::: drools-addons-springboot-events-rules
----
----
org.kie ::: kie-addons-quarkus-events-process
----
----
org.kie ::: kie-addons-quarkus-knative-eventing
----
----
org.kie ::: kie-addons-quarkus-messaging
----
----
org.jbpm ::: jbpm-addons-quarkus-mail
----
----
org.kie.kogito ::: kogito-rest-workitem
----

=== Workflows (Dev + testing)
----
org.jbpm ::: jbpm-quarkus-devui
----
----
org.kie ::: kie-addons-quarkus-process-svg
----
----
org.kie ::: kie-addons-quarkus-source-files
----

=== Workflows (Stateful) persistence
----
org.kie ::: kie-addons-quarkus-persistence-jdbc
----

=== Workflows (Stateful) persistence
_Additional dependency only for Microsoft SQL Server_
----
com.ibm.bamoe ::: bamoe-mssql-mappings
----

=== Workflows (Stateful) subsystem :: Data-Index
----
org.kie ::: kogito-addons-quarkus-data-index-jpa
----

=== Workflows (Stateful) subsystem :: Data-Audit
----
org.kie ::: kogito-addons-quarkus-data-audit
----
----
org.kie ::: kogito-addons-quarkus-data-audit-jpa
----

=== Workflows (Stateful) subsystem :: Jobs Service
----
org.kie ::: kogito-addons-quarkus-jobs
----
----
org.kie ::: kogito-addons-quarkus-jobs-management
----
----
org.kie.kogito ::: jobs-service-storage-jpa
----

=== Workflows (Stateful) subsystem :: User Tasks
----
org.jbpm ::: jbpm-addons-quarkus-usertask-storage-jpa
----

=== Monitoring
----
org.kie ::: kie-addons-quarkus-monitoring-prometheus
----
----
org.kie ::: kie-addons-springboot-monitoring-prometheus
----

=== Decisions, Rules, and Decision Tables on embedded Java mode
----
org.drools ::: drools-core
----
----
org.drools ::: drools-compiler
----
----
org.drools ::: drools-model-compiler
----
----
org.drools ::: drools-mvel
----
----
org.drools ::: drools-decisiontables
----
----
org.drools ::: drools-xml-support
----
----
org.kie ::: kie-dmn-core
----