= Building _Business Service_ project with Gradle vs Maven
include::../partials/attributes.adoc[]
include::../styles/images.adoc[]

You can use Gradle as the build system by following standard Gradle conventions and practices. Gradle build support is provided in two different ways, depending on the framework you use:

* Quarkus projects are built using the Quarkus plugin.
* Spring Boot projects are built using the `kogito-gradle-plugin`.

The supported version is Gradle 9.2. It is possible to use either a system-wide `gradle` executable or the project-specific `gradlew` executable for both frameworks.

== Structure

The overall structure of your project is the same regardless of the framework you use. The contents of the `src` folder in a Gradle project are the same as in a Maven project.

In comparison to Maven project, you can see the following files in your Gradle project:

* No pom.xml file.
* A `gradle.properties` file, that you use to define properties referenced from `settings.gradle` and `build.gradle` files.
* A `settings.gradle` file, which serves as the entry point of every Gradle project. For more information, see xref:https://docs.gradle.org/current/userguide/settings_file_basics.html[Settings File Basics] in the official Gradle documentation.
* A `build.gradle` file, which defines the build configuration, tasks, and plugins; refer to the official Gradle documentation for more details.

== Profiles

Gradle does not have a built-in *profile* feature like Maven.

To replicate Maven-style profiles in a Quarkus and Spring Boot projects using Gradle, do the following steps:

. Create separate Gradle files for each profile (e.g., `profile-dev.gradle`, `profile-prod.gradle`).
. Put profile-specific settings or properties inside the created files.
. Keep all shared configuration in the main `build.gradle` file.
. At build time, include the correct profile file depending on the `buildProfile` environment variable.

The following example shows how you can simulate Maven-style profiles in a Quarkus project using Gradle. 
Each profile has its own file that contains only the dependencies specific to that environment.

In `profile-dev.gradle` you define required dependencies when building the application in development mode, such as using the in-memory H2 database.

[source,xml]
----
// profile-dev.gradle

dependencies {
    implementation 'io.quarkus:quarkus-jdbc-h2'
}
----

In `profile-prod.gradle` you add the dependencies needed for the production environment, for example using PostgreSQL.

[source,xml]
----
// profile-prod.gradle

dependencies {
    implementation 'io.quarkus:quarkus-jdbc-postgresql'
}
----

In the main `build.gradle` file, you load the correct profile based on the `buildProfile` property. If no profile is provided, it defaults to `prod`.

[source,java]
----
// build.gradle

if (!hasProperty('buildProfile')) ext.buildProfile = 'prod'

apply from: "profile-${buildProfile}.gradle"
----

After setting up Gradle files for each profile, `buildProfile` variable could be set as system property, or as the following command line property:

[source,xml]
----
gradlew -PbuildProfile=dev ....
----

== SpringBoot build support

Spring Boot project support is provided through the `kogito-gradle-plugin`, which serves as the Gradle equivalent of the `kogito-maven-plugin`.

The `kogito-gradle-plugin` adds a new task called `generateModel`, and sets up the following internal task flow that runs before and after it:

**Classes task**:: A default task, that compiles all Java sources under `src/main/java`.

**generateModel**:: Reads the project's models and generates Java sources in `./build/generated/sources/kogito`.

**compileSecondaryJava**:: A custom task, that compiles all of the generated sources from the previous step.

To ensure the application works correctly, all Spring Boot tasks that rely on compiled code must run after `compileSecondaryJava`.

All relevant versions are defined in `gradle.properties` file.

[source,xml]
----
#Gradle properties

springBootVersion=3.4.11
springBootDependencyManagementVersion=1.1.5
taskTreeVersion=4.0.1
junitVersion=5.12.1
bamoeVersion=9.4.0 (<---verify)
----

Overall configuration is done in `settings.gradle` file and ensures the Kogito plugin is correctly mapped at build time. 

[source,xml]
----
pluginManagement {
  repositories {
    mavenLocal()
    mavenCentral()
    maven {
      url = uri("https://plugins.gradle.org/m2/")
    }
  }
  resolutionStrategy {
    eachPlugin {
      if (requested.id.namespace == "org.kie.kogito") {
        useModule("org.kie.kogito:kogito-gradle-plugin:${requested.version}")
      }
    }
  }
}
rootProject.name = "(service_specific)"
----

NOTE: At runtime, `requested.version` is replaced with the actual plugin version coming from `bamoeVersion`.

The main build file, `build.gradle`, applies the Spring Boot and Kogito plugins, sets up repositories, dependencies, and configures build tasks.

[source,xml]
----
plugins {
  id 'java'
  id("org.kie.kogito.gradle") version "${bamoeVersion}"
  id "org.springframework.boot" version "${springBootVersion}"
  id("io.spring.dependency-management") version "${springBootDependencyManagementVersion}"

  // Inspection purpose
  id "com.dorongold.task-tree" version "${taskTreeVersion}"
}

repositories {
  mavenCentral()
  mavenLocal()
}

dependencies {
  implementation platform("org.kie.kogito:kogito-spring-boot-bom:${bamoeVersion}")
  implementation("org.springframework.boot:spring-boot-starter-web")
  implementation("org.jbpm:jbpm-spring-boot-starter")
  implementation("org.drools:drools-decisions-spring-boot-starter")
  testImplementation("org.junit.jupiter:junit-jupiter:${junitVersion}")
  testImplementation("org.springframework.boot:spring-boot-starter-test")
  testImplementation("io.rest-assured:rest-assured")
  developmentOnly 'org.springframework.boot:spring-boot-devtools'
}

group '(service_specific)'
version '(service_specific)'

generateModelConfig {
  jsonSchemaVersion = "DRAFT_2019_09"
}

compileJava {
  options.encoding = 'UTF-8'
  options.compilerArgs << '-parameters'
}

compileTestJava {
  options.encoding = 'UTF-8'
}

springBoot {
  mainClass = '(service_specific)'
}

tasks.named("resolveMainClassName") {
  dependsOn(tasks.named("compileSecondaryJava"))
}

tasks.named("bootRun") {
  dependsOn(tasks.named("compileSecondaryJava"))
}

tasks.named("bootJar") {
  dependsOn(tasks.named("compileSecondaryJava"))
}

tasks.named("jar") {
  dependsOn(tasks.named("compileSecondaryJava"))
  from(tasks.named("compileSecondaryJava").get())
}

tasks.named("compileTestJava") {
  dependsOn(tasks.named("compileSecondaryJava"))
}

test {
  dependsOn(tasks.named("compileSecondaryJava"))
  useJUnitPlatform()
}
----

NOTE: During execution, the `bamoeVersion` value you assign to the `org.kie.kogito.gradle` plugin is internally mapped to `requested.version` by Gradle’s plugin resolution mechanism.

To ensure that Spring Boot builds and runs correctly, you must configure `build.gradle` so that all final tasks execute after the `compileSecondaryJava` task. This is done through the following task dependencies:

[source,xml]
----
tasks.named("resolveMainClassName") {
  dependsOn(tasks.named("compileSecondaryJava"))
}

tasks.named("bootRun") {
  dependsOn(tasks.named("compileSecondaryJava"))
}

tasks.named("bootJar") {
  dependsOn(tasks.named("compileSecondaryJava"))
}

tasks.named("jar") {
  dependsOn(tasks.named("compileSecondaryJava"))
  from(tasks.named("compileSecondaryJava").get())
}

tasks.named("compileTestJava") {
  dependsOn(tasks.named("compileSecondaryJava"))
}

test {
  dependsOn(tasks.named("compileSecondaryJava"))
  useJUnitPlatform()
}
----

This configuration ensures that tasks such as `test`, `jar`, `bootRun`, and others are executed only after the `compileSecondaryJava` task.

With this configuration, all final build and execution tasks run after the `kogito-gradle-plugin` finishes generating and compiling the model classes, which in turn happens after the static Java classes are compiled. You can see the task ordering in the Gradle task tree:

[source,xml]
----
:bootRun
+--- :classes
|    +--- :compileJava
|    \--- :processResources
+--- :compileJava *
+--- :compileSecondaryJava
|    \--- :generateModel
|         \--- :classes *
\--- :resolveMainClassName
     +--- :classes *
     +--- :compileJava *
     \--- :compileSecondaryJava *
----

The following command build and start the project using the Spring Boot bootRun task:

[source,xml]
----
gradlew clean bootRun
----

=== Hot reload

Hot reload support in Gradle projects works similarly to Maven.

To enable the hot reload, do the following steps:

. Add the `org.springframework.boot:spring-boot-devtools` dependency inside the `dependencies` section of your `build.gradle` file. For more information, see xref:https://central.sonatype.com/artifact/org.springframework.boot/spring-boot-devtools[`org.springframework.boot:spring-boot-devtools`] external documentation.
. In the terminal, start the `compileSecondaryJava` task with continuous build enabled using the following command:
+
[source,xml]
----
gradlew clean compileSecondaryJava --continuous --parallel
----
+
This task will automatically re-run whenever source files are updated.
. In a second terminal, run the Spring Boot application:
+
[source,xml]
----
gradlew bootRun
----
+
NOTE: The `clean` task is not invoked.

When you modify any source file, Gradle rebuilds the affected code and Spring Boot reloads the application so the changes take effect immediately.

== Quarkus build support

Build support for Quarkus projects, including hot reload, is provided by the `io.quarkus` plugin. All necessary versions are defined in `gradle.properties file`.

[source,xml]
----
#Gradle properties
##3.27.1 needed to support gradle 9.2
quarkusPluginId=io.quarkus
quarkusPluginVersion=3.27.1
quarkusPlatformGroupId=io.quarkus.platform
quarkusPlatformArtifactId=quarkus-bom
quarkusPlatformVersion=3.27.1
taskTreeVersion=4.0.1
junitVersion=5.12.1
bamoeVersion=9.4.0 (<---verify)
----

Overall configuration is done in `settings.gradle` file and ensures the Quarkus plugin is correctly mapped at build time. 

[source,xml]
----
pluginManagement {
  repositories {
    mavenLocal()
    mavenCentral()
    maven {
      url = uri("https://plugins.gradle.org/m2/")
    }
  }

  plugins {
    id "${quarkusPluginId}" version "${quarkusPluginVersion}"
  }
}
rootProject.name = "(service_specific)"
----

The main build file, `build.gradle`, applies the Quarkus plugin, sets up repositories, dependencies, and configures build tasks.

[source,xml]
----
plugins {
  id 'java'
  id 'io.quarkus'

  // Inspection purpose
  id "com.dorongold.task-tree" version "${taskTreeVersion}"
}

repositories {
  mavenCentral()
  mavenLocal()
  maven {
    url = uri("https://repo.maven.apache.org/maven2/")
  }
  maven {
    url = uri("https://repository.apache.org/snapshots/")
  }
}

group '(service_specific)'
version '(service_specific)'

dependencies {
  implementation enforcedPlatform("${quarkusPlatformGroupId}:${quarkusPlatformArtifactId}:${quarkusPlatformVersion}")
  implementation 'io.quarkus:quarkus-arc'
  implementation 'io.quarkus:quarkus-resteasy'
  implementation 'io.quarkus:quarkus-resteasy-jackson'
  implementation 'io.quarkus:quarkus-smallrye-openapi'

  implementation platform("org.kie.kogito:kogito-bom:${bamoeVersion}")

  implementation 'org.jbpm:jbpm-with-drools-quarkus'
  implementation 'org.kie.kogito:process-workitems'
  implementation 'org.kie.kogito:jbpm-flow'
  implementation 'org.kie.kogito:jbpm-bpmn2'
  implementation 'org.drools:drools-quarkus-decisions'
  testImplementation("org.junit.jupiter:junit-jupiter:${junitVersion}")
  testImplementation 'io.quarkus:quarkus-junit5'
  testImplementation("io.rest-assured:rest-assured")
}

test {
  systemProperty "java.util.logging.manager", "org.jboss.logmanager.LogManager"
}

compileJava {
  options.encoding = 'UTF-8'
  options.compilerArgs << '-parameters'
}

compileTestJava {
  options.encoding = 'UTF-8'
}
----

Quarkus provides built-in hot reload via the `quarkusDev` task. To build and start the project with hot reload enabled, run the following command:
[source,xml]
----
gradlew clean quarkusDev
----

When you modify any source file, Gradle rebuilds the affected code and Quarkus reloads the application so the changes take effect immediately.