= Building _Business Services_ executables
include::../partials/attributes.adoc[]
include::../styles/images.adoc[]

Building an executable application is the first step in deploying _Business Services_ to your runtime environment. There are several types of executable you can create, and trade-offs will vary depending on your requirements. This section covers building with the two supported frameworks: Quarkus and Spring Boot.

While both frameworks offer convenient ways for building container images and/or other types of executables directly from your _Business Services_ projects, you are not constrained by them. You are free to use any other build method, technique, tool or workflow you find suitable for your team and organization.

As an additional option, you can use Gradle build support. Quarkus projects use the `io.quarkus` plugin, while Spring Boot projects use the `kogito-gradle-plugin`. Although Gradle does not offer native build profiles like Maven, similar behavior can be achieved through conditional configuration based on a `buildProfile` environment variable. The supported Gradle version is 9.2, using either a system-installed `gradle` command or the included `gradlew` wrapper. For more information about Gradle, see https://docs.gradle.org/9.2.1/userguide/gradle_basics.html[Gradle official documentation].

== Quarkus build support with Maven

When you build your Business Service with Quarkus, you can select from several strategies to generate executables. Because you fully manage your _Business Service_ project on {PRODUCT_SHORT}, you can choose the build method that best aligns with your deployment architecture.

Quarkus supports the following build strategies:

* Recommended: Container image
* Native executable
* Standard JAR

=== Building your _Business Service_ project by using Container image

_Business Services_ on {PRODUCT_SHORT} are commonly deployed to hybrid cloud environments, including Red Hat OpenShift and Kubernetes. To build your _Business Service_ project as a container image, see https://quarkus.io/version/3.20/guides/container-image[Container Images] in the Quarkus documentation.

For standard use-cases, run the following command to build the container image and store it in your local container registry:

[source,shell]
----
mvn clean package -Dquarkus.container-image.build=true
----

To verify that the image was created, run the following:

[source,shell]
----
docker image ls
----

Container images created with Quarkus can be both JVM- or native executable- based.

=== Building your _Business Service_ project by using native executable

Follow the official Quarkus guide at https://quarkus.io/version/3.20/guides/building-native-image[Building a Native Executable].

For standard use-cases, run the following command to build a native executable:

[source,shell]
----
mvn clean package -Dnative
----

The native executable is generated in the `target/` directory. You can run it with the following command:

[source,shell]
----
./target/{your-business-service-name}-{version}-runner
----

For more information on supported and tested environments, see xref:../release-notes/supported-environments.adoc[Supported environments].
For more information on {PRODUCT_SHORT} native support, see xref:../release-notes/known-limitations.adoc[Known limitations] for more information on {PRODUCT_SHORT} native support.

=== Building your _Business Service_ project by using standard JAR

For more information on how to create executable JARs with Maven, see the official Maven documentation, https://maven.apache.org/guides/getting-started/index.html#How_do_I_create_a_JAR_and_install_it_in_my_local_repository.3F[How to create a JAR]. 

Since Quarkus is included in your _Business Service_ project, an executable JAR is created automatically. For more information about types of executable JARs, see the official Quarkus documentation https://quarkus.io/version/3.20/guides/maven-tooling#fast-jar[Using fast-jar and Uber-jar creation].

For standard use-cases, run the following command to build the JAR:

[source,console]
----
mvn clean package
----

The JAR is generated in the `target/` directory. You can run it with the following command:

[source,shell]
----
java -jar target/quarkus-app/quarkus-run.jar
----

[NOTE]
====
If you are building container versions destined to be run on Linux s390x running on IBM Z you will need to specify the type of build-platform to use. This varies depending on the underlying Container Image extension that is being used:

Jlib:: Set `quarkus.jib.platforms=linux/s390x`.

Docker:: Set `quarkus.docker.buildx.platform=linux/s390x`.

Podman:: Set `quarkus.podman.platform=linux/s390x`.
====

== Spring Boot build support with Maven

Use standard Maven and Java commands to package and run the generated Spring Boot application.

Use the following command for building the application:

[source,shell]
----
mvn clean package
----

Use the following command for running the application locally:

[source,shell]
----
java -jar ./target/(name_of_the_application).jar
----

== Quarkus build support with Gradle

Build support for Quarkus projects is provided by the `io.quarkus` plugin. All necessary versions are defined in `gradle.properties` file.

[source,xml]
----
#gradle.properties
##3.27.1 needed to support gradle 9.2
quarkusPluginId=io.quarkus
quarkusPluginVersion=3.27.1
quarkusPlatformGroupId=io.quarkus.platform
quarkusPlatformArtifactId=quarkus-bom
quarkusPlatformVersion=3.27.1
taskTreeVersion=4.0.1
junitVersion=5.12.1
bamoeVersion=9.4.0
----

Overall configuration is done in `settings.gradle` file and ensures the Quarkus plugin is correctly mapped at build time. 

[source,xml]
----
pluginManagement {
  repositories {
    mavenLocal()
    mavenCentral()
    maven {
      url = uri("https://plugins.gradle.org/m2/")
    }
  }

  plugins {
    id "${quarkusPluginId}" version "${quarkusPluginVersion}"
  }
}
rootProject.name = "(service_specific)"
----

The main build file, `build.gradle`, applies the Quarkus plugin, sets up repositories, dependencies, and configures build tasks.

=== GraalVM

GraalVM is required for native builds. If you are using Gradle instead of Maven, the following Maven commands:

[source,shell]
----
mvn clean package -Dnative
----

[source,shell]
----
mvn clean package -Dquarkus.container-image.build=true
----

can be replaced with the equivalent Gradle command:

[source,shell]
----
./gradlew clean build \
  -Dquarkus.native.enabled=true \
  -Dquarkus.package.jar.enabled=false
----

NOTE: Maven places all build artifacts in the `/target` directory, while Gradle places them in the `build/` directory.

== Spring Boot build support with Gradle

Spring Boot support is provided by the `kogito-gradle-plugin`, the Gradle equivalent of `kogito-maven-plugin`, which introduces a `generateModel` task that runs after the standard classes task and before a custom `compileSecondaryJava` task that compiles generated sources. All Spring Boot tasks depending on compiled code must run after `compileSecondaryJava`, with versions defined in `gradle.properties`.

[source,xml]
----
#gradle.properties

springBootVersion=3.4.11
springBootDependencyManagementVersion=1.1.5
taskTreeVersion=4.0.1
junitVersion=5.12.1
bamoeVersion=9.4.0
----

Overall configuration is done in `settings.gradle` file and ensures the Kogito plugin is correctly mapped at build time. 

[source,xml]
----
pluginManagement {
  repositories {
    mavenLocal()
    mavenCentral()
    maven {
      url = uri("https://plugins.gradle.org/m2/")
    }
  }
  resolutionStrategy {
    eachPlugin {
      if (requested.id.namespace == "org.kie.kogito") {
        useModule("org.kie.kogito:kogito-gradle-plugin:${requested.version}")
      }
    }
  }
}
rootProject.name = "(service_specific)"
----

NOTE: At runtime, `requested.version` is replaced with the actual plugin version coming from `bamoeVersion`.

The main build file, `build.gradle`, applies the Spring Boot and Kogito plugins, sets up repositories, dependencies, and configures build tasks.

During execution, the `bamoeVersion` value you assign to the `org.kie.kogito.gradle` plugin is internally mapped to `requested.version` by Gradle's plugin resolution mechanism. To ensure that Spring Boot builds and runs correctly, you must configure `build.gradle` so that all final tasks execute after the `compileSecondaryJava` task. This is done through the following task dependencies:

[source,xml]
----
tasks.named("resolveMainClassName") {
  dependsOn(tasks.named("compileSecondaryJava"))
}

tasks.named("bootRun") {
  dependsOn(tasks.named("compileSecondaryJava"))
}

tasks.named("bootJar") {
  dependsOn(tasks.named("compileSecondaryJava"))
}

tasks.named("jar") {
  dependsOn(tasks.named("compileSecondaryJava"))
  from(tasks.named("compileSecondaryJava").get())
}

tasks.named("compileTestJava") {
  dependsOn(tasks.named("compileSecondaryJava"))
}

test {
  dependsOn(tasks.named("compileSecondaryJava"))
  useJUnitPlatform()
}
----

This configuration ensures that tasks such as `test`, `jar`, `bootRun`, and others are executed only after the `compileSecondaryJava` task.

With this configuration, all final build and execution tasks run after the `kogito-gradle-plugin` finishes generating and compiling the model classes, which in turn happens after the static Java classes are compiled.

You can build and start the project using the Spring Boot `bootRun` task, using the following command:

[source,xml]
----
gradlew clean bootRun
----
