= Building _Business Services_ executables
include::../partials/attributes.adoc[]
include::../styles/images.adoc[]

Building an executable application is the first step in deploying _Business Services_ to your production environment. There are several types of executable you can create, and trade-offs will vary depending on your requirements. This section covers building with the two supported frameworks: Quarkus and Spring Boot.

While both frameworks offer convenient ways for building Container images and/or other types of executables directly from your _Business Services_ projects, you are not constrained by them. You are free to use any other build method, technique, tool or workflow you find suitable for your team and organization.

== Quarkus

When you build your _Business Service_ with Quarkus, there are different strategies you can choose to build executables. You fully control your _Business Service_ project on {PRODUCT_SHORT} and can choose which strategy better suits your planned architecture.

The official Quarkus guides will help you choose the strategy that is the best match for you.

* *a. Container image (recommended)*: _Business Services_ on {PRODUCT_SHORT} usually get deployed to a hybrid-cloud environment  (OpenShift or Kubernetes). To build your _Business Service_ project as an executable Container image, follow the official Quarkus guide at https://quarkus.io/version/3.20/guides/container-image[Container Images].
+
For standard use-cases, run the following command:
+
[source,shell]
----
mvn clean install -Dquarkus.container-image.build=true
----
+
A Container image will be installed to your local Container image registry. You can see it using the following command:
+
[source,shell]
----
docker image ls
----
+
Container images created with Quarkus can be both JVM - or Native Executable - based.
+
*b. Native Executable*: Follow the official Quarkus guide at https://quarkus.io/version/3.20/guides/building-native-image[Building a Native Executable].
+
For standard use-cases, run the following command:
+
[source,shell]
----
mvn clean install -Dnative
----
+
The Native Executable will be on the `target/` directory and you can execute it with
+
[source,shell]
----
./target/{your-business-service-name}-{version}-runner
----
+
For more information on supported and tested environments see xref:../release-notes/supported-environments.adoc[Supported environments]. See xref:../release-notes/known-limitations.adoc[Known limitations] for more information on {PRODUCT_SHORT} native support.
+
* *c. Standard JAR*: _Business Services_ projects on {PRODUCT_SHORT} are Maven projects. For more information on how to create executable JARs with Maven, see the official Maven documentation at https://maven.apache.org/guides/getting-started/index.html#How_do_I_create_a_JAR_and_install_it_in_my_local_repository.3F[How to create a JAR]. Since Quarkus is included in your _Business Service_ project, an executable JAR will be produced for you. See more information about types of executable JARs in https://quarkus.io/version/3.20/guides/maven-tooling#fast-jar[Using fast-jar and Uber-jar creation].
+
For standard use-cases, run the following command:
+
[source,console]
----
mvn clean package
----
+
Your executable JAR will be on the `target/` directory and you can execute it with
+
[source,shell]
----
java -jar target/quarkus-app/quarkus-run.jar
----

[NOTE]
====
If you are building container versions destined to be run on Linux s390x running on IBM Z you will need to specify the type of build-platform to use. This varies depending on the underlying Container Image extension that is being used:

Jlib:: set `quarkus.jib.platforms=linux/s390x`

Docker:: set `quarkus.docker.buildx.platform=linux/s390x`

Podman:: set `quarkus.podman.platform=linux/s390x`
====

== Spring Boot

Standard Maven or Java commands are required to package and start the generated application:

.Building
[source]
----
mvn clean package
----
.Running locally
[source]
----
java -jar ./target/(name_of_the_application).jar
----

