= Decisions Embedded Java mode
include::../partials/attributes.adoc[]

This documentation is a simplified version of the community documentation available https://docs.drools.org/8.44.0.Final/drools-docs/drools/KIE/index.html[here].

Building Drools-based KIE project make use of Maven, and aligns with Maven practices.
A KIE project or module is simply a Maven Java project or module; with an additional metadata file `META-INF/kmodule.xml`.
The `kmodule.xml` file is the descriptor that selects resources to KIE bases and configures those KIE bases and sessions.
We explain those later in this document.

While standard Maven can build and package KIE resources, it will not provide validation at build time.
There is a Maven plugin (`kie-maven-plugin`) which is recommended to use to get build time validation.
The plugin also generates many classes, making the runtime loading faster too.

== kmodule.xml
Since meaningful defaults have been provided for all configuration aspects, the simplest `kmodule.xml` file can contain just an empty kmodule tag like the following:

.An empty kmodule.xml example
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<kmodule xmlns="http://www.drools.org/xsd/kmodule"/>
----

In this way the kmodule will contain one single default `KieBase`.
All KIE assets stored under the resources folder, or any of its subfolders, will be compiled and added to it.
To trigger the building of these artifacts it is enough to create a `KieContainer` for them.

.Creating a KieContainer that reads the files to be built from the classpath
[source,java]
----
KieServices kieServices = KieServices.Factory.get();
KieContainer kieContainer = kieServices.getKieClasspathContainer();
----

`KieServices` is the interface from where it is possible to access all the KIE building and runtime facilities.
In the code above, all the Java sources and the KIE resources are compiled and deployed into the `KieContainer` which makes its contents available for use at runtime.

The `kmodule.xml` allows to define and configure one or more `KieBase` s and for each `KieBase` all the different `KieSession` s that can be created from it, as showed by the https://docs.drools.org/8.44.0.Final/drools-docs/drools/KIE/index.html#_thekmodulexmlfile[example].
Then it is possible to simply retrieve the `KieBase` s and `KieSession` s from the `KieContainer` using their names.

.Obtaining KieBase and KieSession using their names from kmodule.xml
[source,java]
----
KieServices kieServices = KieServices.Factory.get();
KieContainer kieContainer = kieServices.getKieClasspathContainer();

KieBase kieBase1 = kieContainer.getKieBase("KBase1");
KieSession kieSession1 = kieContainer.newKieSession("KSession2_1");
StatelessKieSession kieSession2 = kieContainer.newStatelessKieSession("KSession2_2");
----

== pom.xml
To run decision in embedded java mode, we will need to use `kie-maven-plugin` in our project.
Also few KIE specific dependencies are needed.
Please update your `pom.xml` in the following way.

// TODO is 9.1.0.rc2-ibm-0001 the final to use?
[source,xml]
----
  <packaging>kjar</packaging>
  ...
  <dependencies>
    <dependency>
      <groupId>org.drools</groupId>
      <artifactId>drools-compiler</artifactId>
      <version>9.1.0.rc2-ibm-0001</version>
    </dependency>
    <dependency>
      <groupId>org.drools</groupId>
      <artifactId>drools-model-compiler</artifactId>
      <version>9.1.0.rc2-ibm-0001</version>
    </dependency>
    <!-- For DebugRuleRuntimeEventListener.java -->
    <dependency>
      <groupId>org.drools</groupId>
      <artifactId>drools-core</artifactId>
      <version>9.1.0.rc2-ibm-0001</version>
    </dependency>  
    <!-- For DRL files -->
    <dependency>
      <groupId>org.drools</groupId>
      <artifactId>drools-mvel</artifactId>
      <version>9.1.0.rc2-ibm-0001</version>
    </dependency>
    <!-- For kmodule.xml -->
    <dependency>
      <groupId>org.drools</groupId>
      <artifactId>drools-xml-support</artifactId>
      <version>9.1.0.rc2-ibm-0001</version>
    </dependency>
    <!-- Logging -->
    <dependency>
        <groupId>org.slf4j</groupId>
        <artifactId>slf4j-api</artifactId>
        <version>2.0.13</version>
    </dependency>
    <dependency>
        <groupId>org.slf4j</groupId>
        <artifactId>slf4j-simple</artifactId>
        <version>2.0.13</version>
    </dependency>
  </dependencies>
  ...
  <build>
    <plugins>
      <plugin>
        <groupId>org.kie</groupId>
        <artifactId>kie-maven-plugin</artifactId>
        <version>9.1.0.rc2-ibm-0001</version>
        <extensions>true</extensions>
      </plugin>
    </plugins>
  </build>
----

== DRL based rules execution
Before we execute DRL based rules in java, we will mention few KIE API classes.

=== KieBase
The `KieBase` is a repository of all the application\'s knowledge definitions.
It will contain rules, processes, functions, and type models.
The `KieBase` itself does not contain data; instead, sessions are created from the `KieBase` into which data can be inserted and from which process instances may be started.
The `KieBase` can be obtained from the `KieContainer` containing the `KieModule` where the `KieBase` has been defined.


[source,java]
----
KieBase kieBase = kieContainer.getKieBase();
----

=== KieSession
The `KieSession` stores and executes on the runtime data.
It is created from the `KieBase` and has two implementations.

==== Stateful
The first one is https://docs.drools.org/8.44.0.Final/drools-docs/drools/rule-engine/index.html#kie-sessions-stateful-con_rule-engine[stateful].
It is obtained using `newKieSession()` method.
Stateful sessions can be worked with iteratively over time.

[source,java]
----
KieSession kieSession = kieBase.newKieSession();
----

=== Stateless
The second one is https://docs.drools.org/8.44.0.Final/drools-docs/drools/rule-engine/index.html#kie-sessions-stateless-con_rule-engine[stateless].
It is obtained using `newStatelessKieSession()` method.
Stateless is a one-off execution of a `KieRuntime` with a provided data set.
It may return some results, with the session being disposed at the end, prohibiting further iterative interactions.
You can think of stateless as treating an engine like a function call with optional return results.

[source,java]
----
StatelessKieSession kieSession = kieBase.newStatelessKieSession();
----

=== KieRuntime
The `KieRuntime` provides methods that are applicable to both rules and processes, such as setting globals and registering channels.
("Exit point" is an obsolete synonym for "channel".)

==== Globals
Globals are named objects that are made visible to the Drools rule engine, but in a way that is fundamentally different from the one for facts: changes in the object backing a global do not trigger reevaluation of rules.
Still, globals are useful for providing static information, as an object offering services that are used in the RHS of a rule, or as a means to return objects from the Drools rule engine.
When you use a global on the LHS of a rule, make sure it is immutable, or, at least, don\'t expect changes to have any effect on the behavior of your rules.

A global must be declared in a rules file, and then it needs to be backed up with a Java object.

[source]
----
global java.util.List list
----

With the KIE base now aware of the global identifier and its type, it is now possible to call `ksession.setGlobal()` with the global\'s name and an object, for any session, to associate the object with the global.
Failure to declare the global type and identifier in DRL code will result in an exception being thrown from this call.

[source,java]
----
List<String> list = new ArrayList<>();
kieSession.setGlobal("list", list);
----

Make sure to set any global before it is used in the evaluation of a rule.
Otherwise a `NullPointerException` will be thrown.

=== Event Model
The event package provides means to be notified of Drools rule engine events, including rules firing, objects being asserted, etc.
This allows separation of logging and auditing activities from the main part of your application (and the rules).

The `KieRuntimeEventManager` interface is implemented by the `KieRuntime` which provides two interfaces, `RuleRuntimeEventManager` and `ProcessEventManager`.
We will only cover the `RuleRuntimeEventManager` here.

The `RuleRuntimeEventManager` allows for listeners to be added and removed, so that events for the working memory and the agenda can be listened to.

The following code snippet shows how a simple agenda listener is declared and attached to a session.
It will print matches after they have fired.

[source,java]
----
kieSession.addEventListener(new DefaultAgendaEventListener() {
    public void afterMatchFired(AfterMatchFiredEvent event) {
        super.afterMatchFired(event);
        System.out.println(event);
    }
});
----

Drools also provides `DebugRuleRuntimeEventListener` and `DebugAgendaEventListener` which implement each method with a debug print statement.
To print all Working Memory events, you add a listener like this:

[source,java]
----
kieSession.addEventListener(new DebugRuleRuntimeEventListener());
----

All emitted events implement the `KieRuntimeEvent` interface which can be used to retrieve the actual `KnowlegeRuntime` the event originated from.

// TODO what branch/tag to use ? 999-20240521?
NOTE: To see available events browse `org.kie.api.event.rule` https://github.com/apache/incubator-kie-drools/tree/999-20240521/kie-api/src/main/java/org/kie/api/event/rule[package].


=== KieRuntimeLogger
The `KieRuntimeLogger` uses the comprehensive event system in Drools to create an audit log that can be used to log the execution of an application for later inspection.

[source,java]
----
KieRuntimeLogger logger =
  KieServices.Factory.get().getLoggers().newFileLogger(kieSession, "logdir/mylogfile");
// ... kieSession in action ...
logger.close();
----

=== Commands and the CommandExecutor
Both the stateful and stateless session interfaces extend the `CommandExecutor` interface.
The `CommandExecutor` allows for commands to be executed on those sessions, the only difference being that the `StatelessKieSession` executes `fireAllRules()` at the end before disposing the session.
The commands can be created using the https://github.com/apache/incubator-kie-drools/blob/999-20240521/kie-internal/src/main/java/org/kie/internal/command/CommandFactory.java[`CommandFactory`].

//TODO replace with some non cheese example, more business like
[source,java]
----
ExecutionResults executionResults = statelessKieSession.execute(
    CommandFactory.newBatchExecution(Arrays.asList(
        CommandFactory.newInsert(new Applicant("#0001", 20), "applicant"),
        CommandFactory.newInsert(new LoanApplication("#0001"), "application"),
        new SetActiveAgendaGroup("applicationGroup")           
      )
    )
);

executionResults.getResults().get("application");    
----

The previous example executes a single command.
The `BatchExecution` represents a composite command, created from a list of commands.
It will iterate over the list and execute each command in turn.
This means you can insert some objects, start a process, call `fireAllRules` and execute a query, all in a single `execute(…​)` call, which is quite powerful.

The `StatelessKieSession` will execute `fireAllRules()` automatically at the end.
However the keen-eyed reader probably has already noticed the `FireAllRules` command and wondered how that works with a `StatelessKieSession`.
The `FireAllRules` command is allowed, and using it will disable the automatic execution at the end; think of using it as a sort of manual override function.

Any command, in the batch, that has an out identifier set will add its results to the returned `ExecutionResults` instance.
Please notice `"applicant"` and `"application"` identifiers in our example.

=== Complete example
// TODO update link once PR merged
Can be found https://github.com/bamoe/bamoe-docs-source-code-examples/pull/5[here].

== DMN model execution
You can create or import DMN files in your Drools project using xref:../tools/authoring-decisions.adoc[KIE DMN Editor].

After you implement your DMN files in your Drools project, you can execute the DMN decision service by instantiating a KIE container that contains it directly as a dependency of the calling application.
Other options for creating and deploying DMN knowledge packages are also available, and most are similar for all types of knowledge assets, such as DRL files or process definitions.

Alternatively, you could package your DMN files as part of a Kogito cloud-native microservice.

A KIE container is local when the knowledge assets are either embedded directly into the calling program or are physically pulled in using Maven dependencies for the KJAR.
You typically embed knowledge assets directly into a project if there is a tight relationship between the version of the code and the version of the DMN definition.
Any changes to the decision take effect after you have intentionally updated and redeployed the application.
A benefit of this approach is that proper operation does not rely on any external dependencies to the run time, which can be a limitation of locked-down environments.

Using Maven dependencies enables further flexibility because the specific version of the decision can dynamically change, (for example, by using a `kmodule.xml` or a system property), and it can be periodically scanned for updates and automatically updated.
This introduces an external dependency on the deploy time of the service, but executes the decision locally, reducing reliance on an external service being available during run time.

=== Prerequisites
You have built the DMN project as a KJAR artifact and deployed it to a Maven repository, or you have included your DMN assets as part of your project classpath:

[source,bash]
----
mvn clean install
----

=== Procedure
In your client application, add the following dependencies to the relevant classpath of your Java project:

[source,xml]
----
<!-- Required for the DMN runtime API -->
<dependency>
  <groupId>org.kie</groupId>
  <artifactId>kie-dmn-core</artifactId>
  <version>9.1.0.rc2-ibm-0001</version>
</dependency>

<!-- Required if not using classpath KIE container -->
<dependency>
  <groupId>org.kie</groupId>
  <artifactId>kie-ci</artifactId>
  <version>9.1.0.rc2-ibm-0001</version>
</dependency>
----

Instead of specifying a Drools `<version>` for individual dependencies, consider adding the Drools bill of materials (BOM) dependency to dependencyManagement section of your project pom.xml file.
When you add the BOM files, the correct versions of transitive dependencies from the provided Maven repositories are included in the project.

.Example BOM dependency:
[source,xml]
----
<dependency>
  <groupId>org.kie</groupId>
  <artifactId>kie-dmn-bom</artifactId>
  <version>9.1.0.rc2-ibm-0001</version>
  <scope>import</scope>
  <type>pom</type>
</dependency>
----

.Create a KIE container from classpath or ReleaseId:
[source,java]
----
KieServices kieServices = KieServices.Factory.get();

ReleaseId releaseId = kieServices.newReleaseId( "org.acme", "my-kjar", "1.0.0" );
KieContainer kieContainer = kieServices.newKieContainer( releaseId );
----

.Alternative option:
[source,java]
----
KieServices kieServices = KieServices.Factory.get();

KieContainer kieContainer = kieServices.getKieClasspathContainer();
----

.Obtain DMNRuntime from the KIE container and a reference to the DMN model to be evaluated, by using the model namespace and modelName:
[source,java]
----
DMNRuntime dmnRuntime = KieRuntimeFactory.of(kieContainer.getKieBase()).get(DMNRuntime.class);

String namespace = "https://kie.org/dmn/_C83DFD16-A42A-46BE-A843-370444580E0F";
String modelName = "loan-application-age-limit";

DMNModel dmnModel = dmnRuntime.getModel(namespace, modelName);
----
.Execute the decision services for the desired model:
[source,java]
----
DMNContext dmnContext = dmnRuntime.newContext();  
dmnContext.set("Applicant", new Applicant("#0001", 20));  
dmnContext.set("Application", new LoanApplication("#0001"));  
DMNResult dmnResult = dmnRuntime.evaluateAll(dmnModel, dmnContext);  

for (DMNDecisionResult dr : dmnResult.getDecisionResults()) {  
    System.out.println(
        "Decision: '" + dr.getDecisionName() + "', " +
        "Result: " + dr.getResult());        
}
----

Instantiate a new DMN Context to be the input for the model evaluation.
Assign input variables for the input DMN context.
Evaluate all DMN decisions defined in the DMN model.
This example prints the similar output:

[source,bash]
----
Decision: 'Approvement', Result: {approved=false, explanation=Underage}
----

=== Complete example
// TODO update link once PR merged
Can be found https://github.com/bamoe/bamoe-docs-source-code-examples/pull/5[here].