= Runtime Services Modeling 
IBM, KIE Community

include::../partials/attributes.adoc[]

You can use {SERVERLESS_WORKFLOW_REPO_URL_VERSION}/specification.md[Serverless Workflow] definition files in your {PRODUCT} project to define your domain-specific orchestration services. Your Serverless Workflow definition files can be in JSON or YAML format with the extension `.sw.json` or `.sw.yaml`.

.Prerequisites
* You have created a {PRODUCT} project and have included any Java objects or other business assets required for your Serverless Workflow service.

.Procedure
. In your {PRODUCT} project, create or import a `.sw.json` or `.sw.yaml` Serverless Workflow definition file in the relevant folder, typically in `src/main/resources`.
+
{PRODUCT} supports both JSON and YAML formats for workflow definitions. You can use multiple workflow definitions in both formats if needed.
. Open the workflow definition file and define the following basic components:
+
--
.Serverless Workflow definition format in JSON
[source,json]
----
{
  "id": "sampleWorkflow",
  "version": "1.0",
  "name": "Sample Workflow",
  "description": "Sample Workflow",
  "functions": [],
  "events": [],
  "states": []
}
----

.Serverless Workflow definition format in YAML
[source,yaml]
----
id: sampleWorkflow
version: '1.0'
name: Sample Workflow
description: Sample Workflow
functions: []
events: []
states: []
----

The Serverless Workflow `functions`, `events`, and `states` are the core constructs for defining the orchestration behavior for your services. You can use one or all of these three constructs in your workflow definitions.

NOTE: You can find more information about the core constructs in the {SERVERLESS_WORKFLOW_REPO_URL_BASE}/blob/{SERVERLESS_WORKFLOW_VERSION_IN_REPO_URL}/specification.md#workflow-model[Workflow Model] section of the specification.

For example, the following Serverless Workflow definition performs a customer credit check in a loan application service to approve or deny the customer loan application:

.Example Serverless Workflow definition for credit check (JSON)
[source,json]
----
{
  "id": "customercreditcheck",
  "version": "1.0",
  "name": "Customer Credit Check Workflow",
  "description": "Perform Customer Credit Check",
  "functions": [
    {
      "name": "callCreditCheckMicroservice",
      "resource": "creditCheckResource",
      "type": "service"
    },
    {
      "name": "sendRejectionEmailFunction",
      "resource": "rejectEmailResource"
    }
  ],
  "events": [
    {
      "name": "CreditCheckCompletedEvent",
      "type": "creditCheckCompleteType",
      "source": "creditCheckSource",
      "correlation": [
        {
          "contextAttributeName": "customerId"
        }
      ]
    }
  ],
  "states": [
    {
      "name": "CheckCredit",
      "type": "callback",
      "start": {
        "kind": "default"
      },
      "action": {
        "functionRef": {
          "refName": "callCreditCheckMicroservice",
          "parameters": {
            "customer": "{{ $.customer }}"
          }
        }
      },
      "eventRef": "CreditCheckCompletedEvent",
      "transition": {
        "nextState": "EvaluateDecision"
      }
    },
    {
      "name": "EvaluateDecision",
      "type": "switch",
      "dataConditions": [
        {
          "condition": "{{ $.creditCheck[?(@.decision == 'Approved')] }}",
          "transition": {
            "nextState": "StartApplication"
          }
        },
        {
          "condition": "{{ $.creditCheck[?(@.decision == 'Denied')] }}",
          "transition": {
            "nextState": "RejectApplication"
          }
        }
      ],
      "defaultCondition": {
        "transition": {
          "nextState": "RejectApplication"
        }
      }
    },
    {
      "name": "StartApplication",
      "type": "operation",
      "actions": [
        {
          "subFlowRef": "startApplicationWorkflowId"
        }
      ],
      "end": {
        "kind": "default"
      }
    },
    {
      "name": "RejectApplication",
      "type": "operation",
      "actionMode": "sequential",
      "actions": [
        {
          "functionRef": {
            "refName": "sendRejectionEmailFunction",
            "parameters": {
              "applicant": "{{ $.customer }}"
            }
          }
        }
      ],
      "end": {
        "kind": "default"
      }
    }
  ]
}
----

.Example Serverless Workflow definition for credit check (YAML)
[source,yaml]
----
id: customercreditcheck
version: '1.0'
name: Customer Credit Check Workflow
description: Perform Customer Credit Check
functions:
- name: callCreditCheckMicroservice
  resource: creditCheckResource
  type: microservice
- name: sendRejectionEmailFunction
  resource: rejectEmailResource
events:
- name: CreditCheckCompletedEvent
  type: creditCheckCompleteType
  source: creditCheckSource
  correlation:
  - contextAttributeName: customerId
states:
- name: CheckCredit
  type: callback
  start:
    kind: default
  action:
    functionRef:
      refName: callCreditCheckMicroservice
      parameters:
        customer: "{{ $.customer }}"
  eventRef: CreditCheckCompletedEvent
  transition:
    nextState: EvaluateDecision
- name: EvaluateDecision
  type: switch
  dataConditions:
  - condition: "{{ $.creditCheck[?(@.decision == 'Approved')] }}"
    transition:
      nextState: StartApplication
  - condition: "{{ $.creditCheck[?(@.decision == 'Denied')] }}"
    transition:
      nextState: RejectApplication
  defaultCondition:
    transition:
      nextState: RejectApplication
- name: StartApplication
  type: operation
  actions:
    - subFlowRef: startApplicationWorkflowId
  end:
    kind: default
- name: RejectApplication
  type: operation
  actionMode: sequential
  actions:
  - functionRef:
      refName: sendRejectionEmailFunction
      parameters:
        applicant: "{{ $.customer }}"
  end:
    kind: default
----

For more Serverless Workflow definition examples in {PRODUCT}, see the https://github.com/kiegroup/kogito-examples[kogito-examples] repository in GitHub.
--
. Continue adding and defining any remaining components for your workflow definition files and save the completed files.

After you define your serverless workflow definitions, you can build and deploy your {PRODUCT} services as usual to your preferred cloud or container platform, such as {OPENSHIFT}. When an event trigger occurs, your application orchestrates your {PRODUCT} services according to the workflow definition or definitions that you have defined. If you are using a serverless deployment platform, such as OpenShift Serverless, your application automatically scales up based on incoming demand, or scales to zero after use.

[id="con-serverless-workflow-error-handling_{context}"]
== Error handling in Serverless Workflow

You can handle the exceptions that are thrown by `operation` nodes as described in the {SERVERLESS_WORKFLOW_REPO_URL_BASE}/blob/{SERVERLESS_WORKFLOW_VERSION_IN_REPO_URL}/specification.md#Workflow-Error-Handling[Serverless Workflow Specification].

NOTE: You need to specify the qualified name of the exception that might be thrown by the `operation` in the `code` field of the error definition.

https://github.com/kiegroup/kogito-examples/tree/stable/kogito-quarkus-examples/serverless-workflow-error-quarkus[serverless-workflow-error-quarkus] is an example application that invokes an `EvenService`, which is throwing `IllegalArgumentException` if the number in the workflow model is odd.
