= Configuring Service Security
include::../partials/attributes.adoc[]

{PRODUCT_SHORT} one of those applications that is designed for Quakus or SpringBoot application. Both frameworks natively offer a reliable authentication and authorization layer, consumable by user-designed applications if properly
configured. You will know how to configure your {PRODUCT_SHORT} project to exploit the Quarkus or SpringBoot authentication and authorization layer by defining some property values.

After you configure your {PRODUCT_SHORT} runtimes  correctly to integrate its framework security layer, it is possible to rely on an external IdP like Keycloak or Microsoft Entra ID as your project’s Identity and Access Management Solution. A key role of this architecture is the Management Console, which provides your {PRODUCT_SHORT} application’s user an integrated environment to log in to your application and interact with its entities like process instances, submit task forms, and view jobs, in a secured and authenticated way. For more information on Management Console, see xref:../installation/consoles-helm-charts.adoc[Management Console].

