= Securing _Business Service_ API endpoints
include::../partials/attributes.adoc[]
include::../styles/images.adoc[]


_Business Services_ on {PRODUCT_SHORT} rely on Quakus or Spring Boot for configuring authentication and authorization, and will query their provided security-related data for information about who is the authenticated user performing a request and what permissions (roles/groups) they have, especially the stateful Workflows subsystem for User Tasks.

After configuring your _Business Service_ correctly to integrate its security layer, it is possible to rely on an external Identity Providers (IdPs) like Keycloak or Microsoft Entra ID as your project’s Identity and Access Management Solution.

{MANAGEMENT_CONSOLE} can connect to secured _Business Services_ provided they expose enough information about their configured Identity Provider. See xref:#mgmt-console-oidc-proxy[Allowing {MANAGEMENT_CONSOLE} to connect to live _Business Services_] for more details.


== Authentication (Quarkus)

Quarkus supports the Bearer token authentication mechanism through the Quarkus OpenID Connect (OIDC) extension, based on the https://openid.net/developers/how-connect-works/[OpenID Connect] protocol. You will know how the authorization layer works in Quarkus with this useful https://quarkus.io/version/3.15/guides/security-oidc-bearer-token-authentication[guide] that explains how to do the set up correctly.

The first step is to configure the Quarkus OpenID Connect (OIDC) extension by setting the properties in the `src/main/resources/application.properties` file. 

The list of properties required to setup your project may change based on your security needs, Identity and Access Management Solution. 

Following is an example of the configuration.

[source]
----
quarkus.oidc.enabled=true
quarkus.oidc.tenant-enabled=true
quarkus.oidc.auth-server-url=http://localhost:8280/auth/realms/kogito
quarkus.oidc.client-id=kogito-service
quarkus.oidc.credentials.secret=secret
quarkus.oidc.application-type=hybrid
----

The following table describes in detail the properties suggested in the example, but it is only a subset of https://quarkus.io/version/3.15/guides/security-oidc-configuration-properties-reference[all properties available here].


[%header,cols=4]
[%autowidth]

|===

|Property | Description | Type | Default value
|quarkus.oidc.enabled | It determines OIDC extension is enabled
 | Boolean | true
|quarkus.oidc.tenant-enabled | Specifies whether the tenant configuration is
enabled
 | Boolean | true
|quarkus.oidc.auth-server-url  | The base URL of the OpenID
Connect (OIDC) server
 | URI | -
|quarkus.oidc.client.id  | The client id of the application
 | string  | -
|quarkus.oidc.credentials.secret  | The client secret used by the
client_secret_basic
authentication method
 | string  | -
|quarkus.oidc.application-type  | The application type, which can
be one of the following values:
web-app, service, hybrid.
To enable the compatibility
with Managment Console, this
property should be set as
“hybrid”
 | string  | service

|===


== Authorization (Quarkus)

Quarkus incorporates a pluggable web security layer. When security is active, the system performs a permission check on all HTTP requests to determine if they should proceed. For more information, see the official Quarkus guide for https://quarkus.io/version/3.15/guides/security-authorize-web-endpoints-reference[Authorization of web endpoints].

Following is an example of the configuration:

[source]
----
quarkus.http.auth.permission.authenticated.paths=/*
quarkus.http.auth.permission.authenticated.policy=authenticated
quarkus.http.auth.permission.public.paths=/q/*,/docs/*,/oidc/info
quarkus.http.auth.permission.public.policy=permit
----

Properties are pluggable based on how many permission rules you want to define for your application.

In the following example, two permissions are defined:

• authenticated: Used for REST entrypoints that requires an Authorization to be done.
• public: Used for publicly accessible REST entrypoints.

You can find a detailed explanation and  https://quarkus.io/version/3.8/guides/security-authorize-web-endpoints-reference[guide] to define your permissions and the effect on the required properties to add in your `application.property` file.

The available properties can be configured for all the used-defined permission rules.
For example, the `quarkus.http.auth.permission."permissions".policy` property with the specified permissions can have two properties detailed  in the following table:


[%header,cols=4]
[%autowidth]
|===

|Property | Description | Type | Default value
|quarkus.http.auth.permission."permissions".paths

_E.g.,

quarkus.http.auth.permission.authenticated.paths
quarkus.http.auth.permission.public.paths_

 | The paths that this
permission check applies
to. If the path ends in /*
then this is treated as a
path prefix, otherwise it is
treated as an exact
match.
 | List of
URI
 | -
 |quarkus.http.auth.permission."permissions".policy

_E.g.,

quarkus.http.auth.permission.authenticated.policy
quarkus.http.auth.permission.public.policy_

 | The HTTP policy that this
permission set is linked
to. There are three built-
in policies: permit, deny
and authenticated. Role
based policies can be
defined, and extensions
 | String | -
|===


[#mgmt-console-oidc-proxy]
== Allowing {MANAGEMENT_CONSOLE} to connect to live _Business Services_

For {MANAGEMENT_CONSOLE} to authenticate and connect to a _Business Service_ that is secured through an Identity Provider, the instance must make the Identity Provider URL available.

To solve this, you need to use the `quarkus-oidc-proxy` extension, as it creates new endpoints in the _Business Service_ where one of them is `/q/oidc/.well-known/openid-configuration`, which provides the Identity Provider URL (the same URL that is defined in the `quarkus.oidc.auth-server-url` property).

To add the `quarkus-oidc-proxy` extension, you need to add the following code to the list of dependencies in the `pom.xml` file:

[source,xml]
----
<dependency>
  <groupId>io.quarkiverse.oidc-proxy</groupId>
  <artifactId>quarkus-oidc-proxy</artifactId>
  <version>0.1.3</version>
</dependency>
----

NOTE: Version 0.1.3 of `quarkus-oidc-proxy` is compatible with Quarkus 3.15 (LTS). Do not use versions 0.2.x.
