= Building Business Services executables
include::../partials/attributes.adoc[]
include::../styles/images.adoc[]

[id="proc-kogito-creating-project"]
== Creating a Maven project for a {PRODUCT} service using {CANVAS}

[role="_abstract"]
Before you can begin developing _Business Services_, you need to create a Maven project where you can build your Business Automation assets and any other related resources for your application.

.Procedure
. Run {CANVAS} - see the xref:../installation/canvas.adoc[installation] chapter for more details on how to install and run it.
. If you do not already have a project or an asset file, create a DMN or BPMN file.
. Use the xref:../tools/applying-accelerators.adoc[Accelerators] functionality in {CANVAS} to create a project that is buildable and deployable.


== Building the project
.Procedure
. Download the (project).zip archive to a local directory and extract the file.
. In a command terminal, navigate to the extracted folder, and enter one of the following commands to build the project.

Quarkus support the following building modes:

* *JVM mode*: For compatibility with a Java virtual machine (JVM).
* *Native mode*: (Quarkus only, requires GraalVM or Mandrel) For direct binary execution as native code.

The command that you use depends on your preferred run mode and application environment:

* For JVM mode:
+
.On Quarkus
[source]
----
$ mvn clean package
----
+
* For native mode (requires GraalVM or Mandrel):
+
.On Quarkus only
[source]
----
$ mvn clean package -Dnative
----

[id="proc-kogito-running-app"]
== Running a _Business Service_

[role="_abstract"]
After you design the business decisions and processes for your {PRODUCT} service, you can run your Quarkus application in one of the following modes:

* *Development mode*: For local testing. On Quarkus, development mode also offers live reload of your processes and decisions in your running applications for advanced debugging.
* *JVM mode*: For compatibility with a Java virtual machine (JVM).
* *Native mode*: (Quarkus only, requires GraalVM or Mandrel) For direct binary execution as native code.

.Procedure
In a command terminal, navigate to the project that contains your {PRODUCT} service and enter one of the following commands, depending on your preferred run mode and application environment:

* For development mode:
+
--
.On Quarkus
[source]
----
$ mvn clean compile quarkus:dev
----
--
* For JVM mode:
+
--
.On Quarkus
[source]
----
$ mvn clean package
$ java -jar target/quarkus-app/quarkus-run.jar
----
--

* For native mode (requires GraalVM):
+
--
.On Quarkus only
[source]
----
$ mvn clean package -Dnative
$ ./target/sample-kogito-1.0-SNAPSHOT-runner
----
--

[NOTE]
========

Alternatively, you can use a container builder image. You do not need to install GraalVM because a container containing GraalVM is pulled automatically. Note that the executable targets a Linux kernel by default. For example:

--
.On Quarkus only (GraalVM native build using container)
[source]
----
$ mvn clean package -Dnative -Dquarkus.native.container-build
----
--

To use Mandrel instead of GraalVM, run the following command:

--
.On Quarkus only (Mandrel native build using container)
[source]
----
$ mvn clean package -Dnative -Dquarkus.native.container-build -Dquarkus.native.builder-image=quay.io/quarkus/ubi-quarkus-mandrel:21.1-java11
----
--

========


For further information about building a native image, see https://quarkus.io/guides/building-native-image#container-runtime[Quarkus - Building a Native Executable].
