= Using _Business Services_
include::../partials/attributes.adoc[]
include::../styles/images.adoc[]

Once your _Business Services_ are deployed (or when you're developing them locally), there are three main ways you can interact with the Workflows, Decisions, Rules, and/or Decision Tables you created:

- **REST and GraphQL API endpoints**
- **Message broker events** (for event-driven _Business Services_ containing specific events-related add-ons, configured in `application.properties`)
- **{MANAGEMENT_CONSOLE}** (for UI-based admin management of _Business Services_ containing Workflows)


== Using REST and GraphQL API endpoints

You can use any HTTP client to use your _Business Services_, and you're encouraged to do so in any way that aligns with your business goals and practices. _Business Services_ on {PRODUCT_SHORT} are mainly meant to be consumed by your other systems. Please refer to the individual API reference for more details. 

=== Workflows
** xref:../workflow/process-api.html[Process API]
** xref:../workflow/data-index-graphql-api.html[Data-Index GraphQL API]
** xref:../workflow/management-apis.html[Process Management API]
** xref:../workflow/user-tasks.html[User Tasks API]

=== Decisions
** xref:../editing/decision-api.html[Decision API]

// missing Rules
// missing Decision Table

== Using message broker events

Please refer to all examples containing *event-driven* in their name to see how you can configure your _Business Service_ to be executed when events are sent to your configured message broker's topic. All examples can be found in xref:../getting-started/examples.adoc[Example Business Services] shipped with the product deliverables.

== Using {MANAGEMENT_CONSOLE}

{MANAGEMENT_CONSOLE} connects to live _Business Services_ and allows you to manage _Business Services_ containing Workflows via a web-based UI. {MANAGEMENT_CONSOLE} is intended for admin usage. See more at xref:../runtime-services-modeling/consoles.adoc[Managing live Workflows using BAMOE Management Console].