[id='rn-removed-issues-ref']

include::_artifacts/document-attributes.adoc[]

= Removed components

The components listed in this section are removed.

== Support for Red Hat build of Kogito
Support for the Red Hat build of Kogito and Kogito image components are removed from the {PRODUCT} {ENTERPRISE_VERSION_806}. Security updates beyond version 8.0.5 are no longer provided. Contact IBM Support or your Tech Sales Representative for further assistance.

== Java 8 support
Java 8 support is removed in version {ENTERPRISE_VERSION_806} due to limitations with ongoing security vulnerability resolution and support. {PRODUCT} 8 security fixes continue to be provided to support Java 11. 
Upgrade to Java 11 and use Java 11 compatible applications. Contact IBM Support or your Tech Sales Representative for further assistance.

== Legacy process designer
The legacy process designer in {CENTRAL} is removed in {PRODUCT} {ENTERPRISE_VERSION_LONG}. If you intend to use the new process designer, migrate your existing processes to the new process designer and create new processes in the new process designer. For information about migrating projects to the new designer, see {URL_DEPLOYING_AND_MANAGING_SERVICES}/assembly-managing-projects.html[_{MANAGING_PROJECTS}_].
