= Key components
include::../partials/attributes.adoc[]


{PRODUCT_LONG} is a developer-first technology that offers a highly customizable solution setup. {PRODUCT_SHORT} is backed by well-known technologies, specifications, and open standards. 

The design of an automation solution and the components that are involved in the application lifecycle can be adapted to best fit each scenario. The modular structure of the solution allows for tailored, lightweight deployment units that efficiently use computational resources by including only what is needed.
This approach is possible with {PRODUCT_SHORT} v9.1 through the architectural design of the solution, which allows the creation of targeted solutions that are aimed for automating decisions, business rules, straight-through processes, and long-running business processes. 

Services designed to address particular domain business problems can improve team performance and simplify the application lifecycle from development to deployment.
An automation solution with IBM BAMOE includes:

* Development tools
* Process and decisions services: Java applications that delivers one or more automation capabilities.
* Additional components and supporting tools: to accelerate development, simplify installing product components on cloud platforms, and to add a developer-friendly UI to support process management capabilities.

Development tools, process and decision service, and additional components and supporting tools are the building blocks that are used to design applications to address the following requirements:

*Decision Automation*

* Decision Model and Notation (DMN): An open-standard designed to simplify the automation of repeatable rules by business users.
* Decisions tables in Excel: A common approach for automating simpler types of business rules based on tables written on `.xls` format.
* Technical business rules: By using Drools Rules Language (DRL), developers rely on maximum flexibility for rules automation.

*Process Automation (BPMN)*

* Straight-through Process: Executed from start to end without human interaction, and does not have state persistence.
* Business Process: covers a larger set of needs, such as long-running processes, human-driven workflows, timer-based process events, task audibility, storage of business key performance indicators (KPIs), and other scenarios involving data persistence.

*Process and Decision Automation*

A unified experience for combining decision and process automation that enables you to implement more complex scenarios through intelligent processes with automated decisions, orchestration of business decisions that are effortlessly combined independently of the chosen approach (DMN/XLS/DMN), and more. As a result, developers can seamlessly use data across different types of business assets, even though each asset type has a distinct data representation paradigm (For example, in processes, process variables; in decisions, data types; in business rules, facts).

[IMPORTANT]
====
The stateful process automation feature is a technology preview functionality in IBM {PRODUCT_SHORT} v9.1.0. For more information, see xref:../workflow/overview.html[Stateful processs overview].
====

== Components overview

When designing an automation service, each capability has a set of required and optional components that can be combined. The following sections describe the product components:

=== Development

* xref:../tools/canvas.adoc[{CANVAS}]
* {VS_CODE_BUNDLE_LINK}[{VS_CODE_BUNDLE}]
* xref:../tools/form-generation-tool.adoc[{FORM_GENERATION_TOOL}]

=== Execution

* Decision and Rules Engine
* Process Engine

=== Process Management

* xref:../runtime-services-modeling/console.html[Management Console]
* xref:../runtime-services-modeling/console.html[Task Console]

=== Automation add-ons

* Human tasks
* Integration
* Data persistence
* Data auditing
* Jobs and asynchronous services execution
* Observability with metrics decision and process services

For more information, see xref:../workflow/overview.adoc[Overview stateful process] and  xref:../runtime-services-modeling/runtime-services-modeling.adoc[Service monitoring with Prometheus and Grafana].