= Components
IBM, KIE Community

include::../partials/attributes.adoc[]

{PRODUCT} is a productized offering consisting of various components made in the Open Source KIE Community.
These components include Drools, Kogito, KIE Tools, and KIE Sandbox.

== Drools
Drools is a Business Rules Management System (BRMS) solution.
It provides a core Business Rules Engine (BRE), a web authoring and rules management application (Drools Workbench), full runtime support for Decision Model and Notation (DMN) models at Conformance level 3.

== Kogito
Kogito is a cloud-native business automation technology for building cloud-ready business applications.
Kogito is optimized for a hybrid cloud environment and adapts to your domain and tooling needs. 
The core objective of Kogito is to help you mold a set of business processes and decisions into your own domain-specific cloud-native set of services.

== KIE Tools and KIE Sandbox
These are the user facing applications used to aid in creating Business Process Model and Notation (BPMN), rules, diagrams, etc.
This includes a chrome extension, VS Code extension, and standalone editors
