= Key components
include::../partials/attributes.adoc[]


{PRODUCT_LONG} is a developer-first technology that offers a highly customizable set-up and solution. {PRODUCT_SHORT} is developed using well-known technologies, specifications, and open standards. 

The design of an automation solution, including the components that are part of the application lifecycle, can be easily be adapted to different scenarios. The modular structure of the solution allows for custom, lightweight deployment units that efficiently use computational resources by including only what is needed.
This approach is possible with {PRODUCT_SHORT} version 9.1 through the architectural design of the solution, which allows the creation of solutions targeting the automation of decisions, business rules, straight-through processes, and long-running business processes. 

Services designed to address particular domain business problems can improve team performance and simplify the application lifecycle from development to deployment.
An automation solution with IBM BAMOE includes:

* Development tools
* Process and decision services: Java applications that deliver one or more automation capabilities.
* Additional components and supporting tools: to accelerate development, simplify installation of product components on cloud platforms, and to add a developer-friendly UI to support process management capabilities.

These are the building blocks that are used to design applications to address the following requirements:

*Decision Automation*

Decisions can be automated using one of the three following technologies:

. Decision Model and Notation (DMN): An open-standard designed to simplify the automation of repeatable rules by business users.
. Decisions tables in Excel: A common approach for automating simpler types of business rules based on tables written on `.xls` format.
. Technical business rules: By using Drools Rules Language (DRL), developers rely on maximum flexibility to automate rules.

*Process Automation (BPMN)*

Automated processes may be one of the following:

* Straight-through process: Executed from start to end without human interaction, with no persistence of state.
* Business process: covers a larger set of needs, such as long-running processes, human-driven workflows, timer-based process events, task audibility, storage of business key performance indicators (KPIs), and other scenarios involving data persistence.

*Process and Decision Automation*

More complex scenarios can be implemented through the orchestration of business decisions to combine intelligent processes with automated decisions. They can easily be combined whatever the chosen approach (DMN/XLS/DMN), providing a unified experience and the seamless use of data across different business assets. This is possible despite each asset type using a specific data representation paradigm:

* `process variables` in processes
* `data types` in decisions
* `facts` in business rules

[IMPORTANT]
====
The stateful process automation feature is a technology preview in IBM {PRODUCT_SHORT} version {VERSION_910} and {VERSION_911}. For more information, see xref:../workflow/overview.html[Stateful processs overview].
====

== Components overview

When you design an automation service each capability has a set of required and optional components. The following sections list the product components:

*Development*

* xref:../tools/canvas.adoc[{CANVAS}]
* {VS_CODE_BUNDLE_LINK}[{VS_CODE_BUNDLE}]
* xref:../tools/form-generation-tool.adoc[{FORM_GENERATION_TOOL}]

*Execution*

* Decision and Rules Engine
* Process Engine

*Process Management*

* Management Console
* Task Console

For more information see xref:../workflow/consoles.html[Interacting with processes and tasks using Consoles]

*Automation add-ons*

* Human tasks
* Integration
* Data persistence
* Data auditing
* Jobs and asynchronous services execution
* Observability with metrics decision and process services

For more information, see xref:../workflow/overview.adoc[Overview stateful process] and  xref:../runtime-services-modeling/runtime-services-modeling.adoc[Service monitoring with Prometheus and Grafana].