= Key components
include::../partials/attributes.adoc[]

{PRODUCT} is a productized offering consisting of various components made in close collaboration with the Open Source Apache KIE Community.
These components include Drools, Kogito, jBPM, and KIE Tools.

== Apache Drools
Drools is a Business Rules Management System (BRMS) solution.
It provides a core Business Rules Engine (BRE), a web authoring and rules management application, and full runtime support for Decision Model and Notation (DMN) models at Conformance level 3.

== Apache Kogito
//Kogito Apps, Kogito Runtimes - need to mention both?
Kogito is a cloud-native business automation technology for building cloud-ready business applications.
Kogito is optimized for a hybrid cloud environment and adapts to your domain and tooling needs. 
The core objective of Kogito is to help you mold a set of business processes and decisions into your own domain-specific cloud-native set of services.

== Apache jBPM
jBPM originates from BPM (Business Process Management), but has evolved to enable users to pick their own path in business automation.
It provides various capabilities that simplify and externalize business logic into reusable assets such as cases, processes, decision tables and more.

== KIE Tools
These are the user facing applications used to aid in creating Business Process Model and Notation (BPMN), rules, diagrams, etc.

This includes:

* {VS_CODE_BUNDLE_LINK}[{VS_CODE_BUNDLE}]
* xref:../tools/canvas.adoc[{CANVAS}]
* xref:../tools/form-generation-tool.adoc[{FORM_GENERATION_TOOL}]

////
The following tools are useful community tools that are usable with {PRODUCT_SHORT} but that are not supported as part of the product delivery:

* Standalone editors
* Chrome extension
////

