= Components
include::../partials/attributes.adoc[]

{PRODUCT} is a productized offering consisting of various components made in close collaboration with the Open Source KIE Community.
These components include Drools, Kogito, and KIE Tools.

== Drools
Drools is a Business Rules Management System (BRMS) solution.
It provides a core Business Rules Engine (BRE), a web authoring and rules management application (Drools Workbench), full runtime support for Decision Model and Notation (DMN) models at Conformance level 3.

== Kogito
Kogito is a cloud-native business automation technology for building cloud-ready business applications.
Kogito is optimized for a hybrid cloud environment and adapts to your domain and tooling needs. 
The core objective of Kogito is to help you mold a set of business processes and decisions into your own domain-specific cloud-native set of services.

== KIE Tools
These are the user facing applications used to aid in creating Business Process Model and Notation (BPMN), rules, diagrams, etc.

This includes:

* {VS_CODE_BUNDLE_LINK}[*{VS_CODE_BUNDLE}*]
* xref:../tools/canvas.adoc[{CANVAS}]
* Standalone editors
* Chrome extension
* xref:../tools/form-generation-tool.adoc[{FORM_GENERATION_TOOL}]

NOTE: The Chrome extension, Standalone editors and {FORM_GENERATION_TOOL} are not supported as part of {PRODUCT}, however, they are community projects that are usable.
