= Key components
include::../partials/attributes.adoc[]


{PRODUCT_LONG} is a developer-first technology that offers a highly customizable solution setup. {PRODUCT_SHORT} is backed by well-known technologies, specifications, and open standards. The design of an automation solution and the components that are involved in the application lifecycle can be adapted to best fit each scenario. The modular structure of the solution allows for tailored, lightweight deployment units that efficiently use computational resources by including only what is needed.
This approach is possible with {PRODUCT_SHORT} v9.1 through the architectural design of the solution, which allows the creation of targeted solutions that are aimed for automating decisions, business rules, straight-through processes, and long-running business processes. Services designed to address particular domain business problems can improve teams performance and simplify the application's lifecycle from development to deployment.
From a high-level view, an automation solution with IBM BAMOE includes:

* Development tools
* Process and decisions service: Java applications that delivers one or more automation capabilities.
* Side components and supporting tools: Multiple components and tools to accelerate development (aqui to falando do form cli runner, n da pra botar comment), simplify installing product components on cloud platforms, and to add a developer-friendly UI to support process management capabilities.

Development tools, process and decision service, and side components and supporting tools are the building blocks that are used to design applications to address the these requirements:

* Decision Automation
+
** Decision Model and Notation (DMN): An open-standard designed to simplify the automation of repeatable rules by business users.
** Decisions tables in Excel: A common approach for automating simpler types of business rules based on tables written on xls format.
** Technical business rules: By using DRL (Drools Rules Language), developers rely on maximum flexibility for rules automation.

* Process Automation (BPMN):
+
** Straight-through Process: Executed from start to end without human interaction, and does not have state persistence.
** Business Process: covers a larger set of needs, such as long-running processes, human-driven workflows, timer-based process events, task audibility, storage of business key performance indicators (KPIs), and other scenarios involving data persistence.

* Process and Decision Automation:
A unified experience for combining decision and process automation that opens doors for going beyond basic scenarios by having intelligent processes with automated decisions, orchestration of business decisions that are effortlessly combined independently of the chosen approach (DMN/XLS/DMN), and much more. As a result, developers can seamlessly consume (? exchange/use/?) data across different types of business assets, despite each distinct data representation paradigm across the asset types (Foe example, in processes, process variables; in decisions, data types; in business rules, facts.).

[IMPORTANT]
====
The stateful process automation feature is a tech-preview functionality in IBM {PRODUCT_SHORT} v9.1.0. For more information, see [#todo add link].
====

== Components overview

When designing an automation service, each of the previously mentioned capabilities has a set of required and optional components to mix and match. Following are the product components high-level view:

* Development:
+
** IBM Business Automation Manager Open Editions Canvas [#TODO add Link]
** IBM BAMOE Developer Tools for Microsoft VS Code [#TODO add Link]
** Forms Generation CLI (Tech Preview) [#TODO add Link]
**  Accelerator projects (?)

* Execution:
+
** Decision & Rules Engine
** Process Engine

* Process Management (Tech Preview):
+
** Management Console [#TODO add Link] | add description
** Task Console [#TODO add Link] | add description

* Automation add-ons:
** Human tasks
** Integration
** Data persistence
** Data auditing
** Jobs and asynchronous services execution
** Observability with metrics decision and process services

For additional information about the add-ons, see [#todo add link].

//Below are old Data
{PRODUCT} is a productized offering consisting of various components made in close collaboration with the Open Source Apache KIE Community.
These components include Drools, Kogito, jBPM, and KIE Tools.

== Apache Drools
Drools is a Business Rules Management System (BRMS) solution.
It provides a core Business Rules Engine (BRE), a web authoring and rules management application, and full runtime support for Decision Model and Notation (DMN) models at Conformance level 3.

== Apache Kogito
//Kogito Apps, Kogito Runtimes - need to mention both?
Kogito is a cloud-native business automation technology for building cloud-ready business applications.
Kogito is optimized for a hybrid cloud environment and adapts to your domain and tooling needs. 
The core objective of Kogito is to help you mold a set of business processes and decisions into your own domain-specific cloud-native set of services.

== Apache jBPM
jBPM originates from BPM (Business Process Management), but has evolved to enable users to pick their own path in business automation.
It provides various capabilities that simplify and externalize business logic into reusable assets such as cases, processes, decision tables and more.

== KIE Tools
These are the user facing applications used to aid in creating Business Process Model and Notation (BPMN), rules, diagrams, etc.

This includes:

* {VS_CODE_BUNDLE_LINK}[{VS_CODE_BUNDLE}]
* xref:../tools/canvas.adoc[{CANVAS}]
* xref:../tools/form-generation-tool.adoc[{FORM_GENERATION_TOOL}]

////
The following tools are useful community tools that are usable with {PRODUCT_SHORT} but that are not supported as part of the product delivery:

* Standalone editors
* Chrome extension
////



