= Upstream KIE Community
include::../partials/attributes.adoc[]

{PRODUCT} is not solely worked on by IBM employees.
Engineering and planning are done in the open - for everyone to see and participate.
We welcome contributions (code, bug reports, documentation, demos, etc) from around the globe and are happy to call all contributors our colleagues.
The "upstream" for a software project are any libraries, dependencies, or original works that are used in a project.
Red Hat described this relationship quite well at https://www.redhat.com/en/blog/what-open-source-upstream[What is an open source upstream] on redhat.com.

{PRODUCT} follows a mixed type of https://www.redhat.com/en/blog/understanding-open-source-governance-models[governance model].
Firstly, {PRODUCT}, is an IBM product.
As such, it is "corporate-backed".
Other projects that are part of the upstream follow a "benevolent dictatorship" model.
Don't let that scare you though, that simply means that there is a structure involved in how source code contributions are accepted.

== Who's who in this upstream community?

There are three tiers within the community:

. Architects/Senior Members
. Component Leads
. Contributors

People within the community move within these tiers for various reasons.
At some point an architect may not be able to contribute as much as they would like, and they step down and become a contributor.
A contributor, conversely, over time may become a component lead and eventually architect based on merit and time with the project.

=== Senior Members - The Architects

The following list reflects the current state of the senior members. 
Mark Proctor, the Drools co-founder, and the benevolent dictator. 
Red Hat also appointed him as the community leader.

Alex Porcelli. 
Initial contribution dated 15+ years with a new DRL compiler. 
The last decade or so led all related tools—the original author of Business Central, the architect responsible for VS Code and KIE Sandbox. 
Once pointed out by Red Hat as the Engineer leader assigned for the transition to IBM, Alex's position became "number 2". 
Before the change, Alex and Kris Verlaenen were peers at "number 2".

Kris Verlaenen. 
Original Drools Flow engineer, runtime architect. 
Workflow domain expert.

Eder Ignatowicz. 
Eder joined this group as soon as Alex was announced to lead the IBM transition of the projects. 
Eder's focus is associated with tools.

=== Component Leads

* Mario Fusco, Drools
* Matteo Mortari, DMN
* Enrique Gonzalez Martinez, jBPM
* Tiago Bento, KIE-Tools & Multiplying Architecture
* Roger Martinez Palleja, Stunner & BPMN
* Yeser Amer, DMN Editor
* Pere Fernandez, Forms and Consoles
* Ricardo Zanini, Serverless Workflow

=== How work is tracked?

There isn't a single way to track work in community.
While the projects were sponsored by Red Hat, JIRA was used for community and also product. 

Since moving to IBM, the project work is tracked at https://github.com/orgs/IBM/projects/21/views/1[IBM's GitHub board]

This board is for community work only, product specifics may not show up in the board.
