= Helm Charts
IBM; KIE Community
include::../partials/attributes.adoc[]

This chart can be used to deploy a {CANVAS} image on a https://kubernetes.io[Kubernetes] cluster using the https://helm.sh[Helm package manager].

== Installing the Chart

To install the chart with the release name `kie-sandbox`:

First download all chart dependencies into the the charts folder:

[source,console]
----
$ helm dependency update
----

Netx, run the helm chart:

[source,console]
----
$ helm install kie-sandbox ./
----

== Uninstalling the Chart

To uninstall the `kie-sandbox` deployment:

[source,console]
----
$ helm uninstall kie-sandbox
----

== Passing Environmental variables

This chart uses default environmental variables from `values.yaml` file.
We can override those by passing it from command line.

[source,console]
----
$ helm install kie-sandbox ./ --set image.repository=quay.io
----

== Configuration

The following table lists the configurable parameters of the KIE sandbox chart and their default values.

|===
| Parameter | Description | Default

| `image.registry`   
| Name of image registry                                                    
| `"quay.io"`              

| `image.account`    
| Account of image                                                          
| `"kie-tools"`            

| `image.tag`        
| Overrides the KIE sandbox image tag whose default is the chart version 
| `"latest"`               

| `image.name`       
| The name of image                                                         
| `"kie-sandbox-image"` 

| `service.port`     
| The http service port port                                                
| `8080`                   

| `service.nodePort` 
| The HTTP Service node port if type is NodePort                            
| `32002`                  
|===
