= Tracking license use in Kubernetes and OpenShift
include::../partials/attributes.adoc[]
include::../styles/images.adoc[]


== Prerequisites

Follow the https://www.ibm.com/docs/en/cloud-paks/foundational-services/4.14.0?topic=service-installing-license[procedure] to install the License Service for stand-alone software.

NOTE: The link directs you to the instructions on installing the standalone version of IBM License Service included in the IBM Cloud Pak(TM) Foundational Services. Use the Change Version menu in the docs to select the most recent version. It is important to note that the {PRODUCT_SHORT} is not part of IBM Cloud Pak(TM).

== Tracking {PRODUCT_SHORT} Component Licenses
When you install a component via the product specific Dev and Runtime Helm charts that correspond to your IBM license ({PRODUCT_DM} or {PRODUCT_PAM}). The chart includes preconfigured license annotations in the global values. These are automatically propagated to all sub-chart deployments and merged with any custom pod annotations. The merge uses the Helm merge function and happens in each deployment template. The chargedProductAnnotations (containing License Manager metadata) are combined with podAnnotations (any custom annotations). The template expressions are evaluated using the `tpl` function, which replaces token references with actual values from the global configuration.

If you choose not to install via these Helm charts, the license tracking annotations must be manually added to each of the {PRODUCT_SHORT} containers after installation. To do this you can run the following commands from where the containers are installed and depending on your product and component container.

* OpenShift - {PRODUCT_DM}
+
[source,shell]
----
oc patch deployment <bamoe-canvas_deployment_name> -p \
  '{"spec": {"template":{"metadata":{"annotations":{"productID":"46b14c7f2f894218a7879b3f6416024f", "productName": "IBM Decision Manager Open Edition", "productMetric": "VIRTUAL_PROCESSOR_CORE", "productChargedContainers": "All"}}}} }'
----
  

* Kubernetes - {PRODUCT_DM}
+
[source,shell]
----
kubectl patch deployment <bamoe-canvas_deployment_name> -p \
  '{"spec": {"template":{"metadata":{"annotations":{"productID":"46b14c7f2f894218a7879b3f6416024f", "productName": "IBM Decision Manager Open Edition", "productMetric": "VIRTUAL_PROCESSOR_CORE", "productChargedContainers": "All"}}}} }'
----

* OpenShift - {PRODUCT_PAM}
+
[source,shell]
----
oc patch deployment <bamoe-canvas_deployment_name> -p \
  '{"spec": {"template":{"metadata":{"annotations":{"productID":"72984f114b54496a8a44be139154a988", "productName": "IBM Process Automation Manager Open Edition", "productMetric": "VIRTUAL_PROCESSOR_CORE", "productChargedContainers": "All"}}}} }'
----
  

* Kubernetes - {PRODUCT_PAM}
+
[source,shell]
----
kubectl patch deployment <bamoe-canvas_deployment_name> -p \
  '{"spec": {"template":{"metadata":{"annotations":{"productID":"72984f114b54496a8a44be139154a988", "productName": "IBM Process Automation Manager Open Edition", "productMetric": "VIRTUAL_PROCESSOR_CORE", "productChargedContainers": "All"}}}} }'
----

Where `bamoe-canvas_deployment_name` is the name of the Deployment resource created when you installed {CANVAS}.


* Deployment using `yaml` resources - {PRODUCT_DM}
+
[source,yaml]
----
spec:
  ...
  template:
    metadata:
      annotations:    
        productID: "46b14c7f2f894218a7879b3f6416024f"
        productName: "IBM Decision Manager Open Edition"
        productMetric: "VIRTUAL_PROCESSOR_CORE"
        productChargedContainers: "All"
----

* Deployment using `yaml` resources - {PRODUCT_PAM}
+
[source,yaml]
----
spec:
  ...
  template:
    metadata:
      annotations:    
        productID: "72984f114b54496a8a44be139154a988"
        productName: "IBM Process Automation Manager Open Edition"
        productMetric: "VIRTUAL_PROCESSOR_CORE"
        productChargedContainers: "All"
----

=== Tracking _Business Service_ license usage
Once you have created your _Business Service_ using {PRODUCT_SHORT} you must also ensure that license tracking is enabled before deployment. You can do this by updating the `src/main/resources/application.properties` file by adding the following properties for {PRODUCT_DM}:

[source,properties]
----
# OpenShift - License Service Annotations
openshift.quarkus.openshift.annotations.productID="46b14c7f2f894218a7879b3f6416024f"
openshift.quarkus.openshift.annotations.productName="IBM Decision Manager Open Edition"
openshift.quarkus.openshift.annotations.productMetric="VIRTUAL_PROCESSOR_CORE"
openshift.quarkus.openshift.annotations.productChargedContainers="All"
----

Or the following properties for {PRODUCT_PAM}, see xref:../installation/licensing.adoc[Licensing Overview]:

[source,properties]
----
# OpenShift - License Service Annotations
openshift.quarkus.openshift.annotations.productID="72984f114b54496a8a44be139154a988"
openshift.quarkus.openshift.annotations.productName="IBM Process Automation Manager Open Edition"
openshift.quarkus.openshift.annotations.productMetric="VIRTUAL_PROCESSOR_CORE"
openshift.quarkus.openshift.annotations.productChargedContainers="All"
----