= Tracking license use in Kubernetes and OpenShift
include::../partials/attributes.adoc[]
include::../styles/images.adoc[]


== Prerequisites

Follow the https://www.ibm.com/docs/en/cloud-paks/foundational-services/3.23?topic=software-installing-license-service-stand-alone[procedure] to install the License Service for stand-alone software.

NOTE: The link directs you to the instructions on installing the standalone version of IBM License Service included in the IBM Cloud Pak(TM) Foundational Services. It is important to note that the {PRODUCT_SHORT} is not part of IBM Cloud Pak(TM).

== Tracking {PRODUCT_SHORT} Licenses
To set up the license tracking for {PRODUCT_DM} components (after installing {CANVAS}) and its dependencies, run the following command from where the containers are installed:

|=== 
|Platform |Command for {PRODUCT_DM} 

|OpenShift 
|`oc patch deployment <bamoe-canvas_deployment_name> -p \
  '{"spec": {"template":{"metadata":{"annotations":{"productID":"46b14c7f2f894218a7879b3f6416024f", "productName": "IBM Decision Manager Open Edition", "productMetric": "VIRTUAL_PROCESSOR_CORE", "productChargedContainers": "All"}}}} }`
  
  |Kubernetes 
  |`kubectl patch deployment <bamoe-canvas_deployment_name> -p \
  '{"spec": {"template":{"metadata":{"annotations":{"productID":"46b14c7f2f894218a7879b3f6416024f", "productName": "IBM Decision Manager Open Edition", "productMetric": "VIRTUAL_PROCESSOR_CORE", "productChargedContainers": "All"}}}} }`
|===
  
To set up the license tracking for {PRODUCT_PAM} (after installing {CANVAS}, its dependencies, and the Management Console) run the following command from where the containers are installed:
  
|===
|Platform |Command for {PRODUCT_PAM}

|OpenShift 
|`oc patch deployment <bamoe-canvas_deployment_name> -p \
  '{"spec": {"template":{"metadata":{"annotations":{"productID":"72984f114b54496a8a44be139154a988", "productName": "IBM Process Automation Manager Open Edition", "productMetric": "VIRTUAL_PROCESSOR_CORE", "productChargedContainers": "All"}}}} }`
  
  |Kubernetes |`kubectl patch deployment <bamoe-canvas_deployment_name> -p \
  '{"spec": {"template":{"metadata":{"annotations":{"productID":"72984f114b54496a8a44be139154a988", "productName": "IBM Process Automation Manager Open Edition", "productMetric": "VIRTUAL_PROCESSOR_CORE", "productChargedContainers": "All"}}}} }`
|===
 
Where `bamoe-canvas_deployment_name` is the name of the deployment resource created when you installed {CANVAS}. The same command can be used for Management console by substituting the name of the console deployment resource. 


=== Alternative method via YAML resources
+
If you have installed {CANVAS} by using `yaml` resources, the deployment resource must be edited to add the following lines for DMOE:
+
[source,yaml]
----
spec:
  ...
  template:
    metadata:
      annotations:    
        productID: "46b14c7f2f894218a7879b3f6416024f"
        productName: "IBM Decision Manager Open Edition"
        productMetric: "VIRTUAL_PROCESSOR_CORE"
        productChargedContainers: "All"
----
And add the following lines in case of PAMOE:
+
[source,yaml]
----
spec:
  ...
  template:
    metadata:
      annotations:    
        productID: "72984f114b54496a8a44be139154a988"
        productName: "IBM Process Automation Manager Open Edition"
        productMetric: "VIRTUAL_PROCESSOR_CORE"
        productChargedContainers: "All"
----

=== Tracking _Business Service_ license usage
Once you have created your _Business Service_ using {PRODUCT_SHORT} you must also ensure that license tracking is enabled before deployment. You can do this by updating the `src/main/resources/application.properties` file by adding the following properties for {PRODUCT_DM}:

[source,properties]
----
# OpenShift - License Service Annotations
openshift.quarkus.openshift.annotations.productID="46b14c7f2f894218a7879b3f6416024f"
openshift.quarkus.openshift.annotations.productName="IBM Decision Manager Open Edition"
openshift.quarkus.openshift.annotations.productMetric="VIRTUAL_PROCESSOR_CORE"
openshift.quarkus.openshift.annotations.productChargedContainers="All"
----
Or the following properties for {PRODUCT_PAM}, see xref:installation/licensing.adoc [Licensing Overview]:

[source,properties]
----
# OpenShift - License Service Annotations
openshift.quarkus.openshift.annotations.productID="72984f114b54496a8a44be139154a988"
openshift.quarkus.openshift.annotations.productName="IBM Process Automation Manager Open Edition"
openshift.quarkus.openshift.annotations.productMetric="VIRTUAL_PROCESSOR_CORE"
openshift.quarkus.openshift.annotations.productChargedContainers="All"
----