= Licensing and tracking BAMOE usage
include::../partials/attributes.adoc[]
include::../styles/images.adoc[]

This section includes a License Guide to assist you in deploying the Program(s) you have licensed from IBM through your purchased entitlement. To do this you will need install and configure IBM License Metric Tool (ILMT) or IBM License Service if you are you are working in a Kubernetes based cloud environment. The licensing solution you deploy enables you to maintain an up-to-date inventory of software assets that are installed in your infrastructure, gather information about your hardware, and ensure license compliance of your enterprise. 

By monitoring the consumption of PVU, VPC, and RVU MAPC metrics in IBM® products with full and subcapacity licensing terms, you can understand the current license consumption as well as predict the future license consumption and optimize your license costs.


- xref:licensing.adoc[Licensing guide]
- xref:ilmt-track-bamlcns-metrictool.adoc[Tracking BAMOE License use in IBM License Metric Tool]
- xref:ilmt-track-bamlcns-kubernetes.adoc[Tracking BAMOE license use in Kubernetes]

