= Tracking license use in ILMT
include::../partials/attributes.adoc[]
include::../styles/images.adoc[]

IBM® License Metric Tool generates reports to help you maintain compliance with your Virtual Processor Core (VPC) subcapacity license terms. 
License Metric Tool (ILMT) can calculate VPC consumption only when software identification tags exist and are activated by the customer. 

See the section, https://www.ibm.com/support/pages/downloading-ibm-license-metric-tool-92[License Metric Tool with disconnected scanners to install on Linux or Windows] on the page, for guidelines on how to obtain and install ILMT.

== Using and Configuring BAMOE ILMT Libraries

License Metric Tool automatically detects the following {PRODUCT_LONG} version {VERSION} release chargeable components that are part of the product:

|=== 
|Chargeable Software Components| Library

|{PRODUCT_PAM}|ilmt-compliance-quarkus-pamoe
|{PRODUCT_DM}|ilmt-compliance-quarkus-dmoe
|===

The respective libraries use the system variable SWIDTAG_DIR to determine the directory for creating a swidtag file. If the SWIDTAG_DIR variable is set, the library uses the specified directory for swidtag file creation. 
If the SWIDTAG_DIR is not set, the library defaults to the home directory of the hosting application.

It is important to note that if the SWIDTAG_DIR environment variable contains invalid content or an invalid path, the hosting application fails to deploy.

The swidtag file is an XML file content based on ISO/IEC 19770-2:2015 specification. 
Following is an example of the swidtag file content:

[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<SoftwareIdentity name="IBM Decision Manager Open Edition" tagId="ibm.com-3d9d28f19d0f45fda113c07fb481e3ea-9.0.0" version="9.0.0" versionScheme="multipartnumeric" xml:lang="en" xmlns="http://standards.iso.org/iso/19770/-2/2015/schema.xsd" xmlns:ds="http://www.w3.org/2000/09/xmldsig#" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://standards.iso.org/iso/19770/-2/2015-current/schema.xsd schema.xsd">
    <Meta persistentId="3d9d28f19d0f45fda113c07fb481e3ea"/>
    <Meta generator="4-1-20210113"/>
    <Entity name="IBM" regid="ibm.com" role="licensor tagCreator softwareCreator"/>
</SoftwareIdentity>
----

