= Tracking license use in Kubernetes
include::../partials/attributes.adoc[]
include::../styles/images.adoc[]


== Prerequisites

Follow the https://www.ibm.com/docs/en/cloud-paks/foundational-services/3.23?topic=software-installing-license-service-stand-alone[procedure] to install the License Service for stand-alone software.

NOTE: The link directs you to the instructions on installing the standalone version of IBM License Service included in the IBM Cloud Pak(TM) Foundational Services. It is important to note that the {PRODUCT_SHORT} is not part of IBM Cloud Pak(TM).

== Tracking BAMOE License
After installing {CANVAS} and its dependencies following the installation tutorial, run the following commands depending on where {CANVAS} was installed.

* OpenShift
+
[source,shell]
----
oc patch deployment <bamoe-canvas_deployment_name> -p \
  '{"spec": {"template":{"metadata":{"annotations":{"productID":"46b14c7f2f894218a7879b3f6416024f", "productName": "IBM Decision Manager Open Edition", "productMetric": "VIRTUAL_PROCESSOR_CORE", "productChargedContainers": "All"}}}} }'
----
  

* Kubernetes
+
[source,shell]
----
kubectl patch deployment <bamoe-canvas_deployment_name> -p \
  '{"spec": {"template":{"metadata":{"annotations":{"productID":"46b14c7f2f894218a7879b3f6416024f", "productName": "IBM Decision Manager Open Edition", "productMetric": "VIRTUAL_PROCESSOR_CORE", "productChargedContainers": "All"}}}} }'
----
Where `bamoe-canvas_deployment_name` is the name of the Deployment resource created when you installed {CANVAS}.


* Alternative
+
If you have installed {CANVAS} by using `yaml` resources, the deployment resource must be edited to add the following lines:
+
[source,yaml]
----
spec:
  ...
  template:
    metadata:
      annotations:    
        productID: "46b14c7f2f894218a7879b3f6416024f"
        productName: "IBM Decision Manager Open Edition"
        productMetric: "VIRTUAL_PROCESSOR_CORE"
        productChargedContainers: "All"
----
