= Licensing Guide
include::../partials/attributes.adoc[]
include::../styles/images.adoc[]
This License Guide provides supplementary information to assist you in deploying the Program(s) you have licensed from IBM through your purchased entitlement. Your license agreement (such as the _IBM International Program License Agreement_ (IPLA) or equivalent and its transaction documents, including the License Information for {PRODUCT_LONG}) is the sole and complete agreement between you and IBM regarding use of the {PRODUCT_LONG}).

If you are not familiar with the concepts of how licensing works for IBM software, see the https://www.ibm.com/about/software-licensing/us-en/licensing/basics[Licensing Basics], https://www.ibm.com/about/software-licensing/us-en/licensing/essentials[Essential Elements], and https://www.ibm.com/about/software-licensing/us-en[Licensing & Compliance] pages.

This licensing guide covers the following topics.

* Licensing Overview
** Licensing for Disaster Recovery or Backup
** Supporting Program: IBM Robotic Process Automation
* License Metrics
* License Reporting
* Accessing the software
* Advanced Features

== Licensing Overview

{PRODUCT_LONG} is available to clients who have entitlement through purchasing part numbers from IBM directly, or through IBM business partners.

IBM offers {PRODUCT_LONG} license subscriptionsfootnote:[For additional information on the IBM Software Subscription and Support License refer to the https://www.ibm.com/software/passportadvantage/licensing.html[Passport Advantage Licensing Overview]].

Different part numbers are available for purchase depending on your usage pattern and the capabilities of {PRODUCT_LONG} that are required. You can choose from the following products:

- https://www.ibm.com/products/business-automation-manager-open-editions/decision-manager[{PRODUCT_DM}], which enables you to develop _Business Services_ that use rules, decisions, test scenarios and workflow for straight through processing to orchestrate execution. 
- https://www.ibm.com/products/business-automation-manager-open-editions/process-automation-manager[{PRODUCT_PAM}], which enables you to develop _Business Services_ that use rules, decisions, test scenarios and stateful workflow in addition to straight through processing. 

More information on the capabilities and components of {PRODUCT_LONG} can be found in the xref:#advanced_features[Advanced features].

[NOTE]
====
The different product components are available for evaluation on a single-user workstation in a development environment, through the https://ibm.biz/bamoe-developer-program[IBM Developer Program for Open Editions].

If you decide to go further in deploying solutions, proper entitlements are required as described by the license terms. 
====

For both products, {PRODUCT_DM} and {PRODUCT_PAM}, clients can expect the following:

* The different parts reflect different levels of entitlement for product capabilities. 
** {PRODUCT_DM} includes the subset of {PRODUCT_SHORT} functionality to be able to develop and orchestrate decision and rule based _Business Services_.
** {PRODUCT_PAM} includes all functionality available in {PRODUCT_DM} and additional functionality to be able to develop stateful workflow _Business Services_. For example, Management console is only available in this product. 
* Subscription includes entitlements to run the purchased capabilities in containers or virtual machines.
* This solution is currently not available as a Software as a Service (SaaS) offering.
* While active, the subscription entitles clients to use and receive support for the commercially available releases.
* While maintaining at least one active subscription, each and every active instance or installation of the software requires active subscriptions.
* _Business Services_ built using {PRODUCT_SHORT} must include the license tracking annotations.  

=== Licensing for Disaster Recovery or Backup

When considering backup installations, active licenses are required for backup copies that are running simultaneously with the primary installation. Inactive or idling backup copies typically do not need extra licenses. In-depth information can be found in the https://www.ibm.com/about/software-licensing/assets/guides_pdf/Backup.pdf[Backup and Disaster Recovery Licensing Guide].


You can find the latest LI information for the available products, parts, and software versions in the https://www.ibm.com/about/software-licensing/us-en/product_search?search=5900-AR4&type=pid&platform=[License Information (LI) for {PRODUCT_LONG}].

=== Supporting Program: IBM Robotic Process Automation

Subscriptions for {PRODUCT_LONG} include access to https://www.ibm.com/br-pt/products/robotic-process-automation[IBM Robotic Process Automation] as a Supporting program.

Through the Supporting program IBM grants limited access to (IBM Robotic Process Automation) at no additional charge on the condition that the program is only used in conjunction with (and only to the extent necessary to support) the components of {PRODUCT_LONG}.

==== Included components
The following IBM Robotic Process Automation components are included in the supporting program:

- Unattended Bot Agent
- IBM Robotic Process Automation Environment
- IBM Robotic Process Automation Studio

==== Limitations

Regardless of the number of entitlements obtained to {PRODUCT_LONG}, the entitlement to IBM Robotic Process Automation components is limited to:

- *IBM Robotic Process Automation Environment*: 1 Virtual Server
- *IBM Robotic Process Automation Unattended Bot Agent*: 1 Concurrent Connection

Usage of IBM Robotic Process Automation is only permitted in traditional installations and does not inlcude container-based installations.

You will require separate entitlement to IBM Robotic Process Automation if you need additional entitlements. 

== License Metrics

{PRODUCT_LONG} offerings are licensed on a capacity basis. Clients purchase entitlements for the number of Virtual Processor Cores (VPCs) that will be used by the components in ({PRODUCT_DM} and/or {PRODUCT_PAM}).

Virtual processor core (VPC) is a unit of measurement that is used to determine the licensing cost of IBM products. When you license a virtual machine (VM), VPC is based on the number of virtual cores that are assigned to the VM. One VPC license is required for every core that is available to the IBM program.

In short, {PRODUCT_LONG} deployments are licensed by *Virtual Processor Core (VPC)*, where generally, 1 VPC = 1 physical core or 1 virtual core.

Regarding the usage of the product in association with the entitled number of VPCs:

** Active subscriptions allow product deployments into as many environments as clients choose, as long as they do not exceed the total number of VPCs they have purchased.
** The number of entitlements must cover the highest expected usage of VPCs during peak periods.
** Clients are responsible for ensuring they do not exceed their deployment entitlement.

Additional information, can be found at https://www.ibm.com/software/passportadvantage/about_software_licensing.html[IBM Licensing Metrics].

== License Reporting

The IBM License Metric Tool (ILMT) tracks which software programs are installed on particular physical hardware. ILMT provides reports that can be presented to IBM when compliance around entitlement capacity is requested. The tool can also be used to track installations in VMs entitled under VPCs.

When installing {PRODUCT_LONG} in *containers*:

* The container size specifies the CPU-limit of the container. This is reported as the deployment size of the container instance for {PRODUCT_LONG}. If no CPU-limit is set for the container, then the reported size of the container is set to be the size of the worker node where the container instance is deployed.
* Container deployments of the product components must use IBM License Service to report on their deployment for licensing usage.The IBM License Service needs to be deployed on Kubernetes. For more information see xref:ilmt-track-bamlcns-kubernetes.adoc[Tracking BAMOE License use Kubernetes]

When installing {PRODUCT_LONG} in *Virtual Machines (VMs)*:

* the size of the Virtual Machine will determine the size that needs to be entitled. Licensing is unaffected if multiple other products are deployed in the same Virtual Machine.
* Deployments in Virtual Machines need to use IBM License Management Tool (ILMT) or other approved tools for tracking deployments in sub-capacity environments.
* For additional information on how ILMT tracks deployments of VPC metrics in Virtual Machines, refer to the https://www.ibm.com/docs/en/license-metric-tool?topic=metrics-virtual-processor-core-vpc[Documentation for License Metric Tool - Virtual processor core (VPC)].


IBM clients are responsible for:

* Deploying and configuring {PRODUCT_LONG} in line with their license entitlement.
* Ensuring container deployments of {PRODUCT_SHORT} and _Business Services_ built with {PRODUCT_SHORT} are reporting correctly to IBM License Service.
* Ensuring that if installing into virtual machines, that ILMT or other tools are correctly configured to track installations.

== Accessing the software

There are no activation keys for using {PRODUCT_LONG}.

To access the product purchased, clients should log in to IBM Passport Advantage and download the product install images they want to use.

{PRODUCT_LONG} offers downloadable resources for installing on-premise and certified container images for deployment into supported Kubernetes environments.

Available supporting programs are also available for download from Passport Advantage.

[#advanced_features]
== Advanced features
Certain advanced features of {PRODUCT_SHORT} developed by IBM, are not part of the Open Source repository. The following table describes them:

[%header,cols=3]
[%autowidth]
|===
|Component |Description |Offering

|{CANVAS}
|A standalone web application that provides authoring and testing tools for Decisions and Processes, directly in the browser. Business Analysts will find this particularly helpful. IBM recommends developers use the BAMOE Developer Tools for VS Code which provides the same features in addition to enterprise developer features.
|{PRODUCT_DM}, {PRODUCT_PAM}

|{DEV_TOOLS}
|An integration with Microsoft VS Code editor bringing tools to create, edit, test, and visualize business processes (BPMN), decisions (DMN) and test scenarios (SceSim). These tools, combined with existing Java extensions, allows for a fully integrated workspace for Business Service developers allowing developers to work within a consistent environment.
|{PRODUCT_DM}, {PRODUCT_PAM}

|{PRODUCT_SHORT} Accelerators
|Feature used to quickly setup a functional project starting with a business process or a decision file then add the necessary files and locations to build and deploy a Business Service. Each new project will contain instructions in a README file, an Apache Maven `pom.xml` file referencing project dependencies, and build the expected file structure for the Business Service.
|{PRODUCT_DM}, {PRODUCT_PAM}

|{MVN_REPO}
|An image or a zip file which contains all of the third-party libraries referenced by core BAMOE components. It can be installed in an artifact repository or locally ensuring proper component versions and references are maintained with supported versions.
|{PRODUCT_DM}, {PRODUCT_PAM}

|{MANAGEMENT_CONSOLE}
|A Web application that provides a view into a running process. You can view which step a process is in, while it is running, trigger new processes, and interact with user/human tasks via forms. 
|{PRODUCT_PAM}

|{QUARKUS_DEV_UI}
|Tools and views into a Business Service, that can be used during development, to interact and view _Business Services_. These tools run locally and are accessible in your browser. The {QUARKUS_DEV_UI} is built upon the existing Quarkus DevUI.
|{PRODUCT_DM}, {PRODUCT_PAM}

|{SPRING_WEB_CONSOLE}
|Tools and views into a _Business Service_, that can be used during development, to interact and view _Business Services_. These tools run locally and are accessible in your browser. The {SPRING_WEB_CONSOLE} is built via Spring Boot and existing assets from the {QUARKUS_DEV_UI}.
|{PRODUCT_DM}, {PRODUCT_PAM}

|{PRODUCT_SHORT} Spring Boot IdP Discovery Library
|A Spring Boot library for OIDC provider discovery. Matches the capability that exists with Quarkus OIDC for Identity Provider discovery.
|{PRODUCT_DM}, {PRODUCT_PAM}

|{PRODUCT_SHORT} Database mapping libraries for Oracle and MS SQL Server
|Different databases use different reserved words. These mapping libraries adapt the base SQL queries and connections to their respective databases avoiding conflicts with reserved words.
|{PRODUCT_PAM}

|AI Integrations {PRODUCT_SHORT} Gen AI task
|A new BPMN workflow task which allows for easy invocation of an LLM. It provides input for the provider, model, temperature, token limit and prompt. When executed, the task will use the configured information to query the LLM and return the provided response.
|{PRODUCT_PAM}


|AI Integrations {PRODUCT_SHORT} MCP Server (technology preview)
|A Quarkus-based service that exposes BAMOE decision and rule models to external AI agents via the MCP protocol. Allows DMN, DRL, and BPMN decisions and workflows to be exposed as “Tools” to support an Agentic AI landscape. Builds upon Quarkus’s MCP server extension, more information available at https://docs.quarkiverse.io/quarkus-mcp-server/dev/
|{PRODUCT_DM}, {PRODUCT_PAM}

|===

More information on the capabilities and components of {PRODUCT_LONG} can be found in the xref:../overview/overview.adoc[Overview].


