= Managing your license entitlements
include::../partials/attributes.adoc[]
include::../styles/images.adoc[]

This section includes information on managing your {PRODUCT_SHORT} licenses for containerized and non-containerized deployments of {PRODUCT_SHORT} components and _Business Services_.

== Using IBM License Service (ILS) for {PRODUCT_SHORT} component containers
Follow the https://www.ibm.com/docs/en/cloud-paks/foundational-services/4.x_cd?topic=license-service[procedure to install IBM License Service] for stand-alone software.

NOTE: The link directs you to the instructions on installing the standalone version of IBM License Service included in the IBM Cloud Pak(TM) Foundational Services. It is important to note that the {PRODUCT_SHORT} is not part of IBM Cloud Pak(TM).

When you install a component via the product specific Dev and Runtime Helm charts that correspond to your IBM license ({PRODUCT_DM} or {PRODUCT_PAM}), preconfigured license annotations are included in the global values. These annotations are automatically propagated to all sub-chart deployments and merged with any custom pod annotations. The merge uses the Helm merge function and happens in each deployment template. The `chargedProductAnnotations` (containing License Manager metadata) are combined with `podAnnotations` (any custom annotations). The template expressions are evaluated using the `tpl` function, which replaces token references with actual values from the global configuration.

If you choose not to install via these Helm charts, the license tracking annotations must be manually added to each of the {PRODUCT_SHORT} containers after installation. To do this you can run the following commands from where the containers are installed and depending on your product and component container.

* OpenShift - {PRODUCT_DM}
+
[source,shell]
----
oc patch deployment <bamoe-canvas_deployment_name> -p \
  '{"spec": {"template":{"metadata":{"annotations":{"productID":"46b14c7f2f894218a7879b3f6416024f", "productName": "IBM Decision Manager Open Edition", "productMetric": "VIRTUAL_PROCESSOR_CORE", "productChargedContainers": "All"}}}} }'
----
  

* Kubernetes - {PRODUCT_DM}
+
[source,shell]
----
kubectl patch deployment <bamoe-canvas_deployment_name> -p \
  '{"spec": {"template":{"metadata":{"annotations":{"productID":"46b14c7f2f894218a7879b3f6416024f", "productName": "IBM Decision Manager Open Edition", "productMetric": "VIRTUAL_PROCESSOR_CORE", "productChargedContainers": "All"}}}} }'
----

* OpenShift - {PRODUCT_PAM}
+
[source,shell]
----
oc patch deployment <bamoe-canvas_deployment_name> -p \
  '{"spec": {"template":{"metadata":{"annotations":{"productID":"72984f114b54496a8a44be139154a988", "productName": "IBM Process Automation Manager Open Edition", "productMetric": "VIRTUAL_PROCESSOR_CORE", "productChargedContainers": "All"}}}} }'
----
  

* Kubernetes - {PRODUCT_PAM}
+
[source,shell]
----
kubectl patch deployment <bamoe-canvas_deployment_name> -p \
  '{"spec": {"template":{"metadata":{"annotations":{"productID":"72984f114b54496a8a44be139154a988", "productName": "IBM Process Automation Manager Open Edition", "productMetric": "VIRTUAL_PROCESSOR_CORE", "productChargedContainers": "All"}}}} }'
----

Where `bamoe-canvas_deployment_name` is the name of the Deployment resource created when you installed {CANVAS}.


* Deployment using `yaml` resources - {PRODUCT_DM}
+
[source,yaml]
----
spec:
  ...
  template:
    metadata:
      annotations:    
        productID: "46b14c7f2f894218a7879b3f6416024f"
        productName: "IBM Decision Manager Open Edition"
        productMetric: "VIRTUAL_PROCESSOR_CORE"
        productChargedContainers: "All"
----

* Deployment using `yaml` resources - {PRODUCT_PAM}
+
[source,yaml]
----
spec:
  ...
  template:
    metadata:
      annotations:    
        productID: "72984f114b54496a8a44be139154a988"
        productName: "IBM Process Automation Manager Open Edition"
        productMetric: "VIRTUAL_PROCESSOR_CORE"
        productChargedContainers: "All"
----


== Using IBM License Metric Tool (ILMT) for non-containerized Business Services deployments
IBM® License Metric Tool generates reports to help you maintain compliance with your Virtual Processor Core (VPC) license terms. ILMT can calculate VPC consumption only when software identification tags exist and are activated by the customer. 

See the section, https://www.ibm.com/support/pages/downloading-ibm-license-metric-tool-92[License Metric Tool with disconnected scanners to install on Linux or Windows] on the page, for guidelines on how to obtain and install ILMT.

If you are developing traditional Java applications, non-containerized Quarkus or Spring Boot applications or using embedded mode, the following libraries must be included in your application:

|=== 
|Chargeable Software Components| Libraries

|{PRODUCT_DM}
|`com.ibm.bamoe:ilmt-compliance-quarkus-dmoe` (Quarkus) _or_
 `com.ibm.bamoe:ilmt-compliance-spring-boot-dmoe` (Spring Boot) _or_
 `com.ibm.bamoe:ilmt-compliance-java-dmoe` (Java)

|{PRODUCT_PAM} 
|`com.ibm.bamoe:ilmt-compliance-quarkus-pamoe` (Quarkus) _or_
 `com.ibm.bamoe:ilmt-compliance-spring-boot-pamoe` (Spring Boot) _or_
 `com.ibm.bamoe:ilmt-compliance-java-pamoe` (Java)
|===

If you developed your _Business Service_ using the project Accelerators the required libraries are automatically included in your application (see xref:../getting-started/project-setup.adoc#gs-accelerators[Getting Started → Introducing Accelerators])

License Metric Tool automatically detects the following {PRODUCT_LONG} version {VERSION} release chargeable components that are part of the product:

The respective libraries use the system variable SWIDTAG_DIR to determine the directory for creating a swidtag file. If the SWIDTAG_DIR variable is set, the library uses the specified directory for swidtag file creation. 
If the SWIDTAG_DIR is not set, the library defaults to the home directory of the hosting application.

It is important to note that if the SWIDTAG_DIR environment variable contains invalid content or an invalid path, the hosting application fails to deploy.

The swidtag file is an XML file content based on ISO/IEC 19770-2:2015 specification. 
Following is an example of the swidtag file content:

[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<SoftwareIdentity name="IBM Decision Manager Open Edition" tagId="ibm.com-3d9d28f19d0f45fda113c07fb481e3ea-9.0.0" version="9.0.0" versionScheme="multipartnumeric" xml:lang="en" xmlns="http://standards.iso.org/iso/19770/-2/2015/schema.xsd" xmlns:ds="http://www.w3.org/2000/09/xmldsig#" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://standards.iso.org/iso/19770/-2/2015-current/schema.xsd schema.xsd">
    <Meta persistentId="3d9d28f19d0f45fda113c07fb481e3ea"/>
    <Meta generator="4-1-20210113"/>
    <Entity name="IBM" regid="ibm.com" role="licensor tagCreator softwareCreator"/>
</SoftwareIdentity>
----



== Using IBM License Service (ILS) for containerized Business Services deployments
You can define license tracking annotations in your version-controlled deployment YAML file under `spec.template.metadata.annotations`:

For {PRODUCT_DM}:

[source,yaml]
----
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-business-service
spec:
  template:
    metadata:
      annotations:
        productName: "IBM Decision Manager Open Edition"
        productID: "46b14c7f2f894218a7879b3f6416024f"
        productVersion: "9.5.0"
        productMetric: "VIRTUAL_PROCESSOR_CORE"
----


Or the following properties for {PRODUCT_PAM}:

[source,yaml]
----
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-business-service
spec:
  template:
    metadata:
      annotations:
        productName: "IBM Process Automation Manager Open Edition"
        productID: "72984f114b54496a8a44be139154a988"
        productVersion: "9.5.0"
        productMetric: "VIRTUAL_PROCESSOR_CORE"
----
