= Runtime Environment
include::../partials/attributes.adoc[]
include::../styles/images.adoc[]

This section describes how to install the components required to host and manage deployed Business Services in the runtime environment:

{MANAGEMENT_CONSOLE}:: for monitoring and administration,
{MCP_SERVER}:: to enable AI agents to connect to Business Services.

[#runtime-env-helm]
== The Runtime environment Helm chart
The recommended way of installing {MANAGEMENT_CONSOLE} and {MCP_SERVER} is to install the pre-configured Helm charts for the {PRODUCT_SHORT} offering that you have purchases licenses for, {PRODUCT_DM} or {PRODUCT_PAM}:

* pamoe-{VERSION}-runtime-environment-helm-chart
* dmoe-{VERSION}-runtime-environment-helm-chart

These Helm charts include the necessary licensing annotations and do not require any manual configuration, as was the case in previous releases. Required annotations are injected into all deployed containers, ensuring accurate license tracking from deployment, and simplifying the installation process. The charts are pre-configured with the correct product IDs, product names, and metrics for each {PRODUCT_SHORT} offering.

The charts integrate Management Console configuration via Helm parameters, enabling centralized configuration in a single `values.yaml`, version-controlled settings, and automatic conversion to environment variables during deployment, eliminating manual configuration, see xref:#helm-chart-configuration [Configuration reference for Runtime Helm Charts]

Each Dev Helm chart contains two sub-charts:

* management_console: {MANAGEMENT_CONSOLE} application for monitoring and managing process instances, available via https://quay.io/repository/bamoe/management-console[quay.io/bamoe/management-console@{IMAGE_VERSION}]
* mcp_server: {MCP_SERVER} contains the Model Context Protocol server enabling AI agents to invoke _Business Services_, available via https://quay.io/repository/bamoe/mcp-server[quay.io/bamoe/mcp-server:{IMAGE_VERSION}]

The only difference between the PAMOE and DMOE Dev environment Helm chart is the License Service annotations which contain different `productID` and `productName`. All sub-charts receive License Service annotations automatically through the global configuration of the parent chart. The annotations are applied to every pod deployment,
ensuring complete license tracking coverage for all {PRODUCT_SHORT} containers.

The {PRODUCT_SHORT} Runtime Helm charts are architecture-agnostic and work for both:

* Linux/s390x architecture which runs on the IBM Z platform
* Linux/x86_64 architecture

All {PRODUCT_SHORT} container images are available as multi-architecture images on Quay.io, and the host machine architecture is automatically resolved when you pull the container images. You can use the following command to specify a platform if required:

[source,shell]
----
`docker pull --platform linux/s390x quay.io/bamoe/management-console:{IMAGE_VERSION}`
----

If you prefer to install the Runtime environment components individually using OpenShift CLI and Docker this can be done using the same container images. 

For more information on the product distribution see xref:../release-notes/whats-new-9-4-0.adoc#download-doc[What's New → Download Documentation]. 


== Installing the Runtime Environment Helm chart (recommended)
The Helm chart provides a simple way to deploy {MANAGEMENT_CONSOLE} and {MCP_SERVER} in Kubernetes, OpenShift, and Minikube with pre-configured licensing depending on your licensed product (see xref:licensing.adoc[License Guide]). For more information on using the Helm tool, see https://helm.sh/docs[Helm Docs].

Choose the required helm chart based on your licensed product:

* pamoe-{VERSION}-runtime-environment-helm-chart
* dmoe-{VERSION}-runtime-environment-helm-chart


===  OpenShift Install

To install on OpenShift, first get the default OpenShift domain for your routes using the following command:

[source,shell,subs="attributes+"]
----
oc get ingresses.config cluster --output jsonpath={.spec.domain}
----

////
If you do not have access rights to this configuration, try creating a dummy route resource and checking its domain.

Then, install the Helm chart by using the following commands:

[source,shell,subs="attributes+"]
----
helm pull oci://quay.io/bamoe/consoles-helm-chart --version={IMAGE_VERSION} --untar
helm install bamoe-management-console ./consoles-helm-chart \
 --values ./consoles-helm-chart/values-openshift.yaml \
  --set global.openshiftRouteDomain="<YOUR_OCP_ROUTE_DOMAIN>"
----

////

You can then install the Helm chart with the following commands:

[source,shell,subs="attributes+"]
----
helm pull oci://quay.io/bamoe/dmoe-runtime-environment-helm-chart --version={IMAGE_VERSION} --untar
helm install my-bamoe-runtime-environment ./dmoe-runtime-environment-helm-chart --values ./dmoe-runtime-environment-helm-chart/values-openshift.yaml --set global.openshiftRouteDomain="<YOUR_OCP_ROUTE_DOMAIN>"
----

Replace `dmoe-runtime-environment-helm-chart` with `pamoe-runtime-environment-helm-chart` when using {PRODUCT_PAM}, and replace `<YOUR_OCP_ROUTE_DOMAIN>`` with your OpenShift Route domain.
You can customize the installation name by replacing `my-bamoe-runtime-environment` with your preferred name.

=== Generic Kubernetes install

To install {MANAGEMENT_CONSOLE} directly on a Kubernetes cluster, you will need to get the default Kubernetes cluster domain for your Ingress (see https://kubernetes.io/docs/concepts/services-networking/ingress/[Kubernetes Documentation] for more information). This can vary depending on your cluster configuration.

Once you have the domain information, you can run the following helm commands:

[source,shell,subs="attributes+"]
----
helm pull oci://quay.io/bamoe/dmoe-runtime-environment-helm-chart --version={IMAGE_VERSION} --untar
helm install my-bamoe-runtime-environment ./dmoe-runtime-environment-helm-chart --values ./dmoe-runtime-environment-helm-chart/values-kubernetes.yaml --set global.kubernetesClusterDomain="<YOUR_KUBERNETES_CLUSTER_DOMAIN>" --set global.kubernetesIngressClass="<YOUR_KUBERNETES_INGRESS_CLASS>"
----

Where you replace `dmoe-runtime-environment-helm-chart` with `pamoe-runtime-environment-helm-chart` if you are working with {PRODUCT_PAM}, `<YOUR_KUBERNETES_CLUSTER_DOMAIN>` with the domain of your cluster and `<YOUR_KUBERNETES_INGRESS_CLASS>` with the ingress class of your cluster.
You can customize the installation name by replacing `my-bamoe-runtime-environment` with your preferred name.

=== Minikube install

To install {MANAGEMENT_CONSOLE} Helm chart on a Minikube cluster, you will need:

- https://minikube.sigs.k8s.io/docs/start/[A local Minikube cluster up and runnning]
- https://v1-32.docs.kubernetes.io/docs/tasks/access-application-cluster/ingress-minikube/[The Nginx Ingress installed]

Once you have the domain information, you can run the following helm commands to do a Minikube specific install:

[source,shell,subs="attributes+"]
----
helm pull oci://quay.io/bamoe/dmoe-runtime-environment-helm-chart --version={IMAGE_VERSION} --untar
helm install my-bamoe-runtime-environment ./dmoe-runtime-environment-helm-chart --values ./dmoe-runtime-environment-helm-chart/values-minikube-nginx.yaml
----

Where dmoe-runtime-environment-helm-chart is replaced by pamoe-runtime-environment-helm-chart if you are working with {PRODUCT_PAM}.

=== Uninstalling the chart

To uninstall the `bamoe-management-console` deployment:

[source,shell,subs="attributes+"]
----
helm uninstall bamoe-management-console
----

=== MCP Server
The {MCP_SERVER} is deployed and configured by default during the Runtime environment installation. 

You can disable the installation of the MCP Server in the Helm chart deployment using this command:

[source,shell,subs="attributes+"]
----
helm install my-bamoe-runtime-environment ./dmoe-runtime-environment-helm-chart --set mcp.server.enabled=false
----

To run the {MCP_SERVER}, complete the setup and launch the server image in a Docker environment using the following command:

[source,shell, subs="attributes+"]
----
docker run -it --rm \
  -p 8084:8080 \
  --name mcp-server \
  -e MCP_SERVER_OPENAPI_URLS=<your_business_services_OpenAPIv3_path> \
  quay.io/bamoe/mcp-server:{IMAGE_VERSION}
----

=== Passing Environment variables

This chart uses default environmental variables from `values.yaml` file. You can override the variables by passing them through the command line. See xref:#helm-chart-configuration[Runtime Helm Chart configuration reference] for all options.
 
[source,shell]
----
helm install my-bamoe-runtime-environment ./dmoe-runtime-environment-helm-chart --set management_console.image.registry=quay.io
----

Where dmoe-runtime-environment-helm-chart is replaced by pamoe-runtime-environment-helm-chart if you are working with {PRODUCT_PAM}.

////

For all Helm chart installations mentioned, different settings can be applied by editing the `values.yaml` file or passing the `--set` flag as in the example:
[source,shell,subs="attributes+"]

----
helm install bamoe-management-console ./consoles-helm-chart --set <my.configuration>="<value>"
----

Following is the list of all available configurations for the Helm chart.

////

== Deploy directly on OpenShift (using `oc` CLI)

If you have an OpenShift cluster and are authenticated through the `oc` CLI tool, follow these steps to deploy the {MANAGEMENT_CONSOLE}. Note that you will need to add licensing annotations manually if you follow this procedure rather than using the Dev Helm chart.

NOTE: Labeling the resources is optional, but it will make organizing and identifying your deployed resources significantly easier.

. Create the Deployment
+
[source,shell,subs="attributes+"]
----
oc new-app quay.io/bamoe/management-console:{IMAGE_VERSION} --name=bamoe-management-console-app
----
+
. Expose the Service
+
 This will create an OpenShift *Route* so the {MANAGEMENT_CONSOLE} can be accessed externally.
[source,shell,subs="attributes+"]
----
oc create route edge --service=bamoe-management-console-app
----
+
. Optionally add labels to easily identify the resources.
+
[source,shell,subs="attributes+"]
----
oc label services/bamoe-management-console-app app.kubernetes.io/part-of=bamoe-management-console-app
oc label routes/bamoe-management-console-app app.kubernetes.io/part-of=bamoe-management-console-app
oc label deployments/bamoe-management-console-app app.kubernetes.io/part-of=bamoe-management-console-app
oc label deployments/bamoe-management-console-app app.openshift.io/runtime=js
----
+
. Configure Environment Variables
+
 You can configure the {MANAGEMENT_CONSOLE} by using the environment variables in the Deployment:
[source,shell,subs="attributes+"]
----
oc set env deployment/bamoe-management-console-app <ENV_VAR>="<VALUE>"
----
NOTE: For a list of environment variables, check the <<available-environment-variables>> section.

// [#air-gapped]
// == Deploy in an air-gapped OpenShift environment
//
// If you have an air-gapped OpenShift cluster and need to deploy {MANAGEMENT_CONSOLE} and {MCP_SERVER} using images from the internal registry, follow these steps. This procedure involves pulling images from Quay.io, pushing them to the OpenShift internal registry, and deploying the applications.
//
//
// . Log in to the OpenShift cluster using the OpenShift CLI.
// +
// [source,shell]
// ----
// oc login <OPENSHIFT_API_URL>
// ----
// +
// . Select or create the target Namespace where the runtime environment components will be deployed.
// +
// [source,shell]
// ----
// oc project bamoe-runtime
// ----
// +
// . Retrieve the OpenShift internal image registry route.
// +
// [source,shell]
// ----
// oc get route default-route -n openshift-image-registry --template='{{ .spec.host }}'
// ----
// +
// If the default route is not enabled, enable it using the following command.
// +
// [source,shell]
// ----
// oc patch configs.imageregistry.operator.openshift.io/cluster --type=merge -p '{"spec":{"defaultRoute":true}}'
// ----
// +
// . Set environment variables for the registry and namespace.
// +
// [source,shell]
// ----
// REGISTRY=$(oc get route default-route -n openshift-image-registry --template='{{ .spec.host }}')
// NAMESPACE=$(oc project -q)
// ----
// +
// . Log in to the OpenShift image registry.
// +
// [source,shell]
// ----
// docker login -u kubeadmin -p $(oc whoami --show-token) $REGISTRY --tls-verify=false
// ----
// +
// . Pull the runtime environment images from the Quay repository.
// +
// [source,shell,subs="attributes+"]
// ----
// docker pull --arch amd64 quay.io/bamoe/management-console:{IMAGE_VERSION}
// docker pull --arch amd64 quay.io/bamoe/mcp-server:{IMAGE_VERSION}
// ----
// +
// . Tag the images for the OpenShift internal registry.
// +
// [source,shell,subs="attributes+"]
// ----
// docker tag quay.io/bamoe/management-console:{IMAGE_VERSION} $REGISTRY/$NAMESPACE/management-console:{IMAGE_VERSION}
// docker tag quay.io/bamoe/mcp-server:{IMAGE_VERSION} $REGISTRY/$NAMESPACE/mcp-server:{IMAGE_VERSION}
// ----
// +
// . Push the images to the OpenShift internal registry.
// +
// [source,shell,subs="attributes+"]
// ----
// docker push $REGISTRY/$NAMESPACE/management-console:{IMAGE_VERSION} --tls-verify=false
// docker push $REGISTRY/$NAMESPACE/mcp-server:{IMAGE_VERSION} --tls-verify=false
// ----
// +
// . Verify that the images are available in the internal registry.
// +
// [source,shell]
// ----
// oc get imagestreams
// ----
// +
// .Example output
// [source,shell,subs="attributes+"]
// ----
// NAME                   IMAGE REPOSITORY                                                                                             TAGS             UPDATED
// management-console     default-route-openshift-image-registry.apps.example.com/bamoe-runtime/management-console                     {IMAGE_VERSION}   2 minutes ago
// mcp-server             default-route-openshift-image-registry.apps.example.com/bamoe-runtime/mcp-server                             {IMAGE_VERSION}   21 seconds ago
// ----
// +
// . Define environment variables for naming and labeling the resources.
// +
// [source,shell]
// ----
// export APP_PART_OF=bamoe-runtime-environment
// export APP_NAME_MANAGEMENT_CONSOLE=bamoe-management-console
// export APP_NAME_MCP_SERVER=bamoe-mcp-server
// ----
// +
// . Deploy the {MANAGEMENT_CONSOLE} and label its resources.
// +
// [source,shell,subs="attributes+"]
// ----
// oc new-app image-registry.openshift-image-registry.svc:5000/$NAMESPACE/management-console:{IMAGE_VERSION} --name=$APP_NAME_MANAGEMENT_CONSOLE
//
// oc create route edge --service=$APP_NAME_MANAGEMENT_CONSOLE
// oc label services/$APP_NAME_MANAGEMENT_CONSOLE app.kubernetes.io/part-of=$APP_PART_OF
// oc label routes/$APP_NAME_MANAGEMENT_CONSOLE app.kubernetes.io/part-of=$APP_PART_OF
// oc label deployments/$APP_NAME_MANAGEMENT_CONSOLE app.kubernetes.io/part-of=$APP_PART_OF
// oc label deployments/$APP_NAME_MANAGEMENT_CONSOLE app.openshift.io/runtime=nodejs
// ----
// +
// . Deploy the {MCP_SERVER} and label its resources.
// +
// [source,shell,subs="attributes+"]
// ----
// oc new-app image-registry.openshift-image-registry.svc:5000/$NAMESPACE/mcp-server:{IMAGE_VERSION} --name=$APP_NAME_MCP_SERVER
//
// oc create route edge --service=$APP_NAME_MCP_SERVER
// oc label services/$APP_NAME_MCP_SERVER app.kubernetes.io/part-of=$APP_PART_OF
// oc label routes/$APP_NAME_MCP_SERVER app.kubernetes.io/part-of=$APP_PART_OF
// oc label deployments/$APP_NAME_MCP_SERVER app.kubernetes.io/part-of=$APP_PART_OF
// oc label deployments/$APP_NAME_MCP_SERVER app.openshift.io/runtime=nodejs
// ----
// +
// . Retrieve the route details to access the deployed applications.
// +
// [source,shell]
// ----
// oc get route
// ----
// +
// .Example output
// [source,shell]
// ----
// NAME                       HOST/PORT                                                                PATH   SERVICES                   PORT        TERMINATION   WILDCARD
// bamoe-management-console   bamoe-management-console-bamoe-runtime.apps.example.com                         bamoe-management-console   8080-tcp    edge          None
// bamoe-mcp-server           bamoe-mcp-server-bamoe-runtime.apps.example.com                                 bamoe-mcp-server           8080-tcp    edge          None
// ----
//
// The {MANAGEMENT_CONSOLE} is now accessible at the route URL shown in the output (for example, `\https://bamoe-management-console-bamoe-runtime.apps.example.com`), and the {MCP_SERVER} is accessible at its respective route URL (for example, `\https://bamoe-mcp-server-bamoe-runtime.apps.example.com`).

== Running locally with Docker
Note that you will need to add licensing annotations manually if you follow this procedure rather than using the Dev Helm chart.

Start the container with:

[source,shell,subs="attributes+"]
----
docker run -p <EXTERNAL_PORT>:8080 quay.io/bamoe/management-console:{IMAGE_VERSION}
----


If necessary, pass the environment variables with the `-e` flag:

[source,shell,subs="attributes+"]
----
docker run -p <EXTERNAL_PORT>:8080 -e <ENV_VAR>="<VALUE>" quay.io/bamoe/management-console:{IMAGE_VERSION}
----

The {MANAGEMENT_CONSOLE} will be running at http://localhost:<EXTERNAL_PORT>


[#available-environment-variables]
== Available Environment Variables

[cols="3,6,3",options="header"]
|===
| Name | Description | Default

| `RUNTIME_TOOLS_MANAGEMENT_CONSOLE_APP_NAME` | Management Console app name. | BAMOE Management Console
| `RUNTIME_TOOLS_MANAGEMENT_CONSOLE_OIDC_CLIENT_CLIENT_ID` | OpenID Connect client ID for connecting to Identity Providers. | bamoe-management-console
| `RUNTIME_TOOLS_MANAGEMENT_CONSOLE_OIDC_CLIENT_DEFAULT_SCOPES` | OpenID Connect default scopes. | openid email profile
| `RUNTIME_TOOLS_MANAGEMENT_CONSOLE_OIDC_CLIENT_DEFAULT_AUDIENCE` | OpenID Connect default audience. | _Empty_
| `RUNTIME_TOOLS_MANAGEMENT_CONSOLE_MANAGED_BUSINESS_SERVICES` | List of Business Services automatically connected to the {MANAGEMENT_CONSOLE}. | _Empty_
| `RUNTIME_TOOLS_MANAGEMENT_CONSOLE_BASE_PATH` | Base path used for all routes. | _Empty_
| `RUNTIME_TOOLS_MANAGEMENT_CONSOLE_USE_APACHE_HTTPD_BASE_PATH_ALIAS` | Set to `"true"` if Apache HTTPD should serve files under an alias prefixed by the base path. | _Empty_
|===

[#helm-chart-configuration]
== Configuration reference for Runtime Helm Charts

The following table lists the configurable parameters of the {PRODUCT_SHORT} Runtime Environment chart and their default values.

=== Global Configuration

|===

| Key | Type | Default | Description

| global.ingressSource 
| string 
| "" 
| Which ingress source is being used (none/"minikube"/"kubernetes"/"openshift") For NOTES generation only 

| global.kubernetesClusterDomain 
| string 
| "" 
| If using Minikube or Kubernetes, set the cluster domain

| global.kubernetesIngressClass 
| string 
| "" 
| If using Minikube or Kubernetes, set the Ingress class (i.e: nginx)

| global.openshiftRouteDomain 
| string 
| "" 
| If using OpenShift Routes, set the Route domain

| global.chargedProductValues.productID 
| string 
| "46b14c7f2f894218a7879b3f6416024f" (DMOE) / "72984f114b54496a8a44be139154a988" (PAMOE) 
| Product ID for License tracking

| global.chargedProductValues.productMetric 
| string 
| "VIRTUAL_PROCESSOR
_CORE" 
| Product metric for License tracking

| global.chargedProductValues.productName 
| string 
| "IBM Decision Manager Open Edition" (DMOE) / "IBM Process Automation Manager Open Edition" (PAMOE) 
| Product name for License tracking

| nameOverride 
| string 
| "" 
| Overrides chart name

| fullnameOverride 
| string 
| "" 
| Overrides chart full name
|===

=== Management Console Configuration

|===
| Key | Type | Default | Description

| management_console.enabled 
| bool 
| TRUE 
| Enable or disable Management Console installation

| management_console.name 
| string 
| "management-console" 
| Component name

| management_console.appNameOverride 
| string 
| "" 
| Overrides the deployed application name

|===


=== MCP Server Configuration

|===
| Key | Type | Default | Description

| mcp_server.enabled 
| bool 
| TRUE 
| Enable or disable MCP Server installation

| mcp_server.name 
| string 
| "mcp-server" 
| The MCP Server application name

| mcp_server.env 
| object 
| {} 
| Env variables for {MCP_SERVER} deployment
|===

[#pre-configured-business-services]
== {MANAGEMENT_CONSOLE} pre-configured _Business Services_ connections

The {MANAGEMENT_CONSOLE} supports a pre-defined list of Business Services that will be automatically connected when opening the application in the browser for the first time.

This is achieved by configuring the `RUNTIME_TOOLS_MANAGEMENT_CONSOLE_MANAGED_BUSINESS_SERVICES` environment variable (or the `management-console.managedBusinessServices` value in the Helm chart) with a list of the specifications for the desired Business Services in the following format:

[source,json]
----
{
  "name": "string",
  "businessServiceUrl": "string",
  "clientId": "string", // Optional
  "scope": "string", // Optional
  "audience": "string" // Optional
}
----

Where:

 - *name*: is the alias given to the Business Service in the {MANAGEMENT_CONSOLE}; _[required]_
 - *businessServiceUrl*: the URL of the Business Service, where the API is served from; _[required]_
 - *clientId*: is the Client ID used during OIDC authentication. Needs to be set only if the Identity Provider used by the Business Service needs an OIDC Client ID different from the one defined by the `RUNTIME_TOOLS_MANAGEMENT_CONSOLE_OIDC_CLIENT_CLIENT_ID` environment variable; _[optional]_
 - *scope*: space-separated list of the scopes used during OIDC authentication. Needs to be set only if the Identity Provider used by the Business Service needs a list of scopes different from the one defined by the `RUNTIME_TOOLS_MANAGEMENT_CONSOLE_OIDC_CLIENT_DEFAULT_SCOPES` environment variable; _[optional]_
 - *audience*: is the Audience parameter used during OIDC authentication. Needs to be set only if the Identity Provider used by the Business Service requires a value different from the one defined by the `RUNTIME_TOOLS_MANAGEMENT_CONSOLE_OIDC_CLIENT_DEFAULT_AUDIENCE` environment variable. _[optional]_

Example:

[source,json]
----
[
  {
    "name": "My Business Service 1",
    "businessServiceUrl": "http://my-business-service-1.url",
  },
  {
    "name": "My Business Service 2",
    "businessServiceUrl": "http://my-business-service-2.url",
    "clientId": "custom-client-id",
    "scope": "custom scopes for openid",
    "audience": "business-service-audience"
  },
  ...
]
----

[#serving-from-a-subpath]
== Serving the {MANAGEMENT_CONSOLE} from a custom subpath

By default, the {MANAGEMENT_CONSOLE} is served from the root path (`/`) on its web server, either when running directly from the container image or deployed to a Kubernetes/OpenShift cluster. This means that the web application is served through an URL that looks like `https://my.domain.com/`.

In some cases, you may want to serve the application from a subpath for example, `/bamoe-management-console`, with the final URL looking like `https://my.domain.com/bamoe-management-console`.

To achieve this, the {MANAGEMENT_CONSOLE} container image accepts two environment variables that are used to configure the subpath:

- *RUNTIME_TOOLS_MANAGEMENT_CONSOLE_BASE_PATH*: The target subpath where the web application will be served from (for example, `/bamoe-management-console`). Empty by default, which means that the web application is served from the root (`/`) path. Obs.: The subpath should *not* include the leading `/`.
- *RUNTIME_TOOLS_MANAGEMENT_CONSOLE_USE_APACHE_HTTPD_BASE_PATH_ALIAS*: Whether or not the Apache HTTP Server should define an `Alias` in the `/etc/httpd/conf/httpd.conf` inside the container image during runtime. The alias will look like: `Alias /$RUNTIME_TOOLS_MANAGEMENT_CONSOLE_BASE_PATH /var/www/html`.

There are two different scenarios for running the {MANAGEMENT_CONSOLE}: behind a reverse proxy (be it an Ingress in a Kubernetes cluster, a Route in an OpenShift cluster, or an Nginx instance in a Docker Compose, for example) or served directly from the container image (by running it via Docker locally, for example).

=== Behind a reverse proxy (Kubernetes / OpenShift / Nginx)

In this scenario, only the `RUNTIME_TOOLS_MANAGEMENT_CONSOLE_BASE_PATH` environment variable needs to be set, while `RUNTIME_TOOLS_MANAGEMENT_CONSOLE_USE_APACHE_HTTPD_BASE_PATH_ALIAS` should remain empty or set to `"false"`.

If you are installing by using the Helm chart, this can be set by using the `management-console.applicationSubpath` value and appending `--set management-console.applicationSubpath=your-subpath` to the `helm install` command. 

But if installed by using the `oc` CLI, the Deployment resource can be updated with `oc set env deployment/bamoe-management-console-app RUNTIME_TOOLS_MANAGEMENT_CONSOLE_BASE_PATH=your-subpath`.


=== Container image running locally using Docker

In this case, if running on a different port is not an option, both environment variables need to be set. `RUNTIME_TOOLS_MANAGEMENT_CONSOLE_BASE_PATH` with the subpath value and `RUNTIME_TOOLS_MANAGEMENT_CONSOLE_USE_APACHE_HTTPD_BASE_PATH_ALIAS` with `"true"`.

Example:

[source,shell,subs="attributes+"]
----
docker run -d -p 8080:8080 -e RUNTIME_TOOLS_MANAGEMENT_CONSOLE_BASE_PATH=bamoe-management-console -e RUNTIME_TOOLS_MANAGEMENT_CONSOLE_USE_APACHE_HTTPD_BASE_PATH_ALIAS=true quay.io/bamoe/management-console:{IMAGE_VERSION}
----

