include::../partials/attributes.adoc[]

= Upgrade {PRODUCT_SHORT} from {VERSION_90X} to {Version_91x}

The following new features may require you to upgrade your projects:

* The new DMN editor
* Canvas Helm chart
* DMN 1.5 support

To upgrade {PRODUCT_SHORT} from {VERSION_90X} to {Version_91x}, follow these steps:

* Update QUARKUS Version to {QUARKUS_VERSION}
* Update pom files from your projects with {Version_91x} {PRODUCT_SHORT} BOM
* For direct library components, use Version 10.0.0 for Drools or Version 10.0.0 for Apache kogito libraries.
* Rebuild projects and re-deploy as regular software rollout.

For {CANVAS}:

The new containers are the drop-in replacements for the existing. 
You can use https://docs.openshift.com/container-platform/4.14/applications/deployments/route-based-deployment-strategies.html#deployments-blue-green_route-based-deployment-strategies[blue/green deployment strategies]

For the new DMN editor:
After upgrade, the new DMN editor will be opened automatically when you first access it in Canvas or Developer tools for VS Code.
Existing DMN files (any version) can be opened directly in the editor. However if you edit and save your file it will be migrated automatically to DMN 1.5 and cannot subsequently be opened by the classic editor. If you wish to continue with your current DMN version and the classic editor, you can select the DMN Editor dropdown to toggle between the classic and new editor. For more information, see xref:../tools/authoring-decisions.adoc[Authoring decisions]