= Upgrading from BAMOE 9.0.x

include::../partials/attributes.adoc[]

The following new features may require you to upgrade your projects:

* Canvas Helm chart
* The new DMN editor supporting DMN 1.5

To upgrade {PRODUCT_SHORT} from {VERSION_90X} to {Version_91x}, follow these steps:

* Update QUARKUS Version to {QUARKUS_VERSION}
* Update pom files from your projects with {Version_91x} {PRODUCT_SHORT} BOM
* Rebuild projects and re-deploy as regular software rollout.

For {CANVAS}:

The new containers are the drop-in replacements for the existing. 
You can use https://docs.openshift.com/container-platform/4.14/applications/deployments/route-based-deployment-strategies.html#deployments-blue-green_route-based-deployment-strategies[blue/green deployment strategies]

For the new DMN editor:
After upgrade, the New DMN Editor will be opened automatically when you first access it in Canvas or Developer tools for VS Code.
Existing DMN files (any version) can be opened directly in the editor. For more information, see xref:../tools/authoring-decisions.adoc[Authoring decisions]

== Maven libraries mapping guide

With the transition of the KIE projets to the Apache Software Foundation (ASF), it has become necessary to rename a number of Maven modules.  The following table(s) describe the changes to the Maven GAV (GroupID/ArtifactID/Version) in {VERSION_910}:

The general guidelines are:

* xref:../../installation/gav-mapping-rules.adoc[Drools Maven mappings] for anything related to rules or decisions.
* xref:../../installation/gav-mapping-process.adoc[jBPM Maven mappings] for anything related to BPMN-based stateless/stateful processes.
* xref:../../installation/gav-mapping-kogito.adoc[Kogito Maven mappings] for anything related to infrastructure or extended services.
* xref:../../installation/gav-mapping-kie.adoc[KIE Maven mappings] for anything else that doesn't fall into the above categories.
