= Migrating your in-flight Process Instances using PIM
include::../partials/attributes.adoc[]
include::../styles/images.adoc[]

When Process Definitions (PDs) are deployed as Business Services in a Cloud environment, client applications or Management Console users can create Process Instances (PIs) that follow the sequence flow defined in its originating PD. When PIs are on long-running (e.g., days/months/weeks) waiting states, such as Timers or User Tasks, new versions of its originating PDs can be deployed to Business Services, making existing PIs on waiting states follow obsolete PDs.

To solve this problem, Process Instance Migration (PIM) is introduced, allowing PIs to migrate to new PDs, effectively updating themselves to newer versions of its PDs, or even entirely different PDs. By mapping the original PD nodes to newer PD nodes, PIs can transition to the new sequence flow and stop being attached to its originating PD.

Process Instances (PIs) contain information about the entities that are necessary to walk through the Workflow’s execution path. Such entities are passed from node to node as Process Variables, and this input/output relationship between nodes is defined via I/O Assignments in BPMN Editor (classic), and Data Mapping in the new BPMN Editor.

For more information on using the {MANAGEMENT_CONSOLE} to migrate Process Instances see xref:consoles.adoc#process-instance-migration-ui[Management Console → Process Instance Migration]

For more information on using the Process Add-on API to migrate Process Instances to a new Process Definition see xref:management-apis.adoc#process-instance-migration-addon[Management APIs Process → Process Instance Migration APIs]

=== Migration of Process Instances to a different User Task Lifecycle

User Tasks complete their entire lifecycle with the lifecycle implementation they were started with and it is not possible to migrate an in-flight Process Instance to an alternative User Task Lifecycle. For more information see xref:../workflow/overview.adoc[]

When migrating from kogito to ws-human-task lifecycle, the active usertasks will continue to complete their lifecycle with kogito, provided there is no custom lifecycle and the new ones would start using ws-human-task. 

When migrating from a custom usertask lifecycle to kogito or ws-human-task lifecycles, the active tasks can continue with the custom lifecycle as long as they are present in the business service application and the new ones would start with the selected lifecycle.
