= Migrating your in-flight Process Instances using PIM
include::../partials/attributes.adoc[]
include::../styles/images.adoc[]

When Process Definitions (PDs) are deployed as Business Services in a Cloud environment, client applications or Management Console users can create Process Instances (PIs) that follow the sequence flow defined in its originating PD. When PIs are on long-running (e.g., days/months/weeks) waiting states, such as Timers or User Tasks, new versions of its originating PDs can be deployed to Business Services, making existing PIs on waiting states follow obsolete PDs.

To solve this problem, Process Instance Migration (PIM) is introduced, allowing PIs to migrate to new PDs, effectively updating themselves to newer versions of its PDs, or even entirely different PDs. By mapping the original PD nodes to newer PD nodes, PIs can transition to the new sequence flow and stop being attached to its originating PD.

Process Instances (PIs) contain information about the entities that are necessary to walk through the Workflow’s execution path. Such entities are passed from node to node as Process Variables, and this input/output relationship between nodes is defined via I/O Assignments in BPMN Editor (classic), and Data Mapping in the new BPMN Editor.

For more information on using the {MANAGEMENT_CONSOLE} to migrate Process Instances see xref:consoles.adoc#process-instance-migration-ui[Management Console → Process Instance Migration]

For more information on using the Process Add-on API to migrate Process Instances to a new Process Definition see xref:management-apis.adoc#process-instance-migration-addon[Management APIs Process → Process Instance Migration APIs]

[#migration-PIM]
== Migrating active process instances using the Process Instance Migration API
Use this tool to enable process instances to migrate to newer versions of its PDs, or even entirely different PDs. By mapping the original PD nodes to newer PD nodes, PIs can transition to the new sequence flow and stop being attached to its originating PD.

BAMOE PIM Add-on underpins the UI available in the BAMOE Management Console. 

The Process Instance Migration Service enables you to migrate active process instances from one deployment version to another. This ensures that long-running business processes can adapt to changes in their definitions over time without losing their current state or requiring a restart.

The advantage of using this utility is that it:

* _Preserves state_: During migration, process or task variables remain unchanged.

* _Supports evolving processes_: Enables seamless upgrades to new process definitions as business needs evolve.

* _Handles subprocesses automatically_: When a process is migrated, all its subprocesses—including nested ones—are automatically migrated as well.

* _Maintains parent dependencies_: Attempting to migrate a subprocess independently, without migrating its parent process, will result in migration failure.

Process Instance Migration (PIM) using the Compact Architecture is based on simplified communication among the different __Business services__ without using events (Kafka/HTTP). 

Using the xref:../workflow/management-apis.adoc[Process Management API], the following two endpoints are used to migrate active process instances:

`POST /management/processes/{processId}/migrate`:: Endpoint to migrate all active process instances of a given processId to a new target process. 

`POST /management/processes/{processId}/instances/{processInstanceId}/migrate`:: It migrates the process instance specified by the processID and processInstanceID to the target process and process instance. 

=== Starting and stopping processes
You can use the following `curl` command to start a process:

[source,shell]
----
curl -H "Content-Type: application/json" -H "Accept: application/json" -X POST http://localhost:8080/<processId> -d
----

You can use the following `curl` command to stop a process:

[source,shell]
----
curl -H "Content-Type: application/json" -H "Accept: application/json" -X POST http://localhost:8080/<processId>/<processInstanceId>/continue -d '{}'
----

=== Example
Migrate all active process instances of a specified processId to a new target process definition using the following `curl` command:

[source,shell]
----
curl -H "Content-Type: application/json" -H "Accept: application/json" -X POST http://localhost:8080/management/processes/<sourceProcessId>/migrate -d 
{
  "targetProcessId": <targetProcessId>
  "targetProcessVersion": <targetProcessVersion>
}    
----
Where `sourceProcessId` is a path parameter in the URL and the `targetProcessId` and `targetProcessVersion` are included as query parameters depending on the API design. If the migration is successful you will receive the following output. 

[source,shell]
----
{
   "message":"All instances migrated",
   "numberOfProcessInstanceMigrated":1
}
----
