[id='components-con_{context}']
= {PRODUCT} components

{PRODUCT} is made up of {CENTRAL} and {KIE_SERVER}.

* {CENTRAL} is the graphical user interface where you create and manage business rules. You can install {CENTRAL} in a {EAP} instance or on the Red Hat OpenShift Container Platform (OpenShift).
+
{CENTRAL} is also available as a standalone JAR file. You can use the {CENTRAL} standalone JAR file to run {CENTRAL} without deploying it to an application server.
+
* {KIE_SERVER} is the server where rules and other artifacts are executed. It is used to instantiate and execute rules and solve planning problems. You can install {KIE_SERVER} in a {EAP} instance, in a {EAP} cluster, on OpenShift, in an Oracle WebLogic server instance, in an IBM WebSphere Application Server instance, or as a part of Spring Boot application.
+
You can configure {KIE_SERVER} to run in managed or unmanaged mode. If {KIE_SERVER} is unmanaged, you must manually create and maintain KIE containers (deployment units). A KIE container is a specific version of a project. If {KIE_SERVER} is managed, the {CONTROLLER} manages the {KIE_SERVER} configuration and you interact with the {CONTROLLER} to create and maintain KIE containers.

