= BAMOE Canvas
include::../partials/attributes.adoc[]
include::../styles/images.adoc[]

{CANVAS} enables developers and business users to efficiently collaborate on business automation projects stored in a single enterprise Git repository. 

{CANVAS} enables you to work with Decisions and Workflows, directly in your browser. Decisions are https://www.omg.org/dmn/[DMN] files, and Workflows are https://www.omg.org/bpmn/[BPMN] files.
Both are open source standards defined by https://www.omg.org/[OMG]. It integrates with Git repositories and Cloud providers for a familiar and convenient development experience.
It is based on the open source https://sandbox.kie.org/[Apache KIE Sandbox], a project from the https://kie.apache.org/[Apache KIE community]. If you have not installed it yet see xref:../installation/development-environment.adoc#canvas-installation[Installing {CANVAS}]

Unlike most web applications, {CANVAS} does not feature its own authentication mechanism, and instead you authenticate through your Git and Cloud providers. {CANVAS} communicates directly with the providers to save your decisions and processes in the Cloud, or to deploy them during development.

{CANVAS} stores all data on locally on your machine inside your browser, only connecting to a Git repository or Cloud provider to push your Decisions and Workflows to a remote repository or to deploy them to the Cloud. 
If you close your tab or restart your computer all changes made on {CANVAS} are persisted in your disk and are available when you open {CANVAS}.

You can change the {CANVAS} interface language by updating your browser language settings or navigating to Settings in {CANVAS}, opening the Language tab, and selecting your preferred language. By default, the {CANVAS} uses your browser settings, but you can select a specific language to override the browser setting. Once configured, all UI elements, including the {CANVAS} homepage and interactive components, will display in the selected language, providing a fully localized experience. 

More information on the main features available in {CANVAS} to configure before starting to develop your BPMN and DMN business artifacts in the following topics:

* xref:creating-models.adoc[Creating models]
* xref:importing-existing-projects.adoc[Importing existing projects]
* xref:connecting-accounts.adoc[Connecting to Git and Cloud providers]
* xref:working-with-git.adoc[Working with Git]
* xref:applying-accelerators.adoc[Using Accelerators]
* xref:dev-deployments.adoc[Dev Deployments]
* xref:create-custom-dev-deployment.adoc[Creating a custom Dev Deployment image]
* xref:dev-deployment-upload-service.adoc[Dev Deployment Upload Service]