= BAMOE Canvas
IBM; KIE Community
include::../partials/attributes.adoc[]

{CANVAS} makes it possible to work with Decisions and Workflows, directly on the browser.
It integrates with Git repositories and Cloud providers for a familiar and convenient development experience.
It is based on the open source https://sandbox.kie.org/[KIE Sandbox], a project from the https://www.kie.org/[KIE community].

Unlike most web applications, {CANVAS} does not feature its own authentication mechanism, instead, you authenticate with your Git and Cloud providers, so BAMOE Canvas can communicate with them to save your Decisions and Workflows in the Cloud, or deploy them during development.

Another unconventional aspect of {CANVAS} is that it doesn't store any of your information in the Cloud.
Instead, everything you do on {CANVAS} is persisted on your machine, inside your browser.
This doesn't mean that you'll lose your work if you close your tab or restart your computer, as all changes made on {CANVAS} are persisted in your disk, so you can be assured that your files are safe.

To share your Decisions and Workflows with others and collaborate, {CANVAS} allows you to push your changes to remote Git repositories, or deploy them to a Cloud provider.

On {CANVAS}, Decisions are https://www.omg.org/dmn/[DMN] files, and Workflows are https://www.omg.org/bpmn/[BPMN] files.
Both are open source standards defined by https://www.omg.org/[OMG].

Let's dive in and see how you can start working on {CANVAS}.