= BAMOE Canvas
include::../partials/attributes.adoc[]
include::../styles/images.adoc[]

With {CANVAS}, developers and business users can collaborate on business automation projects in a single enterprise Git repository, which facilitates collaboration across roles and 
improves efficiency.

{CANVAS} enables you to work with Decisions and Workflows, directly in your browser. Decisions are https://www.omg.org/dmn/[DMN] files, and Workflows are https://www.omg.org/bpmn/[BPMN] files.
Both are open source standards defined by https://www.omg.org/[OMG]. It integrates with Git repositories and Cloud providers for a familiar and convenient development experience.
It is based on the open source https://sandbox.kie.org/[Apache KIE Sandbox], a project from the https://kie.apache.org/[Apache KIE community].

Unlike most web applications, {CANVAS} does not feature its own authentication mechanism, and instead you authenticate through your Git and Cloud providers. {CANVAS} communicates directly with the providers to save your decisions and processes in the Cloud, or to deploy them during development.

{CANVAS} stores all data on locally on your machine inside your browser, only connecting to a Git repository or Cloud provider to push your Decisions and Workflows to a remote repository or to deploy them to the Cloud. 
If you close your tab or restart your computer all changes made on {CANVAS} are persisted in your disk and are available when you open {CANVAS}.


