= IBM BAMOE Developer Tools for VS Code
include::../partials/attributes.adoc[]

{PRODUCT_SHORT} provides a handy VS Code Extension that bundles graphical Editors for BPMN and DMN files.
The {PRODUCT_SHORT} Developer Tools extension can be downloaded from {VS_CODE_BUNDLE_LINK}[*{VS_CODE_BUNDLE}*].

The bundled BPMN and DMN Editors are made available through the KIE DMN Editor and KIE BPMN Editor extensions, and they feature all available features you have on {CANVAS}.
Static file validation, DMN Runner, and Dev deployments are not available for {PRODUCT_SHORT} Developer Tools yet, but you can achieve a similar experience of DMN Runner with our Scenario Simulation Editor.
See how below.

== Running unit tests with Scenario Simulation files

Running Scenario Simulation (.scesim) files requires a configured Java project with the JUnit dependency available.
Please follow this https://blog.kie.org/2021/04/how-to-use-test-scenario-editor-to-test-your-dmn-asset-in-vscode.html[blog post tutorial] to get started with Scenario Simulation on {PRODUCT_SHORT} Developer Tools.

== Importing DMN Data Types from Java classes

{PRODUCT_SHORT} Developer Tools allows you to create DMN Data Types directly from Java POJOs.
Please follow this https://blog.kie.org/2022/05/dmn-types-from-java-classes.html[blog post tutorial] to get started.
