= Importing DMN Data Types from Java classes
include::../partials/attributes.adoc[]
include::../styles/images.adoc[]

{DEV_TOOLS} allows you to create DMN Data Types directly from Java classes. The following section describes an example scenario to demonstrate how to do this in the DMN Editor.

== Project Setup

You can start with any _Business Service_ project that contains DMN assets; however, this guide refers to a project that can be found in the xref:../getting-started/examples.adoc[Example Business Service projects] table.

Before you start, ensure that xref:https://marketplace.visualstudio.com/items?itemName=redhat.java[Language Support for Java by Red Hat extension] is installed. You can then follow these steps to set up the project:

1. Go to the xref:../release-notes/whats-new-9-5.adoc#download-doc[Download documents] section and download the Example ZIP file.
2. Choose `dmn-quarkus-example` file and open it with VS Code.
3. Add the Java Classes you need to convert to DMN Data Type in any package under the `src/main/java` directory of your _Business Service_ project.
4. In the same package defined in the previous point, create the `Activator` Java Class. The Activator class **must** be an empty Java Class exactly named "Activator.java". Any change or additional code can negatively affect the feature behavior.

== Importing your Java Classes as DMN Types

Open your target DMN file, the reference for this guide is the `TrafficViolation.dmn` file already available in the example project. Go to the `Data Types` tab. Select `Import Java Classes` from the drop-down list.
Be aware that this option is enabled only if the previously described requirements are satisfied.

After selecting the option, the `Import Java Classes` panel appears. To import your Java Classes as DMN types, do the following steps:

. Select Java Classes. In the search box, enter the name of the Java Class you want to import as a DMN Type. You can use the class simple name (for example, Book) or the fully qualified name (for example, dto.Book). The search box displays a list of all Java Classes that match the provided key. Select the ones you want to import. When ready, click **Next**.

. Select fields and review the list of all Java Classes' properties.

. Click **Import** to automatically import the selected Java Class in the DMN Data Type tab.

[NOTE]
====

If the existing data type is not available in the list, it will display a screen with options like `Create a custom data type` or `Import Java classes` or `Paste data type`. You can select `Import Java classes`.

If you try to import a data type from a Java class that already exists in another DMN file referenced in your Business Service project, the editor will detect a conflict and a dialog will ask you to confirm your preferred action.

====

== About conflicts while importing data types

When working with DMN models, especially when including external models, it is important to know how data types are managed and how conflicts are resolved. This section outlines the behavior and options available when data type conflicts occur during import.

=== Data type classification

Data types are classified into the following two types:

* Internal Data Types: These are data types defined within the current DMN model.

* External Data Types: These are data types that originate from an included (imported) DMN model.

=== Conflict scenarios and resolution options

When importing a DMN model, conflicts might arise if a data type with the same name already exists in the current model. The resolution options vary depending on whether the conflict involves internal or external data types.

=== Internal data type conflicts

If the conflict is between two internal data types, meaning both the existing and the imported data types are defined within the current model, you can choose one of the following options:

* *Replace*: The existing data type is replaced with the imported one.

* *Keep Both*: Both data types are retained. The imported data type is added with a modified name (for example, DataType-1, DataType-2, etc.) to avoid naming collisions.

=== External data type conflicts

* *Replace*: This is disabled.

* *Keep Both*: This is the only available option. Since external data types cannot be modified, the imported data type is retained with a unique name to distinguish it from the existing one (for example, DataType-1, DataType-2, etc.).

=== Mixed Conflicts (Internal and External)

In cases where both internal and external data types with the same name exist:

* For the internal data type, both **Replace** and **Keep Both** options are available.

* For the external data type, only the **Keep Both** option is enabled, **Replace** is disabled.

In the **Keep Both** option, when the user selects multiple Java classes with the same name from the list of Java classes, they are renamed as `javaclassname-1`, `javaclassname-2`, and so on.