
== The Editor

Here we show all the functionalities of the new DMN editor.

The diagram can be accessed on the A. The data types editor can be access on B and to manage the included models we have C.

=== A. Diagram

Opening the diagram for the first time we have a few components to pay attention, and here we enumerate them:

. The editor empty state.

Here you can easily create a starting decision table or a decision with input data node;

[start=2]
. The node Palette:
.. DRG nodes;
.. Artifact nodes;
.. All DRG nodes;
.. External nodes.

[start=3]
. The DRD dropdown.

The place where you can change the current opened DRD, rename it or change its properties.

[start=4]
. The properties panel of the selected element;
. The overlay panel, with customizable style and visualization properties
. The auto layout button, to help you organize your DRD;
. The canvas properties, where you can control the zoom or what you are visualizing.

On the next sections we will explain more about of these functionalities.

==== 1.Empty state

The empty state enables the user to easily bootstrap a new DMN. It has two options:

. New Decision Table

Creates a new Decision node with an empty Decision Table.

[start=2]
. New Decision with Input Data

Creates a new Input Data and Decision node with an Information Requirement relationship.

==== 2.Palette

The node palette enables the user to interact with the DRG by creating new nodes, using nodes from other DRDs and nodes from external models. Also, give the option to create artifact nodes, improving documentation, organization and visualization.

.a. DRG nodes

As the name suggests, those nodes enables the user to change the DRG, and adding a node will change the current DRD. As part of these nodes we have the “Input Data”, “Decision”, “Business Knowledge Model” (BKM), “Knowledge Source” and “Decision Service”. Each node has their own options which can be visualized by hovering the mouse on top of it.

Each node has their own characteristics, but they have similarities. Here we show all the elements of a Decision node to explain how the features can be used.

. Node name

The node name has a uniqueness validation. The editor doesn’t allow you to rename a node to a name that is already being used by another node. Empty names are also invalid. Trying to rename a node to an invalid one will cause it to rollback to its previous name. The only moment you can have nodes with the same name is when you create two or more nodes of the same type without renaming it. The following example illustrate two Decision nodes that were created without renaming, and an Input Data node where we try to rename it to “New Decision”, and after it to an empty name.

[start=2]
. Node type

Nodes that have a data type, shows this information on top of the node. It’s possible to change the node data type using the dropdown menu, or even access a custom data type to have a better visualization of the type. More about the Data Types are covered on the B section.

[start=3]
. New relationship

It’s possible to create a new requirement or association relationship from the target node to another  node respecting the DMN specification. The available options varies from node to node.
 
[start=4]
. New connected node

It’s possible to create a new connected node from the target node. It will create a node with the respective relationship. The available options varies based on the node type and respects the DMN specification.

[start=5]
. Edit

This button is only available for the Decision and BKM nodes. Clicking on it, opens the Boxed Expression editor with the node expression. The Boxed Expression editor have access to the DRG context, and are powered by an Auto completion tool, enhancing the user experience when building their Boxed expressions.

[start=6]
. Properties panel

Clicking on this button, will open the Properties Panel of the node. On this panel it’s possible to check and edit the node name, type, description, allowed answer, documentation links, font styles, and shape styles. Also it’s possible to check the node ID. More about this can be read on the "Properties Panel” section.

[start=7]
. Resize handler

Clicking on the small arrow and dragging around it’s possible to resize the target node. Each node has a minimal width and height, trying to resize to a smaller size will not affect the node.

.Decision Service
. <write about decision service specific behaviors>
. <multiple DRDs>
. <decision on multiple decision services>
. <collapsed>
. <deletion>

.b. Artifact nodes

The artifact nodes give the user the tools to improve the documentation and visualization of the DRG by modifying the DRD. The Group node creates a visual separation, and the Text Annotation enables to write a small documentation.

.c. All DRG nodes

Clicking on it will open a modal where we have access to the list of all DRG nodes that are part of the current file. It’s possible to filter the nodes by name, and nodes that are part of the current DRD are grayish. Clicking and dragging the node name to the diagram will add the node to the current DRD. More about this can be found at the DRD section.

.d. External nodes

All nodes that are part of the included models can be found here. Clicking on it will open a modal showing all nodes separated by namespace, where you can filter the nodes by name. 

Additionally, it’s possible to see the chosen name for the included model and the DMN file name from where it comes from. On the above example the name is “ex” and the filename “Another DMN.dmn”.


==== 3.DRD

The new editor gives us a brand new experience related to the DRDs, on the image below we can have an overview of this functionality

Clicking on 1 will open the DRD dropdown. To edit the DRD name, you can click on its name and type the new desired name. On 2 you can create new DRDs, which will automatically change to a new empty DRD. The 3 is the list of DRDs on the DRG. Finally, 4 is the DRD options of the selected DRD.

On the example above, the user has created a new DRD, and has it renamed to DRD2, which we can see on 1. Clicking on 2 will open the DRG nodes (3). On this example, the “My Decision” and “Person” nodes are present on the DRG but not in the current DRD. By clicking on it and dragging into the diagram the node will be added to the current DRD. This behavior is illustrate below.

It’s possible to see that the “My Decision” became grayish on the DRG nodes modal, as it’s now present on the current DRD. Also, it have a “three dot” mark on bottom of it, which tells us, this node have dependencies that are not shown on the current DRD. By dragging the “Person” node we can see the three dots disappearing, and an information requirement is automatically placed.

Also, it’s possible to change the classic shape to an alternative one, making it more visual cohesive with the BPMN model. This change affects the entire DRD, so it’s not possible to have just one node with the alternative shape.


==== 4.Properties panel
. global
. single
. multiple

==== 5.Overlay properties
. snapping
. hierarchy
. show data type tools
. enable styles

==== 6.Autolayout
==== 7.Visualization controls

. Others
.. Unkown node

=== B. Data types
. Adding a data type
. manually
. pasting
. Type
.. structure data type
.. extracting
.. collection
.. Constraints

=== C. Included models