include::../partials/attributes.adoc[]
= Overview

https://www.ibm.com/products/business-automation-manager-open-editions[{PRODUCT_LONG}] (BAMOE) is a Business Automation foundational platform for developing, deploying, manging, and monitoring Enterprise-grade, cloud-native _Business Services_ in hybrid-cloud enviroments, like https://www.redhat.com/en/technologies/cloud-computing/openshift[Red Hat® OpenShift®] and Kubernetes.

{PRODUCT_LONG} is based on Open-Source https://kie.apache.org[Apache KIE] technologies such as Drools, jBPM, and Kogito, and provides a set of libraries, applications and tools that adapt to your Software Development Lifecycle (SDLF) and integrate with services and technologies you're probably already using, like Visual Studio Code (VS Code), Git-based source code hosting services, event streaming platforms like Apache Kafka, and popular microservice monitoring and metrics technologies like Prometheus.

_Business Services_ created with {PRODUCT_LONG} contain domain-specific logic in the form of **Workflows**, **Decisions**, **Rules**, and **Decision Tables**, all based on open standards, like https://www.omg.org/spec/BPMN/2.0/About-BPMN[Business Process Model and Notation (BPMN)] and https://www.omg.org/spec/DMN[Decision Model and Notation (DMN)], or well-established formats, like regular spreadsheets.

{PRODUCT_LONG} empowers you to transform regular containerized microsservices based on https://quarkus.io/[Quarkus] or https://spring.io/projects/spring-boot[Spring Boot] into domain-rich _Business Services_, containing not only Workflows, Decisions, Rules, and/or Decision Tables, but also your custom logic and functionalities. {PRODUCT_LONG} allows you to be in full control of your _Business Services_, their development lifecycle, deployment strategy, topology, and scale.

For secure, auditable, and fault-tolerant Process Automation and Decision Management, _Business Services_ created with {PRODUCT_LONG} can be configured to transactionally store data in relational databases like PostgreSQL and Microsoft SQL Server, and authenticate users and API calls via OpenID Connect, allowing for your Identity Provider of choice to be used.

For Workflows requiring human intervention or scheduled jobs (stateful Workflows), {PRODUCT_LONG} provides specific subsystems that can be configured inside _Business Services_. For Straight-Through Processes (STP) (stateless Workflows) or Decisions and Rules orchestration, _Business Services_ built with {PRODUCT_LONG} will work out-of-the-box.

Once _Business Services_ containing stateful Workflows are live, {PRODUCT_LONG} lets you manage Process Instances, User Tasks, and Jobs via the web-based {MANAGEMENT_CONSOLE}, while also providing a comprehensive set of REST and GraphQL APIs for system-to-system integrations.

Even though its main focus remains in hybrid-cloud environments, more traditional architectures are also contemplated by {PRODUCT_LONG} with its programmatic Java APIs that allow embedding Decisions, Rules, and Decision Tables directly into your conventional Java applications running as standalone JARs, or web apps deployed in application servers, like https://www.redhat.com/en/technologies/jboss-middleware/application-platform[Red Hat® JBoss® Enterprise Application Platform (JBoss EAP)], https://www.ibm.com/products/websphere-application-server[IBM WebSphere Application Server], and others.

{PRODUCT_LONG} is a developer-friendly foundational platform, meaning Workflows, Decisions, Rules, and Decision Tables are all saved in text-based formats (E.g., XML and/or plain-text), making them compatible with standard software development pratices like Pull Requests, Merge Requests, and code reviews. _Business Services_ are Java applications, built on top of the Maven build system's convention. Through {CANVAS}, however, non-developers are also empowered to collaborate in the process of creating _Business Services_, where Git operations are abstracted and simplified for reducing friction and letting Business Analysts or domain experts to focus on the business logic, rather than code.

To start building your _Business Services_ with {PRODUCT_LONG}, refer to xref:project-setup.adoc[Getting started → Initial Business Service project setup and walkthrough].

---

For more information on each of the components that compose {PRODUCT_LONG}, please refer to xref:../reference-guide/components.adoc[Reference → BAMOE Components].

Architectural information for {PRODUCT_LONG} is available at xref:../reference-guide/architecture.adoc[Reference → BAMOE Architecture].

---

{PRODUCT_LONG} is licensed under the https://www.gnu.org/licenses/old-licenses/lgpl-2.1.en.html[GNU Lesser General Public License v. 2.1]. Each software component is governed by a license located in the component source code that permits you to run, copy, modify, and redistribute (subject to certain obligations) the software component.