= Overview
include::../partials/attributes.adoc[]
include::../styles/images.adoc[]

https://www.ibm.com/products/business-automation-manager-open-editions[{PRODUCT_LONG}] (BAMOE) is a Business Automation foundational platform for developing, deploying, managing, and monitoring Enterprise-grade, cloud-native _Business Services_ in hybrid-cloud enviroments, such as https://www.redhat.com/en/technologies/cloud-computing/openshift[Red Hat® OpenShift®] and Kubernetes.

{PRODUCT} is based on Open-Source https://kie.apache.org[Apache KIE] technologies such as Drools, jBPM, and Kogito, and provides a set of libraries, applications and tools that adapt to your Software Development Life Cycle (SDLC) and integrate with services and technologies that you are probably already using:

* Visual Studio Code (VS Code), 
* Git-based source code hosting services,
* event streaming platforms such as Apache Kafka,
* popular microservice monitoring and metrics technologies such as Prometheus.

_Business Services_ built on {PRODUCT} contain domain-specific logic in the form of **Workflows**, **Decisions**, **Rules**, and **Decision Tables**, all based on open standards, like https://www.omg.org/spec/BPMN/2.0/About-BPMN[Business Process Model and Notation (BPMN)], https://www.omg.org/spec/DMN[Decision Model and Notation (DMN)] and the {DROOLS_DOCS_LINK}/language-reference/index.html[Drools Rule Language (DRL)], or well-established formats, like regular spreadsheets.

{PRODUCT_LONG} empowers you to transform regular containerized microservices based on https://quarkus.io/[Quarkus] or https://spring.io/projects/spring-boot[Spring Boot] into domain-rich _Business Services_, combining your custom logic and functionality with Workflows, Decisions, Rules, and/or Decision Tables. {PRODUCT} allows you to be in full control of your _Business Services_, their development lifecycle, deployment strategy, topology, and scale.

*Decision Management*

Managing your business Decisions and Rules in {PRODUCT_LONG} is done through the following four types of models:

* Decisions (_DMN_): Non-developer-friendly based on open standards for visually authoring Decision logic.
* Rules (_DRL_): Developer-friendly based on the battle-proof Drools engine.
* Spreadsheet Decisions Tables (_XLS_ or _XLSX_): Business rules that can be better expressed in tabular format. Usually based on a large number of inputs.
* Test Scenarios (_SCESIM_): Tabular-style unitary tests for Decisions and Rules, compatible with JUnit.

*Process Automation*

Automating business Processes in {PRODUCT_LONG} can be done via Workflow (_BPMN_) models in the following two paradigms, both equally capable of leveraging Decision Management capabilities through built-in interoperability with Decisions (DMN) and Rules (DRL):

* Stateless Workflows (_Straight-Through Process - STP_): Executed from start to finish without human interaction, no persistence of state, and no scheduled jobs. Perfect for Decisions and Rules orchestration.
* Stateful Workfows (_Business Process_): Usually long-running, human-driven, and dependent on timer-based scheduled events. Suitable for complex business processes requiring a lot of domain knowledge from business experts, auditability and fault tolerance.

{PRODUCT} is a developer-friendly foundational platform, meaning Workflows, Decisions, Rules, and Decision Tables are all saved in text-based formats (i.e., XML and/or plain-text), making them compatible with standard software development pratices like Pull Requests, Merge Requests, and code reviews. _Business Services_ are Java applications, built on top of the Maven build system conventions. As an alternative the {CANVAS} web application empowers non-developers to collaborate in the process of creating _Business Services_. Git operations are simplified to reduce friction and enable Business Analysts or domain experts to focus on the business logic, rather than the code.

For Stateful Workflows (e.g., human-driven long-running business processes), specific subsystems guarantee that security, auditability, and fault-tolerance are the default on _Business Services_ built on {PRODUCT}. Operational and audit data are transactionally stored in relational databases such as PostgreSQL or Microsoft SQL Server, and users and API calls authenticated via OpenID Connect with your Identity Provider of choice.

For Stateless Workflows (e.g., Decisions and Rules orchestration), _Business Services_ built on {PRODUCT} require no additional configuration.

Once _Business Services_ containing Workflows of any kind are live, {PRODUCT_LONG} lets you manage Process Instances, User Tasks, and scheduled Jobs via the web-based {MANAGEMENT_CONSOLE}, while also providing a comprehensive set of REST and GraphQL API endpoints for system-to-system integrations.

Even though the main focus of {PRODUCT} remains in hybrid-cloud environments, more traditional architectures are also suported by {PRODUCT} with its programmatic Java APIs that enable you to embed Decisions, Rules, and Decision Tables directly into your conventional Java applications running as standalone JARs, or web apps deployed in application servers, such as https://www.redhat.com/en/technologies/jboss-middleware/application-platform[Red Hat® JBoss® Enterprise Application Platform (JBoss EAP)], https://www.ibm.com/products/websphere-application-server[IBM WebSphere Application Server], and others.

---

To start building your _Business Services_ with {PRODUCT_LONG}, refer to xref:../getting-started/project-setup.adoc[Getting started → Initial Business Service project setup and walkthrough].

---

Architectural information for {PRODUCT_LONG} is available at xref:../reference-guide/architecture.adoc[Reference → BAMOE Architecture].

---

_{PRODUCT_LONG} is licensed under the https://www.gnu.org/licenses/old-licenses/lgpl-2.1.en.html[GNU Lesser General Public License v. 2.1]. Each software component is governed by a license located in the component source code that permits you to run, copy, modify, and redistribute (subject to certain obligations) the software component._