= Overview 
include::../partials/attributes.adoc[]

{PRODUCT_LONG} is an open-source business automation platform that combines flexible business process automation and decision management. {PRODUCT_SHORT} facilitates the collaboration between business and IT users throughout the creation, management, validation, and deployment of tailored process and decision automation solutions. Business users can modify business logic and business processes without requiring assistance from IT personnel.

{PRODUCT_LONG} is an application development platform that enables developers and business experts to create cloud-native applications. It is available as a set of Maven dependencies accessed through Maven Central. 

{PRODUCT_SHORT} is a cloud-native technology fully supported on both Red Hat OpenShift Container Platform and Kubernetes, allowing for flexible deployment across hybrid cloud environments.

Business Automation Manager Open Editions includes IBM Process Automation Manager Open Edition and IBM Decision Manager Open Edition as licensed products. Each of these developer-centric products can be purchased separately.  

== Benefits of Business Automation Manager Open Editions: 

Open, developer-friendly solutions. Highly customized applications can be built using common development and CI/CD tools on transparent, secure code. 

Standards-based tooling. BPMN models and DMN models provide multiple options to model flows and policies, and to help ensure automation services integrate with legacy and third-party applications. 

Cloud-native development. Apps can be built and deployed as containerized microservices on Red Hat OpenShift. 

Decision management. Open-source rules engine and Kogito-based, cloud-native tooling and runtimes can provide fast boot times and scaling. 

== New in IBM Decision Manager Open Edition 9

New cloud-native features. Aligned with the improved BAMOE Canvas and Developer Tools experience, the decision and rules engine powered by Kogito is designed to be lightweight and fast, enabling usage of hot reload features for business assets, and native compilation, which helps make serverless model adoption and container scale-down achievable. 

Immediate testing. BAMOE Canvas provides a completely client-side visual modeling experience, enabling immediate testing without deploying the solution to a separate runtime environment. It fast-tracks the feedback loop, promoting rapid iterations. 

Enhanced microservices architecture. As part of the shift from an application server based architecture to a microservices based architecture, users can build and run their decision services as cloud-native Java applications on Quarkus. This shift to microservices based on the Quarkus framework enhances the modularity, scalability, and maintainability of applications. 

Improved scalability. Users can deploy their decision services as microservices in a containerized environment, taking full advantage of Kubernetes' scalability features such as down-scaling and auto-scaling. 

Support for additional Kubernetes. IBM's commitment to open source continues with support for various Kubernetes platforms, including Red Hat OpenShift. This broadens the deployment options, ensuring adaptability to various infrastructural needs. 
