= About IBM Business Automation Manager Open Editions
include::../partials/attributes.adoc[]

{PRODUCT_LONG} is a cloud-native business automation technology designed for building cloud-ready business applications.
It is based on the upstream https://kie.apache.org[Apache KIE open-source community], which includes popular technologies such as Drools, jBPM, and Kogito.

{PRODUCT_LONG} is licensed under the https://www.gnu.org/licenses/old-licenses/lgpl-2.1.en.html[GNU Lesser General Public License v. 2.1]. Each software component is governed by a license located in the component source code that permits you to run, copy, modify, and redistribute (subject to certain obligations) the software component.

IBM {PRODUCT_SHORT} is not a one-size-fits-all solution.
It is optimized for hybrid cloud environments and can easily adapt to specific domain and tooling needs.
Its core objective is to empower you to transform a set of business processes and decisions into your own domain-specific, cloud-native services.
With {PRODUCT_SHORT}, you build a cloud-native application by creating a set of independent, domain-specific services designed to deliver business value.
The processes and decisions you use to describe the desired behavior are executed as part of the services you create.
The resulting services are highly scalable, and the runtime is optimized for your service's needs.

== Cloud-native Approach
IBM {PRODUCT_SHORT} is designed to run and scale on cloud infrastructure, leveraging the latest cloud-based technologies to enhance performance and scalability.
By integrating with technologies like Quarkus, Spring Boot and Apache Kafka, {PRODUCT_SHORT} ensures quick start times and instant scaling on container application platforms like OpenShift. Some of the Compatible Technologies are as follows:

OpenShift:: Based on Kubernetes, OpenShift is the target platform for building and managing containerized applications with {PRODUCT_SHORT}.

Quarkus:: A native Java stack for Kubernetes, Quarkus allows you to build applications efficiently using IBM {PRODUCT_SHORT} services.

GraalVM:: Used with Quarkus, GraalVM enables native compilation with IBM {PRODUCT_SHORT}, resulting in fast start-up times and a minimal footprint.
For example, a native {PRODUCT_SHORT} service can start in approximately 0.003 milliseconds, about 100 times faster than a non-native start-up.
This speed is crucial in a cloud ecosystem, especially for small serverless applications.
Prometheus and Grafana: These tools are compatible with {PRODUCT_SHORT} services for monitoring and analytics, with optional extensions available for enhanced functionality.

Kafka:: A middleware technology supported by {PRODUCT_SHORT} for messaging and security, ensuring robust communication and data integrity within your applications.


=== Domain-specific Flexibility
IBM {PRODUCT_SHORT} adapts to your business domain, eliminating the need to modify your domain to work with {PRODUCT_SHORT}.
You can expose your {PRODUCT_SHORT} services through domain-specific APIs based on the processes and decisions you have defined.
These domain-specific APIs for {PRODUCT_SHORT} services do not require third-party or internal APIs.
For example, a process for onboarding employees could generate remote REST API endpoints that allow you to onboard new employees or retrieve information about their status using domain-specific JSON data.
You can also expose domain-specific data through events so that the data can be consumed and queried by other services.

=== Developer-centered Experience
IBM {PRODUCT_SHORT} is designed to provide an optimal developer experience.
You can utilize much or all of your existing tooling and workflow to develop, build, and deploy {PRODUCT_SHORT} services, whether locally for testing or in the cloud.
Quarkus offers development-mode features to assist with local testing, such as live reloading of your processes and decisions in your running applications for advanced debugging.
{PRODUCT_SHORT} tooling is embeddable, allowing you to continue using the workflow you are already familiar with for cloud-native services. For
example, the IBM {PRODUCT_SHORT} Developer Tools for VS Code enable you to edit your Business Process Model and Notation (BPMN) business processes and Decision Model and Notation (DMN) decision models directly in your VS Code IDE alongside your regular application code.



{PRODUCT_LONG} is an open-source business automation platform that combines flexible business process automation and decision management. {PRODUCT_SHORT} facilitates the collaboration between business and IT users throughout the creation, management, validation, and deployment of tailored process and decision automation solutions. Business users can modify business logic and business processes without requiring assistance from IT personnel.

{PRODUCT_LONG} is an application development platform that enables developers and business experts to create cloud-native applications. It is available as a set of Maven dependencies accessed through Maven Central. 

{PRODUCT_SHORT} is a cloud-native technology fully supported on both Red Hat OpenShift Container Platform and Kubernetes, allowing for flexible deployment across hybrid cloud environments.

Business Automation Manager Open Editions includes IBM Process Automation Manager Open Edition and IBM Decision Manager Open Edition as licensed products. Each of these developer-centric products can be purchased separately.  

== Benefits of Business Automation Manager Open Editions: 

Open, developer-friendly solutions. Highly customized applications can be built using common development and CI/CD tools on transparent, secure code. 

Standards-based tooling. BPMN models and DMN models provide multiple options to model flows and policies, and to help ensure automation services integrate with legacy and third-party applications. 

Cloud-native development. Apps can be built and deployed as containerized microservices on Red Hat OpenShift. 

Decision management. Open-source rules engine and Kogito-based, cloud-native tooling and runtimes can provide fast boot times and scaling. 

== New in IBM Decision Manager Open Edition 9

New cloud-native features. Aligned with the improved BAMOE Canvas and Developer Tools experience, the decision and rules engine powered by Kogito is designed to be lightweight and fast, enabling usage of hot reload features for business assets, and native compilation, which helps make serverless model adoption and container scale-down achievable. 

Immediate testing. BAMOE Canvas provides a completely client-side visual modeling experience, enabling immediate testing without deploying the solution to a separate runtime environment. It fast-tracks the feedback loop, promoting rapid iterations. 

Enhanced microservices architecture. As part of the shift from an application server based architecture to a microservices based architecture, users can build and run their decision services as cloud-native Java applications on Quarkus. This shift to microservices based on the Quarkus framework enhances the modularity, scalability, and maintainability of applications. 

Improved scalability. Users can deploy their decision services as microservices in a containerized environment, taking full advantage of Kubernetes' scalability features such as down-scaling and auto-scaling. 

Support for additional Kubernetes. IBM's commitment to open source continues with support for various Kubernetes platforms, including Red Hat OpenShift. This broadens the deployment options, ensuring adaptability to various infrastructural needs. 



{PRODUCT_LONG} is a developer-first technology that offers a highly customizable set-up and solution. {PRODUCT_SHORT} is developed using well-known technologies, specifications, and open standards. 

The design of an automation solution, including the components that are part of the application lifecycle, can be easily be adapted to different scenarios. The modular structure of the solution allows for custom, lightweight deployment units that efficiently use computational resources by including only what is needed.
This approach is possible via the creation of solutions targeting the automation of decisions, business rules, straight-through processes, and long-running business processes. 

Services designed to address particular domain business problems can improve team performance and simplify the application lifecycle from development to deployment.
An automation solution with IBM BAMOE includes:

* Development tools
* Process and decision services: Java applications that deliver one or more automation capabilities.
* Additional components and supporting tools: to accelerate development, simplify installation of product components on cloud platforms, and to add a developer-friendly UI to support process management capabilities.

These are the building blocks that are used to design applications to address the following requirements:

*Decision Automation*

Decisions can be automated using one of the three following technologies:

. Decision Model and Notation (DMN): An open-standard designed to simplify the automation of repeatable rules by business users.
. Decisions tables in Excel: A common approach for automating simpler types of business rules based on tables written on `.xls` format.
. Technical business rules: By using Drools Rules Language (DRL), developers rely on maximum flexibility to automate rules.

*Process Automation (BPMN)*

Automated processes may be one of the following:

* Straight-through process: Executed from start to end without human interaction, with no persistence of state.
* Business process: covers a larger set of needs, such as long-running processes, human-driven workflows, timer-based process events, task audibility, storage of business key performance indicators (KPIs), and other scenarios involving data persistence.

*Process and Decision Automation*

More complex scenarios can be implemented through the orchestration of business decisions to combine intelligent processes with automated decisions. They can easily be combined whatever the chosen approach (DMN/XLS/DMN), providing a unified experience and the seamless use of data across different business assets. This is possible despite each asset type using a specific data representation paradigm:

* `process variables` in processes
* `data types` in decisions
* `facts` in business rules

== Components overview

When you design an automation service each capability has a set of required and optional components. The following sections list the product components:

*Development*

* xref:../tools/canvas.adoc[{CANVAS}]
* {DEV_TOOLS_VSCODE_MARKETPLACE_LINK}[{DEV_TOOLS}]
* {STANDALONE_EDITORS_CLASSIC_LINK}[BAMOE Standalone Editors (classic)]
* {STANDALONE_DMN_EDITOR_LINK}[BAMOE Standalone DMN Editor]

*Execution*

* Decision and Rules Engine
* Process Engine

*Workflow Management*

* BAMOE Management Console
* REST and GraphQL APIs

For more information see xref:../runtime-services-modeling/consoles.html[Managing live Workflows using BAMOE Management Console]

*Automation add-ons*

* Human tasks
* Integration
* Data persistence
* Data-Auditing
* Jobs and asynchronous services execution
* Observability with metrics decision and process services

For more information, see xref:../workflow/overview.adoc[Overview of Stateful Workflow] and  xref:../runtime-services-modeling/runtime-services-modeling.adoc[Service monitoring with Prometheus and Grafana].