= Known limitations
include::../partials/attributes.adoc[]

Before you use {PRODUCT_LONG}, see the known limitations. When possible, workarounds will be included with the limitations.

Table 1. Known limitations
[%header,cols=2]
[%autowidth]
|===

|Limitation | Description

|{Canvas} cannot import files from GitHub using the raw URL, '/:org/:repo/refs/heads/:tree/:path*'.
|Due to the GitHub API change, the raw URL does not work. Use the URL, '/:org/:repo/:tree/:path*' to import files from GitHub, see https://www.ibm.com/mysupport/aCIKe000000XfIg[issue,window=_blank]


|Standalone BPMN and DMN Editors (classic): The standalone editors examples show some minor issues 
|* Read-only not applied to process variable tags. It can be edited even if a BPMN diagram is set to read-only in the standalone BPMN Editor (classic).

* Incorrect reference of state-control. Though BPMN is mentioned in the top toolbar with buttons for loading files, it refers to DMN.

* Read-only not applied to boxed expressions as it can be edited even if a DMN diagram is set to read-only in the standalone DMN Editor (classic).

See https://www.ibm.com/mysupport/aCIKe000000XfJo[issue,window=_blank]

|===