= Supported environments

include::../partials/attributes.adoc[]
include::../styles/images.adoc[]

This section summarizes the tested and supported configurations available for {PRODUCT_SHORT} {VERSION}. Support is available for any issues you identify while using the product in production or development, physical or virtual environments, and depending on your subscription agreement. For any supplementary details, in particular for patch releases, you can see the https://www.ibm.com/software/reports/compatibility/clarity-reports/report/html/softwareReqsForProduct?deliverableId=1EA3BE2E21944FDABF4A432FD818E438[IBM Support site link].

A supported configuration includes the application containers, the JVM version families and their corresponding Operating Systems.

=== Supported configurations

[%header,cols=2]
[%autowidth]

|===
|Java Virtual Machine | Version
|OpenJDK | 17
|Adoptium Open JDK | 17
|IBM Semeru Runtime Open Edition |17.0.14.0
|GraalVM Community Edition for JDK * | 17 


|===

*GraalVM support is limited to native-image for native compilation.

=== Deployments

[%header,cols=3]
[%autowidth]
|===
|Operating System / Architecture | Container platform | Java Virtual Machines

|Red Hat Enterprise Linux 9.5 (RHEL) / x86_64 | OpenShift Container Platform 4.16 

Kubernetes 1.30 | OpenJDK 17

Adoptium OpenJDK 17

IBM Semeru Runtime Open Edition 17.0.14.0

GraalVM Community Edition for JDK 17

|Microsoft Windows Server 2022 / x86_64 | OpenShift Container Platform 4.16

Kubernetes 1.30 | OpenJDK 17

Adoptium OpenJDK 17

IBM Semeru Runtime Open Edition 17.0.14.0

GraalVM Community Edition for JDK 17
|===

For more information on support statements for various Kubernetes platforms, see https://www.ibm.com/support/pages/node/7037216[BAMOE Support Statements]


=== Message brokers

[%header,cols=2]
[%autowidth]
|===
|Name| Version
|Apache Kafka | 3.6

|===

=== Web browsers

[%header,cols=2]
[%autowidth]
|===

|Name | Version
|Google Chrome | Latest release

|===

=== Databases

[%header,cols=2]
[%autowidth]
|===

|Database | Version
|PostgreSQL| 16.8
|Microsoft SQL Server | 2019

|===

=== Decision services

Decision services are supported as long as they run in production on an OpenShift Container Platform version in Full or Maintenance support in the Stable and EUS channels of OpenShift.

Any fixes, patches, and CVEs in BAMOE are provided only until the next BAMOE release.

Table.1 Supported runtimes
[%header,cols=3]
[%autowidth]
|===

|Framework | Version | JDK Version
|Quarkus | 3.15 | 17
|Spring Boot | 3.4 | 17

|===

Table.2 Models
[%header,cols=2]
[%autowidth]
|===

|Language | Version 
|DRL | Any
|DMN | 1.5 (automatic upgrade from 1.2+)

|===

=== Workflow services

Workflow services are supported as long as they run in production on an OpenShift Container Platform version in Full or Maintenance support in the Stable and EUS channels of OpenShift.

Any fixes, patches, and CVEs in BAMOE are provided only until the next BAMOE release.

Table.1 Supported runtimes
[%header,cols=3]
[%autowidth]
|===

|Framework | Version | JDK Version
|Quarkus | 3.15 | 17

|===

Table.2 Models
[%header,cols=2]
[%autowidth]
|===

|Language | Version 
|DRL | Any
|DMN | 1.5 (automatic upgrade from 1.2+)
|BPMN | 2.0

|===
