= What's new in version 9.2.1
include::../partials/attributes.adoc[]
include::../styles/images.adoc[]


This section summarizes the new functionality and changes in {PRODUCT_SHORT} {VERSION}. Highlights include new integrations with Gitlab and Bit Bucket, a new BPMN editor available as a technology preview and improvements to stateful Workflow management of SLAs and managing different workflow execution scenarios. 

== Modernized technology stack
This version upgrades foundational technologies and brings support for new ones:

* Quarkus - 3.20
* Red Hat Enterprise Linux (RHEL) 9.6
* PostgreSQL - 17.x
* (New!) Oracle 23ai _(for Workflow runtime)_

More information in xref:supported-environments.adoc[Supported Environments].

== Upgrading to {VERSION}
The Upgrade section of the documentation has been expanded to cover the supported upgrade scenarios for {PRODUCT_SHORT} {VERSION} which now includes two new scenarios:

* (New!) the key changes and the upgrade process between {VERSION_80X} projects and applications. xref:../upgrade/upgrading-80x-921.adoc[Learn more...]

* the upgrade process from {VERSION_91X} and {VERSION_92X}. xref:../upgrade/upgrading-91x-92x.adoc[Learn more...]

* (New!) the upgrade process from {VERSION_920} and {VERSION_921}. xref:../upgrade/upgrading-920-921.adoc[Learn more...]


== Technology preview - New BPMN Editor
A new BPMN Editor is available in {CANVAS}, {DEV_TOOLS} and as a standalone Javascript component. This editor...
xref:../workflow/authoring-workflows-techpreview.adoc[Learn more...]

== Integration of Canvas with GitLab and Bitbucket Data Center
You can now enable {CANVAS} users to work with GitLab by setting it up through an optional environmental variable `KIE_SANDBOX_AUTH_PROVIDERS`. xref:../installation/canvas.adoc#canvas-gitrepo-config[Learn more...]

Information on using general Git functionality in {CANVAS} is available in xref:../tools/working-with-git.adoc[Canvas ]

== Accelerators available as commands in {DEV_TOOLS}
Accelerators are now available as commands in {DEV_TOOLS} which makes it easier to create new projects and configure your own accelerators
xref:../getting-started/project-setup.adoc[Learn more...]


== Renew authentication to cloud and Git providers in {CANVAS}
Users can now renew expired AuthSessions without re-entering all details manually. xref:../tools/connecting-accounts.adoc[Learn more...]

== Enable authentication to a private repository in {CANVAS}

You can now configure your {CANVAS} installation to point to a custom accelerator and enable {CANVAS} to athenticate and access a private repository. There are two main reasons to do this: to align all __Business Service__ projects developed with your company standards and practices, or to enable development an air gap environment. A custom project accelerator can now be stored in a private Git repository.

xref:../installation/canvas.adoc[Learn more...]

== Static file validation

You can use the feature static file validation which is available in {DEV_TOOLS}. It offers you the real-time validation. xref:../tools/developer-tools-for-vscode.adoc[Learn more...]

== Improved support for Decision Services in multiple DRDs in the DMN Editor
The DMN editor now enables you to model your decisions in multiple Decision Requirement Diagrams (DRDs), managing them as a single underlying Decision Requirements Graph (DRG). This enables modelers to break down complex decision logic into manageable, focused views. xref:../editing/authoring-decisions.html[Learn more...]

== Enhancements for Workflow engine and runtime
The following new functionality is available in the Workflow engine and runtime in {VERSION}.

=== Improved handling for Process instance retrigger operations in Workflow Engine

If a node instance fails in the middle of a process instance workflow and the error details are not available, it may impact your ability to retrigger the node and mark the process instance as successful. The following changes have been made to the Data Index GraphQL API as a consequence:

The NodeInstance GraphQL interface now has `Retrigger` and `errorMessage` properties, enabling you to identify retriggered nodes and view associated error messages.

The `nodeInstanceId` has been added to the `ProcessInstance` GraphQL `error` property, providing a direct reference to the node that caused the error.

A new event state update event is now fired when a retrigger operation is performed on a process instance. This event sets the `ProcessInstance` GraphQL `state` property to `ACTIVE` and clears the `error` property, ensuring that the process state is accurately reflected in the Data Index.

xref:../workflow/data-index-graphql-api.adoc[Learn more...]

=== Case management scenarios implemented through flexible processes
You can now use BPMN extensions to provide case management functionality through __flexible processes__. A flexible process is any process definition that uses ad-hoc components or other features that enable the process to be executed more flexibly than traditional processes. Ad-hoc tasks refer to tasks that can be initiated dynamically during the execution of a business process, rather than being predefined in the process model. These tasks are particularly useful in scenarios where the workflow needs to accommodate unforeseen or exceptional activities that arise during runtime. xref:../workflow/authoring-workflows.adoc#case-management[Learn more...]

=== Guidance on implementing multi-pod Process Services in a single database
When running multiple instances of a process service on multiple pods using the compact architecture, you must assign a unique Job Service Management ID to each instance. This is to avoid multiple instances attempting to assume leadership over the Job Service and connection to the shared database. 


xref:../workflow/configuring-persistence-for-stateful-workflows.adoc#multi-node[Learn more...]

=== Oracle database support for stateful workflows
You can now use Oracle persistence for workflows in your _Business Service_. 
xref:../workflow/configuring-persistence-for-stateful-workflows.adoc[Learn more...]

=== Querying and rescheduling SLAs and Jobs in the Workflow Runtime
The ProcessInstance GraphQL interface has a new timers field that enables you to set timers on specific node instances within a process instance. xref:../workflow/data-index-graphql-api.adoc[Learn more...]

There are two new endpoints in the Process Instance management API that enable you to retrieve the active times associated with a given process or node instance: 

* `/management/processes/{processId}/instances/{processInstanceId}/timers`

* `/management/processes/{processId}/instances/{processInstanceId}/nodeInstances/{nodeInstanceId}/timers`

xref:../workflow/management-apis.adoc[Learn more...]

=== Improved guidance for workflow evolution
You may need to move process instances to a different server, update their process definition, or take them offline for maintenance without affecting the business logic. The Process Instance Migration Service enables you to to migrate running process instances from one deployment version to another. xref:../runtime-services-modeling/services-deployment.adoc#migration-PIM[Learn more...]

=== Optimistic locking for multithreading in a business service using workflow

In an environment with multithreaded access to a __Business Service__ the workflow engine needs to ensure proper state of the runtime data. A new optimistic locking property has been added to manage concurrent access of database entities, avoiding race conditions. xref:../workflow/configuring-persistence-for-stateful-workflows.adoc#multithreading[Learn more...]
 
== New Test Scenario Activator class based on JUnit 5 

A new Test Scenario (*.scesim) Activator class (`@TestScenarioActivator`) based on JUnit 5 can now be used, replacing `org.kogito.scenariosimulation.runner.KogitoJunitActivator.class`. xref:../editing/authoring-scesim.adoc[Learn more...]


== Import data types from Java classes in DMN Editor

You can now import Java classes as data types in the DMN Editor in {DEV_TOOLS} providing similar functionality to that which is available in the DMN editor (Classic). xref:../tools/importing-dmn-data-types-from-java-classes.adoc[Learn more...]


== {MANAGEMENT_CONSOLE} Enhancements in Production
There are a number of usability improvements in the Management Console:

* Pre-configured connected runtimes bundled with the Management Console deployment.
* Listing Process Definitions and creating new Process Instances.
* Listing Process Instances, Tasks, and Jobs from all connected runtimes simultaneously.
* Viewing a dashboard with a basic summary of all Process Instances, grouped by the Process Definition.
* Improved filtering and search capabilities to manage large numbers of processes.
* Improved visualization of process instances, tasks, and jobs, adding new columns.
* Ability to view the Process Definition diagram in certain contexts. 
* Additional Jobs actions such as retry failed jobs, changing inputs before retry.

xref:../runtime-services-modeling/consoles.adoc[Learn more...]


== General bug fixes and enhancements
See the complete list in xref:fix-list.adoc[Fix List].


== Download documents 
For more information on {PRODUCT_LONG} version {VERSION} download document, see https://www.ibm.com/support/pages/node/7228834[BAMOE 9.2 Download Document].