= What's new in version 9.2.1
include::../partials/attributes.adoc[]
include::../styles/images.adoc[]


This section describes the main new functionalities and changes in {PRODUCT_SHORT} {VERSION}. Highlights include Stateful Workflows (BPMN) support, the new Test Scenario Editor supporting up to DMN 1.5, and Spring Boot 3 for Decisions and Rules services.

See the list below details all changes introduced in {PRODUCT_SHORT} {VERSION}.

== Modernized technology stack
This version upgrades foundational technologies and brings support for new ones:

* Quarkus - 3.20 _(from 3.15)_
* PostgreSQL - 17.x _(from 16.8)_
* (New!) Oracle 21c (TBC) _(for Workflow runtime)_
* (New!) Spring Boot 3.4 _(for Workflow runtime)_

More information in xref:supported-environments.adoc[Supported Environments].

== Documented Migration Scenario from {PRODUCT_SHORT} {VERSION_80x}
There is a new documentation section that contains the steps for a tested scenario to help you upgrade your Business Services and projects from {VERSION_80x}. xref:../upgrading/upgrading.adoc[Learn more...]

== Integration with Github Enterprise Server (GHES)
. xref:../upgrading/upgrading.adoc[Learn more...]

== Stateful Workflows (BPMN)
The following new functionality is available in the stateful workflows in {VERSION}

=== Spring Boot support for stateful workflow
xref:../runtime-services-modeling/security.adoc[Learn more...].

=== Improved handling for Process instance re-trigger operations in Workflow Engine

 xref:../[Learn more...]

=== Oracle database support for Workflow Runtime
 xref:../workflow/overview.adoc#user-tasks[Learn more...]

=== Rescheduling SLAs and Scheduled Jobs Workflow Runtime
 xref:../workflow/overview.adoc#user-tasks[Learn more...]

=== Improved guidance for Workflow Evolution
New and updated process definitions xref:../workflow/authoring-workflows.adoc#business-calendars[Learn more...]

== Spring Boot DMN Accelerator available in {CANVAS}
 xref:../workflow/authoring-workflows.adoc#business-calendars[Learn more...]
 
== New BPMN Editor
Available in {CANVAS}, {DEV_TOOLS} and as a standalone Javascript component. 
 xref:../workflow/authoring-workflows.adoc#business-calendars[Learn more...]

== Test Scenario
The Test Scenario (*.scesim) Activator class is now based on JUnit5. To enable the Test Scenario in your project,
the `@org.junit.runner.RunWith(org.kogito.scenariosimulation.runner.KogitoJunitActivator.class)` annotation in the
Activator class should be replaced by `@TestScenarioActivator`

== New features in {DEV_TOOLS}

=== Accelerators available as commands
Accelerators are now available as commands in VS Code. 
xref:../workflow/authoring-workflows.adoc#business-calendars[Learn more...]

=== Static validation for DMN and BPMN via Extended Services

xref:../workflow/authoring-workflows.adoc#business-calendars[Learn more...]


== {MANAGEMENT_CONSOLE} Enhancements in Production
Enhancements in production xref:../runtime-services-modeling/consoles.adoc[Learn more...]



== General bug fixes and enhancements
See the complete list in xref:fix-list.adoc[Fix List].


== Download documents 
For more information on {PRODUCT_LONG} version {VERSION} download document, see https://www.ibm.com/support/pages/node/7228834[BAMOE 9.2 Download Document].