= What's new in version 9.4.0
include::../partials/attributes.adoc[]
include::../styles/images.adoc[]

This section summarizes the new functionality and changes in {PRODUCT_SHORT} {VERSION}.  

== Modernized technology stack
This version upgrades foundational technologies and brings support for new ones:

* Red Hat OpenShift Container Platform (OCP) - 4.20 _(in addition to 4.16, 4.18)_
* Quarkus - 3.27 LTS
* Spring Boot - 3.5
* Maven 3.9.11+
* Apache Kafka - 4.1, 4.2 _(in addition to 3.9, 4.0)_
* Gitlab Self Managed - 18.16
* GitHub Enterprise Server 3.17.10
* (New!) Azure SQL Managed Instance 
* (New!) Gradle - 9.2

More information in xref:supported-environments.adoc[Learn more...].

== Support for Quarkus 3.27 LTS
{PRODUCT_SHORT} now supports Quarkus 3.27 LTS, ensuring long-term stability, security, and compatibility with the latest Quarkus ecosystem. In this version of Quarkus the shift from @ConfigGroup to @ConfigMapping interfaces continues and you may need to update your Quarkus extensions xref:../upgrade/upgrading-93x-940.adoc[Learn more...]

== New Gradle 9.2 Support
{PRODUCT_SHORT} introduces support for you to use Gradle to build your Quarkus or Spring Boot based _Business Services_. It requires additional configuration of the {MVN_REPO} and Gradle commands can be used throughout the development lifecycle. 

You can access new accelerators in {CANVAS} to bootstrap a Gradle-based _Business Services_ project:

* Workflows (Quarkus + Gradle)
* Workflows (Spring Boot + Gradle)
* Decisions (Quarkus + Gradle)
* Decisions (Spring Boot + Gradle)

You can also view new examples of Gradle‑based projects in the `bamoe-{VERSION}-examples.zip` collection.

xref:../building-deploying/services-build.adoc[Learn more...]

== New Dev and Runtime Helm charts with integrated licensing
To facilitate the installation and license tracking of {PRODUCT_SHORT} components in your selected offering, {PRODUCT_DM} (DMOE) or {PRODUCT_PAM} (PMOE), four new Helm charts are provided. They include the product specific licensing annotations, removing the need for manual intervention:

The Dev helm charts include the following component Containers:

* {CANVAS}
* {EXT_SERVICES}
* {CORS_PROXY}
* {MVN_REPO} (new in {VERSION})

xref:../installation/development-environment.adoc[Learn more...]

The Runtime helm charts for include the following Component Containers:

* {MANAGEMENT_CONSOLE}
* {MCP_SERVER}

xref:../installation/runtime-environment.adoc[Learn more...]

== New tutorials to facilitate upgrading from {PRODUCT_SHORT} {VERSION_80X}
This release includes 13 comprehensive migration scenarios, provided to complement the {PRODUCT_SHORT} v8 to v9 upgrade guide and delivered in the https://github.com/IBM/bamoe-docs/tree/9.4.x[BAMOE Documentation public repository]. These hands-on tutorials provide concrete examples and step-by-step instructions for common migration challenges as you move from {VERSION_80X} to {VERSION}.

A full list and the individual tutorial READMEs are accessible from the Upgrade from {VERSION_80X} section of the documentation. xref:../upgrade/intro-tutorials.adoc[Learn more...]

== Fully supported {PRODUCT_SHORT} Event Listener lifecyle compatible with {PRODUCT_SHORT} {VERSION_80X} 
{PRODUCT_SHORT} {VERSION} includes full Task and Process lifecycle event support, including before/after hooks and payloads with both old and new data values. This feature ensures parity with the {PRODUCT_SHORT} {VERSION_80X} event listeners behavior, enabling smooth upgrades and preserving critical event-driven integrations for compliance, monitoring, and auditing. 

Two interfaces are provided: `UserTaskEventListener` and `ProcessEventListener` to align as much as possible with version {VERSION_80X} and facilitate upgrade and migration of your projects. xref:../workflow/event-driven-workflow.adoc#event-listener-lifecycle[Learn more...]

== Workflow Runtime support for suspendUntil in WS-HT lifecycle
The ability to suspend a user task until a specified date when it automatically resumes is now supported as part of the full WS-HumanTask 1.1 lifecycle in {PRODUCT_SHORT} {VERSION}. The `suspendUntil` operation triggers timer-based task resumption. xref:../workflow/user-tasks.adoc#human-task-lifecycle[Learn more...]

== Fully customizable {CANVAS} Dev Deployments
You can now define custom Dev Deployment options using Kubernetes YAML manifests, JSON Patches and a descriptor file, giving you full control over how your applications are deployed. Dev Deployment options follow the specVersion spec enabling forwards compatibility. This features gives you full control over all aspects of your _Business Services_ deployment including:

* Definition of custom Kubernetes resource manifests
* Application of JSON Patches to dynamically modify manifests at deploy time
* Configure parameters that can be adjusted when creating a deployment
* Reference dynamic values (deployment name, namespace, deployed resource status, ...) via token interpolation with recursive JSON Path expressions

For installation set-up xref:../tools/create-custom-dev-deployment-image.adoc[Learn more...]

== Additional Error log details in {MANAGEMENT_CONSOLE} 
{MANAGEMENT_CONSOLE} now provides detailed error information when a job fails, enabling you to diagnose issues without having to access external logs. The error information includes logs, error messages and stack traces where available. This option is activated for individual _Business Services_ by setting an application property. xref:../managing-monitoring/consoles.adoc#jobs-service-error-details[Learn more...]


[#download-doc]
== Download documents 
For more information on {PRODUCT_LONG} version {VERSION} download document, see https://www.ibm.com/support/pages/node/7266365[BAMOE 9.4 Download Document].

// to be updated for 9.4