= What's new in version 9.3.0
include::../partials/attributes.adoc[]
include::../styles/images.adoc[]


This section summarizes the new functionality and changes in {PRODUCT_SHORT} {VERSION}.  

== Modernized technology stack
This version upgrades foundational technologies and brings support for new ones:

* Java - 21 
* OpenShift Container Platform 4.18 (in addition to 4.16)
* DMN - 1.6
* Kafka - 4.0 (in addition to 3.9)

=== Java 21 support
Java 21 is now the default version supported by {PRODUCT_SHORT}. Java 17 remains a supported version and you will find specific packages for the Dev Deployment if you wish to continue using this version.

More information in xref:supported-environments.adoc[Supported Environments].

== New BPMN Editor 
The new BPMN Editor which was available in {VERSION_921} as a technology preview is now the default editor and comes with a number of new features in {VERSION}. 

* Correlation Properties and Keys can now be edited on a dedicated new Panel

* Process Variables can now be edited on a dedicated Panel

* Morphing a node into another variant (e.g., Task → User Task) can now be done with consistent keyboard shortcuts;

* Grid snapping is now available, similarly to DMN Editor;

* A live preview of a new node will be rendered when dragging from the Palette;

* The Group node is now available to visualize enclose nodes that share similar context;

* Assignments (Data I/O) is now under Data Mapping.

xref:../workflow/authoring-workflows.adoc[Learn more...]

=== Custom task nodes for Work Item Handlers

You can now create a node directly in your BPMN model that binds to a custom Work Item Handler. xref:../workflow/authoring-workflows.adoc[Learn more...]

== New AI integrations
{PRODUCT_SHORT} now enables you to create Business Services containing Workflows that are able to send prompts and query LLMs for generated textual-content as part of the business process. This is possible using a new Gen AI Task in the BPMN Editor. 

A technology preview enables you to leverage specific BAMOE capabilities are now exposed through an MCP Server and can be consumed by any Agentic AI framework (such as watsonX Orchestrate). Using this functionality you can create your own AI Agents. xref:../integrating-ai/intro-ai-integration.adoc[Learn more...]

== New Spring boot support for stateful workflow _Business Services_
You can now develop your stateful workflow _Business Services_ using Spring Boot. A new Spring Boot accelerator is available in {CANVAS} and {DEV_TOOLS} enabling you to automatically generate a _Business Service_ project from BPMN. xref:../tools/applying-accelerators.adoc[Learn more...]

Once you have used the acceletor to transform your process model into a _Business Service_ project, a new Spring Boot Web application provides you with an integrated developer experience that is similar to the Quarkus Dev UI. It enables you to run and interact with your Workflows during development, create Process Instances and manage Jobs and Tasks. This replaces the Swagger UI that you will have been using in previous releases to run your __Business Service__ projects in development mode.

xref:../workflow/running-workflows-with-dev-ui.adoc[Learn more...]

== New embedded job service for workflow applications
A new embedded job service is available for integration with Quarkus and Spring Boot based workflow applications following the compact architecture model. This new job service add-on replaces the {VERSION_92X} Job Service and is fully backwards compatible, using the same database schema for persistence. In a multi-pod setup, this add-on works without specific configuration settings. xref:../workflow/overview.adoc#jobs-service[Learn more]

== Open API files delivered for all BAMOE APIs
A new deliverable is included in the distribution that includes the API specifications:

* OpenAPI specs
* GraphQL schema files

Using this deliverable you will have immediate access to standardized, up-to-date API documentation for integration and reference. xref:../installation/installation.adoc[Learn more...]

== Data Cleanup tool for Workflow subsystems
The volume of data generated by stateful workflow _Business Services_ grows exponentially over time. Large volumes of unwanted or old data can potentially slow down queries, search operations, and all other interactions with the production database. 

A new data cleanup tool database tool is now available to remove data that is obsolete. xref:../runtime-services-modeling/services-deployment.adoc[Learn more...]

== DMN 1.6 new feature support
The following features of DMN 1.6 are now supported in the DMN Editor and execution.

* B-FEEL supported as an expression language and you can configure B-FEEL instead of FEEL at the global or expression specific level. 
* Simplified InputData assignment across nested imports. 
* Improve consistency and usability of boxed filter and boxed iterator expressions.
* Updated Collect hit policy behavior for DMN decision tables.
* Deprecation of IANA Time Zone identifiers in time literals
* NumberFunction class now supports a single parameter invoke() method that dynamically handles both String and Number formats.
* Single parameter versions of all rounding functions in FEEL 
* Support type conversion from decimal to integer
* Ability to use two distinct styles for referencing decisions in a single DMN file.
* Support new version of 'date and time' conversion function
* Two distinct modes for managing errors during decision model evaluation (lenient, strict)
* New value property is defined in the following types: date, date and time, years and months duration, days and time duration.
* New descendant operator to enhance the expressiveness of FEEL when working with nested contexts.

xref:../editing/authoring-decisions.adoc[Learn more...]


== General bug fixes and enhancements
See the complete list in xref:fix-list.adoc[Fix List].

== Download documents 
For more information on {PRODUCT_LONG} version {VERSION} download document, see https://www.ibm.com/support/pages/node/7228834[BAMOE 9.3 Download Document].