= What's new in version 9.3.1
include::../partials/attributes.adoc[]
include::../styles/images.adoc[]


This section summarizes the new functionality and changes in {PRODUCT_SHORT} {VERSION}.  

== Modernized technology stack

This version upgrades foundational technologies and brings support for new ones:

* PostgreSQL - 18.0 _(in addition to 16 and 17)_

More information in xref:supported-environments.adoc[Supported Environments].

== AI integration - {MCP_SERVER} (Tech Preview) security and hardening 
The {MCP_Server} was released in {VERSION_930} as a tech preview. {PRODUCT_SHORT} {VERSION} contains a new version of the tech preview that. contains the following updates: 

• Implementation of a default port (80 for HTTP or 443 for HTTPS), used if you do not specify one. 
• The ability to declare a richer description. If the related Business Service model has a description it will be added in the MCP Tool description.
• Spring Boot based _Business Services_ are now supported.
• MCP Tools bound to models with complex data (Input with nested objects and collections) in _Business Services_ are now better covered.
• A new security layer in the {MCP_SERVER} to secure MCP endpoints (disabled by default).

xref:../integrating-ai/ai-mcp-server.adoc[Learn more...]

== AI integration - AI Agent Task for BPMN (Tech Preview)
{PRODUCT_SHORT} provides a new AI Agent Task in BPMN Editor powered by an integration with Langflow. 
Customers authenticate with their Langflow instance (service URL and API key) via the new Langflow Auth Provider, available in {CANVAS} and {DEV_TOOLS}

The Property panel enables you to select flows/agents from their Langflow instance. Flow execution can be tested directly in the Property Panel with user inputs. 
You can design AI flows in the Langflow visual editor and integrate them seamlessly into {PRODUCT_SHORT} workflows. 

xref:../integrating-ai/ai-agent-task.adoc[Learn more...]

== Developing and deploying _Business Services_ for Z platform
In {PRODUCT_SHORT} {VERSION} you are able to install and use the following components delivered as containers in {PRODUCT_SHORT} on OpenShift running on Linux s390x on IBM z/OS: 

* {CANVAS}, 
* {MVN_REPO}, 
* {QUARKUS_DEV_UI}, 
* {MCP_SERVER}, 
* {MANAGEMENT_CONSOLE}, 
* {MCP_SERVER}, 
* {DATA_CLEANUP}  

You can use these components to build deploy and manage _Business Services_ that run on OpenShift on Linux s390x on IBM z/OS. 

xref:../runtime-services-modeling/services-build.adoc[Learn more...]

== New Process Instance Migration (PIM) Add-on and UI to migrate in-flight processes

When you deploy _Business Services_ with a specific Process Definition in a Cloud environment, client applications or {MANAGEMENT_CONSOLE} users can create multiple Process Instances that follow the sequence flow defined in the original Process Definition. Process Instances may run over days, weeks or months with waiting states, such as Timers or User Tasks. During this period, you may want to deploy a new version of the Process Definition to _Business Services_. This can cause Process Instances in waiting states to follow an obsolete Process Definition. 

Using the new PIM Add-on and integrated UIs you can now plan and manage the migration of in-flight Process Instances to new Process Definitions. xref:../managing-monitoring/management-apis.adoc[Learn more...]

The Process Instance Migration (PIM) integration with {MANAGEMENT_CONSOLE} enables you to plan and manage the migration of Process Instances to new Process Definitions via full visualization of Process Definitions, facilitating node mapping and migration execution. xref:../managing-monitoring/consoles.adoc[Learn more...]

== Localization of {PRODUCT_SHORT} User Interfaces
All user interfaces and user messages generated by {PRODUCT_SHORT} are now available in the following languages in addition to English. Language is automatically set according to your machine locale and can be changed by changing your browser or VS Code locale:

* Brazilian Portuguese
* French
* German
* Italian
* Japanese (not included due to quality issues)
* Korean
* Simplified Chinese
* Spanish
* Traditional Chinese

xref:../installation/installation.adoc[Learn more...]

== Support for WS-HumanTask Standard 
{PRODUCT_SHORT} provides a new Human Task Lifecyle that adheres to the xref:https://docs.oasis-open.org/bpel4people/ws-humantask-1.1-spec-cs-01.html[WS-HumanTask standard]. You can select this lifecycle to replace the default User Task lifecycle based on Kogito. The Human Task lifecycle enables more precise management of Human task behavior and state transitions. The default remains the Kogito based User Task lifecycle. 

xref:../workflow/overview.adoc#user-tasks[Learn more...]

== Using sub-processes from a different _Business Service_ project
In {PRODUCT_SHORT} {VERSION_80X} and earlier releases, the engine supported the execution of subprocess from different project. Now in {VERSION} a new documented process using standard Maven procedure is available to implement this in {PRODUCT_SHORT} {VERSION}

xref:../workflow/[Learn more...]



== Unified PDF documentation for multiple DMN models

The {CANVAS} in {PRODUCT_SHORT} now includes a document generation feature that supports multiple DRDs and provides a rich documentation workflow to manage your DMN artifacts. This feature brings the {VERSION} DMN editor into feature parity with the capabilities of the {PRODUCT_SHORT} {VERSION_80X} DMN editor (Classic) from BAMOE v8.

The new Document Generation option is available in the DMN Editor in both {CANVAS} and {DEV_TOOLS}. You can then select the DMN artifacts available in your project to be included in the PDF. xref:../editing/authoring-decisions.adoc[Learn more...]

== Download documents 
For more information on {PRODUCT_LONG} version {VERSION} download document, see https://www.ibm.com/support/pages/node/7244587[BAMOE 9.3 Download Document].