= What's new in version 9.5
include::../partials/attributes.adoc[]
include::../styles/images.adoc[]

This section summarizes the new functionality and changes in {PRODUCT_SHORT} {VERSION_95x} versions.

////
Version {VERSION} is now available. You can find information on fixes and known limitations in {VERSION} in the section: xref:#fix-list-known-limitations[Fixes and Known Limitations in {VERSION_RM} versions]
////

== Modernized technology stack
This version upgrades foundational technologies and brings support for new ones:

* Spring Boot - {SPRING_VERSION_95}
* (New!) DB2 - 11.5, 12.1

More information in xref:supported-environments.adoc[Learn more...].

== Support for Spring Boot 4.x
{PRODUCT_SHORT} now supports Spring Boot 4.x. This update addresses the end of support for Spring Boot 3.x and enables {PRODUCT_SHORT} customers to benefit from a fully supported foundation. It ensures that your applications remain secure, compliant and ready for future innovation.

xref:../upgrade/upgrading-94x-95x.adoc[Learn more...]

== Support for IBM Db2
IBM {PRODUCT_SHORT} now fully supports the IBM Db2 database, completing the set of key database technologies that are supported by {PRODUCT_SHORT}. This feature ensures continuity for IBM clients who have selected IBM DB2 as a strategic database choice. All workflow subsystems and the {DATA_CLEANUP} and {PIM_ADDON_SHORT} run on distributed Db2. Stateful workflow persistence can be configured for _Business Services_ that are:

* Quarkus based xref:../workflow/workflows-with-quarkus.adoc#db2-quarkus-config[Learn more...]

* Spring Boot based xref:../workflow/workflows-with-quarkus.adoc#db2-spring-config[Learn more...]

== New REST Service Call Task WorkItemHandler added to the WIHs Library
The new REST Service Call Task WorkItemHandler is delivered in the BAMOE WorkItemHandlers (WIHs) Library which provides out of the box solutions for common integration tasks. The new WorkItemHandler supports secured endpoints with OpenID Connect token acquisition, making integration with modern APIs easier and more secure. This enhancement also reduces the upgrade effort for v8 customers and simplifies connecting {PRODUCT_SHORT} workflows to external systems. 

xref:../workflow/work-item-handler-intro.adoc[Learn more...]

== Red Hat OpenShift Container Platform Passthrough support for BAMOE containers
In {VERSION_950} the {PRODUCT_SHORT} container images now optionally support traffic directly over HTTPS using a TLS certificate and customer-provided keys. This enables end-to-end encryption between the user browser and the container on OpenShift through a Passthrough Route. If you are operating in regulated environments you may need TLS to be terminated as close to the application as possible, to support:

 * Zero-trust architectures
 * Compliance with industry standards (e.g., PCI-DSS, HIPAA)
 * Environments without Ingress controllers or where passthrough is mandated
 
You can now choose Passthrough TLS when installing your dev and runtime environment helm charts: xref:../installation/development-environment.adoc#dev-env-tls-cert[Learn more...]

You can also configure your _Business Services_ with Passthrough TLS. xref:../building-deploying/security.adoc#bus-services-tls-cert[Learn more...]

== New documented procedure to customize Dev and Runtime component containers
A new section in the documentation describes how to implement common use cases to customize the {PRODUCT_SHORT} containers deployed in the Dev and Runtime environment. You may want to customize the containers ({CANVAS} and related containers, {MVN_REPO}, {MANAGEMENT_CONSOLE}, {MCP_SERVER}) for one of the following reasons:

* to comply with corporate security policies, 
* to rapidly patch vulnerabilities, 
* or to standardize your container infrastructure.

xref:../installation/container-customization-guide.adoc[Learn more...]

== Workflow Runtime Event publishing to external storage systems
It is now possible to publish Process and User Task events from a _Business Service_ to any external read model, without changing the Workflow Engine. A single, stable EventPublisher interface, implemented by a custom handler, is able to receive committed Event batches from the Workflow Engine. This feature enables _Business Services_ to offload data externally, for example to an Elasticsearch index that powers a custom dashboard. Two new product examples have been added to the distribution: `process-event-listeners-quarkus` and `process-event-listeners-springboot`. xref:../workflow/event-driven-workflow.adoc#external-event-publisher[Learn more...]

== Quarkus and Spring Boot dependencies now managed in separate BOMs
{PRODUCT_SHORT} dependencies are now managed in specific BOMs for your projects in Quarkus, Spring Boot, or Embedded mode instead of the previous `bamoe-bom`. This improvement enables support for the latest framework features without version conflicts.

xref:../upgrade/upgrading-94x-95x.adoc[Learn more...]

== Enhanced License usage tracking 
You now have the option to automatically upload {PRODUCT_SHORT} contractual and adoption metrics to IBM Software Central and use IBM Usage Metering Service to collect and analyze data on your {PRODUCT_SHORT} component and _Business Services_ deployments across your organization. The automated upload ensures that you are compliant with your licensing terms at all times. xref:../installation/reporting-usage-metrics.adoc[Learn more...]

== New Accelerator deliverable part of {PRODUCT_SHORT} distribution
The {PRODUCT_SHORT} distribution now includes the default Accelerator files as a downloadable archive. They were previously only available in a public Git repository on version specific branches. Delivering them as part of each release enables you to have offline access to them and quickly identify what has changed between releases. xref:../tools/applying-accelerators.adoc[Learn more...]

[#fix-list-known-limitations]
== Fixes and Known Limitations in {VERSION_95} versions
You can find information on the fixes and Known limitations in each {VERSION_95X} version via the following links:

* xref:fix-list.adoc[Release Notes → Fix List]

* xref:known-limitations.adoc[Release Notes → Known Limitations]

[#download-doc]
== Download documents 
For more information on {PRODUCT_LONG} version {VERSION} download document, see 

// TBD

https://www.ibm.com/support/pages/node/7277082[BAMOE {VERSION_95} Download Document].
