= What's new in version 9.5
include::../partials/attributes.adoc[]
include::../styles/images.adoc[]

This section summarizes the new functionality and changes in {PRODUCT_SHORT} all {VERSION_95x} versions. 

Version {VERSION} is now available. You can find information on fixes and known limitations in {VERSION} in the section: xref:#fix-list-known-limitations[Fixes and Known Limitations in {VERSION_RM} versions]

== Modernized technology stack
This version upgrades foundational technologies and brings support for new ones:

* Spring Boot - {SPRING_BOOT_VERSION_BOM}
* Quarkus 3.33 LTS
* React - 18 
* (New!) DB2 - xx

More information in xref:supported-environments.adoc[Learn more...].

== Support for Spring Boot 4.x
{PRODUCT_SHORT} now supports Spring Boot 4.x. This update addresses the end of support for Spring Boot 3.x and enables {PRODUCT_SHORT} customers to benefit from a fully supported foundation. It ensures that your applications remain secure, compliant and ready for future innovation xref:../.adoc[Learn more...]

== New support for DB2
{PRODUCT_SHORT} now fully supports the DB2 database. All workflow subsystems and tooling: {DATA_CLEANUP} and {PIM_ADDON_SHORT} run on DB2

Stateful workflow persistence can be configured for _Business Services_ that are:

* Quarkus based xref:../workflow/workflows-with-quarkus.adoc[Learn more...]

* Spring Boot based xref:../workflow/workflows-with-quarkus.adoc[Learn more...]

== Work Item Handler library
The first WIH is delivered in the new library of WorkItemHandlers (WIHs) which provides out of the box solutions for common integration tasks. The new REST WIH supports secured endpoints with OpenID Connect token acquisition, making integration with modern APIs easier and more secure. This enhancement also reduces the upgrade effort for v8 customers and simplifies connecting {PRODUCT_SHORT} workflows to external systems. 

xref:../workflow/extending-workflow-engine.adoc[Learn more...]

== Role Based Access Control in {MANAGEMENT_CONSOLE}
It is now possible to manage user permissions in {MANAGEMENT_CONSOLE} through fine-grained role-based access control (RBAC). Features can be restricted by role, enabling enterprises to enforce read-only or read/write access per capability. Permissions are sourced from the Identity Provider (IDP), ensuring centralized governance and compliance.

xref:../managing-monitoring/consoles.adoc[Learn more...]

== OCP Passthrough support for BAMOE containers
In {VERSION_950} the {PRODUCT_SHORT} containers now support TLS termination within BAMOE container images. If you are operating in a regulated environments you may need TLS to be terminated as close to the application as possible for:
 * Zero-trust architectures
 * Compliance with industry standards (e.g., PCI-DSS, HIPAA)
 * Environments without Ingress controllers or where passthrough is mandated
 
  xref:../building-deploying/security.adoc[Learn more...]

== Workflow Runtime Aggregated Transactional external Event publishing
Publishing Workflow-related Events to external storage systems (E.g., ElasticSearch) is now possible. This allows Business Services to off-load data externally to reduce pressure in the transactional Workflow Engine database. xref:../workflow/event-driven-workflow.adoc[Learn more...]

== New Accelerator and {PRODUCT_SHORT} configuration property deliverables
The {PRODUCT_SHORT} distribution now includes the version specific accelerator files as a downloadable archive in addition to being published in a public Git repository. 

The distribution also includes a file that lists and documents all _Business Service_ configuration properties that can be used in your _application.properties_ file. Enabling you to have a full list of supported properties.

 xref:../reference/application.properties.adoc[Learn more...]

[#fix-list-known-limitations]
== Fixes and Known Limitations in {VERSION_95} versions
You can find information on the fixes and Known limitations in each {VERSION_95X} version via the following links:

* xref:fix-list.adoc[Release Notes → Fix List]

* xref:known-limitations.adoc[Release Notes → Known Limitations]

[#download-doc]
== Download documents 
For more information on {PRODUCT_LONG} version {VERSION} download document, see 

// TBD

https://www.ibm.com/support/pages/node/7266365[BAMOE 9.4 Download Document].
