= What's new in version 9.3.0
include::../partials/attributes.adoc[]
include::../styles/images.adoc[]


This section summarizes the new functionality and changes in {PRODUCT_SHORT} {VERSION}. Highlights include...  

== Modernized technology stack
This version upgrades foundational technologies and brings support for new ones:

* Quarkus - 3.20 LTS _(from 3.15 LTS)_
* OpenShift Container Platform - 4.18 _(4.16 still supported)_
* PostgreSQL - 18 
* Oracle 23ai _(for Workflow Runtime)_
* Red Hat Enterprise Linux (RHEL) 9.6 _(9.4 still supported)_
* DMN - 1.6
* Java - 21


More information in xref:supported-environments.adoc[Supported Environments].

== Kogito cloud event functionality using Kafka


== GraphQL mutations for User Tasks


== SpringBoot to develop Workflow services

== Process Automation

== Support statement on commercially reasonable suport

== Usage of New BPMN Editor with new functionality 

== Workflow GA - support predefined 

== CPU licenses

== User task life cycle


== DB schema diagram
Used to represent all the DB tables that are being used by business process instances at runtime. [Learn more...]


== General bug fixes and enhancements
See the complete list in xref:fix-list.adoc[Fix List].


== Download documents 
For more information on {PRODUCT_LONG} version {VERSION} download document, see https://www.ibm.com/support/pages/node/7228834[BAMOE 9.3 Download Document].