= What's new in version 9.2.1
include::../partials/attributes.adoc[]
include::../styles/images.adoc[]


This section summarizes the new functionality and changes in {PRODUCT_SHORT} {VERSION}. Highlights include new integrations of with Gitlab and Bit Bucket, a new BPMN editor available as a technology preview and improvements to stateful Workflow management of SLAs and managing different workflow execution scenarios. 


== Modernized technology stack
This version upgrades foundational technologies and brings support for new ones:

* Quarkus - 3.20 _(from 3.15)_
** `quarkus-oidc-proxy` extension __(from 0.1.2 or 0.1.3)__
* PostgreSQL - 17.x _(from 16.8)_
* (New!) Oracle 21c (TBC) _(for Workflow runtime)_

More information in xref:supported-environments.adoc[Supported Environments].

== Upgrading to {VERSION}
The Upgrade section of the documentation has been expanded to cover the supported upgrade scenarios for {PRODUCT_SHORT} {VERSION} which now includes two new scenarios:

* (New!) the key changes and the upgrade process between {VERSION_80X} projects and applications. xref:../upgrade/upgrading-80x-921.adoc[Learn more...]

* the upgrade process from {VERSION_91X} and {VERSION_92X}. xref:../upgrade/upgrading-91x-92x.adoc[Learn more...]

* (New!) the upgrade process from {VERSION_920} and {VERSION_921}. xref:../upgrade/upgrading-920-921.adoc[Learn more...]


== Technology preview - New BPMN Editor
A new BPMN Editor is available in {CANVAS}, {DEV_TOOLS} and as a standalone Javascript component. This editor...
xref:../workflow/authoring-workflows-techpreview.adoc[Learn more...]

== Integration of Canvas with GitLab
You can now enable {CANVAS} users to work with GitLab by setting it up through an optional environmental variable `KIE_SANDBOX_AUTH_PROVIDERS`. xref:../installation/canvas.adoc[Learn more...]

Information on using the GitLab functionality in {CANVAS} - xref:../tools/working-with-gitlab.adoc[Learn more...]

== Integration of Canvas with Bitbucket Data Center
You can now enable Canvas users to work with Bitbucket Data Center by setting it up through an optional environmental variable: `KIE_SANDBOX_AUTH_PROVIDERS`. xref:../installation/canvas.adoc#[Learn more...]

Information on using the Bitbucket Data Center functionality in {CANVAS} - xref:../tools/working-with-bitbucket.adoc[Learn more...]

== Accelerators available as commands in {DEV_TOOLS}
Accelerators are now available as commands in {DEV_TOOLS} which makes it easier to create new projects and configure your own accelerators
xref:../getting-started/project-setup.adoc[Learn more...]


== Renew authentication to cloud and Git providers in {CANVAS}
Users can now renew expired AuthSessions without re-entering all details manually. xref:../tools/connecting-accounts.adoc[Learn more...]

== Enable authentification to a private repository in {CANVAS}

You can now configure your {CANVAS} installation to point to a custom accelerator and enable {CANVAS} to athenticate and access a private repository. There are two main reasons to do this: to align all __Business Service__ projects developed with your company standards and practices, or to enable development an air gap environment. A custom project accelerator can now be stored in a private Git repository.

xref:../installation/canvas.adoc[Learn more...]


== Improved support for Decision Services in multiple DRDs in the DMN Editor
The new DMN editor now enables you to model your decisions in multiple Decision Requirement Diagrams (DRDs), managing them as a single underlying Decision Requirements Graph (DRG). This enables modelers to break down complex decision logic into manageable, focused views. xref:../editing/authoring-decisions.html[Learn more...]

== Enhancements for Workflow engine and runtime
The following new functionality is available in the Workflow engine and runtime in {VERSION}.

=== Improved handling for Process instance re-trigger operations in Workflow Engine

xref:../[Learn more...]

=== Ad-hoc process functionality for Case management scenarios
Ad-hoc tasks refer to tasks that can be initiated dynamically during the execution of a business process, rather than being predefined in the process model. These tasks are particularly useful in scenarios where the workflow needs to accommodate unforeseen or exceptional activities that arise during runtime. There is a new section describing how you can automate flexible and dynamic processes that rely on case management 

xref:../workflow/workflow-intro.adoc[Learn more...]

=== Guidance on implementing multi-node Process Services in a single database
When running multiple instances of a process service on multiple nodes in the compact architecture, you must assign a unique Job Service Management ID to each instance. This is to avoid multiple instances attempting to assume leadership over the Job Service and connection to the shared database. 


xref:../workflow/configuring-persistence-for-stateful-workflows.adoc#multi-node[Learn more...]

=== Oracle database support for stateful workflows
You can now use Oracle persistence for workflows in your _Business Service_. 
xref:../workflow/configuring-persistence-for-stateful-workflows.adoc[Learn more...]

=== Rescheduling SLAs and Scheduled Jobs in the Workflow Runtime
xref:../workflow/overview.adoc[Learn more...]

=== Query SLAs for workflows and process activities
xref:../workflow/overview.adoc[Learn more...]

=== Improved guidance for workflow evolution
You may need to move process instances to a different server, update their process definition, or take them offline for maintenance without affecting the business logic. The Process Instance Migration Service enables you to to migrate running process instances from one deployment version to another. xref:../runtime-services-modeling/services-deployment.adoc#migration-PIM[Learn more...]

=== Optimistic locking for multithreading in a business service using workflow

In an environment with multithreaded access to a __Business Service__ the workflow engine needs to ensure proper state of the runtime data. A new optimistic locking property has been added to manage concurrent access of database entities, avoiding race conditions. xref:../workflow/configuring-persistence-for-stateful-workflows.adoc#multithreading[Learn more...]
 
== New Test Scenario Activator class based on JUnit 5 

A new Test Scenario (*.scesim) Activator class (`@TestScenarioActivator`) based on JUnit 5 can now be used, replacing `org.kogito.scenariosimulation.runner.KogitoJunitActivator.class`. xref:../editing/authoring-scesim.adoc[Learn more...]


== Import data types from Java classes in DMN Editor

You can now import Java classes as data types in the DMN Editor in {DEV_TOOLS} providing similar functionality to that which is available in the DMN editor (Classic). xref:../tools/importing-dmn-data-types-from-java-classes.adoc[Learn more...]


== {MANAGEMENT_CONSOLE} Enhancements in Production
There are a number of changes in the Management Console xref:../runtime-services-modeling/consoles.adoc[Learn more...]


== General bug fixes and enhancements
See the complete list in xref:fix-list.adoc[Fix List].


== Download documents 
For more information on {PRODUCT_LONG} version {VERSION} download document, see https://www.ibm.com/support/pages/node/7228834[BAMOE 9.2 Download Document].