= What's new in version 9.2.1
include::../partials/attributes.adoc[]
include::../styles/images.adoc[]


This section summarizes the new functionality and changes in {PRODUCT_SHORT} {VERSION}. Highlights include new integrations with Gitlab and Bit Bucket, a new BPMN editor available as a technology preview and improvements to stateful Workflow management of SLAs and managing different workflow execution scenarios. 


== Modernized technology stack
This version upgrades foundational technologies and brings support for new ones:

* Quarkus - 3.20 _(from 3.15)_
* PostgreSQL - 17.x _(from 16.8)_
* (New!) Oracle 21c (TBC) _(for Workflow runtime)_
* (New!) Spring Boot 3.4 _(for Workflow runtime)_

More information in xref:supported-environments.adoc[Supported Environments].

== Documented Migration Scenario from {PRODUCT_SHORT} {VERSION_80x}
There is a new documentation section that contains the steps for a tested scenario to help you upgrade your Business Services and projects from {VERSION_80x}. xref:../upgrading/upgrading.adoc[Learn more...]

== Integration of Canvas with Gitlab

xref:../upgrading/upgrading.adoc[Learn more...]


== Integration with Github Enterprise Server (GHES)
xref:../upgrading/upgrading.adoc[Learn more...]

== New features in {CANVAS} 

=== Enable authentification to a private repository for custom accelerators

You can now configure your {CANVAS} installation to point to a custom accelerator and enable {CANVAS} to athenticate and access a private repository. There are two main reasons to do this: to align all __Business Service__ projects developed with your company standards and practices, or to enable development an air gap environment. A custom project accelerator can now be stored in a private Git repository.

xref:../installation/canvas.adoc[Learn more...]

== Technology preview - New BPMN Editor
Available in {CANVAS}, {DEV_TOOLS} and as a standalone Javascript component. 
xref:../workflow/authoring-workflows.adoc#business-calendars[Learn more...]

== Stateful Workflows (BPMN)
The following new functionality is available in the stateful workflows in {VERSION}


=== Improved handling for Process instance re-trigger operations in Workflow Engine

xref:../[Learn more...]

=== Ad-hoc processes to implement Case management scenarios

xref:../[Learn more...]

=== Guidance on implementing multi-node Process services in a single database

xref:../[Learn more...]

=== Oracle database support for stateful workflows
You can now use Oracle persistence for your _Business Service_,
xref:../workflow/overview.adoc#user-tasks[Learn more...]

=== Rescheduling SLAs and Scheduled Jobs Workflow Runtime
xref:../workflow/overview.adoc[Learn more...]

=== Query SLAs for processes and activities
xref:../workflow/overview.adoc[Learn more...]

=== Improved guidance for Workflow Evolution
New and updated process definitions xref:../workflow/authoring-workflows.adoc#business-calendars[Learn more...]

== Spring Boot DMN Accelerator available in {CANVAS}
xref:../workflow/authoring-workflows.adoc#business-calendars[Learn more...]
 
== Test Scenario

The Test Scenario (*.scesim) Activator class is now based on JUnit5. To enable the Test Scenario in your project, the `@org.junit.runner.RunWith(org.kogito.scenariosimulation.runner.KogitoJunitActivator.class)` annotation in the Activator class should be replaced by `@TestScenarioActivator`.

== New features in {DEV_TOOLS}

=== Import data types from Java classes in DMN Editor
You can now import Java classes as data types in the DMN Editor providing similar functionality to that which is available in the Classic DMN editor. 
 
xref:../tools/importing-dmn-data-types-from-java-classes.adoc[Learn more...]

=== Accelerators available as commands
Accelerators are now available as commands in VS Code. 
xref:../workflow/authoring-workflows.adoc#business-calendars[Learn more...]


== {MANAGEMENT_CONSOLE} Enhancements in Production
Enhancements in production xref:../runtime-services-modeling/consoles.adoc[Learn more...]


== General bug fixes and enhancements
See the complete list in xref:fix-list.adoc[Fix List].


== Download documents 
For more information on {PRODUCT_LONG} version {VERSION} download document, see https://www.ibm.com/support/pages/node/7228834[BAMOE 9.2 Download Document].