= What's new in version 9.2.0
include::../partials/attributes.adoc[]
include::../styles/images.adoc[]


This section describes the main new functionalities and changes in {PRODUCT_SHORT} {VERSION}. Highlights include Stateful Workflows (BPMN) support, the new Test Scenario Editor supporting up to DMN 1.5, and Spring Boot 3 for Decisions and Rules services.

See the list below details all changes introduced in {PRODUCT_SHORT} {VERSION}.

== Modernized technology stack
This version upgrades foundational technologies and brings support for new ones:

* Quarkus - 3.15 _(from 3.8)_
* Red Hat Enterprise Linux (RHEL) - 9.5 _(from 9.4)_
* OpenShift Container Platform - 4.16 _(from 4.14)_
* Kubernetes - 1.30 _(from 1.29)_
* (New!) Spring Boot 3.4 _(for Decisions and Rules)_
* (New!) PostgreSQL - 16.8
* (New!) Microsoft SQL Server - 2019

More information in xref:supported-environments.adoc[Supported Environments].

== Stateful Workflows (BPMN)
In {VERSION_91X}, {PRODUCT_SHORT} introduced Stateful Workfows as technology preview. {VERSION_920} now brings those capabilities to general availability. The following list highlights the most relevant aspects of Stateful Workflows, as well as important differences compared to technology preview in {VERSION_91X}.

If you have used the Stateful Workflows technology preview in {VERSION_91X}, you will need to follow the instructions in xref:../upgrading/upgrading.adoc#migrate-tech-preview[Upgrading from technology preview].  

=== REST and GraphQL APIs for system-to-system integration
{PRODUCT_SHORT} will generate REST API endpoints for your _Business Services_ based on the Workflows, Decisions, and Rules it contains (Domain API). In addition to those, fixed endpoints will also be present for easily managing Process Instances, User Tasks, and scheduled Jobs (Management API). For flexibility, a GraphQL endpoint will be available for you to query information from the Data-Index and Data-Audit subsystems. xref:../workflow/data-index-graphql-api.adoc[Learn more...]

=== Kafka integration for Event-driven Workflows
Complementary to REST and GraphQL APIs, {PRODUCT_SHORT} allows Workflows to connect to Kafka topics that will trigger or consume tasks inside business processes. An example of this integration is delivered in the product (process-event-driven). xref:../getting-started/examples.adoc[Learn more...]

=== User Tasks subsystem for Human-driven Workflows
This version introduces a new User Tasks subsystem in the runtime engine, with new endpoints that do not require global process data to be defined via parameters such as the process ID, process instance ID and task name. The returned JSON objects also contain richer information now.

Some highlights of the new User Tasks subsystem include SLA tracking, Customizable user groups, and customizable automatic User Task assignment. xref:../workflow/authoring-workflows.adoc#user-tasks[Learn more...]

=== Secured Workflows with OpenID Connect
Quarkus natively offers reliable authentication and authorization capabilities, allowing you to integrate with externals Identity Providers (IdPs) like Keycloak or Microsoft Entra ID. By binding into the built-in security layer of Quarkus, {PRODUCT_SHORT} allows you to be in complete control over authentication and authorization in your _Business Services_. {MANAGEMENT_CONSOLE} will also make use of this to let you interact with Process Instances, User Tasks, and scheduled Jobs, in an authenticated way. xref:../runtime-services-modeling/security.adoc[Learn more...].

=== Custom Business Calendar definitions
The Business Calendar feature provides precise time management within a business process by considering specific working hours, workdays, and holidays. This ensures that time-based events and deadlines are aligned with actual business schedules rather than simple chronological time. xref:../workflow/authoring-workflows.adoc#business-calendars[Learn more...]

=== Persistence layer
{PRODUCT_SHORT} enables you to configure databases to store operational data and audit records so that you can back-up periodically, ensuring information is not lost. To make deployments more convienient and not dictate when database creation happens, {PRODUCT_SHORT} offers separate Installation DDL scripts for your convenience.

Installation Data Definition Language (DDL) scripts are available to create from scratch a database that includes all required tables to be used by the persistence layer of the following Workflow subsystems:

•	Data-Index
•	Data-Audit
•	Jobs Service
•	User Tasks
•	Runtime Engine

The scripts can be found in the product deliverables and support both the PostgreSQL and Microsoft SQL databases. xref:../workflow/configuring-persistence-for-stateful-workflows.adoc#jdbc-persistence[Learn more...]

=== Data consistency enforced by transactional operations
In addition to supporting the Saga pattern for compensating failures in distributed operations, {PRODUCT_SHORT} handles actions across multiple subsystems in a transacional way. This means if something fails during execution for unforeseen reasons, your Process Instances, User Tasks, and/or Jobs won't be left in invalid intermediate states. xref:../workflow/configuring-persistence-for-stateful-workflows.adoc#transactions[Learn more...]

=== Workflow monitoring 
Track and analyze the activity within your _Business Services_ using {PRODUCT_SHORT}'s monitoring capabilities. With built-in support for Prometheus, you can collect metrics and visualize them using tools like Grafana. xref:../runtime-services-modeling/monitoring-services.adoc[Learn more...].

=== Workflow auditing 
When enabled, the Data-Audit subsystem will watch for relevant operations and log them to database tables. Creating your own audit logs is also possible by subscribing to internal events emitted by the Workflow engine. xref:../workflow/overview.adoc#data-audit[Learn more...]

== {MANAGEMENT_CONSOLE}
There are many changes in {MANAGEMENT_CONSOLE} compared to {VERSION_91X} technology preview, being the most important:

* BAMOE Task Console (available in {VERSION_91X} technology preview) has now been merged into {MANAGEMENT_CONSOLE}, in the "Tasks" screen.
* Connecting with multiple _Business Services_ in a single {MANAGEMENT_CONSOLE} installation is now supported.
* IdP configuration is now transparent, allowing {MANAGEMENT_CONSOLE} to know what IdP to authenticate with based only on the _Business Service_ URL.
* Authorized users can now impersonate other users when managing User Tasks.
* A Helm Chart is made available for easier installation on K8s/OCP clusters. xref:../installation/management-console.adoc[Learn more...].

{MANAGEMENT_CONSOLE} is an admin tool for managing Workflow applications. xref:../runtime-services-modeling/consoles.adoc[Learn more...]

== Form code generation for User Tasks moved to {DEV_TOOLS}
Instead of a standalone CLI tool, Form code generation capabilities for User Tasks are now available as custom commands provided by {DEV_TOOLS}. xref:../tools/form-generation.adoc[Learn more...]

== New Test Scenario Editor compatible with DMN 1.5
Continuing the modernization efforts that began with the new DMN Editor on {VERSION_91X}, {PRODUCT_SHORT} now provides a new Test Scenario Editor (`.scesim` files) compatible with DMN 1.5. This removes the limitation of only being able to unit-test DMN 1.2 files. The new Test Scenario Editor is available on {DEV_TOOLS} as the new default editor for `.scesim` files. xref:../editing/authoring-scesim.adoc[Learn more...]

== Spring Boot 3 support for Decision and Rules services
For the first time, Spring Boot 3 can be used as a foundational framework for Decisions- and Rules-based _Business Services_. xref:../editing/springboot-dmn-drl.adoc[Learn more...]

== DMN Editor UX improvements
When renaming Decisions, Business Knowledge Models (BKMs), Decision Services, or any other identifier in a DMN model, the DMN Editor will now prompt you to automatically update all occurrences of that identifier in FEEL expressions if you'd like it to. Another improvement is that the DMN Editor is now capable of highlighting Decision Table rules and Conditional Boxed Expression branches based on the DMN Runner evaluation results. xref:../editing/running-decisions.adoc[Learn more...]

== General bug fixes and enhancements
See the complete list in xref:fix-list.adoc[Fix List].


== Download documents 
For more information on {PRODUCT_LONG} version {VERSION} download document, see https://www.ibm.com/support/pages/node/7151078[BAMOE 9.2 Download Document].

// TODO: Update link to BAMOE 9.2.