= What's new in version 9.2.0
include::../partials/attributes.adoc[]


This section describes the main new functionality and changes in the {PRODUCT_SHORT} {VERSION}

=== Modernized Technology Stack

New support for the Spring Boot framework for DRL across the UI

The following new versions are supported for the technology stack:

* SpringBoot 3.4 (for decisions)
* Quarkus - 3.15
* Red Hat Enterprise Linux (RHEL) - 9.5  
* OpenShift Container Platform - 4.16
* Kubernetes - 1.30 
* Google Chrome - Latest release
* PostgreSQL - 16.8
* MS SQL Server - 2019

You can find the supported configurations in the following link: xref:supported-environments.adoc[Supported Environments]

== Form Generation
This is a functionality of the IBM BAMOE Developer Tools for VS Code and is used to generate web forms for BAMOE and Apache KIE projects. Form Generation is included as a command in the BAMOE Developer Tools extension for VS Code (BAMOE VS Code extension). For more information, see xref:../tools/form-generation.adoc[Form Generation]

== Stateful process for {PRODUCT_SHORT} applications
{PRODUCT_SHORT} {VERSION} now supports complex business process development, namely:

* Human-driven processes
* Usage of timer events
* Data persistence
* Business KPIs
* Data audit
* Saga pattern implementation using error and compensation events
* Long-running processes

=== Database schema definition scripts
This version includes new Data Definition Language (DDL) scripts that can be used to create from scratch a Database that includes all required tables to be used by the persistence layer of the following process components (subsystems):

•	Data index
•	Data audit
•	Job Service
•	Runtime Engine
•	User tasks subsystem

The scripts are available in the bamoe-9.1.2-db-utils.zip file and support both the PostgreSQL and MS SQL datbases. 

=== Human-Driven Workflows
Design and consume workflows with:

* SLA tracking
* Customizable user groups
* Decoupled user task data 
* Task assignment strategies
* Business Calendar for precise time management
* New product-oriented endpoints (e.g. /usertasks)

=== New Business calendar for process time management
The Business Calendar feature provides precise time management within a business process by considering specific working hours, workdays, and holidays. This ensures that time-based events and deadlines are aligned with actual business schedules rather than simple chronological time. xref:../workflow/designing-workflow.adoc#using-business-calendars[Learn more...]

=== New User Tasks API
In {VERSION_91X} it was possible to manage User Tasks through the Process API in the same way as any other work item. This version introduces a new subsystem in the runtime engine that is designed to work efficiently with user tasks. The new endpoints will not require global process data to be defined via parameters such as the process ID, process instance ID and task name, and the JSON objects returned contain richer information. 

If you have used the Stateful process technology preview in {VERSION}, you will need to follow the instructions in the xref:upgrading/upgrading.adoc#migrate-tech-preview[Upgrading from technology preview] section.  


=== User task JPA persistence
The User task sub-system can be configured to persists its data in the supported databases(PostgreSQL and MS SQL Server)

=== Transactional Operations
For enhanced data consistency

=== Performant Data querying
For enhanced data consistency

=== Seamless integration with Kafka 
Enabling you to focus on your business processes, as integration code gets automatically generated for you.

=== Event-driven Processes 
Use bpmn events to design event-driven processes

=== Process data auditing 
Asynchronous auditing can automatically emit events and enable tracking processes and tasks execution.

== Management Console
Task management has been integrated from the Task Inbox web application into the Management Console.

The Management console is now provided as a Helm chart to facilitate installation xref:../installation/consoles-helm-charts.adoc[Learn more...].

New support for authenticated runtimes that use external Identity Providers. The Management Console has a specific configuration that can be set via an environment variable when initializing the Container image: 

* RUNTIME_TOOLS_MANAGEMENT_CONSOLE_OIDC_CLIENT_CLIENT_ID

The environment variable receives the “client_id", which the Management Console will use to communicate with the Identity Providers registered with each runtime.

There is new support for multiple runtimes both with or without security enabled. As a result of this the Management Console is not connected to a runtime when you open it, and you are required to select a runtime to connect to. 

You can connect to many runtimes simultaneously, allowing users to manage multiple runtimes on the same web application.

It is now possible to impersonate another user. This is useful when a User Task is assigned to an unavailable user, blocking the status of that task until the assigned user returns. In BAMOE it is possible to define a group of users that may impersonate any other user, giving them the rights to manage User Tasks assigned to unavailable people. 

xref:../workflow/consoles.adoc[Learn more...]

== Security authentification and authorization
{PRODUCT_SHORT} is designed to be a Quarkus or SpringBoot application. Both these frameworks natively offer a reliable authentication and authorization layer. Once this layer is configured it can be consumed by your applications to protect service endpoints or the management console. 

You can then rely on an external IdP like Keycloak or Microsoft Entra ID as your project Identity and Access Management Solution. A key role of this architecture is the BAMOE Management Console, which enables users to access an integrated environment to log in to your application and interact with its entities like process instances, submit task forms, and view jobs, in a secured and authenticated way. xref:security.adoc[Learn more...].

=== Authentification and authorization with OpenID Connect
Protect services, tools, consoles and APIs with robust authentication and authorization, backed by your IDP of choice.

=== Secure communication between components
Protect access and management of sensitive process data by securing connections between consoles and process services

== Download documents 

For more information on {PRODUCT_LONG} version {VERSION} download document, see https://www.ibm.com/support/pages/node/7151078[BAMOE 9.2 Download Document].