= What's new in version 9.4.0
include::../partials/attributes.adoc[]
include::../styles/images.adoc[]

This section summarizes the new functionality and changes in {PRODUCT_SHORT} {VERSION}.  

== Modernized technology stack
This version upgrades foundational technologies and brings support for new ones:

* OCP 4.20_(in addition to xxx)_
* Quarkus 3.27_(in addition to xxx)_
* Spring Boot 3.5_(in addition to xxx)_
* SQL Server support now includes Azure SQL Managed Instance

More information in xref:supported-environments.adoc[Supported Environments].

== Support for Quarkus 3.27 LTSR
xref:../xx.adoc[Learn more...]

== Automation of license tracking and container annotation
To facilitate the installation and license tracking {PRODUCT_SHORT} {VERSION} provides four new Helm charts that depend on the offering you have purchased a license for, {PRODUCT_DM} or {PRODUCT_PAM}.

These Helm charts include the necessary licensing annotations and do not require any manual steps to add license annotations as was required with previous versions:

* dmoe-9.4.0-dev-environment-helm-chart.tgz
* dmoe-9.4.0-runtime-environment-helm-chart.tgz
* pamoe-9.4.0-runtime-environment-helm-chart.tgz
* pamoe-9.4.0-dev-environment-helm-chart.tgz

xref:../installation/installation.adoc[Learn more...]

== Migration tutorials from {PRODUCT_SHORT} {VERSION_80X}
A number of Migration Tutorials are available Project code and Readmes within the bamoe-docs open source repository. They enable you to see worked examples of how to move your version 8 projects to version {VERSION}.
xref:../upgrade/upgrading-80x-current.adoc[Learn more...]

== Gradle 9.2 an alternative to Maven
Gradle is now available as an alternative to Maven to build your _Business Services_. It requires additional configuration of the {MVN_REPO} and then MVN commands can be used throughout the development lifecycle. 

You can access new accelerators in the BAMOE Canvas to bootstrap a Gradle-based _Business Services_ project:

* Workflows (Quarkus + Gradle) Accelerator
* Workflows (Spring Boot + Gradle) Accelerator
* Decisions (Quarkus + Gradle) Accelerator
* Decisions (Spring Boot + Gradle) Accelerator

You can also view new examples of Gradle‑based projects in the `bamoe-{VERSION}-examples.zip` collection.

xref:../xxx.adoc[Learn more...]

== New BAMOE Event Listener Lifecyle compatible with {PRODUCT_SHORT} {VERSION_80X} 
xref:../xx.adoc[Learn more...]

== Workflow Runtime - `suspendUntil` supported in WS-HT lifecycle
Missing construct in WS-HT lifecycle implementation in 9.3.1. 

xref:../xxx.adoc[Learn more...]

== {CANVAS} Dev Deployments via User defined YAML
You can now define custom Dev Deployment options using Kubernetes YAML manifests, JSON Patches and a descriptor file, giving you full control over how your applications are deployed. Dev Deployment options follow the specVersion spec enabling forwards compatibility. This features gives you full control over all aspects of your _Business Services_ deployment including:

* Definition of custom Kubernetes resource manifests
* Application of JSON Patches to dynamically modify manifests at deploy time
* Configure parameters that can be adjusted when creating a deployment
* Reference dynamic values (deployment name, namespace, deployed resource status, ...) via token interpolation with recursive JSON Path expressions

For installation set-up xref:../installation/canvas.adoc[Learn more...]

For configuration and usage options xref:../tools/canvas.adoc[Learn more...]

== Additional Error log details in {MANAGEMENT_CONSOLE} 
xref:../xxx.adoc[Learn more...]



[#download-doc]
== Download documents 
For more information on {PRODUCT_LONG} version {VERSION} download document, see https://www.ibm.com/support/pages/node/7244587[BAMOE 9.4 Download Document].

// to be updated for 9.4