= What's new in version 9.3.0
include::../partials/attributes.adoc[]
include::../styles/images.adoc[]


This section summarizes the new functionality and changes in {PRODUCT_SHORT} {VERSION}. Highlights include...  

== Modernized technology stack
This version upgrades foundational technologies and brings support for new ones:

* OpenShift Container Platform - 4.18 _(4.16 still supported)_
* PostgreSQL - 18.x
* Spring Boot ??
* DMN - 1.6
* Java - 21

=== Java 21 support
You will find new packages for the Dev Deployment if you wish to continue using Java 17.

More information in xref:supported-environments.adoc[Supported Environments].

== New BPMN Editor 
The new BPMN Editor which was available in {VERSION_921} as a technology preview is now the default editor and comes with a number of new features in {VERSION}. xref:../workflow/authoring-workflows.adoc[Learn more...]

=== Custom task nodes for Work Item Handlers

You can now create a node directly in your BPMN model that binds to a custom Work Item Handler. xref:../workflow/authoring-workflows.adoc[Learn more...]

== New AI integrations
{PRODUCT_SHORT} now enables you to create Business Services containing Workflows that are able to send prompts and query LLMs for generated textual-content as part of the business process. You can also leverage the capabilities of an Agentic AI framework by offering a set of BAMOE specific capabilities as Tools, that implement selected use cases from BAMOE’s feature set. BAMOE Tools will be exposed through an MCP Server and eventually be consumed by any Agentic AI framework (such as watsonX Orchestrate), allowing the final user to create their own AI Agents based on BAMOE Tools. c

== Developing with Spring Boot 3 equivalent to Quarkus
In Quarkus-based __Business Service__ projects, customers can count on the Quarkus Dev UI mechanism to access web-based UIs that allow them to interact with the Workflows they are developing. However When you are running __Business Service__ projects in development mode in Spring Boot, using only the Swagger UI, it can be challenging to create Process Instances and manage Jobs and Tasks. 

A new Spring Boot Web application provides an integrated developer expeirence for Spring Boot based __Business Service__ projects. xref:../workflow/running-workflows-with-dev-ui.adoc[Learn more...]

== Building Workflow with Spring Boot
A new Spring Boot accelerator is available in {CANVAS} and {DEV_TOOLS} enabling you to automatically generate a _Business Service_ project from BPMN, transforming your process model into a project that can be built, tested executed and deployed. xref:../tools/applying-accelerators.adoc[Learn more...]

== Open API files delivered for all BAMOE APIs
A new deliverable is included in the distribution that includes the API specifications:
* OpenAPI specs
* GraphQL schema files

Using this deliverable you will have immediate access to standardized, up-to-date API documentation for integration and reference. xref:../installation/installation.adoc[Learn more...]

== Data Cleanup tool for Workflow subsystems
The volume of data generated by stateful workflow _Business Services_ grows exponentially over time. Large volume of unwanted or old data can potentially slow down queries, search operations, and all other interactions with the production database. 

A new data cleanup tool database tool is now available to remove data that is obsolete. xref:../runtime-services-modeling/services-deployment.adoc[Learn more...]

== General bug fixes and enhancements
See the complete list in xref:fix-list.adoc[Fix List].


== Download documents 
For more information on {PRODUCT_LONG} version {VERSION} download document, see https://www.ibm.com/support/pages/node/7228834[BAMOE 9.3 Download Document].