= What's new in version 9.3.1
include::../partials/attributes.adoc[]
include::../styles/images.adoc[]


This section summarizes the new functionality and changes in {PRODUCT_SHORT} {VERSION}.  

== Modernized technology stack

This version upgrades foundational technologies and brings support for new ones:

* PostgreSQL - 18.0 _(in addition to 16 and 17)_

More information in xref:supported-environments.adoc[Supported Environments].

== AI integration - {MCP_SERVER} 
MCP Server updates

== AI integration - Custom AI Agent
Custom AI agent


== Developing _Business Services_ for Z platform

In {PRODUCT_SHORT} {VERSION} you can now build container images to be run on IBM Z systems on Openshift. This enables you to build s390x based images and run on a Z OS cluster running Openshift. xref:../runtime-services-modeling/z-services-deployment.adoc[Learn more...]

== New Add-on and Tools to migrate in-flight Process Instances

The {MANAGEMENT_CONSOLE} now integrates a new Process Instance Migration (PIM) Tool. 

When you deploy Business Services with specific Process Definitions in a Cloud environment, client applications or Management Console users can create multiple Process Instances that follow the sequence flow defined in the original Process Definition. When a Process Instance is running over days, weeks or months with waiting states, such as Timers or User Tasks, it is possible to deploy new versions of the original Process Definition to Business Services, which can cause existing Process Instances in waiting states to follow an obsolete Process Definition.

The Process Instance Migration (PIM) now enables you to manage the migration of Process Instances to new Process Definitions, providing full visualization of process definitions, facilitating tasks such as node mapping and migration scheduling. 

xref:../runtime-services-modeling/services-deployment.adoc#migration-PIM[Learn more...]

== Localization of {PRODUCT_SHORT} User Interfaces

== Using sub-processes from a different _Business Service_ project

== User task lifecycle 

== Event listener lifecycle

== DMN Editor - Unified PDF documentation for multiple models