= What's new in version 9.4.0
include::../partials/attributes.adoc[]
include::../styles/images.adoc[]

This section summarizes the new functionality and changes in {PRODUCT_SHORT} {VERSION}.  

== Modernized technology stack
This version upgrades foundational technologies and brings support for new ones:

* OCP 4.20_(in addition to xxx)_
* Quarkus 3.27_(in addition to xxx)_
* Spring Boot 3.5_(in addition to xxx)_
* SQL Server support now includes Azure SQL Managed Instance

More information in xref:supported-environments.adoc[Supported Environments].

== Support for Quarkus 3.27 LTSR
xref:../xx.adoc[Learn more...]

== Migration tutorials 
xref:../xxx.adoc[Learn more...]

== Gradle 9.2 an alternative to Maven
xref:../xxx.adoc[Learn more...]

== New BAMOE Event Listener Lifecyle compatible with {PRODUCT_SHORT} {VERSION_80X} 
xref:../xx.adoc[Learn more...]

== Workflow Runtime - `suspendUntil` supported in WS-HT lifecycle
Missing construct in WS-HT lifecycle implementation in 9.3.1. 

xref:../xxx.adoc[Learn more...]

== {CANVAS} Dev Deployments via User defined YAML
You can now define custom Dev Deployment options using Kubernetes YAML manifests, JSON Patches and a descriptor file, giving you full control over how your applications are deployed. Dev Deployment options follow the specVersion spec enabling forwards compatibility. This features gives you full control over all aspects of your _Business Services_ deployment including:

* Definition of custom Kubernetes resource manifests
* Application of JSON Patches to dynamically modify manifests at deploy time
* Configure parameters that can be adjusted when creating a deployment
* Reference dynamic values (deployment name, namespace, deployed resource status, ...) via token interpolation with recursive JSON Path expressions

For installation set-up xref:../installation/canvas.adoc[Learn more...]

For configuration and usage options xref:../tools/canvas.adoc[Learn more...]

== Additional Error log details in {MANAGEMENT_CONSOLE} 
xref:../xxx.adoc[Learn more...]

== Automation of license tracking and container annotation
xref:../xxx.adoc[Learn more...]

[#download-doc]
== Download documents 
For more information on {PRODUCT_LONG} version {VERSION} download document, see https://www.ibm.com/support/pages/node/7244587[BAMOE 9.3 Download Document].