= What's new in version 9.3.1
include::../partials/attributes.adoc[]
include::../styles/images.adoc[]


This section summarizes the new functionality and changes in {PRODUCT_SHORT} {VERSION}.  

== Modernized technology stack
This version upgrades foundational technologies and brings support for new ones:

* PostgreSQL - 18.0 _(in addition to 16 and 17)_

More information in xref:supported-environments.adoc[Supported Environments].

== AI integration - {MCP_SERVER} (Tech Preview) security and hardening 
The {MCP_Server} was released in {VERSION_930} as a tech preview. {PRODUCT_SHORT} {VERSION} contains a new version of the tech preview that. contains the following updates: 

• Implementation of a default port (80 for HTTP or 443 for HTTPS), used if you do not specify one. 
• The ability to declare a richer description. If the related Business Service model has a description it will be added in the MCP Tool description.
• Spring Boot based _Business Services_ are now supported.
• MCP Tools bound to models with complex data (Input with nested objects and collections) in _Business Services_ are now better covered.
• A new security layer in the {MCP_SERVER} to secure MCP endpoints (disabled by default). xref:../integrating-ai/ai-mcp-server.adoc[Learn more...]

== AI integration - AI Agent Task for BPMN (Tech Preview)
{PRODUCT_SHORT} provides a new AI Agent Task (tech preview) in the BPMN Editor powered by an integration with Langflow, and available in {CANVAS} and {DEV_TOOLS}. You can design AI flows in the Langflow editor and integrate them seamlessly into {PRODUCT_SHORT} Workflows, authenticating with your Langflow instance via the new Langflow Auth Provider. You can test flow execution with user input directly in the Property Panel. xref:../integrating-ai/ai-agent-task.adoc[Learn more...]

== Developing and deploying _Business Services_ for Z platform
In {PRODUCT_SHORT} {VERSION} you are able to install and use the components delivered as containers in {PRODUCT_SHORT} on Linux s390x running on the IBM Z platform. 

You will find specific Linux versions of each of the containers in the distribution (see xref:#download-doc[Download Docs]) with the appropriate suffix `s390x` or `amd64`.

The host machine architecture should be automatically resolved when you pull the required containers. For more information see:

* {CANVAS} xref:../installation/canvas.adoc[Learn more...]
* {MANAGEMENT_CONSOLE} xref:../installation/management-console.adoc[Learn more...]

You can use these components to build deploy and manage _Business Services_ running on Linux s390x on the IBM Z platform. xref:../building-deploying/services-build.adoc[Learn more...]

== New Process Instance Migration (PIM) Add-on and UI to migrate in-flight processes
When you deploy _Business Services_ with a specific Process Definition in a Cloud environment, client applications or {MANAGEMENT_CONSOLE} users can create multiple Process Instances that follow the sequence flow defined in the original Process Definition. Process Instances may run over days, weeks or months with waiting states, such as Timers or User Tasks. During this period, you may want to deploy a new version of the Process Definition to _Business Services_. This can cause Process Instances in waiting states to follow an obsolete Process Definition. 

Using the new PIM Add-on and integrated UIs you can now plan and manage the migration of in-flight Process Instances to new Process Definitions. xref:../managing-monitoring/management-apis.adoc#process-instance-migration-addon[Learn more...]

The Process Instance Migration (PIM) integration with {MANAGEMENT_CONSOLE} enables you to plan and manage the migration of Process Instances to new Process Definitions via full visualization of Process Definitions, facilitating node mapping and migration execution. xref:../managing-monitoring/consoles.adoc#process-instance-migration-ui[Learn more...]

== Localization of {PRODUCT_SHORT} User Interfaces
All user interfaces and user messages generated by {PRODUCT_SHORT} are now available in the following languages, in addition to English. 

* Spanish
* Brazilian Portuguese
* French
* German
* Italian
* Japanese
* Korean
* Simplified Chinese
* Traditional Chinese

By default the language is set via your machine locale and can be changed in the {PRODUCT_SHORT} UI settings if required: xref:../installation/canvas.adoc[Learn more...]

== Support for WS-HumanTask Standard 
{PRODUCT_SHORT} provides a new WS-Human Task lifecycle that adheres to the xref:https://docs.oasis-open.org/bpel4people/ws-humantask-1.1-spec-cs-01.html[WS-HumanTask standard]. The WS-Human Task lifecycle enables more precise management of Human task behavior and state transitions. You can select this lifecycle to to be applied to the User Tasks in your Workflow but the default remains the Kogito-based User Task lifecycle. xref:../workflow/overview.adoc#user-tasks[Learn more...]

== Task Management API
A new Task Management API is provided in {PRODUCT_SHORT} {VERSION} that provides three additional endpoints to manage User Task Instances in the Runtime environment. xref:../managing-monitoring/management-apis.adoc#task-management-api[Learn more...]

== Using sub-processes from a different _Business Service_ project
In {PRODUCT_SHORT} {VERSION_80X} and earlier releases, the engine supported the execution of subprocess from different project. Now in {VERSION} a new documented process using standard Maven procedure is available to implement this in {PRODUCT_SHORT} {VERSION}. xref:../workflow/authoring-workflows.adoc#subprocess-project[Learn more...]

== PDF documentation for multiple DMN models in {CANVAS}
{CANVAS} now includes a document generation feature that supports multiple DRDs and provides a rich documentation workflow to manage your DMN artifacts. You can select the DMN artifacts available in your project to be included in the PDF.

The functionality of the {VERSION} DMN editor in {CANVAS} is now equivalent to the {PRODUCT_SHORT} {VERSION_80X} DMN editor. xref:../editing/authoring-decisions.adoc#pdf-docs[Learn more...]

[#download-doc]
== Download documents 
For more information on {PRODUCT_LONG} version {VERSION} download document, see https://www.ibm.com/support/pages/node/7244587[BAMOE 9.3 Download Document].