= What's new in version 9.2.0
include::../partials/attributes.adoc[]


This section describes the main new functionalities and changes in {PRODUCT_SHORT} {VERSION}. Highlights include Stateful Workflows (BPMN) support, the new Test Scenario Editor supporting up to DMN 1.5, and Spring Boot 3 for Decisions and Rules services.

See the list below for a complete list of changes introduced in {PRODUCT_SHORT} {VERSION}.

== Modernized technology stack

This version upgrades foundational technologies and brings support for new ones:

* Quarkus - 3.15 _(from 3.8)_
* Red Hat Enterprise Linux (RHEL) - 9.5 _(from 9.4)_
* OpenShift Container Platform - 4.16 _(from 4.14)_
* Kubernetes - 1.30 _(from 1.29)_
* (New!) Spring Boot 3.4 (for Decisions and Rules)
* (New!) PostgreSQL - 16.8
* (New!) Microsoft SQL Server - 2019

More information in xref:supported-environments.adoc[Supported Environments]

== Stateful Workflows (BPMN)
/// TODO

=== REST and GraphQL APIs for system-to-system integration
/// TODO

=== User Tasks subsystem for Human-driven Workflows
In {VERSION_91X} it was possible to manage User Tasks through the Process API in the same way as any other work item. This version introduces a new User Tasks subsystem in the runtime engine, with new endpoints that do not require global process data to be defined via parameters such as the process ID, process instance ID and task name. The returned JSON objects also contain richer information now.

If you have used the Stateful Workflows technology preview in {VERSION_91X}, you will need to follow the instructions in xref:upgrading/upgrading.adoc#migrate-tech-preview[Upgrading from technology preview].  

* SLA tracking
* Customizable user groups 
* Automatic User Task assignment strategies

=== Secured Workflows with OpenID Connect
Protect Service APIs with authentication and authorization, backed by your Identity Provider (IdP) of choice.

{PRODUCT_SHORT} is designed to be a Quarkus or Spring Boot application. Both these frameworks natively offer a reliable authentication and authorization layer. Once this layer is configured it can be consumed by your applications to protect service endpoints or the management console. 

You can then rely on an external IdP like Keycloak or Microsoft Entra ID as your project Identity and Access Management Solution. A key role of this architecture is the BAMOE Management Console, which enables users to access an integrated environment to log in to your application and interact with its entities like process instances, submit task forms, and view jobs, in a secured and authenticated way. xref:security.adoc[Learn more...].

=== Custom Business Calendar definitions
The Business Calendar feature provides precise time management within a business process by considering specific working hours, workdays, and holidays. This ensures that time-based events and deadlines are aligned with actual business schedules rather than simple chronological time. xref:../workflow/designing-workflow.adoc#using-business-calendars[Learn more...]

=== Kafka integration for Event-driven Workflows
/// TODO

=== Persistence layer
Data Definition Language (DDL) scripts are available to create from scratch a database that includes all required tables to be used by the persistence layer of the following Workflow subsystems:

•	Data-Index
•	Data Audit
•	Jobs Service
•	User Tasks
•	Runtime Engine

The scripts can be found in the product deliverables and support both the PostgreSQL and Microsoft SQL databases. [Learn more...]

=== Data consistency enforced by transactional operations
/// TODO

=== Workflow monitoring 
/// TODO

=== Workflow auditing 
Asynchronous auditing can automatically emit events and enable tracking processes and tasks execution.

/// TODO

== {MANAGEMENT_CONSOLE}
Task management has been integrated from the Task Inbox web application into the Management Console.

The {MANAGEMENT_CONSOLE} installation is now facilitated via a Helm chart xref:../installation/consoles-helm-charts.adoc[Learn more...].

New support for authenticated runtimes that use external Identity Providers. The Management Console has a specific configuration that can be set via an environment variable when initializing the Container image: 

* RUNTIME_TOOLS_MANAGEMENT_CONSOLE_OIDC_CLIENT_CLIENT_ID

The environment variable receives the “client_id", which the Management Console will use to communicate with the Identity Providers registered with each runtime.

There is new support for multiple runtimes both with or without security enabled. As a result of this the Management Console is not connected to a runtime when you open it, and you are required to select a runtime to connect to. 

You can connect to many runtimes simultaneously, allowing users to manage multiple runtimes on the same web application.

It is now possible to impersonate another user. This is useful when a User Task is assigned to an unavailable user, blocking the status of that task until the assigned user returns. In BAMOE it is possible to define a group of users that may impersonate any other user, giving them the rights to manage User Tasks assigned to unavailable people. 

xref:../workflow/consoles.adoc[Learn more...]


== Form code generation for User Tasks moved to {DEV_TOOLS}
Instead of a standalone CLI tool, Form generation capabilities for User Tasks are now available as custom commands provided by {DEV_TOOLS}. xref:../tools/form-generation.adoc[Learn more...]

== New Test Scenario Editor compatible with DMN 1.5
/// TODO

== Spring Boot 3 support for Decision and Rules services
/// TODO

== DMN Editor UX improvements
/// TODO

== Bug fixes and enhancements
/// TODO

== Download documents 
For more information on {PRODUCT_LONG} version {VERSION} download document, see https://www.ibm.com/support/pages/node/7151078[BAMOE 9.2 Download Document].

/// TODO: Update link to BAMOE 9.2.