= What's new in version 9.3.1
include::../partials/attributes.adoc[]
include::../styles/images.adoc[]


This section summarizes the new functionality and changes in {PRODUCT_SHORT} {VERSION}.  

== Modernized technology stack

This version upgrades foundational technologies and brings support for new ones:

* PostgreSQL - 18.0 _(in addition to 16 and 17)_

More information in xref:supported-environments.adoc[Supported Environments].

== AI integration - {MCP_SERVER} security and hardening (Tech Preview)
MCP Server updates

== AI integration - AI Agent Task for BPMN (Tech Preview)
{PRODUCT_SHORT} provides a new AI Agent Task in BPMN Editor powered by and integration with Langflow. 
Customers authenticate with their Langflow instance (service URL + API key) via the new Langflow auth provider, now available in {CANVAS} and {DEV_TOOLS}

The Property panel enables you to select flows/agents from their Langflow instance.
Flow execution can be tested directly in the property panel with user inputs. 
You can design AI flows in the Langflow visual editor and integrate them seamlessly into {PRODUCT_SHORT} workflows. 

== Developing _Business Services_ for Z platform

In {PRODUCT_SHORT} {VERSION} you can now deploy {PRODUCT_SHORT} components on z/OS platforms as well a build container images to be run on IBM z/OS platforms running on Openshift on Linux (s390x). Using these container images you can install adapted {PRODUCT_SHORT} components and use them to build s390x based images that run on an IBM z/OS cluster running Openshift. xref:../runtime-services-modeling/z-services-deployment.adoc[Learn more...]

== New Add-on and Tools to migrate in-flight Process Instances

The {MANAGEMENT_CONSOLE} now integrates a new Process Instance Migration (PIM) Tool. 

When you deploy Business Services with specific Process Definitions in a Cloud environment, client applications or {MANAGEMENT_CONSOLE} users can create multiple Process Instances that follow the sequence flow defined in the original Process Definition. When a Process Instance is running over days, weeks or months with waiting states, such as Timers or User Tasks, it is possible to deploy new versions of the original Process Definition to _Business Services_, which can cause existing Process Instances in waiting states to follow an obsolete Process Definition.

The Process Instance Migration (PIM) now enables you to manage the migration of Process Instances to new Process Definitions, providing full visualization of process definitions, facilitating tasks such as node mapping and migration scheduling. 

xref:../runtime-services-modeling/services-deployment.adoc#migration-PIM[Learn more...]

== Localization of {PRODUCT_SHORT} User Interfaces
All user interfaces and user messages generated by {PRODUCT_SHORT} are now available in the following languages are are automatically set according to your machine locale:

* Brazilian Portuguese
* French
* German
* Italian
// * Japanese (not included due to quality issues)
* Korean
* Simplified Chinese
* Spanish
* Traditional Chinese

xref:../installation/installation.adoc[Learn more...]

== Using sub-processes from a different _Business Service_ project

== User task lifecycle 
{PRODUCT_SHORT} provides a new Human Task Lifecyle that you can select to replace the default User Task lifecycle based on Kogito. The Human Task lifecycle enables more precise management of Human task behavior and state transitions. You can also integrate your custom User Task lifecycle. The default remains the Kogito based User Task lifecycle. 

xref:../workflow/overview.adoc#user-tasks[Learn more...]


== DMN Editor - Unified PDF documentation for multiple models

The DMN Editor in {PRODUCT_SHORT} now includes a document generation feature that supports multiple DRDs and provides a rich documentation workflow to manage your DMN artifacts. This feature brings the {VERSION} DMN editor into feature parity with the capabilities of the {PRODUCT_SHORT} {VERSION_80X} DMN editor (Classic) from BAMOE v8.

The new Document Generation option is available in the DMN Editor from Share dropdown. You can then choose the DMN artifacts in available in your project. xref:../editing/authoring-decisions.adoc[Learn more...]